### ISSUE TITLE
DatePicker does not render date-times that end with 0

### ISSUE THREAD

**Issue by isatemple** [telerik/kendo-angular#940] opened 2017-09-25 18:48 UTC
## I'm submitting a...

* Bug report 

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment] 2017-09-26 07:40
@isatemple, thanks for the report. I tried to replicate the issue in [our online demos](http://www.telerik.com/kendo-angular-ui/components/dateinputs/), but to no avail. Could you fill in the missing places in the provided `issue template` and share a repro demo? This will help us to proceed with the investigation and find a solution faster.

**Comment by isatemple** [comment] 2017-09-26 16:19
Georgi,
I tried to replicate it but the issue involves a SQL database and a
DateTime field containing the full date time (2017-10-25 10:41:54.210). I'm
rather new to using github/plunker and wasn't able to find a demo that was
suitable.

-Zadok

**Comment by ggkrustev** [comment] 2017-09-27 07:31
@isatemple, I do believe that the SQL database won't be require to replicate the issue. The data binding can be easily mocked just using the JSON received from the server.

I prepared a simple Plunker using the provided date time, but it seems to work. Could you modify it 
and demonstrate the issue? 

http://plnkr.co/edit/f4golS0TpiajaA0Zr9Tm?p=preview

Please note that without a repro demo and additional details (listed in the issue template initially shown) we won't be able to continue with our investigation.

**Comment by isatemple** [comment] 2017-09-27 16:40
Yes, it does seem to function fine even when I use the Reactive forms
Plunker and JSON data. I wish I could hit a SQL Web API datasource to repro
it for you. Is there a northwind plunker available?

**Comment by ggkrustev** [comment] 2017-09-27 23:58
I am afraid not. But still, requesting a SQL Web API is irrelevant in the case of Kendo DatePicker/DateInput component, because they work only with JavaScript Date objects. If the provided Plunker works for you then you will need to look for the problem somewhere between server and the Angular HTTP request. Ensure that the received JSON is parsed and converted correctly into JavaScript Date objects.

I will close the issue for now, as it seems to be unrelated to the Kendo component. I would be able to continue with the investigation if a runnable demo that demonstrates the issue is provided.

**Closed by ggkrustev** 2017-09-27 23:58 UTC
Labels: pkg:date-inputs

**Comment by isatemple** [comment] 2017-09-28 18:42
Georgi,
Thanks for the help. This is the basic code I'm using to parse it:

if (this.workProject.ScheduledStartDate != null) {
this.workProject.ScheduledStartDate =
this.intl.parseDate(this.workProject.ScheduledStartDate.toString()); }

**Comment by ggkrustev** [comment] 2017-09-29 07:00
@isatemple, what is the output of `this.workProject.ScheduledStartDate.toString()`? I'm wondering why converting to string is required before parsing it to date? What is the time of `ScheduledStartDate`? If it is date, there is no need to reparse it again.
