### ISSUE TITLE
Kendo Editor Formatting no longer works

### ISSUE THREAD

**Issue by paologrimaldi** [telerik/kendo-angular#2435] opened 2019-08-13 15:20 UTC
**Describe the bug**
On the editor select any text and place it as an H1 and visual format is not changed, also if the text fed to the editor has any tag like H1 or H2 etc. this tags do not get rendered visually in the editor, this used to work properly in the previous version.

**To Reproduce**
Select text, Open Format dropdown and select H1, observe that it does not change the look of the text

https://stackblitz.com/edit/angular-7qvapu?file=app/app.component.ts

**Expected behavior**
Text should render as an H1 tag

**Browser**
All browsers

**Comment by Raisolution** [comment] 2019-08-13 18:05
Hi @paologrimaldi,

Thank you for noticing this. We are aware of this regression in the sandbox mode and are currently working on solution, which will be introduced in the mid September release.

**Comment by valchev** [comment] 2019-10-14 13:11
The issue is fixed with the introduction of the `iframe` rendering mode in v0.8.0.

**Closed by valchev** 2019-10-14 13:11 UTC
Labels: Bug, Team2, pkg:editor
