### ISSUE TITLE
Column titles hidden in Detail Grid with locked column

### ISSUE THREAD

**Issue by jeromepl** [telerik/kendo-angular#643] opened 2017-06-14 13:34 UTC
Using a master-detail grid and with at least one locked column in the detail grid, the titles of the detail grid columns disappear (except the titles of the locked columns).

It looks like the width of the `.k-grid-header > .k-grid-header-wrap` element is not calculated correctly.

**Note**: The titles are visible and seem to work as intended if **all** columns fit in the width of the grid **initially**.

[Plunker](http://plnkr.co/edit/kcHOhFAG31gusyG0f9AK?p=preview)

![image](https://user-images.githubusercontent.com/7671307/27134777-9cb371e8-50e4-11e7-970d-99ee1c199bcd.png)

**Comment by rkonstantinov** [comment] 2017-06-15 07:36
Hey @jeromepl, thanks for contacting us. The issue is caused by the fact that the grid element is too narrow when initially shown and the logic for calculating the layout gets incorrect input. To make this work you will need to set the width of the grid in order to use locked columns feature.

**Comment by jeromepl** [comment] 2017-06-15 14:48
For me setting the width of the grid was not a possibility.
The easiest solution I have found was this hack:
```javascript
// In the detail-grid component
public ngAfterViewInit(): void {
    setTimeout(() => {
        window.dispatchEvent(new Event("resize"));
    }, 0);
}
```

Now this is not pretty code and I would very much like to avoid this if possible. Are there any plans on your side to handle this type of situation?

**Comment by tsvetomir** [comment] 2017-08-22 15:22
Looks like this is fixed in the latest version of the Grid, see [plunkr](http://plnkr.co/edit/8ci2VFMdQahx14mBFFph?p=preview).

**Closed** 2017-08-22 16:53 UTC
Labels: Bug, Passed-QA, pkg:grid

**Comment by magoss** [comment] 2018-03-05 09:26
The same issue in version 2.1.2 of kendo-angular-grid. Indicated plunkr does not work. Could you please reopen?

**Comment by tsvetomir** [comment] 2018-03-05 09:50
@magoss I've updated [the plunkr](http://plnkr.co/edit/4u72T2nYmLcoOGT23Ann?p=preview), but the header is visible. There's a positioning glitch, but that looks like a separate issue:

![image](https://user-images.githubusercontent.com/247917/36968508-66eb26e4-206b-11e8-9d66-eebe892c98b7.png)

**Comment by magoss** [comment] 2018-03-05 09:56
How did you updated it? I still see just \loading\ in your plunker - 'live preview' tab.

![image](https://user-images.githubusercontent.com/7815504/36968731-b4fbb55e-2063-11e8-9c02-42cdd5bc1862.png)

**Comment by tsvetomir** [comment] 2018-03-05 10:23
Please use the new link and clear the browser cache, if necessary.
