### ISSUE TITLE
Tooltip show method throwing

### ISSUE THREAD

**Issue by LBShyacinth** [telerik/kendo-angular#1660] opened 2018-07-11 13:06 UTC
## I'm submitting a...

* Bug report

## Current behavior
Tooltip show method throwing

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/TW06USDkYKd1d9RWP21R?p=preview

## Environment

```

```

Browser:
- Chrome (desktop) version 67.0.x

**Comment by elena-gancheva** [comment] 2018-07-11 14:18
Hi @LBShyacinth,
This is an expected behavior. In the plunker you sent, you want to show tooltip, while angular's component lifecycle hooks are not finished yet, but the `tooltip.show()` method is changing some of its properties and states, so you will not have a proper change detection and error will be thrown. You can read more about hooks here: https://angular.io/guide/lifecycle-hooks.
The provided official solution of this case (changing props and states in lifecycle hooks of component) is to wrap `this.tooltip.show()` method in `setTimeout(() => this.tooltip.show(anchor))` for triggering change detection. Here is the updated plunker: https://plnkr.co/edit/DQF9qsbO7rCkdm5OXqt6?p=preview.
I am closing this issue, since it is not a bug.

**Closed by elena-gancheva** 2018-07-11 14:18 UTC
Labels: Question
