### ISSUE TITLE
Datepicker in grid with paging gets overlapped

### ISSUE THREAD

**Issue by mogwai1** [telerik/kendo-angular#512] opened 2017-05-02 11:39 UTC
Hello,

Datepicker gets overlapped when used as editor template in grid with paging.
See plunkr example
http://plnkr.co/edit/hcUC8BlrmS1R7fdvCmPV?p=preview

Removing [pageSize]="pageSize" line (breaking the paging support), makes datepicker opening without overlapping.

**Comment by tsvetomir** [comment] 2017-05-02 11:43
Closing this as duplicate of #410. We're working on a fix for the problem.

**Closed by tsvetomir** 2017-05-02 11:43 UTC
