### ISSUE TITLE
Strange texts in generated xlf localizations

### ISSUE THREAD

**Issue by mesztam** [telerik/kendo-angular#3743] opened 2022-08-19 06:15 UTC
When generating i18n xlf localization for an app with the grid component (7.2.4), we're getting strange TUs in the result xlf file, e.g. (among others):

```
<trans-unit id="03a0df03d11d80b3aeca50cf4827096a51a853fc" datatype="html">
        <source><x id="INTERPOLATION" equiv-text="&quot;"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/@progress/kendo-angular-grid/__ivy_ngcc__/dist/fesm2015/index.js</context>
          <context context-type="linenumber">9395,9401</context>
        </context-group>
        <note priority="1" from="description">The label for the Grid pager</note>
        <note priority="1" from="meaning">kendo.grid.pagerLabel</note>
</trans-unit>
```
And such TUs are confusing the localization team. 
If I fill the translations with npx kendo-translate, then it is translated as:
        `<target>Page navigation, page {currentPage} of {totalPages}</target>`
Is the source segment correct? And properly paired with the translation? Or there is a bug somewhere? (kendo or extract-i18n ?)

In some other app, we are using kendo grid 5.2.1 still, there the following text is extracted for the same TU:

<source><x id="INTERPOLATION" equiv-text="}
    get to"/></source>
(I cannot even find "get to" in the files of the grid component.)

**Comment by mbechev** [comment] 2022-09-26 14:52
Closing this issue as its a duplicate of https://github.com/telerik/kendo-angular/issues/3435

**Closed by mbechev** 2022-09-26 14:52 UTC
Labels: Duplicate, pkg:grid, Team2
