### ISSUE TITLE
DatePicker shows the wrong CSS in ReactiveForm if other FormControl has validation error.

### ISSUE THREAD

**Issue by eastjie** [telerik/kendo-angular#1076] opened 2017-11-14 13:45 UTC
Hallo, 

If I use DatePicker for my reactive form with required validation, at the same time, I have other FormControl, e.g. TextBox, which also uses required validation.

If other FormControl fails by validation. The DatePicker show the wrong CSS, e.g. red border, just like, the validation of DatePicker fails. The same happens also in TimePicker.

This is my Plunker code, just delete the content of the text box. 
http://plnkr.co/edit/YjrJNyGJzUjcu9kxDlXC?p=preview

Thanks very much.

**Comment by gyoshev** [comment] 2017-11-14 14:46
@eastjie Thank you for reporting this. It is a problem in the theme, caused by the cascading styles for form validation. When the form is invalid, the DateInput inside the DatePicker shows the invalid styles. I am afraid that there isn't a good workaround for this at this time, so we'll strive to address this problem in the theme soon.

**Comment by gyoshev** [comment] 2017-11-22 09:20
The problem has been fixed in version `2.45.1` of the default theme. Here is the [updated plunker](http://plnkr.co/edit/OeLdLJYMl4WlBSVocRwH?p=preview).

**Closed by gyoshev** 2017-11-22 09:20 UTC
Labels: Bug, Styling
