### ISSUE TITLE
DropDownList not updating ngModel when changed back to default item by keyboard

### ISSUE THREAD

**Issue by geoffross** [telerik/kendo-angular#1570] opened 2018-05-29 13:37 UTC
## I'm submitting a...

* Bug report - No existing issue for this bug found

## Current behavior
When using a drop down list, and using the keyboard to re-select the default item the ngModel does not get changed back to the default item.

## Expected behavior
It should get changed back to the default item, regardless of how the value is selected.

## Minimal reproduction of the problem with instructions
This is very specific to they exact what you use the control so please follow carefully.
[Here is a plunker](https://plnkr.co/edit/uHiMs5m0pWSc5glCjAIY?p=preview)

1. Change the dropdown list to be Male
1. The value will updated above
1. Click on the control to drop it down
1. Then use up key to re-select 'Choose One...'
1. Then click off the control to set the value 
1. The value above is *not* updated and still reads Male

## What is the motivation or use case for changing the behavior?
I want to check for the placeholder and make my submit button disabled when this is selected. This can be 'gotten around' by a user completing the steps above.

## Environment

Package versions:
+-- @angular/animations@5.2.9
+-- @angular/cli@1.7.3
+-- @angular/common@5.2.9
+-- @angular/compiler@5.2.9
+-- @angular/compiler-cli@5.2.9
+-- @angular/core@5.2.9
+-- @angular/forms@5.2.9
+-- @angular/http@5.2.9
+-- @angular/language-service@5.2.9
+-- @angular/platform-browser@5.2.9
+-- @angular/platform-browser-dynamic@5.2.9
+-- @angular/router@5.2.9
+-- @progress/kendo-angular-buttons@4.1.0
+-- @progress/kendo-angular-dateinputs@3.2.0
+-- @progress/kendo-angular-dialog@3.6.1
+-- @progress/kendo-angular-dropdowns@3.0.0
+-- @progress/kendo-angular-excel-export@2.0.0
+-- @progress/kendo-angular-grid@3.3.0
+-- @progress/kendo-angular-inputs@3.1.1
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-data-query@1.3.1
+-- @progress/kendo-drawing@1.5.5
+-- @progress/kendo-theme-bootstrap@2.13.3
+-- @types/jasmine@2.8.6
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.103
+-- UNMET PEER DEPENDENCY bootstrap@4.0.0
+-- codelyzer@4.2.1
+-- core-js@2.5.3
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@1.4.2
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.10
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.5.3
`-- zone.js@0.8.20

Browser:
- Chrome (desktop) version 66.0.3359.139

System:
- Node version: v8.10.0
- NPM version: 5.6.0
- Platform:  Windows

**Comment by valchev** [comment] 2018-06-06 08:32
@geoffross the issue is resolved in latest dev version of the package.

Please download `v3.0.2-dev.201806051505` and let me know if it works as expected on your end.

**Comment by tsvetomir** [comment] 2018-08-22 07:06
Shipped in v3.0.3

**Closed by tsvetomir** 2018-08-22 07:06 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
