### ISSUE TITLE
RangeSlider doesn't rerender on resize

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#3677] opened 2022-05-19 18:55 UTC
RangeSlider is responsive, however only when first render time. If you resize parent element, its not re-rendered correctly:

i am not sure but i think it worked correctly in previous versions?
https://stackblitz.com/edit/angular-7j7hu2?file=src%2Fapp%2Fapp.component.ts

https://user-images.githubusercontent.com/10418323/169379652-cdd48aa0-98f5-4970-86c5-c30f0f74179f.mp4

If its not considered as a bug, is there a way how to rerender it manually? (render() funkction) ?

Or we have to attach resizeObserver on the parent and do some kind of hacks with ngIf -> setTimeout(ngIf) ?

**Comment by Raisolution** [comment] 2022-05-20 06:08
Closing as a duplicate of #3593

**Closed by Raisolution** 2022-05-20 06:08 UTC
Labels: pkg:inputs, Team2
