### ISSUE TITLE
Combobox - seems like a bug?

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2399] opened 2019-07-23 02:35 UTC
select a value
![image](https://user-images.githubusercontent.com/34930870/61678335-1f35c400-ad35-11e9-98da-08e1ec81c8b5.png)

open it again, then enter a search text which gets no corresponding result
![image](https://user-images.githubusercontent.com/34930870/61678383-3d032900-ad35-11e9-9cd3-e67c23434138.png)

finally, close it. it becomes empty. and valueChange event is triggered

![image](https://user-images.githubusercontent.com/34930870/61678407-52785300-ad35-11e9-9651-fb7a860e3234.png)

I think it should select the previous value and should not trigger valueChange event

**Comment by jiangyh1024** [comment] 2019-07-23 02:38
by the way. dropdownlist component works well

**Comment by dimitar-pechev** [comment] 2019-07-23 10:51
@jiangyh1024, this is indeed the intended behavior.

The **ComboBox** component value is updated on blur. When custom values are not allowed, the component tries to resolve the `trtrtrt` text from your example as value and fails as it's not part of the data set, so it discards it. 

The **DropDownList** doesn't discard such values as its input field is intended for searching only. While the **ComboBox** value and search inputs are actually the same element.

By design, as the entered value is invalid (not just the search query but the entered value), it gets discarded. The idea is to avoid the confusion that may be caused among some end users of entering some value and having it replaced with some previous value.

Closing the issue now, as the component is working as expected. I encourage you to continue the conversation if I'm missing something. We could reopen the thread and take it from there.

**Closed by dimitar-pechev** 2019-07-23 10:51 UTC
Labels: pkg:dropdowns
