### ISSUE TITLE
kendo-dialog with input field and/or disabled primary button is not closed on ESC

### ISSUE THREAD

**Issue by mesztam** [telerik/kendo-angular#1401] opened 2018-03-23 13:01 UTC
## I'm submitting a...
* Bug report 

## Current behavior

if a kendo-dialog contains an input field, then Esc does not work right after opening the dialog, or if you put focus into the input field. Only if you click on the header or put focus on one of the buttons. Probably related: the primary button is not fired on Enter if the focus is in an input field.

Also, if the primary button is disabled by default, then the dialog is not closed on Esc either.

## Expected behavior

The dialog should be closed on Esc / primary button should be clicked on Enter

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/OQmyLylcYTjCvym5xxg9?p=preview

(remove the [disabled]="true" attribute from the primary button to reproduce the issue with Enter)

**Comment by Raisolution** [comment] 2018-03-23 17:13
Hi @mesztam,

The Dialog is intentionally not closed on `Esc` if an input field is focused (Same goes for the `Enter` key not triggering the primary button). This behavior is by design. We may however consider adding a `close` method to the API, when this is not wanted.

There is an issue in the current example and it is indeed in the case when the primary button is disabled i.e. the dialog wrapper is not focused, so it cannot be closed on `Esc`. I will log this one for fixing. Thank you for noticing it.

**Comment by Raisolution** [comment] 2018-04-17 14:06
Fixed in `v3.5.0-dev.201804171355`

**Closed by Raisolution** 2018-04-17 14:06 UTC
Labels: Bug, pkg:dialog
