### ISSUE TITLE
Combobox - grouping of remote data does not render all group labels in the result set

### ISSUE THREAD

**Issue by bniedermeyer** [telerik/kendo-angular#2229] opened 2019-04-24 23:26 UTC
**Describe the bug**
When a user groups data that is being retrieved from a remote source the first group's label does not display in the result set. In this specific case I retrieve data based on what the user types into the combobox - almost like a search. 

**To Reproduce**

1)Go to Stackblitz that recreates this behavior
https://stackblitz.com/edit/kendo-group-remote-data
2) Type a value (e.g. 'a') into the combobox
3) See the data set populate but with the missing group labels

**Expected behavior**
All group labels should be visible when grouping remote data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8354477/56699998-c9596d80-66ac-11e9-96d4-d81a135d0499.png)

**Browser**
 - OS: [Windows]
 - Browser [Chrome, Firefox]
 - Version [Chrome 74, Firefox 66.0.3]

**Additional context**
The repro example was forked from the example [here](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/data-binding/#toc-services).

**Comment by bniedermeyer** [comment] 2019-05-20 22:48
Hi @danielkaradachki, Is there any update to the timeline for when we can expect a fix to be published?

**Comment by dimitar-pechev** [comment] 2019-06-03 10:43
@bniedermeyer, sorry for the delayed response.

The issue is resolved in the latest dev version of the `@progress/kendo-angular-dropdowns` package (**v3.5.6-dev.201906031029**).

**Comment by dimitar-pechev** [comment] 2019-06-06 12:46
Shipped in **v3.5.6**.

**Closed by dimitar-pechev** 2019-06-06 12:46 UTC
Labels: Bug, Passed-QA, Team1, pkg:dropdowns
