### ISSUE TITLE
Add possibility to handle scroll in kendo-grid

### ISSUE THREAD

**Issue by Oraz07** [telerik/kendo-angular#1575] opened 2018-05-30 10:54 UTC
## I'm submitting a...
  * Feature requests
  * Suggestion for improvement

## Current behavior

I include in my kendo-grid a button used to delete the related row: a modal is shown to confirm the action. I want to capture the scroll event of the grid to prevent that also the modal scroll with the grid.
I don't want to use JQuery solutions.

## Expected behavior
The optimal solution could be to handle the event like this:
`<kendo-grid (scroll)="closeModal()" ...> .... </kendo-grid>`

## What is the motivation or use case for changing the behavior?
The target is to be able to close the confirmation modal.

**Comment by danielkaradachki** [comment] 2018-05-31 07:56
I am not sure if I understand the scenario. How is the user able to scroll the grid while the modal is opened?
https://plnkr.co/edit/SVuNgiOeE66pFuBG2aWO?p=preview

**Comment by Oraz07** [comment] 2018-05-31 08:56
Sorry, I miss some details.
The grid is already nested in a modal, so I decide to use the kendo popup service.
I reproduce the problem here:
https://plnkr.co/edit/EoCVajjiDRfBylsRzuVZ?p=preview

I also attach a gif:
![scroll_issue_crop](https://user-images.githubusercontent.com/17404386/40772807-4a84b9f8-64c1-11e8-89ed-da3fad97c07d.gif)

**Comment by danielkaradachki** [comment] 2018-06-01 09:16
Shouldn't the confirmation also be shown in a modal? How else is choosing an action enforced? If selecting an action should be optional and the problem is that the popup goes above the grid then you could use the [anchorViewportLeave](https://www.telerik.com/kendo-angular-ui/components/popup/closing/#toc-after-leaving-the-viewport) event to close it.

In general, I don't think that we should introduce a scroll event. The event is fired quite often and will probably cause performance issues if the grid emits it in the zone. It should still be possible to handle the scroll by binding handler to the element with class `k-grid-content` via JavaScript.

**Closed by danielkaradachki** 2018-06-01 09:16 UTC
Labels: pkg:grid
