### ISSUE TITLE
[Bug] DropDownList with filtering not always closing

### ISSUE THREAD

**Issue by asd123321** [telerik/kendo-angular#1606] opened 2018-06-12 08:53 UTC
## I'm submitting a...

* Bug report 

## Current behavior

When you open DropDownList (with filtering enabled), you cannot close it by clicking outside the component. The component closes every second time.

## Expected behavior

It should be possible every time to close the DropDownList with filtering enabled by clicking outside of it, like it is in the DropDownList without filtering.

## Minimal reproduction of the problem with instructions

The problem is noticeable in your documentation. Steps to reproduce:
  1. Open [the documentation](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/#toc-basic-configuration)
  2. In Basic Configuration Example open the DropDownList
  3. Close it by clicking somewhere else
  4. Open it again
  5. Try to close it again by clicking outside

Browser:
- Chrome (desktop) version 67.0.3396

**Comment by tsvetomir** [comment] 2018-06-12 10:44
Duplicate of #1368

The issue is fixed in v3.0.2 of the `@progress/kendo-angular-dropdowns` package. The site is still using an older version - we'll publish an update in the next few days.

**Closed by tsvetomir** 2018-06-12 10:44 UTC
Labels: Duplicate, pkg:dropdowns
