### ISSUE TITLE
Accessibility issue with kendo-datepicker

### ISSUE THREAD

**Issue by aasis21** [telerik/kendo-angular#3261] opened 2021-04-01 07:36 UTC
**Describe the bug**
We are using the kendo-datepicker in our application and we are trying to reconcile accessibility issues outlined by the FastPass tool (documented in this [blog post](https://www.telerik.com/blogs/the-need-for-automated-accessibility-testing)). Fastpass is finding accessibility issue with kendo-datepicker, I tried running fastpass on kendo-datepicker example on kendo-documentation page and found similar issue. The one I am specifically looking is "Ensures ARIA attributes are allowed for an element's role".

![image](https://user-images.githubusercontent.com/25389384/113259464-014a9180-9282-11eb-99e4-b89cc9f62d50.png)

**To Reproduce**

- Go to this kendo doc page: https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/
- Get accessibility insights extension for web and run fastpass on the above page. https://accessibilityinsights.io/docs/en/web/overview/ 
- Do inspect element on basic usage example
**Expected behavior**
Fastpass should not find any accessibility issue with kendo-datepicker. Please let me know if there is any custom parameter which can be passed to kendo-datepicker to change aria-expandable attribute,

**Browser**
 - New edge, chrome

**Comment by mbechev** [comment] 2021-04-09 14:22
Closing this as a duplicate of #1707

**Closed by mbechev** 2021-04-09 14:22 UTC
Labels: Duplicate, Team1, pkg:date-inputs
