### ISSUE TITLE
DatePicker error when manually entering date in IE11

### ISSUE THREAD

**Issue by DieterDS1983** [telerik/kendo-angular#538] opened 2017-05-09 09:08 UTC
Hi,

When I manually enter a date in the DatePicker control, the date is changed to NaN/NaN/NaN.
This happens on IE11 as soon as I change the year part of the date.

No problems in Edge/Chrome

Best regards.

**Comment by ggkrustev** [comment] 2017-05-09 12:18
Indeed, the issue is reproducible using the DatePicker component (the same problem was fixed in DateInput while ago).

I will post a update in this thread once the issue is resolved.

**Comment by siyka-marinova** [comment] 2017-05-30 14:08
Fix for this issue should be released shortly (currently available @dev).

**Comment by DieterDS1983** [comment] 2017-05-31 07:40
Thanks for the update.

**Comment by tsvetomir** [comment] 2017-06-07 09:03
Fixed in v1.0.2 of kendo-angular-date-inputs

**Closed by tsvetomir** 2017-06-07 09:03 UTC
Labels: Bug, Passed-QA, pkg:date-inputs
