### ISSUE TITLE
Bug: splitter pane doesn't resize with changeDetection strategy OnPush

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1343] opened 2018-02-27 09:40 UTC
## I'm submitting a...
* Bug report 

## Current behavior
SplitterPane can not be resized.

## Minimal reproduction of the problem with instructions
Run [this Plunkr](https://plnkr.co/edit/e8DO6om9gsX6MpEMczXV?p=preview).
First one works (resizing) and second one does not.

### Sugestion
It would be nice if changeDetection strategy OnPush would be more tested with Telerik team. I just spend 2 hours upgrading/downgrading Angular/rxjs/progress npm packages, pulling all code from Git, trying to prepare a plunkr, removing code from my project until I found the source of problem. It really doesn't occur to me that I should check changeDetection strategy. 

I know OnPush is not default for Angular application, but I am pretty sure everyone is using it in any serious project. So maybe you should consider using it in all demo plunkrs.

**Comment by prabh-62** [comment] 2018-03-24 02:53
Just tried the `@progress/kendo-angular-layout@dev` package, still unable to use `LayoutModule` with `ChangeDetectionStrategy.OnPush`.

**Comment by gyoshev** [comment] 2018-03-29 12:48
We are currently working on a resolution for this issue, and it should be included in an upcoming version in the near future.

A workaround for the problem is to call `markForCheck()` on the Angular change detector in the splitter `layoutChange` event. Here is [a plunker](https://plnkr.co/edit/c98yhHTC5uERwRI15Lx1?p=preview) that shows this approach.

**Comment by gyoshev** [comment] 2018-04-02 09:01
A fix for this problem has been pushed on the [development build channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the layout package. The fix will be included in the next official version.

**Comment by gyoshev** [comment] 2018-05-02 14:41
The fix is included in `@progress/kendo-angular-layout@3.0.0`.

**Closed by gyoshev** 2018-05-02 14:41 UTC
Labels: Bug, pkg:layout
