### ISSUE TITLE
Grid Buttons not working with pagination in production build. Getting error-- "ERROR TypeError: Cannot read property 'value' of undefined at e.emitCRUDEvent"

### ISSUE THREAD

**Issue by lohith4694** [telerik/kendo-angular#2660] opened 2019-12-26 12:48 UTC
** Bug Description**
The bug is in production build. when we trying to delete a row data after going to page 2 of the Grid-, I'm getting Error as- "ERROR TypeError: Cannot read property 'value' of undefined at e.emitCRUDEvent"

We are adding the row data manually one by one with page size 5 and once we added more than 5, the pages 2,3 enabled and hence I want to edit or delete the data from any page, which is not working and giving the error as the attached image below.
My project is of Angular 4 framework and so tried to install @progress/kendo-angular-buttons@4.4.2-dev.201905290935 as I have @progress/kendo-angular-buttons@4.4.2 but still it didn't worked. It is working fine in Local but not in Production.

Please help.

**Screenshots**
![SSL562Error](https://user-images.githubusercontent.com/39521449/71476571-b7b40100-280b-11ea-85be-4d98988c97af.png)

Attaching Package.json in comments

**Comment by lohith4694** [comment] 2019-12-26 12:50
"dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@auth0/angular-jwt": "1.1.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@progress/kendo-angular-buttons": "^4.4.2-dev.201905290935",
    "@progress/kendo-angular-dateinputs": "^1.4.3",
    "@progress/kendo-angular-dialog": "^2.0.0",
    "@progress/kendo-angular-dropdowns": "^1.6.0",
    "@progress/kendo-angular-excel-export": "^1.0.5",
    "@progress/kendo-angular-grid": "^3.5.0",
    "@progress/kendo-angular-inputs": "^1.4.2",
    "@progress/kendo-angular-intl": "^1.3.0",
    "@progress/kendo-angular-l10n": "^1.0.7",
    "@progress/kendo-angular-layout": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.0.0",
    "@progress/kendo-angular-sortable": "^1.0.8",
    "@progress/kendo-angular-treeview": "^2.3.1",
    "@progress/kendo-angular-upload": "^2.1.1",
    "@progress/kendo-data-query": "^1.1.2",
    "@progress/kendo-drawing": "^1.4.0",
    "@progress/kendo-theme-default": "^2.47.0",
    "@types/dwt": "^14.2.1",
    "angular2-virtual-scroll": "^0.3.2",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "classlist-polyfill": "^1.2.0",
    "cldr-data": "^32.0.1",
    "core-js": "^2.4.1",
    "dwt": "^14.3.1",
    "easy-autocomplete": "^1.3.5",
    "hammerjs": "2.0.8",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "ng2-daterangepicker": "^2.0.12",
    "ng2-drag-drop": "^3.0.2",
    "ng2-dragula": "^1.5.0",
    "ngx-bootstrap": "^1.9.3",
    "ngx-malihu-scrollbar": "^1.3.2",
    "node": "^8.11.0",
    "object-assign": "^4.1.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.5.6",
    "underscore": "^1.8.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.3",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/node": "^7.0.13",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/underscore": "^1.8.7",
    "@types/webpack": "^2.2.15",
    "add-asset-html-webpack-plugin": "^1.0.2",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "^3.5.0",
    "codelyzer": "~2.1.1",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "^2.5.2",
    "json-loader": "^0.5.4",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "~2.0.3",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~2.0.0",
    "node-sass": "^4.5.2",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "^1.2.2",
    "protractor": "^5.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.3",
    "script-ext-html-webpack-plugin": "^1.7.1",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.2.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.0.2",
    "tslib": "^1.6.1",
    "tslint": "~4.5.1",
    "tslint-loader": "^3.5.2",
    "typedoc": "^0.7.1",
    "typescript": "~2.8.0",
    "url-loader": "^0.5.8",
    "webpack": "~2.6.1",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "~2.4.2",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  }

**Comment by dtopalov** [comment] 2020-06-08 15:13
The error seems to be caused by a missing FormGroup and thus a failing attempt to obtain its value. However, we are unable to determine the exact problem, based on the provided information only.

As Angular 4 and all older Kendo UI for Angular packages versions compatible with it are no longer officially supported, I can suggest upgraded to a supported version of the Angular framework (8+) and the latest versions of all of our packages.

If you still need assistance with resolving the problem using the obsolete versions of Angular and the Kendo packages, please [open a support ticket](https://www.telerik.com/account/support-tickets), and attach an isolated runnable project where the exact Grid setup and configuration, as well as the described error, can be observed, so our support team can try to suggest a solution, if one is available.

**Closed** 2020-06-08 15:13 UTC
Labels: Question, pkg:grid
