### ISSUE TITLE
Kendo Dropdown open position not properly align

### ISSUE THREAD

**Issue by DnyaneshBaravkar** [telerik/kendo-angular#2725] opened 2020-02-04 05:23 UTC
When choosing the middle or last option of dropdown menu open position is different.

I'm using angular material theme in my project.

package.json
"@progress/kendo-theme-default": "^4.1.0",
"@angular/material": "^8.1.2",
"@progress/kendo-angular-dropdowns": "^4.0.0",

![image](https://user-images.githubusercontent.com/44089859/73716082-08d4e000-473c-11ea-891d-7600f0aae003.png)

**Comment by tapopov** [comment] 2020-02-04 11:37
Hello @DnyaneshBaravkar 

I am closing this as I am unable to reproduce the issue with the provided information.

Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.

**Closed by tapopov** 2020-02-04 11:37 UTC
