### ISSUE TITLE
DateInput / DatePicker gives current time when entering value with keyboard

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#532] opened 2017-05-05 17:13 UTC
It only happens when you start with a null / undefined value bound. 

See plunker:
http://plnkr.co/edit/DXG4kxU1my6ySLkOOftH?p=preview

Behavior is the same for date picker and date input.

Picking a date from the calendar gives a correct time (00:00:00)

**Comment by ggkrustev** [comment] 2017-05-09 12:16
Indeed, the DateInput will use `now` time instead of midnight (00:00:00) as default. IMO that this is intended behavior. Unfortunately, it causes confusion and we will change it to midnight time to have a consistent behavior with other Date components.

I will post here once the fix is published.

**Comment by siyka-marinova** [comment] 2017-05-26 07:55
Fix for this issue will be available in version 1.0.2 of kendo-angular-date-inputs package

**Closed** 2017-06-02 08:31 UTC
Labels: Bug, Needs-QA, pkg:date-inputs

**Comment by siyka-marinova** [comment] 2017-06-02 08:32
Fixed in verison 1.0.2 (2017-06-01)
