### ISSUE TITLE
Setting Combobox popupSettings property makes problem

### ISSUE THREAD

**Issue by semtos** [telerik/kendo-angular#355] opened 2017-03-07 13:18 UTC
From the plnkr below, after scrolling down the content, each selection is scrolled to top. Thus, selection is not possible.

http://plnkr.co/edit/wKIckOlj92XHiTKdwHbx?p=preview

I need to set popupSettings property dynamically from typescript, not statically from html. Can you help me with this ?

**Comment by tapopov** [comment] 2017-03-07 15:26
Hi @semtos 

The component will detect changes in its [popupSettings] attribute and will adjust the popup element accordingly. See example below:
http://plnkr.co/edit/RbnMAAYKOZaUxxA4YDAz?p=preview

This means that changing the AppComponent's DropDownHeight propery programmatically should change the popup dimensions as well.

**Comment by semtos** [comment] 2017-03-07 15:49
Hi @tapopov ,

That is not what I mention. The problem is that you can not select any item from the list and you are throwed up to the first element. Please select the item at the end of dropdown and you will understand what I mean.

**Comment by tapopov** [comment] 2017-03-08 08:48
Hi @semtos, 

Thank for clarifying. Indeed I managed to reproduce the issue and will continue investigating what's causing it. Stay tuned for updates!

**Comment by tapopov** [comment] 2017-03-22 13:54
Hey @semtos 

The issue appeared because returning a new object instance triggered the component's ngOnChanges, where the previous value was re-applied. This is now fixed with v0.37.1

**Closed** 2017-03-22 15:00 UTC
Labels: Needs-QA, pkg:dropdowns
