### ISSUE TITLE
ComboBox cannot be opened with ~1000 options in IE11

### ISSUE THREAD

**Issue by alexeykostevich** [telerik/kendo-angular#1262] opened 2018-01-26 14:18 UTC
## I'm submitting a...

* Bug report 

## Current behavior

It is almost impossible to open a _ComboBox_ with 1000 options in _IE11_. A _ComboBox_ unexpectedly loses focus and collapses instead of opening.

## Expected behavior

A _ComboBox_ opens and let a user select an option regardless of the number of options. However, the large number of options can cause reasonable freezing and delays in _IE_.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/Yl6pIiMLqD8uoqQPsYaV?p=preview

## What is the motivation or use case for changing the behavior?

Having data sources of medium size in business applications is common.  It is essential for users to be able to browse such data sources and select a necessary item.

## Environment

Package versions:

```
+-- @angular/animations@5.2.2
+-- @angular/cli@1.6.5
+-- @angular/common@5.2.2
+-- @angular/compiler@5.2.2
+-- @angular/compiler-cli@5.2.2
+-- @angular/core@5.2.2
+-- @angular/forms@5.2.2
+-- @angular/language-service@5.2.2
+-- @angular/platform-browser@5.2.2
+-- @angular/platform-browser-dynamic@5.2.2
+-- @angular/router@5.2.2
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-dateinputs@1.4.4
+-- @progress/kendo-angular-dialog@2.0.0
+-- @progress/kendo-angular-dropdowns@1.6.0
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.7.2
+-- @progress/kendo-angular-inputs@1.4.2
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.2.0
+-- @progress/kendo-angular-popup@1.3.3
+-- @progress/kendo-angular-upload@2.1.1
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-date-math@1.1.1
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-default@2.47.0
+-- core-js@2.5.3
+-- rxjs@5.5.6
+-- typescript@2.6.2
+-- zone.js@0.8.20
```

Browser:

- IE version 11

System:
- TypeScript version: 2.6.2
- Node version: 8.9.4 (npm 5.6.0)
- Platform:  Windows

There was a visually similar issue caused by slow rendering performance of attribute selectors in IE11 (which are heavily used in our app): https://github.com/telerik/kendo-angular/issues/1096

However, this issue is reproducible even in demo examples without the use of attribute selectors.

**Comment by alexeikostevich** [comment] 2018-01-26 15:39
Could I ask whether it is possible to fix this issue with reasonable effort? I can imagine that the issue is caused by bad IE performance and can be challenging.

This being the case, we will proceed with another approach (like displaying [a pageable grid with selection](https://www.telerik.com/kendo-angular-ui/components/grid/selection/)) as a workaround.

What data source size would you recommend to use with Kendo UI DropDowns?

**Comment by tapopov** [comment] 2018-01-29 17:40
Hi @alexeikostevich 
Indeed, the issue is related to IE's performance and while we will investigate further, at this point there's not much we can do. My advice is to initialize the component with as few items as possible and solely rely on its filtering capabilities. Scrolling through hundreds of items is not particularly good UX anyways.

**Comment by alexeikostevich** [comment] 2018-01-30 18:57
Hello @tapopov ,

Thank you for the advice! I fully agree with your point.

While we try to limit the number of options in drop-downs where it is possible, there are a couple of scenarios where it is difficult to achieve.

This stems from enterprise applications using by companies that vary significantly in their sizes and the amount of data they produce. While small/medium companies would like to have an ability to see a list of all available options in a drop-down, the largest usually use just filtering instead. Unfortunately, our application has to address both use cases.

Fundamentally, virtualization would solve all issues and cover our requirements. Here are related feature requests:
- [DropDownList Virtualization](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/31559278-dropdownlist-virtualization)
- [Virtualization support for AutoComplete & MultiSelect controls](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19042537-virtualization-support-for-autocomplete-multisel)

This feature could be a game changer for awesome Kendo UI DropDowns!

**Comment by alexeikostevich** [comment] 2018-02-12 10:58
Dear @tapopov ,

Please, could I ask you whether there is any roadmap for these feature requests?
- [DropDownList Virtualization](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/31559278-dropdownlist-virtualization)
- [Virtualization support for AutoComplete & MultiSelect controls](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19042537-virtualization-support-for-autocomplete-multisel)

Unfortunately, this feature is really essential for our product suite, and we are going to start working on this shortly. Understanding the plans could be extremely helpful and let to adjust development accordingly.

Thank you!

**Comment by tapopov** [comment] 2018-02-12 11:45
Hi @alexeikostevich 
While we are well aware of the necessity for both data and UI virtualization, the feature is not yet scheduled for implementation. 
We will update our [Roadmap](https://www.telerik.com/kendo-angular-ui/roadmap/) once a specific time-frame is set.

**Comment by alexeikostevich** [comment] 2018-02-12 11:51
That's good to know! Thank you so much for sharing, @tapopov !

**Comment by alexeikostevich** [comment] 2018-02-12 11:56
That's good to know! Thank you so much for sharing, @tapopov !

**Comment by pooya1361** [comment] 2018-03-01 09:25
Hi,
I just want to say that we have exactly the same problem in IE. @tapopov  have you found any work around for this issue?
BR,

**Comment by scatcher** [comment] 2018-03-22 22:14
We're having the same issue.  The control in unusable in IE with 1000+ options.

**Comment by pooya1361** [comment] 2018-03-22 22:16
Use filter to reduce the amount of options

**Comment by scatcher** [comment] 2018-03-22 22:21
Not sure what you mean, they are all valid options.

**Comment by jameswilson281** [comment] 2018-03-22 22:29
@scatcher Yeah, man, just remove all the options and it'll perform great!  

All joking aside, we are having this same issue.  While "just show fewer options" would be an ideal solution, real world requirements sometimes preclude us from the "ideal solution".

We are loving the KendoUI work, however this one issue is a huge thorn in our side.

**Comment by MaklaCof** [comment] 2018-03-23 06:11
I really can't understand why filter is such a big problem. 

I am pretty sure you also have some table with 10 thousands, 100 thousands, million or more records and you don't display all records in grid.

Also allow user to scroll through 1000+ records is also poor design.

The best solution, if filtering is unacceptable, I see in [this feature request](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/17816359-infinite-scrolling-for-grid) if it would be implemented (for Grid and DropDowns).

**Comment by jameswilson281** [comment] 2018-03-23 06:59
> I really can't understand why filter is such a big problem.

I'm sorry you aren't understanding.

> I am pretty sure you also have some table with 10 thousands, 100 thousands, million or more records and you don't display all records in grid.

You are comparing apples to oranges here.  I'm not sure if you are being sarcastic but I'll assume the best and just say that I'm not sure how making this kind of assumption is constructive to the issue at hand.

>Also allow user to scroll through 1000+ records is also poor design.

Stating this when you have no idea what our requirements are is a bit ignorant, don't you think?  The real world is full of projects with requirements that don't always fit into the nice little box of superficial hello-world-todo-list examples repeated ad nauseum on the web.

>The best solution, if filtering is unacceptable, I see in this feature request if it would be implemented (for Grid and DropDowns).

Thank you for the suggestion here, but I'm afraid infinite scroll isn't what we're looking for.  

I was hoping to find some solution to the issue at hand, which is that the control becomes unusable in IE, and, should there not be a known solution, adding my voice to the list of developers experiencing this issue (which is, after all, what these issue threads are for).

**Comment by MaklaCof** [comment] 2018-03-23 07:24
My intention was definitely not sarcastic.  
I only wanted to say that some things simply can not be achieved. You can not pull 10 tons trailer with personal car.

Probably the best solution is virtualization and as kendo team already respond:

> While we are well aware of the necessity for both data and UI virtualization, the feature is not yet scheduled for implementation.

I wanted to say that filtering is probably the only option right now. You can also upvote [feature request for virtualization](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19042537-virtualization-support-for-autocomplete-multisele).

**Comment by tapopov** [comment] 2019-04-12 11:40
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/2195

**Closed by tapopov** 2019-04-12 11:40 UTC
Labels: Question, pkg:dropdowns
