### ISSUE TITLE
Inputs: AoT errors 

### ISSUE THREAD

**Issue by udos86** [telerik/kendo-angular#311] opened 2017-02-19 20:41 UTC
Hi there!

When trying to do AoT compilation some errors are thrown by the Angular compiler CLI for the package `@progress/kendo-angular-inputs`:

```
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/maskedtextbox/maskedtextbox.component.ngfactory.ts(275,35): error TS2346: Supplied parameters do not match any signature of call target.
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/maskedtextbox/maskedtextbox.component.ngfactory.ts(279,35): error TS2346: Supplied parameters do not match any signature of call target.
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/maskedtextbox/maskedtextbox.component.ngfactory.ts(283,35): error TS2346: Supplied parameters do not match any signature of call target.
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/numerictextbox/numerictextbox.component.ngfactory.ts(195,41): error TS2341: Property 'widgetClass' is private and only accessible within class 'NumericTextBoxComponent'.
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/numerictextbox/numerictextbox.component.ngfactory.ts(200,41): error TS2341: Property 'numericClass' is private and only accessible within class 'NumericTextBoxComponent'.
example/aot/node_modules/@progress/kendo-angular-inputs/dist/es/numerictextbox/numerictextbox.component.ngfactory.ts(214,48): error TS2445: Property 'hostBlur' is protected and only accessible within class 'NumericTextBoxComponent' and its subclasses.
```

Thanks for fixing this!

**Comment by ggkrustev** [comment] 2017-02-20 08:43
Hi @udos86, we've got CI builds that run against the latest kendo-angular packages and test the AOT support. Currently, *they pass without any errors*. 

More details about our setup:
- Our builds use [**@angular/cli**](https://www.npmjs.com/package/@angular/cli). Before that we used [angular-cli](https://www.npmjs.com/package/angular-cli), but it is outdated now.
- typescript@~2.0.x is the version of typescript

Could you let me know what is the difference in your setup or even could you provide a repro demo? This will help us to replicate the issue locally, find a fix and avoid such problems in future.

**Comment by udos86** [comment] 2017-02-20 09:08
@ggkrustev Thanks for the quick response.

The difference between your setup and mine is that I'm executing AoT-compilation [manually](https://github.com/udos86/ng2-dynamic-forms/blob/master/package.json) via `@angular/compiler-cli` using a seperate [tsconfig](https://github.com/udos86/ng2-dynamic-forms/blob/master/tsconfig.aot.json).

In general, Angular CLI seems to be less restrictive. Being a SDK developer myself, I can tell that my libs was only throwing some transpile errors when running AoT with @angular/compiler-cli.

**Comment by ggkrustev** [comment] 2017-02-21 13:16
@udos86, thanks for the additional details.

I made a fresh clone of `ng2-dynamic-forms` repo and npm installed all dependencies. The @angular/cli is `@angular/cli: 1.0.0-beta.32.3` and typescript is `typescript@2.2.0`. 

The `compile:app:aot` run **without errors** or whatsoever (tested and the other `npm` tasks).

I am really confused why the errors are not reproducible on our end. Am I missing something obvious?

**Comment by tsvetomir** [comment] 2017-02-21 13:29
Perhaps `rm -rf node_modules` can help NPM sort itself out.

**Comment by tsvetomir** [comment] 2017-02-21 14:51
The reason is that we don't see any errors is that the Kendo UI components are [commented out](https://github.com/udos86/ng2-dynamic-forms/blob/master/example/app/app.module.ts#L19) on the master branch.

We'd appreciate it if you can prepare a branch where running `npm run compile:app:aot` fails with the errors provided initially.

**Comment by udos86** [comment] 2017-02-21 19:45
@tsvetomir Please pull the latest updates into master and execute `npm run compile:app:aot` again. You'll see the errors mentioned above appearing in the command line.

**Comment by tsvetomir** [comment] 2017-03-10 14:04
Sorry for taking so long. The problem should be fixed in 0.19.2 of the **@progress/kendo-angular-inputs** package.

**Comment by udos86** [comment] 2017-03-10 21:17
@tsvetomir Yep, thanks 👍

**Comment by ggkrustev** [comment] 2017-03-13 16:04
Guys, will close the issue as resolved. @udos86 please re-open it if smth doesn't work.

**Closed by ggkrustev** 2017-03-13 16:04 UTC
Labels: Bug, pkg:inputs
