### ISSUE TITLE
Splitter doesn't work in Internet Explorer 10

### ISSUE THREAD

**Issue by shawnhancock** [telerik/kendo-angular#1408] opened 2018-03-26 13:25 UTC
## I'm submitting a...

* Bug report 

## Current behavior

The Splitter doesn't work in Internet Explorer 10 and thus breaks our UI. Whether or not this can be fixed without affecting other browsers will depend on whether we support IE10 going forward. 

## Minimal reproduction of the problem with instructions

View the Basic Usage example in IE10:
https://www.telerik.com/kendo-angular-ui/components/layout/splitter/

## Environment

Browser:

- IE version 10

**Comment by gyoshev** [comment] 2018-03-29 08:27
We have reproduced the problem and are working on fixes in the theme and the splitter component that will adjust the layout in IE10. I'm afraid that there isn't a simple workaround for this issue; we'll strive to release the new versions promptly.

**Comment by Kevat** [comment] 2018-04-19 13:56
When might this issue be fixed? We need to decide if we should use the kendo-splitter or create our own for now since supporting IE 10 is a must have for us. Do expect the issue to be fixed within the next month?

**Comment by gyoshev** [comment] 2018-04-19 15:10
@Kevat the fix in the layout package will be released by the start of next week, and the theme is already patched.

**Comment by Kevat** [comment] 2018-04-19 18:19
@gyoshev Thank you for the prompt response, that is very helpful! We are looking forward to the next release of the layout package.

**Comment by Kevat** [comment] 2018-05-01 14:02
@gyoshev Was this fix released yet? We would really like to test it out and verify that IE 10 will be supported for our next release.

**Comment by gyoshev** [comment] 2018-05-03 10:59
@Kevat the version has been released on the development channel for some time now, and we just published the version to the official channel. Please update to `@progress/kendo-angular-layout@3.0.0` to get the fixes. In order for pane collapsing to work properly, it requires the development build of the theme `@progress/kendo-theme-default@dev`, which should be pushed to the official channel by the end of the week.

**Comment by gyoshev** [comment] 2018-05-09 14:00
Pane collapsing is fixed for IE10 in `@progress/kendo-theme-default@2.52.0`.

**Closed by gyoshev** 2018-05-09 14:00 UTC
Labels: Bug, pkg:layout

**Comment by Kevat** [comment] 2018-05-17 14:27
@gyoshev I have verified that the fix work with the latest pacakges and default theme. Will you be implementing this fix for the bootstrap theme as well?
