### ISSUE TITLE
[TreeList] Resizing TreeList locked column groups causes misalignment

### ISSUE THREAD

**Issue by tswetti** [telerik/kendo-angular#4123] opened 2023-10-10 07:26 UTC
**Describe the bug**
When the TreeList has two or more locked column groups, resizing any of the columns causes misalignment. Sometimes the drag handle disappears until another column is resized.

https://github.com/telerik/kendo-angular/assets/65012268/cda1895f-801a-4b8a-8e4d-4de3d6779514

**To Reproduce**
https://stackblitz.com/edit/angular-pkmreb?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The columns are aligned properly.

**Comment by destus90** [comment] 2023-10-25 04:09
Duplicate of #4069 ?

**Closed** 2023-10-25 06:07 UTC
Labels: Duplicate, Team2, pkg:treelist
