### ISSUE TITLE
TimePicker not working as expected when the page is zoomed

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1111] opened 2017-11-27 09:00 UTC
When the page is zoomed in (e.g. 125%), only even hours can be selected in the TimePicker, and when the user clicks on an odd hour, the closest even hour is selected instead. Observable in the online demos:

[https://www.screencast.com/t/m34nlYfg](https://www.screencast.com/t/m34nlYfg)

**Comment by basdima2** [comment] 2017-11-29 06:53
The same problem, almost on all laptops with Windows 10. The problem can be observed even on the official demo page.

**Comment by ggkrustev** [comment] 2017-11-29 08:27
Hi @basdima2,

Currently, TimePicker supports only zoom 100% or less. We will try to add support for zoomed page soon. We will update the thread once there is more information.

**Comment by PauwelsBart** [comment] 2018-01-23 08:31
We are having this problem with zoom 100%. Zoom 80% is working...

We are testing in Chrome 63.0.3239.132 (Officiële build) (64-bits)

**Comment by mbx338** [comment] 2018-01-26 19:43
This is happening with a browser zoom set to 100% as well if the zoom in Windows (**Control Panel > Display > Make text and other items larger or smaller**) is set to something other than 100%. 

Most laptops are set to 125% or 150%, so this is impacting a large number of systems out there.

Please let us know of any updates regarding this bug as soon as possible.

Thank you.

**Comment by JeremiahWill29** [comment] 2018-01-26 19:54
I have had this issue when the windows zoom is set to something larger 100%. This is a big issue as many people are affected, it makes the user interface/experience clunky, and there is no easy workaround.

Please fix or provide a workaround.

**Comment by ggkrustev** [comment] 2018-03-07 07:40
Should be fixed in the latest release of the `@progress/kendo-angular-dateinputs` package. Please comment if the issue is still present.

**Closed by ggkrustev** 2018-03-07 07:40 UTC
Labels: Bug, Needs-QA, pkg:date-inputs
