### ISSUE TITLE
Grid scrollBottom event on Chrome

### ISSUE THREAD

**Issue by LeoLetourneur** [telerik/kendo-angular#2020] opened 2019-01-15 09:05 UTC
## I'm submitting a...
* Support requests to https://www.telerik.com/account/support-tickets

* Bug report 

## Current behavior
(scrollBottom) event on the grid is not fired on Chrome. The event is fired on Firefox.

## Expected behavior
The event is fired when scrolling to bottom.

## Minimal reproduction of the problem with instructions

All exemple from the doc in stackblitz with (scrollBottom) event are broken.
Like the "Endless Scrolling" exemple in https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/

## Environment

Package versions:
Angular 6-7
kendo-angular-grid 3.11.0

Browser:

- Chrome (desktop) version 71.0.3578.98

System:
- TypeScript version: 3.1.1
- Node version: 10.14.2  npm 6.4.1
- Platform:  Windows

**Comment by tsvetomir** [comment] 2019-01-15 09:35
Tried [the example in StackBlitz](https://stackblitz.com/edit/angular-6wezeu?file=app/app.component.ts) with Chrome 71, but the event seems to fire normally.

![scrollend](https://user-images.githubusercontent.com/247917/51171455-a18e8880-18b9-11e9-9e37-03c6fde4ac62.gif)

**Comment by danielkaradachki** [comment] 2019-01-15 09:37
The examples also work on my machine - [screen cast](https://www.screencast.com/t/oID58w0NEYwx). Try clearing the cache and running the examples in incognito mode in case there is an extension that prevents the default browser behavior.

**Comment by LeoLetourneur** [comment] 2019-01-15 10:10
Thanks for the quick answer !

I tried to:
- Clear my cache, nothing better.
- Remove one by one all my chrome extensions, nothing better.
- Incognito mode, it works.
- Reboot a clear chrome, it works.

Assuming it was an adblock or "Puge ruler" extension... 

Many thanks !

**Comment by LeoLetourneur** [comment] 2019-01-15 10:31
Thanks for the quick answer !

> The examples also work on my machine - [screen cast](https://www.screencast.com/t/oID58w0NEYwx). Try clearing the cache and running the examples in incognito mode in case there is an extension that prevents the default browser behavior.

I tried to:

Clear my cache, nothing better.
Remove one by one all my chrome extensions, nothing better.
Incognito mode, nothing better.

I tried on my second screen, it works...

I have two screens : 
- Laptop screen :  1920 * 1080 (default & recommended) zoom 125% (default & recommended)
- External screen :  1920 * 1080 (default & recommended) zoom 100% (default & recommended)

Assuming, zoom is breaking the scroll ? How can it be possible ?

Many thanks !

**Comment by danielkaradachki** [comment] 2019-01-15 11:20
Thanks for clarifying. Seems that the zoom causes incorrect sub-pixel scrollTop position in Chrome. We will look into it.

**Comment by danielkaradachki** [comment] 2019-02-05 13:34
Should be fixed in 3.12.0 and later

**Comment by velnet2k** [comment] 2019-04-23 14:35
Can we have the scrollBottom to fire just before it reach bottom like buffer of say 50px. it should ignore the zoom issue. do we have this feature?

**Comment by tsvetomir** [comment] 2019-04-24 05:34
@velnet2k are you still experiencing the issue with browser zoom and scrollBottom? Make sure you're using the latest version of the Grid: `npm install --save @progress/kendo-angular-grid@latest`.

**Comment by velnet2k** [comment] 2019-04-24 09:24
@tsvetomir Thanks for your reply on time. I was using little old version 3.14.0, after changing to latest it works till 110%, on 125% its not firing sometime. But for me 80-110% is good for now. Thanks

**Comment by tsvetomir** [comment] 2019-04-25 06:24
@velnet2k I couldn't reproduce the problem in [the demo](https://stackblitz.com/edit/angular-oal654?file=app/app.component.ts). What browser are you using?

**Comment by velnet2k** [comment] 2019-05-02 10:27
@tsvetomir I checked in given demo itself the scrollBottom not fireing after 3/4 times.. i tried in Chrome 90% zoom only 200 records loading but 100% its loading till 500 records. in 100% it works like charm.

**Comment by tsvetomir** [comment] 2019-05-03 08:03
@velnet2k should be fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Thanks!

**Comment by tsvetomir** [comment] 2019-05-15 10:12
Fixed in v3.14.2

**Closed by tsvetomir** 2019-05-15 10:12 UTC
Labels: Bug, Needs-QA, pkg:grid
