### ISSUE TITLE
[Scheduler] errors are raised while dragging/resizing event

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3195] opened 2021-02-01 08:52 UTC
**Describe the bug**

The following errors are raised sporadically while dragging / resizing an event:

TypeError: Cannot read property 'start' of undefined
TypeError: Cannot read property 'id' of undefined

**To Reproduce**

**Case 1 - Resizing**
The issue is reproduced in the following example:

https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/

The errors occur when you try clicking the event while the resize horizontal bar is visible in the event, but the cursor isn't resizable. Please see the following screen cast demonstrating the issue:

http://somup.com/crnVjdoKMj

**Case 2 - Dragging**
Again, open [the same demo as above](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/).

The bug is hard to reproduce, but occurs when a **drag** event is fired at the exact moment when a scheduler event element is being dragged **AND** the mouse cursor happens to be over the 1px-wide border between two event slots.

It is easier to reproduce when you use Ctrl and + to zoom in on the page, so that the borders are thicker.

Screen recording of the reproduction: 
https://user-images.githubusercontent.com/45083324/113278423-95504380-92ea-11eb-8ed0-4da686564919.mp4

**Comment by rsseurope** [comment] 2021-03-29 08:19
Issue is still not fully resolved in v2.1.2-dev.202102231512 but it is happening at a much lower rate. So it seems improved but not resolved. you can find a full stack trace of the exception at: https://sentry.io/share/issue/8200ec3f97ee4f99827d56414b441b0a/

**Comment by gkarapeev** [comment] 2021-03-29 13:32
Hello Tonie (@rsseurope),

Thank you for your reply.

I am unable to reproduce the bug from this issue as of v2.1.2-dev.202102231512.
The provided stack trace from Sentry points to some minified code which is not sufficient for us to reproduce the issue.

Would you be able to give us some more detailed instructions on how to reproduce the problem?

Best,
Georgi

**Comment by rsseurope** [comment] 2021-03-31 06:47
Here is a full stack trace from Sentry with source map. I hope this gives you enough information to tackle this problem.
https://sentry.io/share/issue/89d733c1ad824457b4f816c275521e42/

**Comment by gkarapeev** [comment] 2021-04-01 11:35
Hello Tonie,

Thank you for providing the source mapped version.
Using that, we were able to reproduce the issue and to figure out what is happening. I have updated this issue's description accordingly (Case 2 - Dragging).

When the user drags an event over the 1-pixel-wide border between two scheduler cells, if a drag event happens to fire at that exact moment, the error occurs.

Once we realized what is happening, we found a way to fix it.

The fix is now due to pass review and quality assurance. Once that is done, we will comment here, announcing that the fix is available in the latest development build.

Many thanks,
Georgi

**Comment by rsseurope** [comment] 2021-04-01 11:46
Very happy to read this! Do you think it will be available before our general update that is scheduled for 5-4-2021?

**Comment by gkarapeev** [comment] 2021-04-01 14:22
@rsseurope The proposed fix has to go through some additional discussion and testing in order to make sure we do it in the cleanest way possible. There are several ways to do it. That said, we don't want to make a promise we can't hold, but we will do our best to ship the fix as soon as possible.

**Comment by ipeshev** [comment] 2021-04-21 12:07
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds).

**Comment by gkarapeev** [comment] 2021-06-08 14:43
Released with version [2.1.2](https://www.telerik.com/kendo-angular-ui/components/scheduler/changelog/#4ca45933-f065-543c-869a-e29989087de0)

**Closed by gkarapeev** 2021-06-08 14:43 UTC
Labels: Bug, Team1, freq3: likely, pkg:scheduler, sev1: low
