### ISSUE TITLE
Tooltip issue @progress/kendo-angular-tooltip@1.1.1

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#1957] opened 2018-11-29 09:44 UTC
## I'm submitting a...

* Bug report 

## Current behavior

The **Tooltip** directive was not shown at the second time with the mouse move out and move in. 

![a](https://user-images.githubusercontent.com/9428909/49212999-420a1580-f3fe-11e8-9fbe-491a20ae98dc.gif)

## Expected behavior

Show tooltip every time

## Environment

The bug is found even in the official example code in the documentation for filterable [ComboBox](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/filtering/).

Package versions:

```
@progress/kendo-angular-tooltip: "^1.1.1"
```

Browser:

- Chrome (desktop) version 70.0.3538.110

System:
- TypeScript version: 3.1.6
- Node version: 10.7.0
- Platform:  Windows

**Comment by danielkaradachki** [comment] 2018-11-29 09:58
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/1943

**Closed by danielkaradachki** 2018-11-29 09:58 UTC
Labels: Duplicate, pkg:tooltip
