### ISSUE TITLE
Grid [height] binding working only first time

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#545] opened 2017-05-10 07:35 UTC
It can be seen [here](http://plnkr.co/edit/Zzx71sdatOyQIiJgQ1hh?p=preview), try to change value in the input - grid's height is not changed.

**Comment by meriturva** [comment] 2017-06-05 15:10
I can confirm issue. Any news here?
Thanks.

**Comment by gyoshev** [comment] 2017-06-12 09:27
Confirmed as a bug; we'll address it shortly. In the meantime, one can use the binding `[style.height.px]="heightProp"`, as [shown in this plunker](http://plnkr.co/edit/Y6QGBvBbggiNeOE2Y0Ji?p=preview).

**Comment by siyka-marinova** [comment] 2017-06-15 11:27
Fix for this issue should be released shortly (currently available in the latest dev version).

**Comment by siyka-marinova** [comment] 2017-06-15 11:32
Fixed in v1.2.0

**Closed** 2017-06-15 11:31 UTC
Labels: Bug, Passed-QA, pkg:grid

**Comment by tipag** [comment] 2017-06-20 08:08
I updated to 1.2.0 and it doesn't seem to work correctly. The height property now effects the whole grid and setting it multiple times changes the height of the grid but the content isn't affected. If I set the height to a value smaller than the content, the content just continues on below the grid instead of starting to scroll (I have set the scrollable option to scrollable).

Maybe I'm doing something wrong, but my code worked before this issue was introduced in a previous version.

**Comment by gyoshev** [comment] 2017-06-21 07:35
@tipag please verify that you have upgraded the theme along with the grid. The `height` property applies to the whole component since before the 1.0 release (see [this issue](https://github.com/telerik/kendo-angular/issues/310#issuecomment-295765883)).

**Comment by tsvetomir** [comment] 2017-06-21 07:59
Use `npm ls @progress/kendo-angular-grid` to confirm the installed version.

**Comment by tipag** [comment] 2017-06-22 05:51
Ok, sorry! As @gyoshev suggested the problem was related to an old version of the theme. I updated it and now everything works as expected. Thanks everyone for the help.
