### ISSUE TITLE
[MultiSelect] List options are lost after invalid filter and blur 

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1490] opened 2018-04-25 12:38 UTC
## I'm submitting a...

* Bug report 

## Current behavior
MultiSelect is losing popup options when invalid filter and blurred.

## Expected behavior
It should not lose it's popup items.

## Minimal reproduction of the problem with instructions
1. Open this [plunk sample](https://plnkr.co/edit/vIMWqNBpPslFDZYkkL8I?p=preview)
2. Try to search something that is not in the list and then blur the input.
3. Open the popup no items there

## Environment

Package versions:

```
broken in v3.0.0-dev.201804050943
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by valchev** [comment] 2018-04-27 08:50
Occurs because `filterChange` is not fired on blur.

**Comment by tsvetomir** [comment] 2018-04-27 09:29
So a duplicate of #1488?

**Comment by ipeshev** [comment] 2018-08-06 11:39
Fix is available in [latest dev version](https://github.com/telerik/kendo-angular-dropdowns/releases/tag/v3.0.3-dev.201808031552).

**Comment by tsvetomir** [comment] 2018-08-22 07:04
Shipped in v3.0.3

**Closed by tsvetomir** 2018-08-22 07:04 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
