### ISSUE TITLE
Kendo-DateInput - Change your mind by clicking into the month portion of the date

### ISSUE THREAD

**Issue by gutierfe** [telerik/kendo-angular#3646] opened 2022-04-15 16:30 UTC
**Describe the bug**
Month portion of the date input ignores first key after editing it the second time without leaving the control or using the navitation keys.

**To Reproduce**

1. Go to https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/
2. Click on the Example's date input
3. Type 02022020
4. Without leaving the control and without using the navigation keys (← or →), click on the month portion of the date input using the mouse.
5. Type 01312010
6. The resulting input date is: 03/12/0010

**Expected behavior**
The resulting input date should be 01/31/2010

**Screenshots**
Just after typing the first 0 from 01312010 the date input ignores it and places the month placeholder.
![image](https://user-images.githubusercontent.com/2044041/163595956-771ca2e2-6f7f-450a-ad11-12f7265bfb39.png)

Without the first 0, the 1 is added, however, after the 3 is typed, it replaces the 1 because there is no month 13th.
![image](https://user-images.githubusercontent.com/2044041/163596229-5e968993-5d6f-4261-9bdd-9fe141d73d77.png)

**Browser**
 - OS: Windows 10
 - Browser Brave
 - Version V1.37.116

**Comment by stnikolova** [comment] 2023-12-14 13:23
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/3409

**Closed by stnikolova** 2023-12-14 13:23 UTC
Labels: pkg:date-inputs, Team1
