### ISSUE TITLE
[UI] menu not responsive when larger than parent

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1555] opened 2018-05-24 00:59 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When the menu is larger than the parent, the background-style stops before the scroll. 
Also, an option to fold the menu when it is larger than the parent component would be nice.

## Expected behavior
The background style should be propagated where the menu is not visible.
It would be nice if there was an option to fold the menu or put it on two lines.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/JvilOJjN8sXfXacwYUGx?p=preview

## What is the motivation or use case for changing the behavior?
UX, not having to modify the kendo theme and make conditionals to resize the menu.

**Comment by gyoshev** [comment] 2018-06-06 12:15
The issue is triggered when there is not enough space for the items in the menu container.

The latest theme version on the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) will wrap the menu items when there is not enough space in their container. Here is the [updated plunker](https://plnkr.co/edit/NDIowox50OlGIj15HdNg?p=preview) that shows this in action. The fix will be released in the next official version of the theme.

**Comment by Neaco** [comment] 2018-06-07 01:12
Thanks, looks great !

**Comment by danielkaradachki** [comment] 2018-07-06 10:21
The fix is available in the latest version.

**Closed by danielkaradachki** 2018-07-06 10:21 UTC
Labels: Bug, Styling, pkg:menu
