### ISSUE TITLE
Dropdownlist valuePrimitive=true the selectionChange $event Value not primitive

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#2005] opened 2019-01-02 13:18 UTC
## I'm submitting a...
Bug report 

## Current behavior

kendo-dropdownlist with valuePrimitive=true returns in "selectionChange" Event the complexe object and not the primitive value. I was using a older Version from the dropdownlist here the value was returned, is this a breaking change or just a bug

## Expected behavior
the selectionChange method returns the primitive value and NOT the complex object

## Environment
https://stackblitz.com/edit/angular-d4ysyv

**Comment by ipeshev** [comment] 2019-01-02 14:57
Hi @squadwuschel  thank you for the report, we will consider which is better and eventually will change it.

**Comment by dimitar-pechev** [comment] 2019-03-22 11:58
@squadwuschel, the `selectionChange` event has been emitting the complete `dataItem` regardless of the `valuePrimitive` option ever since the PR that handles [this issue](https://github.com/telerik/kendo-angular/issues/70). If in any point in time afterwards the `selectionChange` has been emitting just the value, than probably that was a bug that's no longer present. 

You mentioned you noticed the change after upgrading the package, which version were you using in that project prior to the upgrade?

Anyway, the `selectionChange` behavior has been as it is now form before the package was in a stable version, so I don't believe this could be considered a breaking change. 

The reasoning behind emitting the entire object is to give more control to the developer. Even if this behavior is somewhat inconsistent with the `valueChange` event which emits just the value in case of primitive values, making such a change now (emitting just the value in the case of `valuePrimitive=true`), would probably do more harm than good now as it would now be an unnecessary breaking change. Therefore, I believe it's unreasonable to go for such an alteration.

Closing the issue, as the component is working as intended. If you have any remarks, you are welcome to address them here, we could continue the conversion and possibly reopen the issue if we come to the conclusion that a change is required.

**Closed by dimitar-pechev** 2019-03-22 11:58 UTC
Labels: Bug, pkg:dropdowns
