### ISSUE TITLE
Misaligned popup when scrolling the body in Mozilla and Edge

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#900] opened 2017-09-12 11:36 UTC
## I'm submitting a...

* Bug report 

## Current behavior

The dropdown multiselect is misaligned when scrolling the body on Mozilla and Edge. 

## Minimal reproduction of the problem with instructions

Sample plunker:

[http://plnkr.co/edit/sQm4ddYzqlJhURXoVeGi?p=preview](http://plnkr.co/edit/sQm4ddYzqlJhURXoVeGi?p=preview)

**Comment by ggkrustev** [comment] 2017-09-29 07:02
We've pushed a fix to the relevant package that caused the issue. Please reinstall `@progress/kendo-popup-common` in order to fetch the latest version.

`rm -rf node_modules/@progress/kendo-popup-common && npm i`

**Comment by jaandric** [comment] 2017-09-29 07:50
It works nice. Good job.
Tested for DropDownList and Multiselect on Chrome (61.0.3163.100), Firefox (56.0), Edge (40.15063.0.0)

**Comment by ggkrustev** [comment] 2017-09-29 10:34
@jaandric, thanks for testing and for sharing the results!

We found one issue when the popup doesn't have an offset parent, applicable only when popup is used as a standalone component. *The issue is addressed in `@progress/kendo-popup-common@1.2.2`*

I will close the issue as resolved. Please comment if anyone still observes the issue with the latest packages.

**Closed by ggkrustev** 2017-09-29 10:34 UTC
Labels: Bug, pkg:popup

**Comment by jinsepi81** [comment] 2017-10-03 20:16
@ggkrustev  it's showing dropdown in right place but it's not getting closed after select item from opened dropdown.

this is what I have now.

    @angular/animations": "^4.4.4",
    @angular/common": "^4.4.4",
    @angular/compiler": "^4.4.4",
    @angular/core": "^4.4.4",
    @angular/forms": "^4.4.4",
    @angular/http": "^4.4.4",
    @angular/platform-browser": "^4.4.4",
    @angular/platform-browser-dynamic": "^4.4.4",
    @angular/platform-server": "^4.4.4",
    @angular/router": "^4.4.4",
    @angularclass/hmr": "^2.1.3",
    @angularclass/hmr-loader": "^3.0.4",
    @ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    @progress/kendo-angular-buttons": "^1.1.0",
    @progress/kendo-angular-dateinputs": "1.2.0",
    @progress/kendo-angular-dialog": "^1.2.0",
    @progress/kendo-angular-dropdowns": "^1.2.1",
    @progress/kendo-angular-excel-export": "^1.0.4",
    @progress/kendo-angular-grid": "^1.4.2",
    @progress/kendo-angular-inputs": "^1.3.1",
    @progress/kendo-angular-intl": "^1.2.1",
    @progress/kendo-angular-l10n": "^1.0.4",
    @progress/kendo-angular-label": "^1.0.3",
    @progress/kendo-angular-layout": "^1.0.7",
    @progress/kendo-angular-popup": "^1.2.0",
    @progress/kendo-angular-ripple": "^0.1.1",
    @progress/kendo-angular-sortable": "^1.0.4",
    @progress/kendo-angular-upload": "^1.2.0",
    @progress/kendo-data-query": "^1.0.5",
    @progress/kendo-drawing": "^1.4.0",
    @progress/kendo-popup-common": "^1.2.2",
    @progress/kendo-theme-default": "^2.42.2",
    @progress/kendo-ui": "^2017.3.913",
    @telerik/kendo-theme-bootstrap": "^0.10.0",
    @types/jquery": "^3.2.10",
    @types/kendo-ui": "^2017.3.1",
    bootstrap": "4.0.0-alpha.6",
    core-js": "^2.5.0",
    font-awesome": "^4.7.0",
    hammerjs": "2.0.8",
    http-server": "^0.9.0",
    ie-shim": "^0.1.0",
    jquery": "^3.2.1",
    json2typescript": "^1.0.4",
    ng-block-ui": "^1.0.0-beta.15",
    ng2-scroll-to-el": "^1.0.0",
    react": "^15.6.2",
    react-dom": "^15.6.2",
    react-hot-loader": "^3.0.0-beta.7",
    reflect-metadata": "^0.1.10",
    rxjs": "^5.4.3",
    zone.js": "^0.8.18"

![image](https://user-images.githubusercontent.com/27040331/31146881-05834b62-a856-11e7-8158-8adbcb8b2dc4.png)

**Comment by Huck** [comment] 2017-10-05 20:54
We are still having serious issues with the kendo angular2 DropDownList.  the 1.2.2 did fix some of the popup placement errors, but we keep having more issues.  

The app is too complex for posting a demo in plunker, but basically its a big angular2 component page with a form split in a ton of bootstrap panels:

`<form [formGroup]="someForm" novalidate>
	<div class="panel panel-default">
        <div class="panel-heading">Investor Summary</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6">
                    <div class="form-group">
                        <label class="center-block">
                            Field:
							some input or kendo dropdown
                        </label>
                        [more fields...]
                    </div>
				</div>
			</div>
		</div>
	</div>
</form>`.

The problems we are facing are:   somewhat starting into the second panel and lower, any dropdown has some or all of the below issues:

1. popup appears way higher in the page (making it invisible unless you scroll much higher). makes it look like no popup appears and users are very unhappy about this.
2. popup opens and we can select values with the keyboard up and down keys, but mouse clicks do nothing.

These issues are seriously blocking, prompting us to wonder if kendo angular is really ready for production use?

N.B.: we are multi license paying customers.

thanks

**Comment by ggkrustev** [comment] 2017-10-06 20:43
Hi @Huck, I am really sorry to hear about the issues you've been struggling with.

Although simple, Popup component needs to handle numerous layout scenarios and work seamlessly in quite versatile environment (transformed parents, different displays, positions and etc). I do believe that the Popup is *production ready*, as it has been used in many different scenarios and it works seamlessly (we've been tackling different issues for almost an year already). 

Of course, there could be unsupported cases/bugs, which could be resolved much faster if a repro demo is provided (it doesn't need to be plunker). *Please open a support ticket in our ticketing system sharing a runnable repro demo and referencing this Github issue.* The posted details will be completely private, allowing you to share a more sensitive data if needed. This will help us immensely to narrow down the cause of the issue much faster and to provide a feasible solution promptly.
Let me know if you want to proceed with the investigation in different way.

**Comment by Huck** [comment] 2017-10-10 18:09
ok, I updated every single kendo package to the absolute latest version and ran an npm update. now the controls are working as expected. Probably was a version mismatch preventing the latest fixes to make it through. works perfectly now.

thanks

**Comment by ggkrustev** [comment] 2017-10-10 18:57
Glad to hear that everything is OK now!

**Comment by tyhink** [comment] 2018-04-12 15:50
I've updated all kendo packages to the absolute latest versions and I'm still struggling with the popup showing way below the dropdown. I can hack it with some css, but I can't find a workaround for the dropdowns in table filters
