### ISSUE TITLE
[Tooltip] with Template is not hidden when mouse leaves the item

### ISSUE THREAD

**Issue by Nikolai-Adamovich** [telerik/kendo-angular#3745] opened 2022-08-19 10:37 UTC
**Describe the bug**
The Tooltip is shown and not hidden when I move mouse over the kendoTooltip element.

**To Reproduce**
Open official documentation page [Tooltips / Tooltip / Templates](https://www.telerik.com/kendo-angular-ui/components/tooltips/tooltip/templates/)
Move mouse cursor fast over any link.

Recording:
https://user-images.githubusercontent.com/19800663/185600659-efcefc4d-7e7a-4017-9e52-12a342ee8b8a.mp4

**Expected behavior**
Tooltip is hidden, when mouse cursor leaves the link.

**Versions**
v3.1.6 works fine
v4.0.1 has this bug

**Comment by mbechev** [comment] 2022-08-19 14:11
Closing this thread as a duplicate of https://github.com/telerik/kendo-angular/issues/3702

**Closed by mbechev** 2022-08-19 14:11 UTC
Labels: Duplicate
