### ISSUE TITLE
Sortable is deleting items when dragging over more than one group

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2101] opened 2019-02-28 06:12 UTC
**Describe the bug**
By support ticket ...
When dragging over more than one group sortable is deleting the item next to originally dragged.

**To Reproduce**
1. Open this [stackblitz sample](https://stackblitz.com/edit/angular-usg6ul-uj3smr?file=app/app.component.ts).
2.Try to drag item 5 to item 1 
3.Item 6 disappears.

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by danielkaradachki** [comment] 2019-02-28 06:37
closing as duplicate of https://github.com/telerik/kendo-angular/issues/2065

**Closed by danielkaradachki** 2019-02-28 06:37 UTC
Labels: Bug, Duplicate, pkg:sortable
