### ISSUE TITLE
Grid: outline display when focus some areas

### ISSUE THREAD

**Issue by RonnyRen** [telerik/kendo-angular#1688] opened 2018-07-24 02:50 UTC
The environment is as following:
Libraries dependencies:
"@angular/animations": "6.0.7",
    "@angular/cdk": "6.3.0",
    "@angular/common": "6.0.7",
    "@angular/compiler": "6.0.7",
    "@angular/core": "6.0.7",
    "@angular/flex-layout": "6.0.0-beta.16",
    "@angular/forms": "6.0.7",
    "@angular/http": "6.0.7",
    "@angular/material": "6.3.0",
    "@angular/platform-browser": "6.0.7",
    "@angular/platform-browser-dynamic": "6.0.7",
    "@angular/router": "6.0.7",
    "@progress/kendo-angular-buttons": "4.1.1",
    "@progress/kendo-angular-charts": "3.2.1",
    "@progress/kendo-angular-dateinputs": "3.4.2",
    "@progress/kendo-angular-dialog": "3.6.2",
    "@progress/kendo-angular-dropdowns": "3.0.2",
    "@progress/kendo-angular-excel-export": "2.1.0",
    **"@progress/kendo-angular-grid": "3.5.0",**
    "@progress/kendo-angular-popup": "2.4.1",
    "@progress/kendo-angular-inputs": "3.1.3",
    "@progress/kendo-angular-intl": "1.4.1",
    "@progress/kendo-angular-l10n": "1.2.0",
    "@progress/kendo-angular-layout": "3.1.1",
    "@progress/kendo-angular-sortable": "1.1.0",
    "@progress/kendo-data-query": "1.4.0",
    "@progress/kendo-drawing": "1.5.6",
    "@progress/kendo-file-saver": "1.0.6",
    **"@progress/kendo-theme-default": "2.54.0",**

Chrome version: 67
Case 1: When focus on Grid content:
![image](https://user-images.githubusercontent.com/33855404/43113621-f2996cac-8eaf-11e8-823a-815cbbffa036.png)

Case 2: Click column header to sort
![image](https://user-images.githubusercontent.com/33855404/43113704-43e8c0f8-8eb0-11e8-943b-8fffd90ff20f.png)
Note:
I saw the changelog and found someone did fix it before (https://github.com/telerik/kendo-theme-default/commit/a4675ef1255f6cafbcc45e759f1753c229b78bdf). 
I checked the CSS and found that focus style is set on <a> element instead of <th> or <td> element.
![image](https://user-images.githubusercontent.com/33855404/43114002-9fcad446-8eb1-11e8-90ef-0264b14fa3d6.png)

I am not sure whether the environment info is enough, if not, please let me know.

**Comment by gyoshev** [comment] 2018-07-24 15:10
@RonnyRen We were unable to reproduce the issue in the Grid online demos. The provided screenshots show a theme that is not the original Default theme, and there may be conflicting styles on the page. Please provide a runnable example that shows the problem, as suggested by the issue template.

**Comment by RonnyRen** [comment] 2018-07-26 09:04
@gyoshev 
Yes, I did some style changes in my project, but I never set the outline style.
Today, the demo could not work. And Plunker also did not work. How can I provide a runnable example? When I create an example with Plunker, how can I know which version of Angular and Kendo Grid (include Kendo default theme) I use? What should I do to configure the environment as my local in Plunker?

**Comment by RonnyRen** [comment] 2018-07-27 03:39
@gyoshev 
I wrote an example in my local and compress it to the attachment file. You can download it and execute the following steps to reproduce my issue:
1. Install package:
run command: npm install
2. Debug application
run command: ng serve --port 4300
3. Open chrome browser and access address: http://localhost:4300
Result in my environment:
![image](https://user-images.githubusercontent.com/33855404/43300410-f910cd30-9113-11e8-8138-314e422e225e.png)
Example Code:
[angular6_example.zip](https://github.com/telerik/kendo-angular/files/2234331/angular6_example.zip)

**Comment by gyoshev** [comment] 2018-07-27 06:34
@RonnyRen Thank you for the example. We have managed to reproduce the problem, and have confirmed this as a problem in the themes. As a workaround until this is fixed, you can add the following style to resolve the problem:

```css
[tabindex="-1"]:focus {
    outline: 0;
}
```

Here is a [plunker snippet](https://plnkr.co/edit/cRiXqtsHFbd8Fq8sdQCW?p=preview) that shows it in action. The problem is not noticeable in the online demos because they include the Bootstrap framework, which adds the above rule.

As a side note, yesterday's problem with the web demos has been resolved.

**Comment by RonnyRen** [comment] 2018-07-27 08:10
@gyoshev 
Thanks for your your quick workaround. It woks well in my environment.

**Comment by gyoshev** [comment] 2018-11-08 07:21
Fixed in `@progress/kendo-theme-bootstrap@2.14.0`, ` @progress/kendo-theme-default@2.56.0`, and `@progress/kendo-theme-material@1.3.0`

**Closed by gyoshev** 2018-11-08 07:21 UTC
Labels: Bug, Styling
