### ISSUE TITLE
Can't bind to 'routerLink' since it isn't a known property of 'kendo-panelbar-item'

### ISSUE THREAD

**Issue by lucifercha** [telerik/kendo-angular#353] opened 2017-03-07 03:25 UTC
Can't bind to 'routerLink' since it isn't a known property of 'kendo-panelbar-item'

my angular2 version is 2.4.8，and the @progress/kendo-angular-layout version is 0.21.5，why？

**Comment by rusev** [comment] 2017-03-07 07:08
It seems to be working in [this example](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/routing/). 

Usually this error means that the `LayoutModule` is not imported in the app module.

Can you provide a plnkr which demonstrates the error?

**Comment by tsvetomir** [comment] 2017-03-07 07:35
Seems like a duplicate of #54

**Comment by lucifercha** [comment] 2017-03-07 07:41
@rusev  I am sure that i imported the `LayoutModule ` to the app module,because if i remove the `[routerLink]` attribute to `kendo-panelbar-item` it works

**Comment by tsvetomir** [comment] 2017-03-10 08:43
Please see [the Routing demo](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/routing/) for reference.

**Closed** 2017-03-13 16:22 UTC
Labels: pkg:layout

**Comment by ORESoftware** [comment] 2018-01-05 02:08
Looks like router-link became routerLink:
https://coursetro.com/posts/code/111/Using-the-Angular-5-Router-%28Tutorial

**Comment by scheltwort-its** [comment] 2019-01-05 18:49
I solved the same issue by adding the RouterModule to the Module that contained the component.

**Comment by orinwalker** [comment] 2020-03-24 13:20
@ORESoftware Good catch: Also note, for anyone coming across this thread, that it is case sensitive: So you would want to use [routerLink] rather than [routerlink]
