### ISSUE TITLE
[Editor] Using new schema throws an error and makes the component unusable

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3720] opened 2022-07-21 09:06 UTC
**Describe the bug**
Using a new schema in the Editor component throws the following error:

`Error: Cannot read properties of undefined (reading 'name')
`

Making the Editor unusable.

**To Reproduce**

https://www.telerik.com/kendo-angular-ui/components/editor/schema/#toc-creating-a-new-schema

**Comment by dtopalov** [comment] 2022-07-21 09:38
The issue is caused by the fact that the new built-in Editor table-resizing plugins rely on table nodes to be defined in the schema. The built-in Editor schema contains them whereas the custom one in the documentation example does not. We will update the demo accordingly, meanwhile refer to the following example:

https://codesandbox.io/s/elastic-smoke-u0m1cj?file=/src/app/nodes.ts

**Comment by dtopalov** [comment] 2022-07-21 12:20
The updated demo is available in the development version of the documentation site, and will be live once the official version is released in the upcoming days:

https://www.telerik.com/kendo-angular-ui-develop/components/editor/schema/#toc-creating-a-new-schema

**Closed by dtopalov** 2022-07-21 12:20 UTC
Labels: Documentation, pkg:editor, Team2
