### ISSUE TITLE
filter Change Function does not trigger the last char delete (clear)

### ISSUE THREAD

**Issue by santutoshi** [telerik/kendo-angular#2767] opened 2020-02-19 11:38 UTC
**Describe the bug**
 trying to clear the filter filed but does not trigger in last char clear
**To Reproduce**

https://stackblitz.com/edit/angular-tdcxeg?file=src%2Fapp%2Fapp.component.ts

use console to track the trigger of the functions
**Expected behavior**
 filter change function should trigger for the null value after clearing the the input field binding data with server side
**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by dimitar-pechev** [comment] 2020-02-19 13:20
Please provide some additional details (at the very least which component are we talking about), steps to reproduce the issue and if possible a runnable example, where the issue is evident.

Possible duplicate of https://github.com/telerik/kendo-angular/issues/2703.

**Comment by santutoshi** [comment] 2020-02-20 05:25
> Please provide some additional details (at the very least which component are we talking about), steps to reproduce the issue and if possible a runnable example, where the issue is evident.
> 
> Possible duplicate of #2703.

i have added the demo for the problem

**Comment by dimitar-pechev** [comment] 2020-02-20 08:57
@santutoshi, for the filtering functionality to work correctly - i.e. emit the event at all times, the `filterChange` event has to be handled and the received `filter` object has to be persisted. If the new filter values are not persisted, the Grid always compares the new filter value with empty filter value. So clearing the string value you've typed would result in comparing an empty filter with an empty filter which is not regarded as a change, thus no `filterChange` event is emitted. When the event is handled properly and the filter value is persisted, the issue is resolved. Refer to [this example](https://stackblitz.com/edit/angular-pmyfkd).

If further assistance is required, I'd encourage you to [open a support ticket](https://www.telerik.com/account/support-tickets).

**Closed by dimitar-pechev** 2020-02-20 08:57 UTC
Labels: Question, pkg:grid

**Comment by santutoshi** [comment] 2020-02-20 10:09
> @santutoshi, for the filtering functionality to work correctly - i.e. emit the event at all times, the `filterChange` event has to be handled and the received `filter` object has to be persisted. If the new filter values are not persisted, the Grid always compares the new filter value with an empty filter value. So clearing the string value you've typed would result in comparing an empty filter with an empty filter which is not regarded as a change, thus no `filterChange` event is emitted. When the event is handled properly and the filter value is persisted, the issue is resolved. Refer to [this example](https://stackblitz.com/edit/angular-pmyfkd).
> 
> If further assistance is required, I'd encourage you to [open a support ticket](https://www.telerik.com/account/support-tickets).

Thanks. All good now

**Comment by santutoshi** [comment] 2020-02-20 10:10
thanks! it worked.
