### ISSUE TITLE
[TileLayout] Not setting the [title] property throws an error

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3237] opened 2021-03-16 15:30 UTC
**Describe the bug**
By not setting the kendo-tilelayout-item [title] property throws the following error "ERROR TypeError: Cannot read property 'classList' of null".

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-ndlexy-mtdz98?file=app/app.component.ts

**Work around**

1.Use <kendo-tilelayout-item-header [hidden]="true">
https://stackblitz.com/edit/titlelayout-hide-title?file=app/app.component.ts
2. Use custom CSS to hide the kendo-tilelayout-item-header tag.
https://stackblitz.com/edit/titlelayout-hide-title2?file=app/app.component.ts

**Comment by mbechev** [comment] 2021-03-17 15:06
Closing this as a duplicate of #3222

**Closed by mbechev** 2021-03-17 15:06 UTC
Labels: Bug, Duplicate, Team2, pkg:layout
