### ISSUE TITLE
Date picker is not working properly on ie10

### ISSUE THREAD

**Issue by jmanikumaran** [telerik/kendo-angular#676] opened 2017-06-21 12:27 UTC
http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

Please open this link in ie10. Click on the calendar and icon the displayed calendar is not visible properly on ie10. day list is empty in that datepicker.

**Comment by tsvetomir** [comment] 2017-06-21 12:53
Closing as duplicate of #651

**Closed by tsvetomir** 2017-06-21 12:53 UTC
