### ISSUE TITLE
Tooltip for chart is not shown in kendo-window

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1272] opened 2018-01-30 14:18 UTC
## I'm submitting a...
* Bug report

## Current behavior
When we have a chart in kendo-window the tooltip for data is not shown. I think it`s because tooltip append to document.body, not to a kendo-chart-tooltip-popup component and window becomes overlay for tooltip.

## Expected behavior
Tooltip is visible

## Minimal reproduction of the problem with instructions
1. [Open plunker](https://plnkr.co/edit/5gr9F9GTUDUJiIFCoDD3?p=preview)

## Environment

Package versions:
kendo-angular-charts v2.0.0
kendo-angular-dialog v3.0.0
angular ^5

**Comment by gyoshev** [comment] 2018-01-31 15:22
Thank you for reporting this. You can apply the following styles to workaround the issue:

```
  styles: [`
    >>> .k-chart-tooltip-wrapper {
      z-index: 12000;
    }
  `]
```

The styles will be added to a future version of the `@progress/kendo-theme-default` package, and we'll update this issue once it is fixed.

**Comment by gyoshev** [comment] 2018-02-08 08:21
The issue is fixed in `@progress/kendo-theme-default@2.47.7`. [Updated plunker](https://plnkr.co/edit/R7dc1c1cXeGp49ph8j6E?p=preview).

**Closed by gyoshev** 2018-02-08 08:21 UTC
Labels: Styling, pkg:charts

**Comment by hgoebl** [comment] 2019-03-19 11:45
I'm using v3.4.0 together with Kendo UI Angular (newest versions), Angular 7.2 and without the workaround of above it still doesn't work. Tooltip and Crosshair have z-index problems in Kendo Window.

**Comment by tsvetomir** [comment] 2019-03-19 13:03
The change appears to be applied to the [theme source code](https://github.com/telerik/kendo-themes/blob/d7832408f9a0d1a390393f385759f35ccec2e3af/packages/default/scss/dataviz/_layout.scss#L56-L64). I've tested the same scenario with the latest version in [this snippet](https://stackblitz.com/edit/angular-jipgkh?file=app%2Fapp.component.ts). It appears to be working correctly.

@hgoebl please, open a new issue with more details and a runnable sample.

**Comment by hgoebl** [comment] 2019-03-20 16:24
@tsvetomir sorry, don't have the time to extract a sample from our project, currently. The workaround is acceptable.
