### ISSUE TITLE
Grid Header background colour issue.

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#411] opened 2017-03-22 02:23 UTC
I have a website of similar design with this [Plunker](http://plnkr.co/edit/IdqbyjYapkrHskotAsoV?p=preview). 

Somehow the background gridview of the header will shift when the gridview is moved down.

Repo steps:
1) Make sure the browser is maximise.
2) Click on save button > Success message will show.
3) Adjust the browser width with smaller.
4) The grid header background will be misaligned

Good to know
1) Issue does not happens when gird view is scrollable.

![image](https://cloud.githubusercontent.com/assets/22805288/24179169/76c5294c-0ee8-11e7-8140-f64c1cdb0da3.png)

**Comment by gyoshev** [comment] 2017-03-22 10:03
Quite strange. This appears to be a browser glitch, which occurs when clicking on the `md-raised-button` component. It seems that the problem is related to the introduced styles for the ripple effect. The following style appears to fix the problem:

    .mat-fab, .mat-mini-fab, .mat-raised-button {
      overflow: hidden;
    }

Here is the [updated plunkr](http://plnkr.co/edit/x29pR3ONRq8wQ3k8eU1h?p=preview).

We could not apply a fix for this in the theme; any suggestions are welcome.

**Closed by gyoshev** 2017-03-22 10:03 UTC
Labels: pkg:grid, Styling

**Comment by skyfremen** [comment] 2017-03-22 10:08
Would it be useful to report it to the material team instead?

**Comment by gyoshev** [comment] 2017-03-22 11:40
It could be, if the raised-button does not support features that require overflowing (like notification badges on mobile).

Reporting this to the browser vendor might be a better long-term solution, but will require a reduced use case.
