### ISSUE TITLE
[ComboBox] the DropDown does not open

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1715] opened 2018-08-06 13:56 UTC
## I'm submitting a...
* Bug report 

## Current behavior
The DropDown does not open, when clicking the border of the ComboBox:

video:
[https://www.screencast.com/t/I76QLgmvIet](https://www.screencast.com/t/I76QLgmvIet)

## Expected behavior
The DropDown should open.

## Minimal reproduction of the problem with instructions
[https://plnkr.co/edit/R2ZOVp95mRr0KZ69jNtk?p=preview](https://plnkr.co/edit/R2ZOVp95mRr0KZ69jNtk?p=preview)

**Comment by tapopov** [comment] 2018-10-11 15:07
This is working as intended, however the cursor should not change to "pointer". This will be fixed in the themes.

**Closed** 2018-10-18 15:28 UTC
Labels: Bug, Passed-QA, Styling, pkg:dropdowns
