### ISSUE TITLE
Window loses focus, i.e. box shadow provided by HTML CSS class .k-state-focused, when clicking any other Telerik kendo-angular-ui HTML element

### ISSUE THREAD

**Issue by cogo79** [telerik/kendo-angular#1675] opened 2018-07-18 09:40 UTC
https://plnkr.co/edit/SbemjxKGBKiuiDvqQqRI?p=preview

When I click on any kendo HTML element inside a focused kendo window, the window till lose its focus. The same thing happens when I click on any non-kendo input HTML element. I also noticed that if I use browser Internet Explorer, the kendo window will lose its focuse where ever I click inside the window. 

I really think it should be possible to stop a kendo window from losing focus when clicking inside it. But as far I have seen in the documentation, I have not found any support for stoping the window from losing focus.

I am also really surprised that I am the first to point this out.

**Comment by Raisolution** [comment] 2018-07-18 13:06
Hi @cogo79,

The described behavior is expected and by design - the box shadow will be present only when the Window wrapper itself is focused and is the current active element.

We will however research the mentioned behavior in Internet Explorer.

**Comment by cogo79** [comment] 2018-07-18 14:07
Hi @Raisolution,

What about the kendo-grid HTML elements. It would be really nice if it did NOT make the containing window lose focus. It is totally understandable why for example a kendo-text box or a tree-view should make the containing window lose focus. But when I as a user click somewhere in a kendo-grid and there is no highlighting occuring then I at least in the project that I am currently working on the containing window is not supposed to lose focus.

Thank you

**Comment by cogo79** [comment] 2018-07-18 15:10
Otherwise I found out a simple CSS solution to my problem:
.k-grid-aria-root {
    pointer-events: none;
}

.k-checkbox-label, .my-class, .my-class2 {
    pointer-events: initial;
}

// But I don't know yet if this solution is good enough for my web-project

**Comment by Raisolution** [comment] 2018-07-31 07:04
I have logged this question for internal discussion (whether the Window requires a new state for this type of scenarios) and will close this, as the current behavior is by design.

**Closed by Raisolution** 2018-07-31 07:04 UTC
Labels: pkg:dialog
