### ISSUE TITLE
kendo-datepicker and ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by rafal-rapcewicz** [telerik/kendo-angular#798] opened 2017-08-04 15:28 UTC
## I'm submitting a...
 

* Bug report 

## Current behavior
When ChangeDetectionStrategy.OnPush is chosen then after selectind day in datepicker's popup input texbox isn't updated. Texbox becomes updated after focus is lost.

## Expected behavior
With ChangeDetectionStrategy.OnPush after day is chosen using mouse then input textbox is immediately updated.

Package versions:

progress/kendo-angular-dateinputs: "^1.0.5"
progress/kendo-angular-inputs: "^1.1.1"
angular 4.2.6 and 4.3.3
```

```

Browser:

- Chrome (desktop) Version 59.0.3071.115

System:
- TypeScript version: 2.3
- Node version: 8.1.3  
- Platform:  Windows 10

**Comment by ggkrustev** [comment] 2017-08-09 08:06
@rafal-rapcewicz thank you for your report. In general, the DateInputs are designed to work with OnPush strategy. Even they set it explicitly internally.

Could you share a runnable plunkr that demonstrates the reported issue?

**Comment by ggkrustev** [comment] 2017-09-14 07:31
Closing due to inactivity. Please post a repro demo that demonstrates the issue in order to continue with the investigation.

**Comment by daryl0313** [comment] 2017-09-18 19:33
Hi @ggkrustev ,

I too was seeing this issue.  I found that it happens when using Forms or ReactiveForms to bind the value.

I've create this plunker to demonstrate the issue:
http://plnkr.co/edit/q6RzFLJqxhhMzrppkJkX?p=preview

**Comment by ggkrustev** [comment] 2017-09-19 07:38
@daryl0313, thanks for the heads up. I reviewed the plunker, but it seems to work. If the issue is still present, could you post a repro demo? Thus we'll be able to observe the scenario and find a fix quicker.

**Comment by daryl0313** [comment] 2017-09-19 12:23
I still see the issue in that plunker.

I had two examples, one using reactive form binding, which was broken, and the other with just form binding with ngModel, which worked.  I've updated that plunker and removed the working form binding example from the plunker.

The behaviour I'm seeing is just what @rafal-rapcewicz described, that the text value doesn't update until focus is lost on the control.  My expectation is that the text updates after a value is selected in the dropdown calendar.

I can reproduce the error in both Firefox and IE (I can't get the plunker to run in chrome).

**Comment by ggkrustev** [comment] 2017-09-19 12:44
Yeah, indeed. The input value is not updated until blur in all major browsers (I was able to run in Chrome too). It seems to be a bug in the `focus` behavior of the component. Basically, when Calendar is opened, the focus is left in the DateInput, which causes the described behavior. If the user clicks the calendar (somewhere in the header) and then choose a date, everything will work as expected.

@daryl0313, thanks for the additional information. I will reopen the issue in order to fix it in some of our next releases.

**Comment by ggkrustev** [comment] 2017-11-01 09:56
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment] 2017-11-13 14:53
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.

**Closed by ggkrustev** 2017-11-13 14:53 UTC
Labels: Bug, Needs-QA, pkg:date-inputs
