### ISSUE TITLE
Custom Elements built with Kendo Ui for Angular components

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1776] opened 2018-09-07 14:22 UTC
## I'm submitting a...

* Suggestion for improvement  

We need to research the topic on Custom Elements and how to integrate Kendo Ui for Angular components in a Custom Element.

## Current behavior
We can create a custom element, that holds a grid with all of its built in functionality. However, when we try to use the generated custom element outside an Angular application, the grid is not re-rendered on dataStateChange or any other event. The grid is initially loaded and displayed correctly, but after a sortChange event is triggered, the grid's data will be sorted, but the grid will not be re-rendered to display the correct data.

The same behavior occurs if we use non-Kendo components in our custom element.

## Environment

Package versions:
    
"@angular/elements":  version: 6.1.7

_for internal use - this issue is related to ticket [1340667](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1340667)_

**Comment by HashanMWanniarachchi** [comment] 2018-09-11 08:08
This seems to be an issue with change detection not working as intended inside angular elements. I got a kendo grid working by using NgZone.run() method. As RobWarmald from the angular core team is saying [here](https://github.com/angular/angular/issues/23841), This happens when the model changes are happening outside of NgZone. As he says it, we should handle the change detection ourselves.

**Comment by remackgeek** [comment] 2018-09-12 00:03
I haven't had a chance to test it yet, but a fix for this landed today in zone.js:
[PR 1133](https://github.com/angular/zone.js/pull/1133)

**Comment by HashanMWanniarachchi** [comment] 2018-09-12 01:43
> I haven't had a chance to test it yet, but a fix for this landed today in zone.js:
> [PR 1133](https://github.com/angular/zone.js/pull/1133)

I saw this solution was referred in angular github, and just noticed that it was merged into angular:master branch. :)

**Comment by rgullhaug** [comment] 2018-09-23 17:09
> Change detection should definitely be handled in the wrapper component, as it knows when the sort order has been applied.
> 
> You should be able to use ChangeDetectorRef.detectChanges() with the same effect as Zone.run - the goal is to trigger the change detection from the custom element down and we don't need the Zone for that.

@tsvetomir What do you mean by handling the change detection in the wrapper component. Will we need to attach to all kendo grid events in the component hosting the kendo grid, and run ChangeDetectorRef.detectChanges() there?

**Comment by tsvetomir** [comment] 2018-09-24 09:52
@rgullhaug this is now a moot point following the fix linked above, as `attributeChangedCallback` will run in the zone.

**Closed** 2018-11-08 08:59 UTC
Labels: Enhancement
