### ISSUE TITLE
ComboBox Filtering using other language keyboard (Chinese Pinying)

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#276] opened 2017-02-07 07:22 UTC
While using Chinese keyboard, while typing 'wo' the filter will become = 'wwwowowo'
[Plunker link](http://plnkr.co/edit/jkRTaWM3DJExy4YQyROM?p=preview)

Screenshot:
[imgur Link](http://imgur.com/zoStvi1)

**Comment by tapopov** [comment] 2017-02-07 14:17
Hi @skyfremen,

I managed to reproduce the issue and will continue to investigate it.

Thanks for reporting this!

**Comment by tapopov** [comment] 2017-02-10 14:25
[This](https://github.com/angular/angular/issues/3352) issue seems to be related. Need more investigation on our side and maybe a word from the Angular team.

**Comment by tapopov** [comment] 2017-04-19 14:21
Should be fixed in v0.39.1 (2017-04-19)

**Closed** 2017-04-20 08:22 UTC
Labels: Bug, pkg:dropdowns
