### ISSUE TITLE
Remote data Grid fails to compile in Strict Template checking mode

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#3210] opened 2021-02-16 10:52 UTC
I'm using the grid with an observable and the async keyword:
` <kendo-grid [data]="gridDataview | async" [selectable]="true" ...`

Compiling that with the Angular 11 defaults (strictTemplate checking), an error is thrown:
` Type 'null' is not assignable to type 'any[] | GridDataResult'`

After some research, I think the problem is the async pipe, as the pipe can return null.
So is that a bug in the definition of the 'data' property (`Array<any> | GridDataResult;`) or isn't it possible to use the async pipe directly?

Thanks
Eric

**Comment by mbechev** [comment] 2021-02-16 15:12
**To Reproduce**
[grid-strict-A11.zip](https://github.com/telerik/kendo-angular/files/5989536/grid-strict-A11.zip)

1. Download and unzip the folder.
2. Install the project dependencies with `npm install` command.
3. Use `ng serve` command to compile the app.
4. The following error is thrown in [strict mode](https://angular.io/guide/strict-mode):

![16 02 2021_17 11 28_REC](https://user-images.githubusercontent.com/33104481/108081823-0fe63c00-707a-11eb-8850-a1a5a4b51270.png)

**Comment by chetanmore0510** [comment] 2021-03-11 06:54
facing the same issue for angular 11 with strict mode
https://angular.io/guide/strict-mode

**Comment by svetq** [comment] 2021-05-20 11:09
The demonstrated behavior is caused due to the usage of the async pipe with an Observable. Such configuration returns a null value before the completion of the Observable which causes the compilation error. What could be done to avoid the error is to:

- use the non-null assertion operator `!` at the end of the nullable expression `[data]="(query | async)!"`
- set the `strictNullInputTypes` option to false

Both options are suggested on the [official Angular documentation](https://angular.io/guide/template-typecheck#strict-null-checks).

**Comment by EricSch** [comment] 2021-05-20 12:00
So the solution is to switch off strictNullInputTypes option or to trick it with the non-null assertion operator?
First, the the strictNullInputTypes option is important for an error-free code and second then non-null assertion operator assumes only something!
This isn't a solution!! The right solution would be to extend the `data` type, so `null` could be a possible value.

**Comment by svetq** [comment] 2021-05-20 13:12
We'll take that into account. You can use the suggested workarounds until the issue is resolved.

**Comment by josh-davis-git** [comment] 2021-05-21 13:59
If you can, update to angular 12, strict mode is enabled by default in the CLI.

**Comment by ChamCham95** [comment] 2021-09-13 13:15
same issue here, anyone can help?

**Comment by von-seydlitz** [comment] 2022-05-09 09:27
issue still exists :(

**Comment by ciiara** [comment] 2022-05-12 11:22
The issue is fixed in the latest version of the Grid (v7.0.1)

[Here](https://stackblitz.com/edit/angular-dca2qy?file=src%2Fapp%2Fapp.component.ts) is a StackBlitz demo that uses  `null` as its initial data value.

**Closed by ciiara** 2022-05-12 11:22 UTC
Labels: Bug, pkg:grid, Team2
