### ISSUE TITLE
Dropdown For DatePicker Not Showing Any Days In IE10 

### ISSUE THREAD

**Issue by daryl0313** [telerik/kendo-angular#651] opened 2017-06-15 20:47 UTC
Hi,

In IE10 the DatePicker does not show any days in the dropdown.

Actually the dropdown seems to be showing months from a couple of month before the selected date to infinity.  The days might exist but at the bottom of the dropdown, which goes off the screen.

This issue can be reproduced if the following plunkr is opened in IE10.
[http://plnkr.co/edit/naMsqlHCe5cNsa3z5IYK?p=preview](http://plnkr.co/edit/naMsqlHCe5cNsa3z5IYK?p=preview)

**Comment by pbalwant** [comment] 2017-06-19 17:58
Hello,

Do we have any status update on this issue?

It is an high priority item for us and is scheduled for production release. It would be of great help, if someone can look into it as soon possible.

Thanks.

**Comment by gyoshev** [comment] 2017-06-21 07:31
The issue is a bug and needs to be addressed by updating both the styles and the virtualization script. We will follow up in the thread once there is more information.

![screenshot](https://user-images.githubusercontent.com/7533599/27335118-263fbc52-55d4-11e7-8ac3-8f628b78a625.png)

**Comment by ggkrustev** [comment] 2017-07-04 10:28
Hi guys,
after further investigation we found out that a specific CSS breaks the Calendar layout in IE10. You can easily workaround the erroneous behavior applying the following styling at the beginning of the page:

```
    <style>
        .k-calendar .k-calendar-monthview .k-content {
            float: left;
        }
    </style>
```
We will release a fix soon, most probably in the theme package.

**Comment by siyka-marinova** [comment] 2017-07-26 08:23
Fix is available in the latest `@progress/kendo-theme-default` package

**Closed by siyka-marinova** 2017-07-26 08:23 UTC
Labels: Bug, Passed-QA, pkg:date-inputs
