### ISSUE TITLE
kendo Popups inside grid edits does not have proper z-index

### ISSUE THREAD

**Issue by codehippie1** [telerik/kendo-angular#1141] opened 2017-12-05 16:32 UTC
Please see this plunkr made of kendo sample angular grid page. http://plnkr.co/edit/j58uiGUumjL14vGxInzW?p=preview

Steps to reproduce
1. Click Edit
2. Remove product name to see validation error message pop-up. The pop-up is hidden beneath the column header.

Expected result: A pop-up should be popped up.

**Comment by ggkrustev** [comment] 2017-12-06 08:33
@codehippie1, the described behavior is expected. The Popup component either with `fixed` or `absolute` positioning cannot be displayed above element with `transform` styling. In this case the Grid table is transformed, which makes it the top most stacking container for the popup component.

The solution is to just place the `<kendo-popup>` element physically outside the grid and open/close it based on some interaction. To prove that, here is a simple POC demo that shows how to connect popup placed outside the grid with specific cell:

https://plnkr.co/edit/M5WaAWOuof1GFeRIYJjv?p=info

I would like to emphasize that the discussed case is not a bug in the component, but rather a limitation how the HTML/CSS work.

**Closed by ggkrustev** 2017-12-06 08:33 UTC

**Comment by codehippie1** [comment] 2017-12-27 21:49
Hi @ggkrustev Looking here bootstrap tooltip and boot strap popover, a feature like this is supported using "container=body" attribute. Can't kendo popup achieve something similar?

A pop-up is expected to be over other html element, logically

Refer: 
1. https://v4-alpha.getbootstrap.com/components/popovers/#example-using-the-container-option
2. https://valor-software.com/ngx-bootstrap/#/popover#container-body

**Comment by ggkrustev** [comment] 2018-01-02 08:48
Hi @codehippie1, the PopupService already supports arbitrary container, which could be defined by `appendTo` PopupSettings option:

https://www.telerik.com/kendo-angular-ui/components/popup/service/#toc-appending-to-specific-containers

The Popup component is a standalone custom element, which doesn't control where it is appended, but rather leaves the control to the developer that uses it. This gives some benefits, like building multiple viewports on the page and where the popup should not pop-up over. 
Of course, the most common scenario is to have only one viewport. In this case, just use the PopupService and the `appendTo` option.
