### ISSUE TITLE
The width of the Splitter Pane is not calculated properly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1659] opened 2018-07-11 12:20 UTC
## I'm submitting a...

* Bug report 

## Current behavior
The width of the Splitter Pane is not calculated properly when setting the min property. If we drag the splitter bar to decrease the splitter pane to its minimum, the actual width of the splitter pane is not correct.

## Expected behavior

When the splitter pane is decreased to its minimum (10%), its width should be equal to 10% of the width of the splitter component.

## Minimal reproduction of the problem with instructions
 Check the following sample plunker:
[https://plnkr.co/edit/M4gPBVSTFoI09I9Y7bH8?p=preview](https://plnkr.co/edit/M4gPBVSTFoI09I9Y7bH8?p=preview)

1. Decrease the left splitter pane to its minimum.
2. Inspect the width of the splitter pane. It should be 10% of the width of the splitter component.

**Comment by danielkaradachki** [comment] 2019-03-14 08:01
The behavior seems correct. Initially the size of the pane is 31.8 pixels which is 30% of the 106 inner width of the splitter. After resizing the pane to the minimum the width its size is 10.6 pixels which is 10% of the inner width. Am I missing something?

**Comment by danielkaradachki** [comment] 2019-03-15 08:46
Closing until further information describing the problem is available.

**Closed by danielkaradachki** 2019-03-15 08:46 UTC
Labels: Bug, pkg:layout
