### ISSUE TITLE
Animation Transitions not working at load time in Kendo-Chart

### ISSUE THREAD

**Issue by sagarvbhale** [telerik/kendo-angular#148] opened 2016-12-23 11:54 UTC
Animation transitions are not loading at the load time of the chart.

I am picking up the sample code from Kendo UI's site. 

@Component({
    selector: 'my-app',
    template: `
        <button (click)="toggleSeries()">Toggle second series</button>
        <kendo-chart [transitions]="true">
          <kendo-chart-series>
            <kendo-chart-series-item [data]="[1, 2, 3, 5,7,8]">
            </kendo-chart-series-item>
            <kendo-chart-series-item [data]="[5, 3, 2, 1]" *ngIf="showSeries">
            </kendo-chart-series-item>
          </kendo-chart-series>
        </kendo-chart>
    `
})
class AppComponent {
    private showSeries: boolean = false;
    private showTransitions: boolean = true;

    private toggleSeries() {
        this.showSeries = !this.showSeries;
        this.showTransitions = false;
    }
}

When I run the code in Kendo-UI website(example that is under header 'Structural Directives' at site: http://www.telerik.com/kendo-angular-ui/components/charts/chart/ ), if I change any value in the [data], then the chart gets reloaded and the animation does not work. After that for the toggleSeries button it works on clicking.

Personally trying, I have a component that is getting dynamically developed that needs to reload the chart on refresh, there the animation is not working as it is getting relaoded.

Kindly provide me a solution. Thanks in Advance.
-Sagar

**Comment by tsvetomir** [comment] 2017-03-01 15:50
Sorry for taking so long. We were able to identify the cause for this issue and will try to fix it in the upcoming releases.

**Comment by tsvetomir** [comment] 2017-03-10 08:35
This should be fixed now. Please run `npm update` and give it a shot.

**Closed** 2017-03-13 16:24 UTC
Labels: Bug, pkg:charts
