### ISSUE TITLE
Kendo UI grid incompatible with Prerendering

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/kendo-angular#1033] opened 2017-10-23 20:38 UTC
I'm re-posting this issue from https://github.com/EdCharbeneau/kuiWithAngularDotnet/issues/1

I was able to verify that the grid fails to work with prerendering.

Followed instructions at https://www.telerik.com/blogs/cooking-with-aspnet-core-and-angular-2 on my own project and found an error.
Then I tracked down this GitHub project hoping that the issue was something in my project, followed the read me instructions to the letter, produced same error.

Error Description:
When navigating to the site an unhanded exception occurs when processing the request: 

> NodeInvocationException:
>  Prerendering failed because of error: ReferenceError: document is not defined
> at C:\Users\GarrettCurtis\Desktop\kuiWithAngularDotnet-master\KuiWithAngularDotnet\ClientApp\dist\main-server.js:639:30
> at content (C:\Users\GarrettCurtis\Desktop\kuiWithAngularDotnet-master\KuiWithAngularDotnet\ClientApp\dist\main-server.js:7679:13)

Debugging this error leads me to believe the error is in the `@progress/kendo-angular-grid` package since removing this package form the module imports removes the error (of course then I get an error about the kendo-grid module properties not being defined).

Following the stack reveals that the error stems from this line, which seems to be part of the calendar date picker for the grid componenet:
`var CALENDAR_ELEMENT_MONTH = calendar(view(content(6), 'k-calendar-view k-calendar-monthview'));`
which, in turn, tries to create a table:
`var content = function (rows) { return (table([
    tbody([
        tr([th('1')]) ...`
 and invokes the DOM:
`var th = util_1.domContainerFactory('th');,`
which we don't have during pre-rendering, thus spitting out the error

Clearly this is a major issue with the Angular Grid module in the context of ASP.NET Core sites. I guess that this wasn't an issue previously and there was some major change somewhere that created it. Unfortunately I can't track down any mention of this anywhere. hopefully you have more luck. 

Environment:
- ASP.NET Core 2.0
-   npm: '3.10.10',
-   ares: '1.10.1-DEV',
-   http_parser: '2.7.0',
-   icu: '58.2',
-   modules: '48',
-   node: '6.11.4',
-   openssl: '1.0.2l',
-   uv: '1.11.0',
-   v8: '5.1.281.108',
-   zlib: '1.2.11' 

from package.json 

"dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/compiler-cli": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/platform-browser-dynamic": "4.2.5",
    "@angular/platform-server": "4.2.5",
    "@angular/router": "4.2.5",
    "@ngtools/webpack": "1.5.0",
    "@progress/kendo-angular-buttons": "^2.0.0",
    "@progress/kendo-angular-dateinputs": "^1.3.0",
    "@progress/kendo-angular-dropdowns": "^1.2.2",
    "@progress/kendo-angular-excel-export": "^1.0.4",
    "@progress/kendo-angular-grid": "^1.5.0",
    "@progress/kendo-angular-inputs": "^1.3.1",
    "@progress/kendo-angular-intl": "^1.2.2",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-data-query": "^1.0.7",
    "@progress/kendo-drawing": "^1.4.0",
    "@progress/kendo-theme-default": "^2.38.1",
    "@types/webpack-env": "1.13.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },

**Comment by rkonstantinov** [comment] 2017-10-24 07:10
Duplicate of https://github.com/telerik/kendo-angular/issues/1031
Meanwhile you should downgrade the date-inputs package to 1.2.x

**Closed by rkonstantinov** 2017-10-24 07:10 UTC
Labels: pkg:grid
