### ISSUE TITLE
Selection state of Rows is not getting reset after Remove event

### ISSUE THREAD

**Issue by nitinbodhwani** [telerik/kendo-angular#1795] opened 2018-09-18 08:27 UTC
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior
In multiselect mode of the UI grid, we are trying to remove all selected rows whenever a remove event is triggered. So after removing the selected rows; the deleted rows doesn't appear in the grid but the selection state of the grid is still not getting cleared. 

## Expected behavior
If Row number 2 and 3 were removed then grid is still marking the Row 2 and 3 as selected after the remove event. So ideally the selection state of grid rows should reset after remove event.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment] 2018-09-18 09:32
Hi @nitinbodhwani,

Could you provide a runnable example that demonstrates the exact Grid setup, so we could suggest a solution. The easiest way would be to update some of our [documentation examples](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/#toc-built-in-directive).

**Comment by nitinbodhwani** [comment] 2018-09-18 09:36
Hi @Raisolution , Though I am not able to load the plunker example but by description of following issue, it seems similar to what I am facing.

https://github.com/telerik/kendo-angular/issues/287

Is there any working example to refer if the above specified issue is resolved?

**Comment by Raisolution** [comment] 2018-09-18 09:39
The linked issue is regarding a very old version of the Grid. The selection functionality was completely rewritten afterwards.

Regarding the examples, we currently use StackBlitz as a platform to load them, which makes it very easy to modify them.

**Comment by nitinbodhwani** [comment] 2018-09-18 09:53
I am using Kendo angular grid version - 2.1.3. And in this version also I am facing issue to deselect any row programatically. My use case is that I have applied a RemoveCommandDirective on one of the grid cell template and I am deleting all selected rows on click of the cell which has Remove command directive applied to it. So after removing the selected rows from the grid I am facing issue that the selection state of the grid is still maintained even when the selected items are removed from the grid.

Example: I have 1,2,3,4,5,6 (total 6 rows) in the grid. Now when I select 2 and 3 and then click on delete so in delete event handler I am removing 2 and 3 from the grid data source so now grid is left with just 1,4,5,6; which is correct as per data but 4,5 are automatically coming as selected rows because they have now replaced the position of 2,3 which were deleted. So, I am in need to reset the grid selection state once the selected items are deleted.

Hope I am able to explain the scenario properly.

**Comment by Raisolution** [comment] 2018-09-18 10:03
In order to log this as a valid bug report, we need a minimal reproduction of the problem with a runnable example and steps to reproduce it (as explained in the issue template). If this is not the current case, I would suggest opening a [support ticket](https://www.telerik.com/account/support-tickets), so we could assist with specific implementation details if needed.

**Comment by Raisolution** [comment] 2018-09-20 13:43
Hi @nitinbodhwani,

I am closing this for the moment, as we are not able to reproduce the problem without a runnable example.

**Closed by Raisolution** 2018-09-20 13:43 UTC
Labels: pkg:grid
