### ISSUE TITLE
Grid Grouping renders improperly in IE 11

### ISSUE THREAD

**Issue by TrevorBroderick1** [telerik/kendo-angular#1687] opened 2018-07-23 21:39 UTC
## I'm submitting a...
* Bug report

## Current behavior
In the latest version, as seen in the grouping plunkr available on the documentation page, the grouping bar does not have the proper height on IE 11.

![image](https://user-images.githubusercontent.com/19823278/43104384-221980fe-8e86-11e8-93e9-8781b3eaf9ef.png)

## Expected behavior
It should have the same height it does on chrome. 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/eHHDzalWLSLmIIsg?p=preview

## Environment

Browser:
- IE version 11.165.17134.0

**Comment by danielkaradachki** [comment] 2018-07-24 06:00
This is a known issue. Possible workaround for the moment is to override the k-grouping-header line-height:
https://plnkr.co/edit/d9Vu6DhQnmVaUB34CDS3?p=preview

Will close this as duplicate of https://github.com/telerik/kendo-themes/issues/210

**Closed by danielkaradachki** 2018-07-24 06:00 UTC
Labels: Bug, Duplicate, Styling, pkg:grid
