### ISSUE TITLE
Grid with grouping and detail row template is causing unusual behavior.

### ISSUE THREAD

**Issue by smcgilvery** [telerik/kendo-angular#701] opened 2017-06-28 19:54 UTC
Plunker: http://plnkr.co/edit/WoqkaDZpq8hU24m0eKcv?p=preview

Expand Chai to view Chai details
Collapse Beverages Group; Chai detail does not hide

**Comment by rkonstantinov** [comment] 2017-06-29 06:10
This is duplicate of https://github.com/telerik/kendo-angular/issues/681

**Closed by rkonstantinov** 2017-06-29 06:10 UTC
