### ISSUE TITLE
A DatePicker does not display a value set with ngModel

### ISSUE THREAD

**Issue by alexeikostevich** [telerik/kendo-angular#1095] opened 2017-11-17 13:43 UTC
## I'm submitting a...

* Bug report 

## Current behavior

The [DatePicker](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/) does not display an initial value set with _ngModel_.
However, a value appears right after focusing a _DatePicker_.

## Expected behavior
The _DatePicker_ should display the latest _ngModel_ value.

## Minimal reproduction of the problem with instructions

The issue is not reproducible in [demos](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/#toc-forms-support) but is reproducible in all our products.

For example, after page loading this template
```html
<kendo-datepicker
     name="dueDate"
     [(ngModel)]="task.dueDate">
</kendo-datepicker>
<span>Value: {{task.dueDate | date:'shortDate'}}</span>
```

renders 

![DatePicker](https://image.ibb.co/gGaThm/1e59cd35_ae5e_4d6b_a9a7_93d6c0f76d30_png_embedded_og.png)

## What is the motivation or use case for changing the behavior?
Pages that display a _DatePicker_ with an initial value are broken.

## Environment

Package versions:

```
+-- @angular/animations@5.0.2
+-- @angular/common@5.0.2
+-- @angular/compiler@5.0.2
+-- @angular/core@5.0.2
+-- @angular/forms@5.0.2
+-- @angular/platform-browser-dynamic@5.0.2
+-- @angular/router@5.0.2
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-dateinputs@1.4.0
+-- @progress/kendo-angular-dialog@1.3.0
+-- @progress/kendo-angular-dropdowns@1.2.4
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.6.1
+-- @progress/kendo-angular-inputs@1.3.3
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.0.10
+-- @progress/kendo-angular-popup@1.3.0
+-- @progress/kendo-angular-upload@2.0.2
+-- @progress/kendo-data-query@1.1.1
+-- @progress/kendo-date-math@1.1.0
+-- @progress/kendo-drawing@1.4.0
+-- @progress/kendo-theme-default@2.44.0
```

Browser:

- Chrome (desktop) version 62
- Firefox version 57
- Edge version 38

System:
- TypeScript version: 2.4.2
- Node version: 6.10.3 (npm 4.6.1)
- Platform:  Windows

The issue is not reproducible with _kendo-angular-dateinputs_ 1.3.1.

**Comment by alexeikostevich** [comment] 2017-11-17 14:06
It seems that issues could have the same root cause: https://github.com/telerik/kendo-angular/issues/1079

I apologize for possible duplication.

**Comment by JaapMosselman** [comment] 2017-11-21 08:25
I noticed the same problem with 1.4.0. Please, fix asap. We want to ship end of next week!

**Comment by ggkrustev** [comment] 2017-11-21 08:27
I do believe that the issue is already fixed and is available in the @dev channel. Could you give it a try? Just run `npm i @progress/kendo-angular-dateinputs@dev`.

P.S. We are going to release officially the package soon.

**Comment by JaapMosselman** [comment] 2017-11-21 09:49
I have installed the latest dev and I can confirm it is fixed. Thanks.
Hope to see the release of 1.4.1 soon.

**Comment by ggkrustev** [comment] 2017-11-21 11:44
Will close this thread as duplicate. Please follow #1079 for official release of the fix.

**Closed by ggkrustev** 2017-11-21 11:44 UTC
Labels: Bug, Duplicate, pkg:date-inputs
