### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using ComboBox

### ISSUE THREAD

**Issue by dwally89** [telerik/kendo-angular#561] opened 2017-05-15 20:53 UTC
I have a ComboBox, that when an item is selected, it gets added to an array "list2". I also have the ComboBox set to be disabled when "list2" is not empty. When an item in the ComboBox gets selected, an ExpressionChangedAfterItHasBeenCheckedError is thrown.

http://plnkr.co/edit/YoMbW0rCyQ0BEZx9MAhb?p=preview

**Comment by tapopov** [comment] 2017-05-16 07:57
Hi @dwally89 

I could not reproduce the issue using the example you shared. Would you please share the exact steps in order to get the error?

**Comment by simon11196** [comment] 2017-05-16 11:54
Looks like it's only happening in Chrome (version 58.0.3029.110).
Tested it in IE11 and Firefox 48.0.2 without error.

**Comment by dwally89** [comment] 2017-05-16 13:23
@tapopov 

1. Open the Plunker using the link above
2. Click the blue button "Launch the preview in a separate window"
3. Press F12 to open the Developer Tools, and switch to the Console tab
4. Pick any item from the Kendo ComboBox
5. ExpressionChangedAfterItHasBeenCheckedError will be displayed in the console

I am using Chrome 58.0.3029.110 (64-bit)

**Comment by simon11196** [comment] 2017-05-17 08:19
[Disabling Fieldset on keyboard-submit causes ExpressionChangedAfterItHasBeenCheckedError](https://github.com/angular/angular/issues/16049)

**Comment by dwally89** [comment] 2017-05-17 14:09
@simon11196 , I don't think this is related as the problem does not occur with a standard HTML select tag. I have updated the Plunker to include a working example with an HTML select tag.

**Comment by dwally89** [comment] 2017-05-24 14:09
@tapopov / @simon11196 any update on this?

**Comment by dtopalov** [comment] 2017-05-26 07:57
The logic, performed on valueChange needs to be moved from the template to a handler, e.g.:
[http://plnkr.co/edit/V4qk71gDAZkHnSwmk99j?p=preview](http://plnkr.co/edit/V4qk71gDAZkHnSwmk99j?p=preview)

This way the Angular change detection mechanism will be stabilized, and the discussed error will not occur.

**Comment by dwally89** [comment] 2017-05-26 13:26
@dtopalov , I'm not sure if you forgot to save the Plunker, but list 1 does not become disabled after an item is selected.

**Comment by dtopalov** [comment] 2017-05-29 08:09
@dwally89 The ComboBox disabling logic was removed in an attempt to isolate the issue. However, you are correct that bringing it back causes the discussed error. It seems that the combination of an "ngModel" binding and an attempt to change the component state at the same time with changing its value, leads to the undesired behavior.

We will need to investigate the issue further and try to provide a solution. Thank you for the understanding.

**Comment by tapopov** [comment] 2017-05-30 13:04
@dwally89 
Here is a more detailed break down of what happens. Disabling the ComboBox triggers its input's blur event, where an internal property tracking the focus is also changed (after it has been checked for), hence the error. Manually detecting for any interim changes should solve this. [Here](http://plnkr.co/edit/wMjhF6JPaidGXDg5hz4R?p=info) is a workaround example while we find a way to fix this on a component level.

**Comment by tapopov** [comment] 2017-06-27 13:23
Still in progress. Related to https://github.com/angular/angular/issues/17793

**Comment by dwally89** [comment] 2017-06-29 00:47
Thanks for the update, glad to see it's being looked into

**Comment by tsvetomir** [comment] 2017-09-28 10:53
Closing this as we're unable to provide a fix in our code. Please use the workaround until the Angular issue is fixed.

**Closed by tsvetomir** 2017-09-28 10:53 UTC
Labels: Bug, pkg:dropdowns, Won't Fix
