### ISSUE TITLE
Enter key is not working for kendo-upload with Jaws tool due to tabindex=-1 in <input> 

### ISSUE THREAD

**Issue by Sowmiya3011** [telerik/kendo-angular#3570] opened 2022-02-02 09:58 UTC
**Describe the bug**
Enter key is not working for kendo-upload with JAWS. It's working perfectly without JAWS.  The default code which generated has input tag where the tabindex is set to -1. I tried changing it to 0 in Dev tool and it was working then. Now how can I override the default code? Or is there any alternate way to fix this bug? 
P.S: I've already tried role=application. Enter key press works but it affects up/down arrow key which should not happen.

**To Reproduce**
1. Open JAWS
2. Navigate via keyboard to kendo upload button and press Enter key

Reference Url 
 https://www.telerik.com/kendo-angular-ui/components/uploads/upload/file-processing/

**Expected behavior**
ENTER key has to work with JAWS Screen reader for kendo-upload button.

**Screenshots**
![IMG_20220202_151341](https://user-images.githubusercontent.com/80323942/152131773-19f2b885-9baa-488a-a066-370245f1c6ae.jpg)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by mbechev** [comment] 2022-02-02 12:30
Closing this issue as a duplicate of https://github.com/telerik/kendo-angular/issues/3569

**Closed by mbechev** 2022-02-02 12:30 UTC
Labels: Duplicate
