### ISSUE TITLE
DropdownList does not blur with [tabindex] not set to a number.

### ISSUE THREAD

**Issue by cp79shark** [telerik/kendo-angular#1856] opened 2018-10-17 12:44 UTC
## I'm submitting a...
* Bug report 

## Current behavior
The `DropdownList` component does not close on blur when `[tabindex]` is `null`, `undefined`, or `NaN`.

## Expected behavior
It should close.

## Minimal reproduction of the problem with instructions
See stackblitz. https://stackblitz.com/edit/angular-zdbzau

## Environment

Package versions:
3.2.2 for inputs, see stackblitz package.json for full list.

Browser:

- Chrome (desktop) version 69

**Comment by dimitar-pechev** [comment] 2018-10-24 15:48
@cp79shark Thank you for your input! 

It seems that when you explicitly set the `tabindex` to an invalid value the component wrapper cannot be focused, and thus cannot be blurred, which would cause the options list to close. To be able to focus elements like `span` (the DropDownList warpper element is a `span`), you need to explicitly assign to the element a valid `tabindex`. I also noticed the the keyboard navigation of the component wasn't working in your example which is again caused by the lack of `tabindex` specified. As explained [here](https://github.com/angular/angular/issues/5168), binding to keyboard events on non-focusable elements doesn't work. 

It's something we've probably overlooked, as setting the `tabindex` is part of the configuration of the component. And if you explicitly assign the `tabindex` to an invalid value, that's just configuring the component incorrectly. By default, `0` is assigned as `tabindex` if you don't define it yourself, and you have to explicitly assign an invalid value to get this unwanted behavior.

May be I'm missing something, so if you could perhaps share a valid scenario in which the `tabindex` should be assigned to e.g. `undefined`, we would consider changing the component accordingly. How would you expect the component to behave when you set it's `tabindex` to `undefined`?

We will, however, look to add some defense mechanisms to ensure the `tabindex` is either a valid number value defined by the user of the component, or the default `tabindex` value (`0`), to help avoid mistakes that cause this unwanted behavior.

**Comment by cp79shark** [comment] 2018-10-27 17:51
@dimitar-pechev , no, everything you've mentioned is known on my end. I simply filed the bug because of accidentally setting it to an invalid value and observing the unwanted behavior. Defensive checks is all I think is needed. Whether that is throwing an exception or a 'sane default' would be up to you and however you normally handle such situations with other controls for consistency.

**Comment by tsvetomir** [comment] 2018-10-29 15:20
I'm with @cp79shark here, an `undefined` value for `tabIndex` should be ignored. A console warning in development mode might help identify an issue in the host component, but that's about the only side-effect that an invalid value should have.

**Comment by dimitar-pechev** [comment] 2018-11-06 10:04
The defense checks are added and available in the [dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package v3.3.1-dev.201811060952. 

If the provided tabindex is invalid (e.g. `undefined`), the component will use the default tabindex value (`0`).

**Comment by dimitar-pechev** [comment] 2018-11-22 13:22
Included in **v3.4.0** of the `@progress/kendo-angular-dropdowns` package.

**Closed by dimitar-pechev** 2018-11-22 13:22 UTC
Labels: Enhancement, Passed-QA, pkg:dropdowns
