### ISSUE TITLE
[DropDownButton] [SplitButton] Inconsistent focus behavior

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-angular#3673] opened 2022-05-17 12:46 UTC
**Describe the bug**
Opening the component's popup a second or more time does not focus the first item.

**To Reproduce**

  1. Open the following StackBlitz demo: https://stackblitz.com/edit/angular-uvfup1?file=src%2Fapp%2Fapp.component.ts
  2. Click on one of the buttons in order to open its popup.
  3. Observe the correctly focused first element.
  4. Close the button's popup and open it a second time.
  5. Observe the inconsistent behavior.

**Expected behavior**
The first item should always be focused upon opening the popup.

**Comment by jaytonic** [comment] 2022-05-18 11:36
IMHO, the expected behavior is incorrect. 

Focusing the first element is required for the keyboard navigation, right(which is a niche usage, since most of those menu need to be triggered by a mouse click/hover)?`

I've never seen an app where this is done by default. Most of the app that allow this require to do a first "arrow down", to see the first element being selected. You can check how it's done on the github buttons(watch/star) by example.

So the expected behavior should be that no element is focused by default, until the user press "arrow down"(or "alt")

**Comment by slavenai** [comment] 2022-05-19 11:20
Hi @jaytonic ,

When implementing both the SplitButton and the DropDownButton, we have followed the Menu Button WAI-ARIA Authoring Practices:
- https://www.w3.org/TR/wai-aria-practices/#menubutton
- https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

Therefore, the first element is focused upon opening the popup. This is needed for the component’s keyboard navigation which is always available:
https://www.telerik.com/kendo-angular-ui-develop/components/buttons/dropdownbutton/keyboard-navigation/

**Comment by dtopalov** [comment] 2022-09-09 08:47
The issue is fixed in v. 8.1.0 of the **@progress/kendo-angular-buttons** package. As @slavenai described, following the accepted WAI-ARIA practices, the first element in the list is focused when the popup gets opened.

**Closed by dtopalov** 2022-09-09 08:47 UTC
Labels: Bug, pkg:buttons, Team2
