### ISSUE TITLE
BUG with Kendo Angular Grid - Issues with Delete and Wrong Rows

### ISSUE THREAD

**Issue by DBhail** [telerik/kendo-angular#1468] opened 2018-04-18 11:35 UTC
## I'm submitting a BUG

The delete and update of a grid has sync. issues. Rather than post my code I have found that the sample codes on the Official Website also have issues which I'll detail below:

## Current behavior
For example the code on the Kendo Website has an example (source code under Template Driven):

   https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-directives/

If you press the delete button the row is deleted... Great !
If you now press the Delete Button for another row...it deletes the wrong row. Wrong !
If you now press the Edit Button for another row...it edits the wrong row. Wrong !
If you press Delete Button for last row...crash...debug issues as row doesn't exist. Wrong !

It appears to be retrieving the wrong index for the underlying data as the index itself isn't updated when a delete occurs. The underlying data (from debug) is correct...it shows row has been deleted. Something is wrong with the Grid source code...its getting the wrong rows after a delete occurs !!

## Expected behavior
If you delete or edit the row...it should be for that specific row. It is important that the grid binds to the underlying data without being async or refreshing it again.

**Comment by danielkaradachki** [comment] 2018-04-19 07:36
The problem should already be fixed in the [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version of the package:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/editing/editing-directives/

Closing as duplicate of https://github.com/telerik/kendo-angular/issues/1462

**Closed by danielkaradachki** 2018-04-19 07:36 UTC
Labels: Bug, Duplicate, pkg:grid
