### ISSUE TITLE
PanelBar on animated wrapper: DOM dirty

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2022] opened 2019-01-16 17:13 UTC
## I'm submitting a...
* Bug report

PanelBar open into a div animated doesn't reset status and clean DOM.

## Current behavior

Just open: https://stackblitz.com/edit/angular-jw9lf5-ku17bk
show/hide wrapper and see animation. When panelPar is open and you click on button to hide wrapper, pannelBar still in a dirty state (open but with no content showed)

## Expected behavior
Works correctly!

**Comment by dimitar-pechev** [comment] 2019-01-17 13:44
@meriturva, the unwanted behavior is caused by using content projection in the `wrapper` component (`ng-content`). As explained [here](https://github.com/angular/angular/issues/18982) and [here](https://github.com/angular/angular/issues/13059#issuecomment-264598276), this _is_ the expected behavior. Although the **PanelBar** is removed from the DOM when you toggle the `show` prop value, the component is not destroyed as explained in the referenced issues from the Angular GitHub repo. That on the other hand means the **PanelBar** state is not correctly cleared and it leads to this unwanted behavior. 

A possible workaround would be to `*ngIf` on the **PanelBar** component itself and not on the `ng-content` wrapper. Refer to [this example](https://stackblitz.com/edit/angular-jw9lf5-szymfa).

**Comment by dimitar-pechev** [comment] 2019-01-18 15:31
Closing the issue as the problem is related to Angular and not specifically to the Kendo component. Please do correct me if I am missing something. If that's the case, we'll reopen the issue and take it from there.

**Closed by dimitar-pechev** 2019-01-18 15:31 UTC
Labels: pkg:layout

**Comment by meriturva** [comment] 2019-01-21 17:16
I think that issue is related to kendo, actually i know about life cycle during content projection but issue is related to animation. Just try to remove animation attribute: @closeOut on wrapper component and panelBar is correctly restored after hide/show phases.

**Comment by dimitar-pechev** [comment] 2019-01-22 11:55
Yes, I see what you mean now. However, after some digging, I came across this [Angular issue](https://github.com/angular/angular/issues/24041). Apparently, when you have an animated container with an `ng-content` inside of it, and the content projected by the placeholder also includes animations it leads to this undesired behavior.

In the case of the **PanelBar** the content of each child item is opened with an animation (by default). 

I'm not sure trying to work around this Angular issue from our side would be productive.

There are a few things you can do to tackle the issue before it's being resolved by the framework:
* remove the `@closeOut` animation **OR** disable the **PanelBar** item content expansion animation ([as demonstrated here](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/animations/)) - that way you can keep the **PanelBar** state if this is your intention;
* use `*ngTemplateOutlet` as demonstrated in [this example](https://stackblitz.com/edit/angular-jw9lf5-uws2ud) - this approach will, however, destroy and recreate the **PanelBar** every time you toggle it, so naturally its state will be lost;
