### ISSUE TITLE
[DropDownTree] Cannot read property 'item' of null when selecting an item

### ISSUE THREAD

**Issue by MLefebvreICO** [telerik/kendo-angular#3305] opened 2021-05-14 14:58 UTC
**Describe the bug**
When a selecting an item in the dropDownTree the javascript throw the error `Cannot read property 'item' of null`.

**To Reproduce**

1. Go to the [StackBlitz](https://stackblitz.com/edit/angular-nxc2to) (which is the `Getting started` template from the docs)
2. Choose a value in the dropDownTree
3. Get the error in console (and even the page shows the error in Stackblitz)

**Expected behavior**
When a selecting an item in the dropDownTree the javascript does not throw an error.

**Browser**
 - OS: Windows 10 Pro x64
 - Browser: Edge
 - Version: 90.0.818.56

**Comment by dimitar-pechev** [comment] 2021-05-17 15:34
The issue is fixed in the TreeView package. Upgrade to `@progress/kendo-angular-treeview@5.3.1` to get fix.

**Closed** 2021-06-08 15:11 UTC
Labels: Bug, Team1, freq4: certain, pkg:dropdowns, sev4: blocking
