### ISSUE TITLE
Popup Examples Not Working on telerik.com

### ISSUE THREAD

**Issue by marvhen** [telerik/kendo-angular#3898] opened 2023-01-26 15:36 UTC
**Describe the bug**
The popup examples at https://www.telerik.com/kendo-angular-ui/components/popup/ are producing this error in the console:
           
        ERROR TypeError: t.getBoundingClientRect is not a function
        at et (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:1498)
        at Ct.offset (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:5709)
        at Et.absoluteRect (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:8757)
        at Et.alignElement (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:8498)
        at Lt.position (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:17255)
        at Lt.reposition (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:16833)
        at Lt.ngOnInit (VM45703 progress-kendo-angular-popup-533b0c0c.js:1:15507)
        at Cn (VM45697 core-572402a1.js:226:5516)
        at xn (VM45697 core-572402a1.js:226:5335)
        at Mn (VM45697 core-572402a1.js:226:4870)

**To Reproduce**
1. Open the browser dev tools and observe the console.
2. Browse to https://www.telerik.com/kendo-angular-ui/components/popup/
3. Watch for the error to appear in the console.
4. Click the button to show/hide the popups and observe the error occur again.

**Expected behavior**
No errors in the console and the popups are visible.

**Browser**
 - OS: Windows 10
 - Browser Edge
 - Version 109.0.1518.61

**Comment by Alexey3** [comment] 2023-01-26 15:59
Bumping up! Spent hours after updating to the latest packages v11.0.0 (thought it was something in my app), but like described above the issue is reproducible on the Telerik demos/examples. Tested in Chome, Edge, FF, mobile 
It's the showstopper for me, so had to revert all the updates

**Comment by marvhen** [comment] 2023-01-27 13:16
Thanks @dtopalov!  Are you saying that the issue only exists in the documentation and demos?  Per @Alexey3's comment it would seem there is a problem in the source code as well.

**Comment by mbechev** [comment] 2023-02-01 17:06
The Popup demos are now fixed on site:
https://www.telerik.com/kendo-angular-ui/components/popup/

**Closed by mbechev** 2023-02-01 17:06 UTC
Labels: Documentation, Team2
