### ISSUE TITLE
Kendo Angular Tooltip Always Showing at the Top When offset is set

### ISSUE THREAD

**Issue by siamcr7** [telerik/kendo-angular#2626] opened 2019-12-03 07:44 UTC
With all the values being set as default only change the following inputs:
- Set offset="2" (or any value)
- Set position="bottom"

Example: https://stackblitz.com/edit/angular-zih4ey (open in new tab for better result)

**Fix:**
Bind the value of offset to an variable.

I am a bit stunned here. Am I missing something here or is it a bug?

**Comment by elena-gancheva** [comment] 2019-12-03 08:56
Hi @siamcr7, the `offset` property of the tooltip is expecting a value of type `number`. Therefore, the proper property binding syntax is `[offset]="2"`. I have updated the [StackBlitz example](https://stackblitz.com/edit/angular-zih4ey-ntnf8o?file=app/app.component.ts) so that it works with the valid configurations.

I am closing this issue, since it is not a bug related to the Kendo Angular Tooltip component.

**Closed by elena-gancheva** 2019-12-03 08:56 UTC
Labels: Team2
