### ISSUE TITLE
[DropDowns] First item is not visible in IE when virtualization is enabled

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2578] opened 2019-10-31 09:28 UTC
**Describe the bug**
When virtualization is enabled, the first item is not visible when the options popup is opened via clicking on the Popup down arrow button. After scrolling or navigating through the list of options the item is displayed as expected.

**To Reproduce**
Observable in the online demos:

https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/virtualization/

**Expected behavior**
The first list item to be visible when the list is opened (like in the other browsers).

**Browser**
 - Browser IE
 - Version 11

**Comment by EricMacarez** [comment] 2019-11-07 13:14
A idea when it can be resolve ?

**Comment by EricMacarez** [comment] 2019-11-21 14:03
any news ?

**Comment by dimitar-pechev** [comment] 2019-11-21 14:41
@EricMacarez, sorry for the delayed response. The fix is available in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the package (**v4.2.3-dev.201911201019**). After some testing it will be included in the official release (usually within a few weeks time). If it's urgent for you, you can acquire the fix even now via `npm i @progress/kendo-angular-dropdowns@dev`.

**Comment by EricMacarez** [comment] 2019-11-21 16:49
Thank you very much @dimitar-pechev

**Comment by EricMacarez** [comment] 2019-11-23 21:12
I install the fix via npm but the problem is already present

**Comment by dimitar-pechev** [comment] 2019-11-25 08:37
This is probably the result either of caching or of an existing `package-lock.json` file. Try removing your `node_modules` folder, then remove the `package-lock.json` file before running `npm i @progress/kendo-angular-dropdowns@4.2.3-dev.201911201019`. If the issue persists, clear your npm cache and repeat the above steps. Testing it on my end with the specified version of the dropdowns under IE everything works as expected.

![combobox-virtualization-in-ie](https://user-images.githubusercontent.com/18740853/69524779-7fe93d80-0f6f-11ea-9664-6ce80fbe2b86.gif)

**Comment by EricMacarez** [comment] 2019-11-26 08:46
Hi Dimitri,

You are right.
It’Ok, probably result of caching.
It works perfectly.
Thank you very much.

Kind regards,

Eric MACAREZ
Directeur Technique
Tél : +33 (0)3 20 28 18 23 – Portable : +33 (0)6 63 76 84 14
Parc des Rives Créatives de l’Escaut
Batiment Nouvelle Forge
80 Avenue Roland Moreno 59410 ANZIN

[CIFEA-MKG-sign]<https://www.cifea-mkg.com/>            [Logo (White)-small] <https://www.privacyprotection-pact.org/>

Suivez-nous sur Twitter<https://twitter.com/CifeaMkg> et LinkedIn<https://www.linkedin.com/company/cifea-mkg>
P  Merci de considérer l'environnement avant d'imprimer ce mail

De : Dimitar Pechev <notifications@github.com>
Envoyé : lundi 25 novembre 2019 09:38
À : telerik/kendo-angular <kendo-angular@noreply.github.com>
Cc : Eric MACAREZ <Eric.MACAREZ@cifea-mkg.com>; Mention <mention@noreply.github.com>
Objet : Re: [telerik/kendo-angular] [DropDowns] First item is not visible in IE when virtualization is enabled (#2578)


This is probably the result either of caching or of an existing package-lock.json file. Try removing your node_modules folder, then remove the package-lock.json file before running npm i @progress/kendo-angular-dropdowns@4.2.3-dev.201911201019. If the issue persists, clear your npm cache and repeat the above steps. Testing it on my end with the specified version of the dropdowns under IE everything works as expected.

[combobox-virtualization-in-ie]<https://user-images.githubusercontent.com/18740853/69524779-7fe93d80-0f6f-11ea-9664-6ce80fbe2b86.gif>

**Comment by siyka-marinova** [comment] 2019-12-03 08:19
The fix is now also available in `@progress/kendo-angular-dropdowns v.4.2.3`

**Closed by siyka-marinova** 2019-12-03 08:19 UTC
Labels: Bug, Team1, freq3: likely, pkg:dropdowns, sev1: low
