### ISSUE TITLE
kendo-angular-layout@1.0.8 package seems corrupted

### ISSUE THREAD

**Issue by jackjoy** [telerik/kendo-angular#1062] opened 2017-11-07 09:48 UTC
```
@progress/kendo-angular-layout@1.0.8 seems corrupted,it does not have right files.

```

**Comment by tsvetomir** [comment] 2017-11-07 11:02
Thanks for the heads-up, will investigate.

**Comment by tsvetomir** [comment] 2017-11-07 13:17
Fixed in v1.0.9, apologies for the caused inconvenience.

We managed to identify the cause (see telerik/kendo-angular#1063). No other packages are affected.

**Closed** 2017-11-16 11:45 UTC
Labels: Bug, pkg:layout
