### ISSUE TITLE
Upload "Drop files here for upload" appears before hovering the drop zone

### ISSUE THREAD

**Issue by 1337-5P34Ker** [telerik/kendo-angular#1865] opened 2018-10-23 12:25 UTC
## I'm submitting a...

  * Support requests to https://www.telerik.com/account/support-tickets.

* Bug report 

## Current behavior

  * The Angular Upload component show the notice "Drop files here for upload" while moving the mouse not hovering the drop zone. So I drop the file and a download instead of an upload is starting. 

## Expected behavior
The notice should only appears if I can also drop the file to start the upload.

## Minimal reproduction of the problem with instructions

Try to drop a file over an existing file or outside the grey box. (while notice is shown)
[the documentation](https://www.telerik.com/kendo-angular-ui/components/upload/) 

## Environment

Package versions:
Angular 6
kendo-angular @latest

Browser:
- Chrome (desktop) version 70
- Firefox version 62
- Edge version 42

System:
- TypeScript version: 2.7.2
- Node version: 8.11.1 
- Platform:  Windows 10

**Comment by Raisolution** [comment] 2018-10-23 12:46
Hi @1337-5P34Ker,

The described behavior is by design - the drop zone hint is shown on dragenter to prompt the user where to drop the files that should be uploaded. Drop-ing the file anywhere else would open the local file by the browser.

**Comment by 1337-5P34Ker** [comment] 2018-10-23 13:55
Thanks for your answer, but the by design behavior doesn't work as desired. 
I would like to see the hint _only_ if I can really drop a file and not already on dragenter - and it doesn't matter where the mouse is.

**Comment by Raisolution** [comment] 2018-10-24 08:20
There is no issue with the current by design behavior - the drop hint is displayed on dragenter, so that the user is aware where to drop files.

I am closing this thread, as it is not a bug report. If we could help with some implementation details and specific scenarios, I would suggest opening a [support ticket](https://www.telerik.com/account/support-tickets).

**Closed by Raisolution** 2018-10-24 08:20 UTC
Labels: pkg:upload
