### ISSUE TITLE
NOTIFICATION_CONTAINER is not correctly exported

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1956] opened 2018-11-28 17:02 UTC
## I'm submitting a...
* Bug report

## Current behavior
Import of NOTIFICATION_CONTAINER is not possible.

`Module '"node_modules/@progress/kendo-angular-notification/dist/es2015/index"' has no exported member 'NOTIFICATION_CONTAINER'.`

## Expected behavior
Import has to work correctly as documented on page: https://www.telerik.com/kendo-angular-ui/components/notification/api/NOTIFICATION_CONTAINER/

## Minimal reproduction of the problem with instructions
Just go to simple stackblitz https://stackblitz.com/edit/angular-it9wft open `app.component.ts` on monaco editor and see error.

## Environment

Package versions:
"@progress/kendo-angular-notification": "1.1.0",

**Comment by danielkaradachki** [comment] 2018-11-29 06:45
The problem should be fixed in the [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version of the package.

**Comment by elena-gancheva** [comment] 2018-11-29 08:17
Hi @meriturva, the problem is fixed and shipped with `v1.1.1` of the package.

**Closed** 2018-11-30 08:35 UTC
Labels: Bug, Passed-QA, pkg:notification
