### ISSUE TITLE
throw NG0100 error, when grid filter dropdown closes (angular v18)

### ISSUE THREAD

**Issue by vargbalazs** [telerik/kendo-angular#4378] opened 2024-07-30 05:51 UTC
**Describe the bug**
With Angular v18 if we click on the filter button in the grid and then click away, then we get the NG0100 error. Interestingly if we select one of the filter, there is no error.

**To Reproduce**
Here is a simple stackblitz demonstrating the issue: https://stackblitz.com/edit/stackblitz-starters-fsdprj

**Expected behavior**
No error.

**Screenshots**

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 126.0.6478.185

**Additional context**
On your web page, with Angular 17 there is no error.

**Comment by yanmariomenev** [comment] 2024-07-30 07:33
Duplicate of - https://github.com/telerik/kendo-angular/issues/4375

Our team is aware that other components inherit the error and will provide a fix as soon as possible.

**Closed by yanmariomenev** 2024-07-30 07:33 UTC
Labels: Duplicate
