### ISSUE TITLE
undefined when no mask in kendo-maskedtextbox

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#366] opened 2017-03-10 12:21 UTC
if no mask it should be simple text-box isnt?
[plnkr](http://plnkr.co/edit/idXfIhA1B5O2naN0Tz1O?p=preview)

**Comment by KirilNN** [comment] 2017-03-10 16:06
duplicate of https://github.com/telerik/kendo-angular/issues/339

**Closed by KirilNN** 2017-03-10 16:06 UTC
