### ISSUE TITLE
[Charts] kendo-chart-tooltip is not working with OnPush change detection

### ISSUE THREAD

**Issue by dzolnjan** [telerik/kendo-angular#808] opened 2017-08-08 18:48 UTC
Just look at this default example with OnPush added.

http://plnkr.co/edit/PKmDukXjAXb1U9VAJxC7?p=preview

**Comment by danielkaradachki** [comment] 2017-08-09 07:14
Duplicate of https://github.com/telerik/kendo-angular/issues/730

**Closed by danielkaradachki** 2017-08-09 07:14 UTC
Labels: Duplicate, pkg:charts
