### ISSUE TITLE
ComboBox clear value if use primitive values from object fields and key Enter

### ISSUE THREAD

**Issue by makito** [telerik/kendo-angular#963] opened 2017-10-03 07:55 UTC
## I'm submitting a...
* Bug report

## Current behavior
When we use primitive values from object fields and select value by clicking on Enter, then value is clearing.

## Expected behavior
When we clicking on Enter, selected value shuld stay selected.

## Minimal reproduction of the problem with instructions
1. [here is demo based on your self documentation](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-primitive-values-from-object-fields)
2. Open example by using the **RUN CODE** button.
3. Set focus to combobox and click Enter (or select value with buttons and click on Enter).
4. Selected value is clearing.

## Environment

Package versions:
```
@progress/kendo-angular-dropdowns@1.2.1
```

Browser:
- Chrome (desktop) version 61.0.3163.100
- Firefox version 56.0
- IE version 11
- Edge version 40.15063.0.0

System:
- TypeScript version: 2.5.2
- Node version: v6.11.2
- Npm version: 3.10.10
- Platform:  Windows

**Comment by tapopov** [comment] 2017-10-03 08:12
Hi @makito 
This seems like a duplicate of https://github.com/telerik/kendo-angular/issues/851, which has already been fixed. Can you please verify this by updating?

**Comment by makito** [comment] 2017-10-03 08:32
Yes you are right. In version 1.2.2, this is fixed.

**Closed** 2017-10-03 08:33 UTC
Labels: pkg:dropdowns
