### ISSUE TITLE
Open as Plunker does not work

### ISSUE THREAD

**Issue by tiliev** [telerik/kendo-angular#1500] opened 2018-04-27 08:52 UTC
## I'm submitting a...
Bug report 

## Current behavior
**Open as Plunker** in the documentation do not work.

## Expected behavior
**Open as Plunker** in the documentation *should* work.

## Minimal reproduction of the problem with instructions
1. Go to [grid documentation](https://www.telerik.com/kendo-angular-ui/components/grid/) or any other component.
2. Click on the **Open as Plunker** button
3. Plunker is opened but the page is blank.

## What is the motivation or use case for changing the behavior?
Should be working.

## Environment

Browser:
- Chrome (desktop)
- Firefox
- IE
- Edge

## Screenshot from plunker in Chrome
![capture](https://user-images.githubusercontent.com/6439482/39353767-55a3cd80-4a11-11e8-9a3d-e0b0d2560873.PNG)

**Comment by Raisolution** [comment] 2018-05-01 08:10
Hi @tiliev,

Thank you for reporting this. It is an issue on the Plunker end, which should be fixed by now. Try clearing the cache on the page, if the problem is still reproducing.

**Closed** 2018-05-02 15:08 UTC
Labels: Documentation, Question
