### ISSUE TITLE
Dropdowns on Screens, that are higher than Monitor screensize, do not work after update to kendo-angular-dropdowns": "3.1.0"

### ISSUE THREAD

**Issue by luKiPfeffer** [telerik/kendo-angular#1851] opened 2018-10-15 15:58 UTC
## I'm submitting a

* Bug report [proposed Label Bug]

## Current behavior
With the update of  "@progress/kendo-angular-dropdowns": "3.1.0" i get the following bug:
On screens that are higher than the screensize of my monitor, Dropdowns do not open after i scroll down and click on them.  Instead it jumps to the top of the page and then jumps back to the dropdown really fast.

By returning to  "@progress/kendo-angular-dropdowns": "3.0.1", it works again.

## Expected behavior
Dropdown overlay should open and show the available options.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-nnsr3y?file=package.json

The first dropdown works fine. I've you scroll down to the second dropdown(copy of the first) and click on it, you will see that it doesn't open, instead it jumps to the top of the page and then jumps back  to the dropdown really fast.

Browser:
- Chrome (desktop) version  69.0.3497.100

System:
- TypeScript version:2.7.2
- Platform:  Windows

**Comment by tapopov** [comment] 2018-10-16 07:50
Thanks for reporting this! We'll investigate as soon as possible.

**Comment by dvdgutzmann** [comment] 2018-10-17 14:51
The bug only surfaces when filtering is enabled (see #1857).

**Comment by dtopalov** [comment] 2018-10-17 14:57
Closing this issue as a duplicate of [https://github.com/telerik/kendo-angular/issues/1784](https://github.com/telerik/kendo-angular/issues/1784)

**Closed by dtopalov** 2018-10-17 14:57 UTC
Labels: pkg:dropdowns
