### ISSUE TITLE
DropDownList with filtering - Closing the popup by click doesn't work properly 

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#688] opened 2017-06-26 06:34 UTC
Hi, 
after opening the popup you want close it if the cursor is in the filterbox, it will open immediately again. I think it is a strange behavior. Is'nt it?

test here
http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/

best regards

**Comment by tapopov** [comment] 2017-06-26 09:28
Hi @anj01 

I tried reproducing this in Chrome and IE11, but it seems to be working as expected. Would you please share the exact steps and setup in order to reproduce the issue?

Thanks!

**Comment by anj01** [comment] 2017-06-26 10:04
Just click for opening und closing popup without leaving the component... 

![grafik](https://user-images.githubusercontent.com/22910183/27534370-062b4b1a-5a67-11e7-9903-ab35371b64ea.png)

**Comment by tapopov** [comment] 2017-06-26 10:47
Thanks, I can confirm this is not expected and it will be investigated as soon as possible.

**Comment by ipeshev** [comment] 2017-10-03 06:40
Fixed in v1.2.2-dev.201710021504

**Closed by ipeshev** 2017-10-03 06:40 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
