### ISSUE TITLE
Sparkline Chart Height

### ISSUE THREAD

**Issue by jhairau** [telerik/kendo-angular#1065] opened 2017-11-07 20:46 UTC
## I'm submitting a...

* Bug report 

## Current behavior

SparkLine Charts are very tall (~400px). They appear to be inheriting the styling from `.k-chart`. I don't recall what their height used to be before updating to the latest RC version of charts.

## Expected behavior

SparkLine Charts should be closer to ~50px. I don't recall what height the used to have and what the class they used to use for defining their height.

## Minimal reproduction of the problem with instructions

Go to the documentation page for Sparkline on the official docs site and you can see they are ~400px high. https://www.telerik.com/kendo-angular-ui/components/charts/sparkline/

## What is the motivation or use case for changing the behavior?

Developers don't have to either create custom styling or notes of breaking changes in the changelogs that heights now need to be specified.

## Environment
Browser:

- Chrome (desktop) version 61.0.3163.100

System:
- Platform:  Mac

**Comment by danielkaradachki** [comment] 2017-11-08 06:17
Seems like regression caused by a fix for setting custom classes. We will fix it in the next version. Apologies for the inconvenience caused.

**Comment by ipeshev** [comment] 2017-11-08 09:58
Fixed in v1.3.3-dev.201711080819

**Comment by jhairau** [comment] 2017-11-14 20:47
Thanks

**Closed** 2017-11-15 05:56 UTC
Labels: Bug, Passed-QA, pkg:charts
