### ISSUE TITLE
[Grid] Opening the filter and column menu triggers page scroll

### ISSUE THREAD

**Issue by oshri551** [telerik/kendo-angular#3392] opened 2021-07-25 07:35 UTC
**Describe the bug**
Situation: When we have a page full of information and the grid in the scroll area.
Click on the filter button will do scroll to top of the page

**To Reproduce**
I have a StackBlitz:

[StackBlitz link](https://stackblitz.com/edit/angular-ncdkt4).

**Expected behavior**
Page should stay on the same scroll position

**Screenshots**
StackBlitz 

**Browser**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [92.0.4515.107]

**Comment by yanmariomenev** [comment] 2021-07-27 08:47
The bug is present in version 5.1.0 to @latest. Also can be observed when opening the Column Menu.

**Comment by yanmariomenev** [comment] 2021-08-11 09:51
I manage to create two workarounds depending on the Grid position.

1. When the Grid is positioned on the bottom of the page, then a click event can be attached to the filter button and adjust the scroll position when clicked:
https://stackblitz.com/edit/angular-ncdkt4-ahtgkc

2. If the Grid position isn't on the bottom of the page, then listening to the scroll event and saving the last know position is a 
 possible solution. The bug itself sets the position at 0, and when that happens, the last know position can be assigned to the window.scrollTo coordinates:
https://stackblitz.com/edit/angular-ncdkt4-lone5o?file=app%2Fapp.component.ts

I hope both workarounds help until the issue is fixed.

**Comment by jcocca** [comment] 2021-09-03 18:02
Same issue here, using "@progress/kendo-angular-grid": "^5.0.1"

**Comment by yanmariomenev** [comment] 2021-09-14 11:24
> Same issue here, using "@progress/kendo-angular-grid": "^5.0.1"

I would also suggest the following steps that might help:

1. Deleting package-lock.json and node_modules folder in your project  

2. Clean the cache - npm cache clean

3. Install back the node modules via "npm install" command

**Comment by yanmariomenev** [comment] 2021-09-14 11:31
The issue is also present/related when using column menu to hide a column inside a Grid with a horizontal scrollbar duo to larger amount of columns. Check the following demo and hide column 'id' that will reproduce the horizontal scrollbar to move right:
https://stackblitz.com/edit/angular-uvszf5-biypem
The bug is also present from v5.1.0 to the latest version of the Grid component and v5.0.3 doesn't seem to be affected by it.

**Comment by ipeshev** [comment] 2022-01-07 13:29
Fix available in latest [@progress/kendo-angular-popup dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by dimitar-pechev** [comment] 2022-01-11 18:11
The fix is available in `@progress/kendo-angular-popup@4.0.3`. Installing the latest Grid version (`5.5.2`) with ng add will also automatically use that Popup version as a minimal requirement.

**Closed by dimitar-pechev** 2022-01-11 18:11 UTC
Labels: Bug, pkg:grid, Team1, sev1: low, freq2: possible
