### ISSUE TITLE
Groupable breaks sorting

### ISSUE THREAD

**Issue by zarpilla** [telerik/kendo-angular#717] opened 2017-07-04 10:56 UTC
Hi, 

In the example: http://plnkr.co/edit/T6TlLgt7rydMqGC4uNo1?p=preview
we can't sort the columns. 

If changing:
[groupable]="true"
to
[groupable]="false"
the sorting functionallity works again.

Thank's

**Comment by tsvetomir** [comment] 2017-07-04 11:42
Sorting seems to work fine in the plunkr. I'm clicking the column headers. Am I missing something?

**Comment by zarpilla** [comment] 2017-07-04 11:52
It works well in Firefox and Edge but it doesn't works on Google Chrome versión 59.0.3071.115 in a Windows 10 64bits SO.

**Comment by zarpilla** [comment] 2017-07-05 08:00
Sorry, works today after restarting Windows. Maybe a Chrome problem.

**Comment by pkoecker** [comment] 2017-08-25 10:44
I am facing the same issue. In Chrome 60.0.3112.101 (64bit) as soon as I click on the column header to sort a small label appears immediately. I can drag this label for grouping, but since it appears immediately I cannot sort my columns anymore. 

After a bit of testing I realised, that the bug cannot be reproduced reliably. It occurs sometimes and my guess is, that it is related to when the drag-event is fired. When I click very carefully without moving my mouse at all, then everything works as exspected. However if I move my mouse by 1px (on a 4k screen) the grouping is started instead of the sorting. 

Maybe there is a way to decrease the "sensitivity" of the grouping event? Maybe it could start only if the user has hold the left mouse button for more than .5 seconds?

Hope this helps you a bit.

**Comment by TrevorBroderick1** [comment] 2017-08-31 18:43
I regularly experience the same bug as @pkoecker. It's a real pain and needs some sort of a fix.

**Comment by zarpilla** [comment] 2017-09-01 05:51
reopened

**Comment by rkonstantinov** [comment] 2017-09-04 08:31
We have increased the time required to hold the mouse down before the drag is triggered. The change is available in [the dev channel](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), please give it a spin and see if it helps.

**Comment by pkoecker** [comment] 2017-09-04 08:44
@rkonstantinov Thanks you! This solved the problem for me. It works much better now.

**Comment by tsvetomir** [comment] 2017-09-13 15:56
The fix was released in v1.4.1 of the kendo-angular-grid package

**Closed** 2017-09-18 06:29 UTC
Labels: pkg:grid, Question
