### ISSUE TITLE
Combobox : Filtering and binding to reactive forms completely broken

### ISSUE THREAD

**Issue by talynone** [telerik/kendo-angular#812] opened 2017-08-09 17:27 UTC
## I'm submitting a...

* Bug report 

## Current behavior

I have an async service (not an observable pipe) that creates a filtered list after a minimum 3 characters are typed.

The combobox is bound as reactive form item.

After a filter is applied selecting an item from the list does not set the bound form item . 

Setting the item manually in typescript via the reactiveform with syntax such as:

this.myForm.get('NameList').setValue(this.selectedName);

Also doesn't work (while the above syntax does work with non Kendo html form controls). 

When typing values for the filter, the input texbox portion of the combobox gets randomly wiped. I can fix this by not setting the [data] binding value of the ComboBox in html and instead setting this.NameCbo.data directly in typescript, but this introduced more problems.

SelectionChange only seems to fire once on a bound reactive form control, but not on subsequent selections. 

Selecting an item via keyboard by pressing down arrow onto the list and pressing enter populates the textbox but does not select the item.

Pressing enter on a selected item multiple times throws an exception in the console. 

Can't figure out a way to get the combobox to select the first item in the list on enter key press (probably related to issue 1).

I can't wait for all these issues to be fixed so for now I'm switching to the Bootstrap 4 typeahead control. I've already wasted too much time on all these issues and trying to figure out a work-around. If the included information is not enough I'll try to create a plunker on the weekend, creating one with dummy async data would take more time than I currently have. 

## Environment

Package versions:

`
+-- @angular/animations@4.3.3
+-- @angular/cli@1.2.7
+-- @angular/common@4.3.3
+-- @angular/compiler@4.3.3
+-- @angular/compiler-cli@4.3.3
+-- @angular/core@4.3.3
+-- @angular/forms@4.3.3
+-- @angular/http@4.3.3
+-- @angular/language-service@4.3.3
+-- @angular/platform-browser@4.3.3
+-- @angular/platform-browser-dynamic@4.3.3
+-- @angular/platform-server@4.3.3
+-- @angular/router@4.3.3
+-- @ng-bootstrap/ng-bootstrap@1.0.0-alpha.30
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-dateinputs@1.0.5
+-- @progress/kendo-angular-dialog@1.1.0
+-- @progress/kendo-angular-dropdowns@1.1.2
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.2.3
+-- @progress/kendo-angular-inputs@1.0.7
+-- @progress/kendo-angular-intl@1.2.2
+-- @progress/kendo-angular-l10n@1.0.2
+-- @progress/kendo-data-query@1.0.6
+-- @progress/kendo-drawing@1.1.2
+-- @progress/kendo-theme-default@2.39.0
+-- @types/jasmine@2.5.53
+-- @types/node@8.0.19
+-- ag-grid@12.0.2
+-- ag-grid-angular@12.0.0
+-- angular-spinners@5.0.4
+-- bootstrap@4.0.0-alpha.6
+-- code-point-at@1.1.0
+-- codelyzer@3.1.2
+-- core-js@2.4.1
+-- font-awesome@4.7.0
+-- jasmine-core@2.7.0
+-- jasmine-spec-reporter@4.1.1
+-- jquery@3.2.1
+-- karma@1.7.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- ngx-loading@1.0.5
+-- ngx-toastr@6.0.0
+-- process-nextick-args@1.0.7
+-- protractor@5.1.2
+-- rxjs@5.4.2
+-- ts-node@3.3.0
+-- tslint@5.5.0
+-- typescript@2.4.2
+-- util-deprecate@1.0.2
+-- zone.js@0.8.16
`
Browser:

- Chrome (desktop) version 60.0.3112.90

System:
- TypeScript version: 2.4.2
- Node version: 6.11.0
- NPM version: 5.2.0
- Platform:  Windows

**Comment by ggkrustev** [comment] 2017-08-10 06:44
@talynone, thanks for the report. Would it be possible to share a minimal repro demo that we can observe locally? This will help us a lot in tracking down the cause of the issue.

**Comment by talynone** [comment] 2017-08-11 13:01
Here's an example of one of the bugs, notice how when you start typing into the combobox the text gets deleted:

http://plnkr.co/edit/MpBHII?p=info

**Comment by tapopov** [comment] 2017-08-28 15:23
Hi @talynone,

We've already identified what's causing the disappearing text while filtering and work on fixing on it. Having a plunkr where the rest of the issues are reproducible would be invaluable though, as the scenarios are really tightly connected and we wouldn't want to miss anything.

**Comment by ipeshev** [comment] 2017-09-28 12:10
Now there is another problem in the sample plunker. 
Once you select an item, if open popup again then it is only one item in the popup - the selected one.

**Comment by tapopov** [comment] 2017-09-28 13:10
@ipeshev 
This is expected, given how the `filterChange` event is handled:
```javascript
handleFilter(value) {
  let parent = this;
  
   setTimeout(() => {
       parent.data =  [parent.source[0]];
    }, 500);
}
```
I'm closing this, since the issues mentioned above have been fixed in the latest `dev` version. Feel free to repoen if necessary.

**Closed by tapopov** 2017-09-28 13:10 UTC
Labels: pkg:dropdowns
