### ISSUE TITLE
 Links must have discernible text (.k-grid-filter[href="#"])

### ISSUE THREAD

**Issue by sryeluri** [telerik/kendo-angular#2040] opened 2019-01-25 08:57 UTC
Below is an accessibility issue that needs investigation.

Issue Details
Links must have discernible text

Snippet
<a class="k-grid-filter" href="#" tabindex="-1"><span class="k-icon k-filter"></span></a>

Expected Fix : 
- Element does not have text that is visible to screen readers
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element's default semantics were not overridden with role="presentation"
- Element's default semantics were not overridden with role="none"

Environment
Chrome version 70.0.3538.77

**Comment by ipeshev** [comment] 2019-01-25 11:42
@sryeluri thank you for the bug report we will investigate it further.

**Comment by tsvetomir** [comment] 2019-01-31 06:44
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/1710

**Closed by tsvetomir** 2019-01-31 06:44 UTC
Labels: Bug, pkg:grid

**Comment by kraay** [comment] 2019-02-21 08:24
@tsvetomir Created issue [4860 ](https://github.com/telerik/kendo-ui-core/issues/4860)in kendo-ui-core as our application uses AngularJS.
