### ISSUE TITLE
Kendo tooltip is not aware of tooltips that have the similiar offset.

### ISSUE THREAD

**Issue by Rudokus** [telerik/kendo-angular#2634] opened 2019-12-04 13:57 UTC
**Describe the bug**
When having multiple tooltips that are defined in a parent child DOM. Both the tooltips have the same position and are positioned on top of each other. The parent tooltip is shown and the child tooltip is shown behind the parent tooltip.
Tooltips positioning does not take account the parent tooltip.
**To Reproduce**

https://48i2qw.run.stackblitz.io

trigger a mouseover on both elements.

**Expected behavior**
Using the popupservice I would expect tooltips are prepended when in "parent child mode" or the tooltip is repositioned above the other tooltip when overlapping.

**Screenshots**
![Annotation 2019-12-04 145532](https://user-images.githubusercontent.com/6574485/70148316-36eb6480-16a6-11ea-8346-6f54ea8daaa4.png)

**Browser**
 - OS: Not relevant
 - Browser Not relevant
 - Version Not relevant

**Additional context**

**Comment by elena-gancheva** [comment] 2020-01-24 13:49
Hi @Rudokus, the StackBlitz link provided in the issue is not working properly.

Could you please check your StackBlitz privacy settings or reproduce the problem [here](https://stackblitz.com/edit/angular-skcsem). What would be great, is to give us runnable StackBlitz project with both the code and the preview.

**Comment by elena-gancheva** [comment] 2020-03-19 12:03
Closing this issue, since the problem is not reproducible.

**Closed by elena-gancheva** 2020-03-19 12:03 UTC
Labels: Bug, Team2, pkg:tooltip
