### ISSUE TITLE
Floating label with Angular reactive form reset

### ISSUE THREAD

**Issue by cknightdevelopment** [telerik/kendo-angular#1027] opened 2017-10-20 17:56 UTC
## I'm submitting a...

* Bug report 

## Current behavior

When using kendo textbox container with a floating label with Angular intergration and resetting the Angular reactive form, the floating label stays on top of the textbox rather than going back "inside" it.

## Expected behavior

I would expect the label to go back inside the "textbox" like when the form is first loaded.

## Minimal reproduction of the problem with instructions

http://plnkr.co/0CxqO4bOG2bvvyBP1Yxd

## What is the motivation or use case for changing the behavior?

This is causing form resets to not behave as expected.

## Environment

Package versions:

```
The issue is reproducible on the demo site.
```

Browser:

- Chrome (desktop) version 61.0.3163.100

System:
- TypeScript version: 2.0.10
- Node version: v6.9.1 3.5.0
- Platform:  Windows

## Additional Info:

From my basic investigation, it looks like the class `k-state-empty` in not added to the `kendo-textbox-container` element when the form is reset.

**Comment by gyoshev** [comment] 2017-11-16 08:47
The fix has been released in version `1.3.3` of the `@progress/kendo-angular-inputs` package.

**Closed by gyoshev** 2017-11-16 08:47 UTC
Labels: Bug, Passed-QA, pkg:inputs

**Comment by giangpham05** [comment] 2019-11-20 02:13
This is not fixed with "@progress/kendo-angular-inputs": "6.0.0".  It's happening in Telerik website as well.

**Comment by danielkaradachki** [comment] 2019-11-20 09:09
Could you clarify in which demo? Seems to work correctly on reset here:
https://stackblitz.com/edit/angular-pubtpe?file=app%2Fapp.component.ts

**Comment by giangpham05** [comment] 2019-11-20 09:17
To reproduce it, you can set the name field to empty, when the app loads at for very first time, the laybel displays on top, I would expect it to display inside the field like its placeholder. If you don't type anything, it will stay on top. When you type in a text and click anywhere, this triggers the textbox to be unfocused, then click back again, this time the label floats back to the textbox. I think there must be something to do with focus event which is not being triggered correctly.

**Comment by giangpham05** [comment] 2019-11-20 09:23
FYI, here is the demo from Telerik website.
See [https://stackblitz.com/run/](url)
You can see the 'First name' label displays on the top, it should be inside of the field (please see screenshot):
Current:
![image](https://user-images.githubusercontent.com/22335965/69225892-588f1b00-0bd3-11ea-8604-890d0f90338e.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/22335965/69225949-7197cc00-0bd3-11ea-9b89-5b909cc0e665.png)

**Comment by danielkaradachki** [comment] 2019-11-20 09:38
The problem seems to be related to this issue:
https://github.com/telerik/kendo-angular/issues/2568
Not to form reset. Correct?

**Comment by giangpham05** [comment] 2019-11-20 10:06
Yes, that's correct.  Was there any progress on this?

**Comment by danielkaradachki** [comment] 2019-11-20 10:10
Not yet. We will update the other issue as soon as there is a fix.

**Comment by giangpham05** [comment] 2019-11-20 10:11
Thanks mate.
