### ISSUE TITLE
Wont be able to change custom position of Tooltip rather its default position top, left, right, bottom in Kendo- Angular

### ISSUE THREAD

**Issue by Napster2019** [telerik/kendo-angular#3031] opened 2020-08-11 13:01 UTC
I need my tooltip like this
![image](https://user-images.githubusercontent.com/55491051/89899122-6ec88580-dbff-11ea-81ba-ede5e7c5eb11.png)
 and I am getting like this
![image](https://user-images.githubusercontent.com/55491051/89899355-cb2ba500-dbff-11ea-8a4f-4fc3b222de16.png)
 You can see the above image has shadow type box because  there is a class k-popup.

Now My code is like this

 <ng-template #alarmdes let-anchor>
                {{anchor.nativeElement.getAttribute('dataTooltip')}}
</ng-template>
              <div  class="alarm"
                    showOn="click"
                    kendoTooltip
                    [tooltipTemplate]="alarmdes"
                    filter=".alarmdescp">

<kendo-grid-column field="alarmId" title="Alarm Type" [width]="250">
     <ng-template kendoGridCellTemplate let-dataItem> 
              <span>{{dataItem.alarmName}}</span>
              <span  class="alarmdescp" [attr.dataTooltip]="dataItem.description">
                <img src="../../assets/images/info.svg" alt="i"  style="width: 12px; height: 12px;margin:10px;" />
              </span>
      </ng-template>
</kendo-grid-column>

css is like this :- 

.k-tooltip {
  box-sizing: border-box !important;
  width:500px;
  border: none;
  background-color: #FFFFFF !important;
  box-shadow: 0 2px 4px 0 rgba(22,34,58,0.11) !important;
  color: white !important;
  left:40%;
}

.k-callout-s {
  color: white;
  box-shadow: 0 2px 4px 0 rgba(22,34,58,0.11) !important;
}

.k-tooltip-content{
  color: #3E3935;
  font-family: "Helvetica Neue";
  font-size: 12px;
  letter-spacing: 0;
  line-height: 20px;
  text-align: justify;
}

Also tooltip is not working on the showOn ="hover" on mobile browser. It is accessible by doing click.

Also, wont be able to change the css explicitly.

**Comment by elena-gancheva** [comment] 2020-08-12 05:30
Hi @Napster2019, could you please specify the desired behavior of the Tooltip and if possible reproduce the problem in this runnable StackBlitz example [here](https://stackblitz.com/edit/angular-czigvn?file=app/app.component.ts).

Hover interactions do not exist on touch devices, this is why on mobile browsers the Tooltip should be opened through its `showOn='click'` configuration.

**Comment by Napster2019** [comment] 2020-08-12 05:55
> Hi @Napster2019, could you please specify the desired behavior of the Tooltip and if possible reproduce the problem in this runnable StackBlitz example [here](https://stackblitz.com/edit/angular-czigvn?file=app/app.component.ts).
> 
> Hover interactions do not exist on touch devices, this is why on mobile browsers the Tooltip should be opened through its `showOn='click'` configuration.

**Comment by Napster2019** [comment] 2020-08-12 05:57
but I need Hover interaction on my mobile browser, how to do that also, I am giving the example on stackoverflow

**Comment by Napster2019** [comment] 2020-08-12 06:02
https://angular-czigvn-jsqhej.stackblitz.io

In the same example I need tooltip's position = top but not at the center of the div, slight to the right! How I would achieve it?

**Comment by elena-gancheva** [comment] 2020-08-12 06:44
@Napster2019, by using the `k-tooltip-wrapper` class selector, the desired custom positioning could be achieved, please see the runnable StackBlitz example [here](https://stackblitz.com/edit/angular-czigvn-mxbzuc). Also, corresponding to [this article](https://patrickhlauke.github.io/touch/tests/results/) the `mouseover` event on mobile browsers can be achieved by `tap and hold` on the anchor element of the tooltip and it works as expected. 

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

I am closing this issue, since this is not a bug related to the Tooltip.

**Closed by elena-gancheva** 2020-08-12 06:44 UTC

**Comment by Napster2019** [comment] 2020-08-12 07:51
Thanks @elena-gancheva !
