### ISSUE TITLE
@progress/kendo-angular-charts 4.1.5 -> error on prod

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2966] opened 2020-06-25 13:10 UTC
Updating all packages to latest version (still on angular 9.1.11) i found that package @progress/kendo-angular-charts 4.1.5 on prod throws error:

main.3f436b464a06d00d92da.js:1 Uncaught TypeError: Cannot read property 'dateFormats' of undefined
    at Module.zUnb (main.3f436b464a06d00d92da.js:1)
    at i (runtime.c532273e4f1e83dd741c.js:1)
    at Object.0 (main.3f436b464a06d00d92da.js:1)
    at i (runtime.c532273e4f1e83dd741c.js:1)
    at t (runtime.c532273e4f1e83dd741c.js:1)
    at Array.r [as push] (runtime.c532273e4f1e83dd741c.js:1)
    at main.3f436b464a06d00d92da.js:1

With version 4.1.4 there is no such problem.

Ticket 1473464 on telerik support

**Comment by tsvetomir** [comment] 2020-06-25 14:16
Thanks for reporting, I've managed to reproduce the issue. It's an odd one because the code that throws the error hasn't been modified for quite a while.

**Comment by meriturva** [comment] 2020-06-25 14:23
In fact, I have another project quite old that now even with version 4.1.4 throws error on prod.
Do you have a version number without that issue? Just to run tests on it

**Comment by tsvetomir** [comment] 2020-06-25 15:12
Fixed in `@progress/kendo-charts` v1.14.2 and `@progress/kendo-drawing` v1.8.1.
That explains why changing the `@progress/kendo-angular-charts` version was not effective.

Running `npm update` should update these depdendencies.
If that fails, remove `node_modules`, `package-lock.json` and re-install.

**Comment by meriturva** [comment] 2020-06-25 15:25
I will give it a try as soon as possible

**Comment by juanslingerURUIT** [comment] 2020-06-25 15:26
Hi, @tsvetomir thanks for the answer.

From Kendo angular chart documentation (https://www.telerik.com/kendo-angular-ui/components/charts/get-started/) I'm seeing `@progress/kendo-drawing` as a dependency but not `@progress/kendo-charts`.

Do the documentation needs to be updated?
I'm testing in our production mode this solution

**Comment by meriturva** [comment] 2020-06-25 17:34
Sorry @tsvetomir on my side still present

**Comment by meriturva** [comment] 2020-06-25 17:45
Ok it works... I forgot to update the lock file on CI.
Now seems ok.

**Comment by tsvetomir** [comment] 2020-06-26 05:49
@juanslingerURUIT The "kendo-charts" package is a direct dependency and is not listed together with the peers.

To make sure that everyone gets the update, we've released v4.1.6 of `@progress/kendo-angular-charts` that explicitly references the fixed version.

Sorry for the trouble!

**Closed by tsvetomir** 2020-06-26 05:49 UTC
Labels: Bug, pkg:charts
