### ISSUE TITLE
Combobox: Suggest=true and allowCustom=true don't work with value=object

### ISSUE THREAD

**Issue by dummdidumm** [telerik/kendo-angular#2111] opened 2019-03-06 09:14 UTC
**Describe the bug**
Using a combobox with object values/data + suggest=true + allowCustom=true gives wrong behavior for suggestions. Suggestions are never resolved to the correct value unless you type in the full text with correct upper/lowercase.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-nzkh5t 
2. Type "A" into the combobox
3. You see that "Albania" is suggested
4. Press enter
5. Alert popups shows up indicating that the suggestion is not used, instead the value the user typed in ("A") is passed to the valueNormalizer.

This always happens when you not fully type in the word (with correct upper/lowercase). So "Alb" or "albania" also don't work, only "Albania" works.

**Expected behavior**
Suggested value is set as the new value (also regardless of upper/lowercase).

**Browser**
 - OS independent
 - Browser independent
 - Version: Latest

**Comment by dimitar-pechev** [comment] 2019-03-07 08:45
It seems to work as you expect in Chrome, but in FF the behavior is as you describe it. 

By design, when the `allowCustom` prop is set to true, hitting enter does not select the focused item, but rather keeps the text you've typed. It does seem, however, the more natural behavior to select the suggestion when it displays it. We'll review the issue and provide a fix.

**Comment by ipeshev** [comment] 2019-04-04 15:02
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment] 2019-04-12 08:28
Released in v3.5.3

**Closed by tsvetomir** 2019-04-12 08:28 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
