### ISSUE TITLE
SplitButton elements are unreachable when there are too many of them

### ISSUE THREAD

**Issue by maciej-bielecki** [telerik/kendo-angular#1385] opened 2018-03-16 14:54 UTC
## I'm submitting a...

* Suggestion for improvement
* Asking for possible solution

## Current behavior
When <kendo-splitbutton> is expanded and its size exceeds height of container, we cannot see those which are at bottom.

## Expected behavior
I think there should be possibility to scroll there.

## Minimal reproduction of the problem with instructions
Any kendo-splitbutton with lots of data that will exceed browser height.

## Environment

Package versions:
"kendo-angular-buttons": "3.0.3",
"kendo-angular-dateinputs": "2.1.1",
"kendo-angular-dialog": "3.1.2",
"kendo-angular-dropdowns": "2.0.2",
"kendo-angular-excel-export": "1.0.6",
"kendo-angular-grid": "2.1.0",
"kendo-angular-inputs": "2.1.1",
"kendo-angular-intl": "1.3.1",
"kendo-angular-l10n": "1.0.6",
"kendo-angular-layout": "2.0.1",
"kendo-data-query": "1.2.0",
"kendo-drawing": "1.5.1",
"kendo-theme-default": "2.48.1",
"kendo-ui": "2018.1.221",

Browser:

Chrome (desktop) Version 64.0.3282.186 (Official Build) (64-bit)
System:

TypeScript version: 2.6.1
Node version: node: v6.11.3, npm: 3.10.10
Platform: Windows 10 64bit

**Comment by gyoshev** [comment] 2018-03-20 06:40
A workaround for the issue is to set a `max-height` and `overflow:auto` on the button container.

```css
>>> kendo-button-list .k-list {
    max-height: 240px;
    overflow: auto;
}
```

Here is a [plunker that shows this approach](https://plnkr.co/edit/aJp87Sz8VcZHulhkgxhA?p=preview).

This could be provided in the component through a `maxHeight` option in the [PopupSettings](https://www.telerik.com/kendo-angular-ui/components/buttons/api/PopupSettings/).

Note that there may be better UI decisions than showing lots of items (and hiding them in a scrollable element). Consider providing search, for example through a [dropdownlist with filtering](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/).

**Comment by maciej-bielecki** [comment] 2018-03-20 08:28
Providing search would do the trick, we will consider it, but it's another topic.

Workaroud that you proposed is using deprecated  shadow-piercing descendant combinator [https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep). So it doesn't seems fine. 

Also I didn't saw `maxHeight` option in [PopupSetting](https://www.telerik.com/kendo-angular-ui/components/buttons/api/PopupSettings/), maybe I missed something.

**Comment by gyoshev** [comment] 2018-03-20 08:57
@maciej-bielecki The suggested approach is a workaround until the `maxHeight` property is implemented (and this issue is closed). Instead of the shadow-piercing selector, you can use `ViewEncapsulation.None` or global styles for the workaround.

**Comment by maciej-bielecki** [comment] 2018-03-20 10:26
@gyoshev Thanks, for detailing. For now  - it'll do the trick. Looking forward for `maxHeight` implementation.

**Comment by gyoshev** [comment] 2018-03-20 11:02
> Is there possibility to show scroll not after fix height is reached (240px in your example) but when it is needed - for example when browser height is exceeded.

Only if the `max-height` is calculated and set through client-side scripting.
For more information, please [open a support ticket](https://www.telerik.com/account/support-tickets).

**Comment by tsvetomir** [comment] 2018-07-06 13:04
Closing as there are no plans for a built-in scroll behavior for the split button.

**Closed by tsvetomir** 2018-07-06 13:04 UTC
Labels: Enhancement, pkg:buttons
