### ISSUE TITLE
[Card] Width is set to 285px 

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2955] opened 2020-06-18 05:08 UTC
We are using the kendo-card component and we are wondering why the width initially is set to 285px?
In most cases we had to override the width with 'auto' or '100%'.

Wouldn't 'auto' the better preset or why is 285px used as default? 

Regards
Markus

**Comment by elena-gancheva** [comment] 2020-06-18 07:09
Hi @SchneiderMK, the Card width is `285px` by design, as having a sensible default, gives better control when positioning and controlling cards in an application layout. I am closing the issue, since this is not a bug related to the Card component.

**Comment by SchneiderMK** [comment] 2020-06-18 09:45
Shure it's not a bug. But please investigate if the preset of 285px is the best one.
We have to change this value every time we use this component and must set it to 'auto'.
I can raise a feature request i it helps with this issue.

**Comment by elena-gancheva** [comment] 2020-06-18 13:01
Hi @SchneiderMK, after a discussion, we decided to enhance the Card component as suggested. I am reopening this issue as an enhancement and once implemented I will update its status.

**Comment by SchneiderMK** [comment] 2020-06-18 13:21
Thank you. That's great!

**Comment by Raisolution** [comment] 2021-11-23 09:29
The update has been applied.

**Closed by Raisolution** 2021-11-23 09:29 UTC
Labels: Enhancement, pkg:layout, Team2
