### ISSUE TITLE
MultiSelect: Backspace Key Does Not Delete Item

### ISSUE THREAD

**Issue by lukelengl** [telerik/kendo-angular#1090] opened 2017-11-16 20:13 UTC
## I'm submitting a...
* Bug report

## Current behavior
When the value array contains an element that does not exist in the list of options, pressing Backspace does not delete that item when it is behind the cursor.

## Expected behavior
Pressing Backspace should delete  items, regardless of whether they are in the options list.

## Minimal reproduction of the problem with instructions
Check out the following example:
http://plnkr.co/edit/nu1MN6Bdt3gI51jqiBxJ

Two items are in the list: "Ping Pong" and "Baseball". Setting focus to the Multiselect and pressing Backspace deletes "Baseball". Pressing Backspace again does not delete "Ping Pong". "Ping Pong" is not in the options to select from, but a user would expect it to delete anyway.

## What is the motivation or use case for changing the behavior?
Consistent behavior of the backspace key.

## Environment
Browser:
- Chrome (desktop) version 62
- Firefox version 57

**Comment by lukelengl** [comment] 2017-12-14 15:32
Any updates on this?

**Comment by valchev** [comment] 2017-12-15 08:23
@lukelengl the issue is fixed in the latest version, please update the kendo-angular-dropdowns package and give it a try.

**Comment by lukelengl** [comment] 2017-12-15 15:05
This bug is fixed, but now it does not display all of the placeholder text.

See the following Plunker: http://plnkr.co/edit/sla1BdMnursyihOVXqGv?p=info

Remove all of the tags. You will see the entire placeholder text. Add another tag. Remove that tag. Now the placeholder text is not entirely visible.

**Comment by elena-gancheva** [comment] 2017-12-15 15:35
@lukelengl, the issue with the placeholder is now fixed in the latest **dev** version. For reference:  https://github.com/telerik/kendo-angular/issues/1144

**Comment by ipeshev** [comment] 2017-12-18 14:13
fixed in v1.4.1-dev.201712180927

**Comment by valchev** [comment] 2018-01-12 13:24
Version 1.4.1 is shipped

**Closed by valchev** 2018-01-12 13:24 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
