### ISSUE TITLE
DropdownList inside a label not opening when clicked

### ISSUE THREAD

**Issue by hannecolaers** [telerik/kendo-angular#4087] opened 2023-08-21 10:24 UTC
## Current behavior
The dropdown list inside a label does not open when clicked. 

## Expected behavior
Like in previous versions, you can click on the dropdown list inside a label element to open it.

## Minimal reproduction of the problem with instructions

See: https://stackblitz.com/edit/angular-yhy3ap?file=src%2Fapp%2Fapp.component.ts

1. wrap the `<kendo-dropdownlist>` in a `<label></label>`
2. click on the input field
3. -> the list doesn't open

Remark: it does open when specifically clicking the arrow.
It looks like the click event is triggered twice causing the list to open and immediately close afterwards.

## Environment

Package versions:
Reproducible on the demo site.
We are upgrading to 13.2.1, in our previous version 7.0.3 it was working as expected.

**Comment by PaskalevStoyan** [comment] 2023-08-21 10:55
Hello @hannecolaers,

I will close this issue as it is a duplicate of - https://github.com/telerik/kendo-angular/issues/4010.

**Closed by PaskalevStoyan** 2023-08-21 10:55 UTC
Labels: Duplicate
