### ISSUE TITLE
Navigable grid with virtual scrolling does not allow proper rows selection

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1818] opened 2018-09-27 12:34 UTC
## I'm submitting a...
* Bug report 

## Current behavior
When we have a navigable grid with virtual scrolling and we try to select a row with a mouse click, the row is not always selected. 

## Minimal reproduction of the problem with instructions
Check the following example and video:
[https://stackblitz.com/edit/angular-kxdzur?file=app/app.component.ts](https://stackblitz.com/edit/angular-kxdzur?file=app/app.component.ts)

[https://www.screencast.com/t/cJH6a6j5U](https://www.screencast.com/t/cJH6a6j5U)

**Comment by danielkaradachki** [comment] 2019-03-08 15:04
closing as duplicate of https://github.com/telerik/kendo-angular/issues/1987

**Closed by danielkaradachki** 2019-03-08 15:04 UTC
Labels: Bug, Duplicate, pkg:grid
