### ISSUE TITLE
Autocomplete - selecting from complex data

### ISSUE THREAD

**Issue by chriscurnow** [telerik/kendo-angular#281] opened 2017-02-08 05:35 UTC
When we select from a list of complex data, autocomplete only returns the value of the valueField in the event. It would be better if it returned the whole of the array element.

Eg.

Array element: {name: "chris", id:1}

If we set the valueField to "name", autocomplete returns "chris".
It would be better if it returned: {name: "chris", id:1}

**Comment by ggkrustev** [comment] 2017-02-08 08:03
@chriscurnow this is a duplicate of this issue: https://github.com/telerik/kendo-angular/issues/269 I would suggest you comment there.

Will close the issue for now.

**Closed by ggkrustev** 2017-02-08 08:03 UTC
