### ISSUE TITLE
Bug in inline editing using click in grid

### ISSUE THREAD

**Issue by badej2009** [telerik/kendo-angular#788] opened 2017-07-30 08:49 UTC
## I'm submitting a...
bug

* Bug report 

## Current behavior
When using a grid in edit mode that one click starts editing sometimes, the click does not start the edit.
In order to reproduce the bug try in the sample to click on different rows, after a few clicks, the editing does not activate any more by clicking.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/q6K52fxWvKqHTJMrz4ky?p=preview
Just click many times in different rows and cells and eventually the edit won't work any more.

## What is the motivation / use case for changing the behavior?
Bg

## Environment

Package versions:
Happens in the version that appears in the demo site.

Browser:

- Chrome (desktop) version 59.0.3071.115

System:
- TypeScript version: 1.0.1.0
- Node version: 3.10.10
- Platform: Windows

**Comment by tsvetomir** [comment] 2017-09-28 11:22
The problem is caused by the validation rule for UnitsInStock. In short, the editor is populated with invalid data and that prevents closing it.

If you click on a cell where UnitsInStock is greater than 100 the cell won't be able to exit edit mode due to a validation editor. At the same time you won't get visual confirmation as the cell is in pristine state. You must click on the input in the UnitsInStock column to see the invalid styling.

![image](https://user-images.githubusercontent.com/247917/30964032-5e69e6c0-a458-11e7-810d-03c06336a9be.png)

**Closed** 2017-10-10 06:32 UTC
Labels: pkg:grid, Question
