### ISSUE TITLE
Grid - Multi selection does not work properly after reorder column.  

### ISSUE THREAD

**Issue by jacekbartek** [telerik/kendo-angular#1276] opened 2018-01-31 12:14 UTC
## I'm submitting a...
* Bug report

## Current behavior
In multiple selecion mode after reorder grid column - selection multiple rows does not work properly.
Can not select more than one row. This look like change selection mode from 'multiple' to 'single'.

When [reorderable] property is set to false. Multiple selection mode works.

## Expected behavior
After reorder grid column - should be possible to select more than one row.

## Minimal reproduction of the problem with instructions

1. Select 2 rows uses check column and change order any column.
2. Try to select additional row by check column.

https://embed.plnkr.co/cj3CJ6pwtJXevwFOPqky/

## Environment

Package versions:
    "kendo-angular-buttons": "2.0.0",
    "kendo-angular-dateinputs": "1.4.3",
    "kendo-angular-dialog": "2.0.0",
    "kendo-angular-dropdowns": "1.6.0",
    "kendo-angular-excel-export": "1.0.5",
    "kendo-angular-grid": "1.7.1",
    "kendo-angular-inputs": "1.4.2",
    "kendo-angular-intl": "1.3.0",
    "kendo-angular-l10n": "1.0.5",
    "kendo-angular-layout": "1.2.0",
    "kendo-data-query": "1.1.2",
    "kendo-drawing": "1.4.1",
    "kendo-theme-default": "2.47.0",
    "kendo-ui": "2018.1.117",

Browser:

- Chrome (desktop) Version 63.0.3239.132 (64-bit)

System:
- TypeScript version: "2.6.1"
- Node version: node : v6.11.3 , npm: 3.10.10
- Platform:  Windows 10 64bit

**Comment by rusev** [comment] 2018-01-31 13:05
Thank you for the report.

It seems the issue is related to the checkbox column, as `ctrl+click` works correctly after column reorder.
We will investigate further and report with more details.

**Comment by tsvetomir** [comment] 2018-02-01 11:25
Should be fixed in the latest [develop build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by jacekbartek** [comment] 2018-02-01 14:23
Thank you, it works correctly. I am waiting for stable version. Regards

**Comment by tsvetomir** [comment] 2018-02-01 14:34
Published as 2.0.1

**Closed** 2018-02-05 12:27 UTC
Labels: Bug, Passed-QA, pkg:grid
