### ISSUE TITLE
Grid Incorrect Selection with Paging

### ISSUE THREAD

**Issue by TrevorBroderick1** [telerik/kendo-angular#868] opened 2017-08-31 17:21 UTC
## I'm submitting a...
* Bug report

## Current behavior
When you have a grid with multi-select and paging, the row selection does not work correctly across different pages. When you select a row (not the check-box) on page 1 then go to page 2 and select another row, it should deselect the selection on page 1 as we are not using the check-boxes. Instead, they both stay selected.

## Expected behavior
The selection on page 1 should have become deselected when the selection was made on page 2.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/avJYIhvUSDmc9EJKQyeL?p=preview

Select and item on page 1, go to page 2 and select another item, go back to page 1 and the first item will still be selected.

## What is the motivation or use case for changing the behavior?
The deselection should be consistent with how it works when on a single page.

## Environment
Browser:
- Chrome (desktop) version 60.0.3112.101

System:
- TypeScript version: 2.5.0
- Node version: 8.1.0
- Platform:  Windows

**Comment by Raisolution** [comment] 2017-08-31 18:42
Hi @TrevorBroderick1,

the described current behavior is intended, as this is the purpose of the `kendoGridSelectBy` directive - to store the selected items during `dataStateChange` operations.

You could implement the desired behavior by checking the state of the ctrlKey (metaKey) in the `selectionChange` event (it is provided as part of the `SelectionEvent` and clear the `selectedKeys` collection if needed. Here is an [example of this](http://plnkr.co/edit/rZcUD6jThqhX5ByAgW6i?p=preview).

**Comment by TrevorBroderick1** [comment] 2017-08-31 18:56
It seems weird that it would not clear the selected data when you're not trying to append to it (not pressing ctrl or the checkbox), and instead trying to overwrite what is selected.

I really appreciate your example, is there anyway to have that work for pressing the checkbox, in addition to ctrl? I don't see any way to tell the difference between an event from selecting a row (should overwrite) and selecting the checkbox (should append).

**Comment by Raisolution** [comment] 2017-08-31 21:03
Hi @TrevorBroderick1,

we recommend our [Support System](http://www.telerik.com/kendo-angular-ui/support/) for similar questions and scenarios. I am closing this issue now, as it is not a bug, but intended behavior.

**Closed by Raisolution** 2017-08-31 21:03 UTC
Labels: pkg:grid, Question
