### ISSUE TITLE
kendo-textbox-container not working with DialogService

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1708] opened 2018-08-02 09:09 UTC
## I'm submitting a...
* Bug report 

## Current behavior
Label is not moved if input has value.

## Expected behavior
Label is moved on top of input component.

## Minimal reproduction of the problem with instructions
[Plunkr](https://plnkr.co/edit/ubYHaPIRPLfHNeDK9GvF?p=preview).

![chrome_2018-08-02_11-08-31](https://user-images.githubusercontent.com/1589573/43574427-6d18534e-9644-11e8-8a49-4f5a20b541dd.png)

**Comment by gyoshev** [comment] 2018-08-03 05:48
This is a duplicate of [this issue](https://github.com/telerik/kendo-angular/issues/1127). The problem is that the `value` binding is used, which does not work with the `kendo-textbox-container`. See the linked issue for more information, and use a `ngModel` to [resolve the problem](https://plnkr.co/edit/jmff4hH6QmgTh1Ggl1Wf?p=preview).

**Closed by gyoshev** 2018-08-03 05:48 UTC
