### ISSUE TITLE
PopupComponent in IE11 over GridComponent problem 

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#452] opened 2017-04-05 07:22 UTC
PopupComponent can not be displayed properly in IE11 when it is over GridComponent

![grafik](https://cloud.githubusercontent.com/assets/22910183/24694150/1721e1ca-19e1-11e7-92fe-7e65d76af190.png)

IE11 Version
![grafik](https://cloud.githubusercontent.com/assets/22910183/24694168/2773748a-19e1-11e7-94e5-3c82d2229ff6.png)

Many thanks!

**Comment by ggkrustev** [comment] 2017-04-05 08:34
@anj01, would it be possible to post a Plunker, which replicates the issue ? This will help us to investigate further the case.

**Comment by anj01** [comment] 2017-04-06 09:40
Unfortunately, I can not reproduce this problem in plunkr so far.

**Comment by ggkrustev** [comment] 2017-04-06 10:24
@anj01, if you can share a Github repo that replicates the issue, then this will be sufficient for us to continue with the investigation.

**Comment by anj01** [comment] 2017-04-07 07:05
I'm afraid I can not share Github Repo at the moment sorry out it. But I've continued working and I've filled popup with more content, changed colors. Now it works in IE11 properly too. I can't explain this behavior,  but for now it's okay for me. I will report you again if necessary

Thanks for your help!

**Comment by ggkrustev** [comment] 2017-04-07 07:42
Glad to hear that the issue is resolved now. I will close the issue. Please post a reply if it come back and you can share a runnable demo or at least repro steps.

**Closed by ggkrustev** 2017-04-07 07:42 UTC
Labels: pkg:popup

**Comment by anj01** [comment] 2017-04-07 07:45
Ok.
