### ISSUE TITLE
How can I make Kendo widgets readonly

### ISSUE THREAD

**Issue by ranag14** [telerik/kendo-angular#961] opened 2017-10-03 05:30 UTC
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment] 2017-10-04 06:52
@ranag14, all Kendo **input** components (those which have `value`) can be disabled using the disabled Input property, e.g. http://www.telerik.com/kendo-angular-ui/components/dateinputs/api/CalendarComponent/#toc-disabled. If you would like to disable grid or layout components then you will need to use a separate *overlay* HTML element that will cover the components.

I will close the issue as it is not a bug or feature request. I would like to ask you to refrain posting general questions in this channel, but rather open a support ticket with our Telerik ticketing system or open a discussion in Stackoverflow.

**Closed by ggkrustev** 2017-10-04 06:52 UTC
Labels: Question
