### ISSUE TITLE
[Editor] Error when using *ngIf and reactive forms

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#3054] opened 2020-09-04 08:38 UTC
**Describe the bug**
When the Editor is part of a reactive form and toggled using `*ngIf`, setting value through the Reactive Forms API throws an error.

**To Reproduce**
https://stackblitz.com/edit/angular-fuqbew-r7pauw?file=app/app.component.ts
1. Click "Switch editor visibility" twice.
2. Click "Set formControl value".
3. The Editor value is not updated and an error is thrown.

**Expected behavior**
The value of the Editor should be updated and no errors should be thrown.

**Comment by SuhasParameshwara** [comment] 2021-01-26 06:14
Hi Team,
Any updates on this issue?
@PetarMetodiev Did you find any workaround to solve this issue?

**Comment by mbechev** [comment] 2021-01-27 08:43
Hi @SuhasParameshwara,

Up to now, we haven't added this issue to our development plans.

**Comment by dtopalov** [comment] 2021-02-17 21:08
Seems to be an issue related to iframes in Chrome - the error is not observed in FireFox. Setting `iframe` to `false` resolves the problem and can be used as a workaround until a fix is released.

Closing this as a duplicate of https://github.com/telerik/kendo-angular/issues/2908

**Closed by dtopalov** 2021-02-17 21:08 UTC
Labels: Bug, Team2, freq2: possible, pkg:editor, sev3: high

**Comment by dtopalov** [comment] 2021-02-18 16:16
Fixed in the latest dev version of the Editor package.
