### ISSUE TITLE
DatePicker auto-corrects invalid dates

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2008] opened 2019-01-03 08:30 UTC
## I'm submitting a...

* Bug report 

## Current behavior
If I try to enter 2/29/2020 via the keyboard in a DatePicker, the day is automatically changed to 28 when I have typed 2/29/2. Indeed, this behavior can be enhanced, so that when we enter an invalid date like 2/29/2, the value should not be auto-corrected but set to null (this is the default behavior of a default HTML input element)

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-bno7qd?file=app/app.component.ts](https://stackblitz.com/edit/angular-bno7qd?file=app/app.component.ts)

Try entering the date 2/29/2020 in both inputs and compare their functionalities.

**Comment by mbechev** [comment] 2019-07-03 11:58
Also mentioned in private support thread № 1416850 

## Behavior
If the entered date is 28th of February (**28**/02/2019) but a new date should be entered (e.g. **31**/12/2019), after typing the first "3" the focus is immediately moved to the month because there is no date in February which has two digits where the first one starts with "3". 

## Minimal reproduction of the problem with instructions
[https://stackblitz.com/edit/angular-fvy3pp](https://stackblitz.com/edit/angular-fvy3pp)

Try entering the date 31/12/2019 when the entered date is in February.

**Comment by dtopalov** [comment] 2019-07-17 11:24
Linked to a public Feedback portal feature request:

https://feedback.telerik.com/kendo-angular-ui/1417908-datevalidation

**Comment by eatinasandwich** [comment] 2019-11-06 15:57
Is there any way to turn the auto correction completely off? I'm developing a product where the last day of the month will be a big deal and I would rather the user be able to type any invalid value and possibly get a validation error than to have it auto-correct and risk them not noticing that the incorrect value was entered.

We otherwise love the functionality of it, but anticipate this piece causing problems down the line.

**Comment by dimitar-pechev** [comment] 2019-11-06 17:03
No, currently the **DateInputs** work only with a masked input. Turning that functionality off would be no simple task, and is unfortunately not supported currently. We are considering adding the option to use a plain input inside the **DateInput**, however, this is not something in our immediate plans.

**Comment by zampage** [comment] 2020-01-22 09:03
I would also appreciate an option to turn this behavior off as long as there is no permanent fix for this matter. Alternatively debounce it or validate theuser input after the field loses focus. The native date input does a decent job in that regard.

**Comment by cwuethrich** [comment] 2020-01-22 12:00
@dtopalov why isn't this a bug if you can't change the date from 28th of February to the 31th of March?

**Comment by dimitar-pechev** [comment] 2020-01-27 13:19
@cwuethrich, this isn't a bug as the **DateInput** currently doesn't support validating the passed value on **blur**. It updates the value on **input**. And as trying to set 31 for date value is invalid for the month of February, the input is prevented, which is exactly the expected behavior.

As mentioned before, the options are to either validate the mask value on blur, or provide a plain input for the value which is parsed on certain events. And both of these fall under the category of enhancements.

Still, I do understand that this behavior can lead to mistakes in end-user input at times, so we'll review if we could give higher priority to this issue.

**Comment by liilii-ii** [comment] 2021-07-26 11:10
Is there any progress made on this ticket? It would be nice to have the option to disable the auto correction

**Comment by federicat74** [comment] 2021-09-17 14:43
Any news on resolution?

**Comment by stedice** [comment] 2021-09-17 15:07
> @cwuethrich, 
> Still, I do understand that this behavior can lead to mistakes in end-user input at times, so we'll review if we could give higher priority to this issue.

Apparently it is, expecially if you use the european date format, where you type the day first. Our users often need to change dates from 'last day of month x' to last day of month y'. In this scenario, this behavior very often leads to end-user input mistakes.

It would be nice to improve this functionality, for example combining it with the incompletedatevalidation attribute. If the day 31 is typed then reset month field if not valid. I'd rather have a validation error than a wrong date input.

**Comment by Trend20** [comment] 2021-10-21 11:43
> Any news on resolution?

How did you solve this?

**Comment by dtopalov** [comment] 2022-02-03 10:48
To be tracked in the following Feedback portal tread:

https://feedback.telerik.com/kendo-angular-ui/1417908-datevalidation

**Closed by dtopalov** 2022-02-03 10:48 UTC
Labels: Enhancement, pkg:date-inputs, Team1

**Comment by subith-dns** [comment] 2022-04-22 05:58
Not respecting the user input is a bad design principle. What design principles you follow kendo?!

**Comment by spearmootz** [comment] 2023-05-09 17:38
this is still an issue., 4 years later

**Comment by ioio1987** [comment] 2023-10-13 16:13
I have the same problem, but I see it is hibernation time in Kendo's support<3 <3  :-*

**Comment by jovana7convect** [comment] 2024-05-24 09:23
Any news guys? Why is this ticket in closed state...?

**Comment by svetq** [comment] 2024-05-28 10:12
The enhancement is planned to be developed this quarter. Please follow the dedicated feature request item for further updates: https://feedback.telerik.com/kendo-angular-ui/1417908-datevalidation

**Comment by karatecarter** [comment] 2024-08-09 13:43
Unfortunately this does not appear to be fixed with https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/typing/#toc-autocorrectparts
It looks like now if I try to type 2/29/2024 I am unable to type the full year.

**Comment by dcarter-mhk** [comment] 2024-08-09 13:45
Unfortunately this does not appear to be fixed with https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/typing/#toc-autocorrectparts
It looks like now if I try to type 2/29/2024 I am unable to type the full year.
