### ISSUE TITLE
Multiple selection does not work with Command + click

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#816] opened 2017-08-11 06:59 UTC
## I'm submitting a...
* Bug report

## Current behavior
Holding Command and clicking on an item does not select the clicked row.

## Expected behavior
The clicked row should be added to the selection, similar to Ctrl + Click on Windows / Linux.

## Minimal reproduction of the problem with instructions
1. Open the [Selection](http://www.telerik.com/kendo-angular-ui/components/grid/selection/) help page on an OSX device
1. Command + click on a row
1. The row is not selected

## What is the motivation or use case for changing the behavior?
The multiple selection should follow the OSX conventions for multiple selection

## Environment

Package versions: latest

Browser: any

System:
- Platform:  Mac

**Comment by tsvetomir** [comment] 2017-08-11 12:12
Detection can be based on [metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey)

**Comment by Raisolution** [comment] 2017-09-01 07:06
The issue is fixed in version `1.3.2`

**Closed by Raisolution** 2017-09-01 07:06 UTC
Labels: Bug, pkg:grid
