### ISSUE TITLE
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by RobCannon** [telerik/kendo-angular#829] opened 2017-08-16 00:49 UTC
## Current behavior
We were experiencing this error with our POC for using Kendo UI for our ASP.NET Core application.  So, I tried your sample, aspnet_core_sample_application and I get the same error.
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: navigator is not defined

## Expected behavior
The sample application should work

## Minimal reproduction of the problem with instructions
Clone the repository at https://github.com/telerik/kendo-angular-universal-demo
Follow the instructions for the ASP.NET Core demo at https://github.com/telerik/kendo-angular-universal-demo#to-run-the-aspnet-core-based-application
Observe the error when launching browser with http://localhost:5000/

Note, I tried the Node sample, and I wasn't able to build that.  It looks like it is still dependent on a beta version of angular universal.

## What is the motivation or use case for changing the behavior?
We are expecting Kendo UI to work with Angular Universal, since that is an advertised feature

## Environment

Package versions:
+-- @angular/animations@4.3.4
+-- @angular/common@4.3.4
+-- @angular/compiler@4.3.4
+-- @angular/core@4.3.4
+-- @angular/forms@4.3.4
+-- @angular/http@4.3.4
+-- @angular/platform-browser@4.3.4
+-- @angular/platform-browser-dynamic@4.3.4
+-- @angular/platform-server@4.3.4
+-- @angular/router@4.3.4
+-- @progress/kendo-angular-dateinputs@1.0.6
+-- @progress/kendo-angular-dropdowns@1.1.3
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.3.2
+-- @progress/kendo-angular-inputs@1.1.0
+-- @progress/kendo-angular-intl@1.2.2
+-- @progress/kendo-angular-l10n@1.0.3
+-- @progress/kendo-data-query@1.0.6
+-- @progress/kendo-drawing@1.2.0
+-- @progress/kendo-theme-default@2.40.0
+-- @types/node@7.0.18
+-- angular2-template-loader@0.6.2
+-- aspnet-prerendering@2.0.6
+-- aspnet-webpack@1.0.29
+-- awesome-typescript-loader@3.1.3
+-- bootstrap@3.3.7
+-- css@2.2.1
+-- css-loader@0.28.1
+-- es6-shim@0.35.3
+-- event-source-polyfill@0.0.9
+-- expose-loader@0.7.3
+-- extract-text-webpack-plugin@2.1.0
+-- file-loader@0.11.1
+-- html-loader@0.4.5
+-- isomorphic-fetch@2.2.1
+-- jquery@3.2.1
+-- json-loader@0.5.4
+-- preboot@4.5.2
+-- raw-loader@0.5.1
+-- reflect-metadata@0.1.10
+-- rxjs@5.4.0
+-- style-loader@0.17.0
+-- to-string-loader@1.1.5
+-- typescript@2.3.2
+-- url-loader@0.5.8
+-- webpack@2.5.1
+-- webpack-hot-middleware@2.18.0
+-- webpack-merge@4.1.0
`-- zone.js@0.8.10

Browser:
- Chrome (desktop) version 60.0.3112.90

System:
- TypeScript version: 2.4.2
- Node version: 8.2.1
- npm version: 5.3.0
- Platform:  Windows

**Comment by gyoshev** [comment] 2017-08-18 06:19
Thank you for reporting this. We have confirmed that this is a bug in the DateInputs package, and we are working towards a resolution. To continue your evaluation without delay, you can downgrade the DateInputs package to `1.0.5` with `npm install @progress/kendo-angular-dateinputs@1.0.5`. Alternatively you can change the `package.json` file to hard-code the version and run `npm install`.

**Comment by kkalitowski** [comment] 2017-08-22 15:52
Thank you for recognizing the error. I am having the same error with "aspnet-prerendering" that came to me via the latest [Microsoft Angular ASP.NET Core template].(https://github.com/aspnet/JavaScriptServices/tree/dev/templates/AngularSpa)

I assume the same Telerik fix should resolve my issue since the bug is that the server-side JS is trying to use the client-side `navigator` JavaScript object.

**Comment by JStarkl** [comment] 2017-09-14 08:58
I had the same problem, package 1.2.0 works fine now

**Comment by gyoshev** [comment] 2017-09-14 09:08
Indeed, this bug has been fixed in version `1.1.0` and later.

**Closed by gyoshev** 2017-09-14 09:08 UTC
Labels: Bug, pkg:date-inputs
