### ISSUE TITLE
kendo-angular grid :Angular change detection is triggered makes rowClassFn keep running while using setInterval

### ISSUE THREAD

**Issue by liuydyyy** [telerik/kendo-angular#2004] opened 2019-01-02 07:53 UTC
## I'm submitting a problem with grid rowclass.
Angular change detection is triggered, and functions, bound to Grid properties (i.e. rowClass) are executed unexpectedly in the following scenarios that do not really require such behavior:
setTimeout 
setInterval

https://stackblitz.com/edit/angular-jnkc7j-fdjbgo?file=app/app.component.ts

**Comment by tsvetomir** [comment] 2019-01-02 08:17
This is expected behavior due to the use of Zone.js to trigger change detection in Angular. See [Zones in Angular](https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html). 

Closing this issue as it is not caused by a bug.
Please, open a support ticket if additional assistance is required.

**Closed by tsvetomir** 2019-01-02 08:17 UTC

**Comment by liuydyyy** [comment] 2019-01-02 08:39
> losing this issue as it is not caused by a bug.
but if i have to use kendo rowclass and setInterval(inthe interval ,i may change dataSource),is there any way suggest to solve the problem?

**Comment by Raisolution** [comment] 2019-01-02 08:46
Hello @liuydyyy,

please open a [support ticket](https://www.telerik.com/account/support-tickets) if further assistance is required regarding this issue.

**Comment by liuydyyy** [comment] 2019-01-02 08:47
> 
> 
> Hello @liuydyyy,
> 
> please open a [support ticket](https://www.telerik.com/account/support-tickets) if further assistance is required regarding this issue.

ok 3ks~
