### ISSUE TITLE
Using [(ngModel)] two way binding with filter in dropdown list

### ISSUE THREAD

**Issue by zhshqzyc** [telerik/kendo-angular#2673] opened 2020-01-13 15:42 UTC
I want to use [(ngModel)] two way binding in dropdown list. The issue is I have two dropdown list, both of them have filters. The selected items are excluded each other. Which means if I do a filtering in dropdown A, the dropdown B is set the default value. Or id I do a filtering in dropdown B, the dropdown A is set the default value. So it is two way binding.

The issue is that it doesn't work well always. Sometimes the binding lost. Please see [the detail](https://stackoverflow.com/questions/59524678/the-data-source-suddenly-lost-when-applying-filter?noredirect=1#comment105224486_59524678)

Is it a bug?

**Comment by dimitar-pechev** [comment] 2020-01-14 13:58
Hello, @zhshqzyc, the explanations here and in the StackOverflow post are a bit obscure. Could you provide a runnable StackBlitz example where the issue is reproducible?

**Comment by zhshqzyc** [comment] 2020-01-14 22:17
Hello. I am trying to create an example but failed.
[stackblize](https://stackblitz.com/edit/angular-ha4zkm). Not sure where is wrong for the reference. But it seems not the ngModel issue. It might be TAB issue. When I select an item from dropdown then I want to switch the TAB. Afterwards, if I use the filter in another dropdown, the filter is not working then. So could you please correct my link error first?

**Comment by dimitar-pechev** [comment] 2020-01-15 08:36
The example doesn't start because of a missing reference to the `LayoutModule`. https://stackblitz.com/edit/angular-ha4zkm-vrlkhj
Seems to work as expected - the filter works just fine no matter how I jump from one drop-down to the other.

Seems like you need help implementing a custom scenario. I'd encourage you to [open a support ticket](https://www.telerik.com/account/support-tickets) where you can share your exact requirements and get further help.

Closing as the repository is for bug reports only.

**Closed by dimitar-pechev** 2020-01-15 08:36 UTC
Labels: Team1, pkg:dropdowns
