### ISSUE TITLE
MultiSelect's allowCustom functionality requires the popup to be opened

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1280] opened 2018-02-01 09:24 UTC
If opening of the popup is prevented, the user can no longer enter custom values:

[https://plnkr.co/edit/A0DRhvcDEDg1iK33Q5Rz?p=preview](https://plnkr.co/edit/A0DRhvcDEDg1iK33Q5Rz?p=preview)

**Comment by valchev** [comment] 2018-06-29 16:06
Adding custom value on 'Enter' when the popup is closed may cause conflicts when the component is used in a form with submit button.

By design the 'Enter' keypress is prevented when the user selects something from the options list (e.g. when the popup is open). The 'Enter' keypress will bubble when the popup is closed which allows the user to submit the form. This behaviour can be observed with native select element.

It is unclear what is expected to happen when the user adds custom value and the popup is closed. Should the 'Enter' bubble or not and how the user will be able to submit the form?

In order to resolve the case, the developer may hide the popup by either setting its `width` and `height` to zero or via CSS.

I am closing this with a `won't fix` label due to the questions explainer above.

**Closed by valchev** 2018-06-29 16:06 UTC
Labels: Bug, pkg:dropdowns
