### ISSUE TITLE
unexpected behavior with kendo-textbox showSuccessIcon defaults 

### ISSUE THREAD

**Issue by dlempia** [telerik/kendo-angular#3092] opened 2020-10-16 20:46 UTC
**Describe the bug**
When using kendo-textbox, if you do not define [showSuccessIcon]=false, the component will include one upon successful entry to the field. 

**To Reproduce**
https://stackblitz.com/edit/angular-kqk8op?file=app/app.component.ts

**Expected behavior**
when defining a kendo-textbox without binding to showSuccessIcon, the default behavior should be that no suffix is shown.

**Screenshots**
see stackblitz

**Browser**
Win-10
Chrome v86

**Comment by Raisolution** [comment] 2020-10-17 07:58
Hi @dlempia 

Thank you for reporting the issue. We are aware of it and the default values of `showSuccessIcon` and `showErrorIcon` properties were intended to be `false` by default.

https://www.telerik.com/kendo-angular-ui-develop/components/inputs/api/TextBoxComponent/#showerroricon

The issue is fixed in the latest development version `6.7.3-dev.202010121143`. Here is the updated [stackblitz example](https://stackblitz.com/edit/angular-kqk8op-n9uhhf?file=app%2Fapp.component.ts) with the dev version.

**Comment by Raisolution** [comment] 2020-11-24 22:43
Fix available in `v6.7.3` and above.

**Closed by Raisolution** 2020-11-24 22:43 UTC
Labels: Bug, Team2, pkg:inputs
