### ISSUE TITLE
[DateInput] blur method doesn't work

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3407] opened 2021-08-13 10:33 UTC
**Describe the bug**
The blur method doesn't work in the DateInput component.

**To Reproduce**
1. Focus and select day or month
2. press the tab key to blur the component
https://stackblitz.com/edit/angular-ynjtie?file=app/app.component.ts

**Expected behavior**
Blur method to work properly and blur the component.

**Comment by JoomFX** [comment] 2023-09-21 07:51
The issue is fixed in v13.5.0

https://stackblitz.com/edit/angular-wdzmrr?file=src%2Fapp%2Fapp.component.ts

**Closed by JoomFX** 2023-09-21 07:51 UTC
Labels: Bug, pkg:date-inputs, Team1
