### ISSUE TITLE
Grid selection checkbox can't be unchecked after dataStateChange in combination with [rowSelected] and function in [kendoGridSelectBy]

### ISSUE THREAD

**Issue by MarianaPyrih** [telerik/kendo-angular#2051] opened 2019-01-29 21:44 UTC
I'm submitting a possible bug

Bug report

## Current behavior
I am using in grid multiselect with function as kendoGridSelectBy to retrieve selected row, also I need deselect rows programmatically outside grid and persist selections on data change, so use rowSelected component input. Also, manually toggle selection via checkbox should work too. 
Something like,
  <kendo-grid  [data]="gridData"
              [selectable]="selectableSettings"
              [kendoGridSelectBy]="selectedCallback"
              [selectedKeys]="selections"
              [rowSelected]="isRowSelected"
              (pageChange)="pageChange($event)"></kendo-grid>
.....
Component Class:
  public selectedCallback = (args: RowArgs) => args.dataItem;
  public isRowSelected = (e: RowArgs) => {
    return  this.selections.some(item=> e.dataItem.id === item.id);
  }
Everything works fine till any data change (filter, sort, paging). After data change I can deselect already selected rows only programmatically. Checkbox does not react on click.
 Strange thing is, that  checkboxes in other rows, which were not selected before data change, work as expected.
Also, I want to notice, that when I am using just string in kendoGridSelectBy, issue, seems, is not reproducable

## Expected behavior
Grid selection checkboxes can be unchecked manually after data change with rowSelected and selected callback

Package versions:
 @angular/core@7.1.4
@progress/kendo-angular-buttons@4.3.2
@progress/kendo-angular-dateinputs@3.5.2
@progress/kendo-angular-dropdowns@3.4.1
@progress/kendo-angular-grid@3.10.2
@progress/kendo-angular-inputs@3.5.0
@progress/kendo-angular-intl@1.6.1
@progress/kendo-data-query@1.5.0
@progress/kendo-drawing@1.5.7

Browser:
- Chrome (desktop) version XX

System:
- TypeScript version: 3.1.3
- Platform:  Windows

**Comment by Raisolution** [comment] 2019-01-30 13:59
Hi @MarianaPyrih,

we were unable to reproduce the mentioned issue on our end. Please provide a runnable example that demonstrates the problem, so we could inspect it.

**Comment by Raisolution** [comment] 2019-02-04 07:46
I am closing this, as it was not reproduced.

**Closed by Raisolution** 2019-02-04 07:46 UTC
Labels: pkg:grid

**Comment by tomadj** [comment] 2020-05-27 20:03
Hello, 

Can you reopen this issue, I have the same problem and I can to reproduce ! 
Here a runnable example that demonstrates the problem : https://angular-go66ie.stackblitz.io

Steps to reproduce : 

1 - Check the checkbox for select the first row (by exemple) (row : "Id : 1 Name:Beverages)
--> the first row is selected
2 - Uncheck the first row 
--> the first row is deselected : OK 
3 - Check the first row again
--> the first row is selected
4 - Go to the next page 
--> the data for the page N°2 are loaded **(from remote server)**
5 - Return to the page N° 1
--> the first row is always selected and it's cool (thanks to isRowSelected function)
6 - Try to deselect this first row 
**--> unable to deselect KO**

It seems that when you **change the page**, you can no longer deselect lines because the line is reselect because of the isRowSelected() because the MySelection[] is not up to date. The deselected row is alaways in MySelection[]  so the row is seleted again

Thank's
