### ISSUE TITLE
Grid - Possible to use selectedKeys with custom setter?

### ISSUE THREAD

**Issue by Tiberriver256** [telerik/kendo-angular#1909] opened 2018-11-12 18:30 UTC
Tried to do it here in this [sample stackblitz](https://stackblitz.com/edit/angular-klscmc) but maybe I'm doing something wrong?

**Comment by Raisolution** [comment] 2018-11-12 19:58
Hi @Tiberriver256,

With the current implementation, the setter function will never get called by the Grid. When selecting/deselecting items, the Grid operates over the existing selectedKeys collection instance without overriding it with a new one (i.e. the getter is invoked and the Grid adds/removes items to/from this array). You could assure this by logging `mySelection` after selecting/deselecting an item in the Grid - it correctly holds the selected items.

As for the interpolation expression in the paragraph element, it is not updated because the array instance is still the same i.e. Angular will not consider it as a `change`. The expression will be updated if the instance changes - here is [an example of this in action, outside of the Grid context](https://stackblitz.com/edit/angular-klscmc-7abt1s?file=app/app.component.ts).

Since this is not a bug, I will close the thread. However, if this behavior is causing an issue with the current implementation, I would suggest to open a ticket in our support system, so we could assist in resolving it.

**Closed by Raisolution** 2018-11-12 19:58 UTC
Labels: pkg:grid
