### ISSUE TITLE
Grid : Resize and Reorder not working on Chromium on Mac although it works on Windows on the same Chromium Version

### ISSUE THREAD

**Issue by NTDY** [telerik/kendo-angular#2107] opened 2019-03-05 08:41 UTC
**Describe the bug**
When running code which contains a resizable and reorderable Grid in an Angular 5 project using Chromium  57.0.2987.74, Grid is resizable  and reorderable on Windows but not on Mac.

For reference, kendo-angular-grid version:

`"@progress/kendo-angular-grid": "^3.3.0"`

**Browser**
 - OS: MacOS 10.14 (Not Working) , Windows 10 (Working)
 - Browser: Chromium 
 - Version: 57.0.2987.74

**Additional context**
The resize cursor appears when mousing over the resizer, suggesting that [resizable] has been set correctly as expected, but nothing happens when the resizer object is clicked and dragged.

I don't believe the specific version of chromium matters, since changing the version and trying it out on both OSes yields the same results.

**Comment by tsvetomir** [comment] 2019-03-05 10:25
Can you confirm if the issue is present in Chromium 72?

**Comment by NTDY** [comment] 2019-03-06 03:14
The project constraints limit the ability to test this on newer chromium versions. Specifically, the project is built on top of Adobe's CEP, and doesn't run natively on the browser :

[https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md](url)

CEP 9.0 uses Chromium version 61.0.3163.91 , so that's the latest version that I can test it on. On that CEP version the project has the same problem, though.

**Comment by tsvetomir** [comment] 2019-03-06 12:39
Thanks for the additional information.

I tried the resizing and reordering demos in a vanilla Chromium 61 build and they seem to work there. The issue might be specific to Adobe CEP 9 or CEF 3. I doubt that the Chromium version is to blame as we don't do anything too exotic.

We don't have any experience with CEF, but we'd be glad to take a look at a minimal reproduction demo. It's Chromium after all and we should be able to get some insights from the debugger.

I also recommend trying out the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) as it contains a fix related to how we handle touch events for the resize and reorder features.

**Comment by tsvetomir** [comment] 2019-04-11 09:47
Closing until more information becomes available.

**Closed by tsvetomir** 2019-04-11 09:47 UTC
Labels: Question, pkg:grid
