### ISSUE TITLE
[BreadCrumb] Multiple consecutive resizes trigger an error

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#3666] opened 2022-05-02 07:38 UTC
**Describe the bug**
Maximum call stack error is thrown on consecutive browser resizes.

**To Reproduce**

Resize the browser window multiple times in a short period of time.
Detailed steps and a video are available in thread 1563202

**Comment by destus90** [comment] 2023-11-15 03:53
@dtopalov 

Is this a fix?

![image](https://github.com/telerik/kendo-angular/assets/17944366/d2bed679-4c07-4626-a8d2-0740fbb4606f)

Sorry, but it doesn't seem that this should rectify the error. The issue was with multiple recursive calling `handleResize` method.

![image](https://github.com/telerik/kendo-angular/assets/17944366/773eaef7-a805-4f57-9800-c367e0886919)

We still have a problem with that and the demo is still broken even if you have the latest kendo packages.

**Comment by slavenai** [comment] 2023-11-27 09:40
Hi @destus90 ,

A fix is now part of the latest dev version `v14.2.0-develop.5`. Could you please verify that everything works as expected with the latest changes, as the error was thrown in certain edge cases with specific configurations and was a bit tricky to reproduce. Thank you in advance.

**Comment by destus90** [comment] 2023-11-27 10:56
Hi @slavenai 

It still gives us the error...

![image](https://github.com/telerik/kendo-angular/assets/17944366/a3bd49c2-5448-4d92-aded-6155ea5db8fd)

const packageMetadata = {
    name: '@progress/kendo-angular-navigation',
    productName: 'Kendo UI for Angular',
    productCodes: ['KENDOUIANGULAR', 'KENDOUICOMPLETE'],
    publishDate: 1700836534,
    version: '14.2.0-develop.5',
    licensingDocsUrl: 'https://www.telerik.com/kendo-angular-ui/my-license/'
};

**Comment by slavenai** [comment] 2023-11-27 11:15
Hi @destus90 ,

Could you please verify that the latest compatible Kendo UI Theme version `v7.0.2` is used? If the theme version is indeed updated and the issue is still reproducible, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets) providing more details and ideally, an archived project that reproduces the undesired behavior. Thank you.

**Comment by destus90** [comment] 2023-11-27 11:42
@slavenai 

It will be difficult to do a runnable example. Why can't you just drop calling handleResize method inside that method? 😬

**Comment by slavenai** [comment] 2023-12-11 09:06
Hi @destus90 ,

The `handleResize` invocation is needed for toggling the visibility of items based on the component width.

A fix is now available in `v14.2.0`.

As previously mentioned, we are unable to reproduce the described discrepancy with `v14.2.0` and Kendo UI Theme Default `v7.0.2`, thus we cannot further investigate. With that said, I will proceed with closing this issue. If you're still experiencing the error, please send us a runnable StackBlitz demo or an archived sample project so we can look into the exact configuration. Thank you.

**Closed by slavenai** 2023-12-11 09:06 UTC
Labels: Bug, Team2, pkg:navigation
