### ISSUE TITLE
[DateRange] Lower value setted two times in a row is populating both fields

### ISSUE THREAD

**Issue by mielewczykyello** [telerik/kendo-angular#1844] opened 2018-10-12 06:55 UTC
## I'm submitting a...

* Bug report

## Current behavior
1. Open DateRange Calendar 
2. set date range 
3. set 'from' date lower than current
4. set 'from' date lower than current
5. now this action populated both fields

![multiview calendar kendo range](https://user-images.githubusercontent.com/44081837/46852747-43569300-cdfc-11e8-9d8b-b59edef2a83d.gif)

## Expected behavior
Setting 'from' date two times in a row lower than current shouldn't populate both fields.

**Comment by dimitar-pechev** [comment] 2019-11-27 11:30
This behavior is expected and is by design ([internal ref](https://github.com/telerik/kendo-ux-private/issues/3)). After selecting a **start** value, the next selection will be assigned to the **end** value, the next one to **start** value and so on. Thus, when selecting an **end** date value prior to the currently selected **start** value, the latter is auto-corrected to the **end** value as the range would otherwise be invalid. Notice that the inputs are focused to indicate which value you are selecting.

Currently the **DateRange** does not support other selection behaviors (e.g. clearing the range when both **start** and **end** are defined and selecting either part of the range anew). We would consider adding different selection behavior support as an option in the future if there's user demand for it. I'd encourage you to create a feature request on our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) where you can describe your exact expectations.

**Closed by dimitar-pechev** 2019-11-27 11:30 UTC
Labels: Team1, pkg:date-inputs
