### ISSUE TITLE
[Grid] Column Menu title displays incorrect text on hover when Ivy is enabled

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3435] opened 2021-09-15 08:52 UTC
**Describe the bug**
Column Menu title displays incorrect text on hover when Ivy is enabled (latest packages)
![ApplicationFrameHost_HeJ6OPaQMs](https://user-images.githubusercontent.com/49076727/133401835-7cf8a2dc-3fce-424f-8ac5-1f5e41bc5bfb.png)
If Ivy is disabled the issue isn't present.

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/grid/columns/menu/
Run the basic usage demo locally with Ivy enabled.

**Expected behavior**
To display the correct title on hover and in the HTML markup.

**Workaround**
Using the CustomMessagesComponent https://www.telerik.com/kendo-angular-ui/components/grid/api/CustomMessagesComponent/
`<kendo-grid-messages columnMenu="{columnName} Column Menu">
</kendo-grid-messages>`

**Comment by dtopalov** [comment] 2021-09-16 06:34
The issue in question is observed when enabling Ivy in certain Angular versions. We tested the Grid component with Angular versions 9-12 and here is what we've encountered:

- In version 9.x the `aria-label` is assigned as expected.
- From version 10 to 11.1.0 the described issue is reproduced.
- In version 11.1.1 the issue seems to be fixed.

Here are some useful links regarding the issue:

https://github.com/angular/angular/blob/master/CHANGELOG.md#bug-fixes-17

https://github.com/angular/angular/pull/40593

As the discussed issue is not directly related to the Kendo UI for Angular product, I am closing this.

**Closed by dtopalov** 2021-09-16 06:34 UTC
Labels: Question, pkg:grid, Team2
