### ISSUE TITLE
Null Errors thrown by Kendo Component when not rendered immediately after init

### ISSUE THREAD

**Issue by Jejuni** [telerik/kendo-angular#3055] opened 2020-09-04 08:53 UTC
**Describe the bug**
When `<kendo-floatinglabel>` (and possibly many other components) are placed inside a template by a parent component and not rendered **immediately** null reference errors are thrown (i.e. `cannot read property 'setAttribute' of null`)

**To Reproduce**
https://stackblitz.com/edit/angular-ctducf

**Expected behavior**
Whether or not kendo components are rendered immediately or not, no errors should be thrown

**Browser**
 - OS: Windows10
 - Browser Chrome, Firefox, etc

**Additional context**
The problem stems from the internal usage of Angular's Renderer2.
You're assigning ids to the kendo controls, then in `ngAfterViewInit` you're asking the document for `document.getElementById(componentId)`. 
However, because the component is actually inside an ng-template that is not yet rendered to the screen, the return value of that call is null. There is no null check, so later down the chain the null reference errors happen.

The problem is that with Angular's view rendering, if I place something inside a component (as in my example) that component's viewchildren are all initialized with that component **unless** that component places them inside a template. However, in this example the `<ng-template>`'ing happens inside another component via `<ng-content>`. This leads to the scenario where components are already initialized, but not rendered to the screen. 
This is a fairly useful use-case, however (see Angular Material's implementation of CdkStep).

**Comment by dimitar-pechev** [comment] 2020-09-09 14:59
Seems caused by the same reason as this one https://github.com/telerik/kendo-angular/issues/2959.
The fix for this is already available in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-label` package (**v2.3.3-dev.202006260747**).

@Jejuni, an official version will probably be released in the upcoming days, but you can give the dev version a go even now. [Here's an example](https://stackblitz.com/edit/angular-ctducf-xzm8jy).

**Comment by dimitar-pechev** [comment] 2020-09-10 06:58
Released in **v2.3.3**.

**Closed by dimitar-pechev** 2020-09-10 06:58 UTC
Labels: Bug, Team2, freq1: rare, pkg:label, sev3: high
