### ISSUE TITLE
Table attributes not persisted when updating them through the View Source tool

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3751] opened 2022-08-30 08:17 UTC
**Describe the bug**
Setting new table attributes through the **View Source** tool, disappears when inserting another table in the cell's content. For example, when setting an id attribute to the `<table>` element and inserting a new table in a cell, the attributes of the parent table are cleared.

**To Reproduce**

1. Insert a table and set any attribute to the <table> element through the View Source tool.
2. Insert a table in the parent cell.
3. Open the View Source dialog. The set attribute is disappeared.

https://stackblitz.com/edit/angular-4s9cqk

Another strange behavior is that if we set an attribute to the nested table, it will update the parent table as well with the same attribute. Check the screencast video for more details.

[editor-table.mov.zip](https://github.com/telerik/kendo-angular/files/9451036/editor-table.mov.zip)

_* This seems to be working correctly in the KendoReact Editor_

**Comment by bdurairaji2** [comment] 2022-09-21 14:30
This is regression issue, Can we have fix for this issue ASAP.

**Comment by nstoychev** [comment] 2022-09-29 17:19
@bdurairaji2 - Thank you for the detailed steps.

I have investigated the issue and it is caused by the table resizing functionality.

We will resolve it very soon.

**Comment by dtopalov** [comment] 2022-10-05 09:42
Fix is available in v. 4.1.11 of the **@progress/kendo-angular-editor package**.

**Closed by dtopalov** 2022-10-05 09:42 UTC
Labels: Bug, pkg:editor, Team2
