### ISSUE TITLE
Why doesn't the minimizing icon appear when the windows is set to maximizing?

### ISSUE THREAD

**Issue by GavinEnjoy2017** [telerik/kendo-angular#1799] opened 2018-09-19 08:26 UTC
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment] 2018-09-19 08:37
Hi @GavinEnjoy2017,

The described behavior is by design. While maximized, the Window cannot be moved, resized and minimized, but only restored to it's default state or closed.

I will close this, as it is not a bug report. If further assistance with specific implementation is required, I would suggest to open a [support ticket](https://www.telerik.com/account/support-tickets).

**Closed by Raisolution** 2018-09-19 08:37 UTC
Labels: pkg:dialog
