### ISSUE TITLE
Whitespace issue with Kendo-editor in Firefox (Angular 8)

### ISSUE THREAD

**Issue by Aayush9507** [telerik/kendo-angular#2900] opened 2020-05-14 22:17 UTC
**Describe the Issue**
The white spaces are trimmed automatically while typing in kendo-editor in Firefox. It works fine in Chrome/IE.
We are using this version of the theme, "@progress/kendo-theme-default": "4.12.1" and latest version of kendo-editor for angular 8.
I guess this issue was supposed to be fixedin version "4.7.0" according to this ticket, 

**Related to**
[https://github.com/telerik/kendo-angular/issues/2227](url)

**Current Behavior**

> "This is example" 
becomes 
> "Thisisexample"

**Comment by PetarMetodiev** [comment] 2020-05-15 09:59
Hi Aayush,

Thanks for the details. As this seems like a nasty regression, I tried reproducing it. I created an Angular 8 project and installed the editor using `ng add @progress/kendo-angular-editor`. I tried the provided example but could not reproduce the problem. Tested it on Firefox(both on Windows and macOS), Chrome(both on Windows and macOS), Safari and IE. I am attaching the sample app for reference - [editor-test.zip](https://github.com/telerik/kendo-angular/files/4633623/editor-test.zip).

One thing I can think of is to try reinstalling `node_modules` and see if the problem persists. Also please try running the app in incognito mode just to be sure that no browser extensions are interfering with it.

**Comment by Aayush9507** [comment] 2020-05-15 15:48
I tried running `npm install`, but that didn't help either, and also in the incognito window, the issue persists.
Is there any special CSS property that I need to set?

**Comment by PetarMetodiev** [comment] 2020-05-18 11:13
#### To answer the questions:
1. Yes, there is a specific CSS property that has to be set:
	```css
	.ProseMirror {
		white-space: pre-wrap;
	}
	```
	It is [part](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/editor/_layout.scss#L131) of the latest version of Kendo themes. Please note that this rule is applied if `[iframe]="false"`. In the case for `[iframe]="true"`(this is the default behaviour for the latest version) the `EditorComponent` takes care for setting the correct styles.
2. All spaces should be preserved - similar to how MS Word works.

#### In order to help with debugging the whole problem I will need more information:
1. Please try running the provided sample project and check if the issue is observed.
2. If the provided project works as expected(no trimmed spaces) - please compare its KendoUI package versions and the ones in your project. If the package versions in your project are lower - please try updating them and see if the problem persists. More info on how to update KendoUI packages can be found [here](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions).
3. If none of the above works it will be best to to provide a small sample app or StackBlitz where the issue is reproducible. I guess the easiest way would be to modify my sample app to a state where spaces are trimmed.

**Comment by Aayush9507** [comment] 2020-05-19 23:26
Adding the `white-space: pre-wrap` fixed that one issue, but created another. We are now able to add spaces as expected to the end of the text field, but the `white-space: pre-wrap` does not preserve any extra spaces when we save and reload our form.
 
For example if we type the following (with SPACE)
 
   **a**_SPACESPACESPACE_**b**_SPACE_**c**_SPACESPACE_**d**_SPACESPACESPACE_**e**_SPACESPACE_**f**
 
the text becomes and preserves only one space. (Even in Chrome)
 
   **a**_SPACE_**b**_SPACE_**c**_SPACE_**d**_SPACE_**e**_SPACE_**f** 
 
when the page reloads.
 
You can see this in the StackBlitz's kendo-editor example if you turn off the `Iframe` and toggle the `white-space: pre-wrap`. When we do this, all the extra white space is removed and re-added as you toggle.

**Comment by PetarMetodiev** [comment] 2020-05-20 07:09
Unfortunately I am unable to reproduce the problem. I will close the issue as this repo is for bug reports only.
If further assistance is needed - please use our support channel.

**Closed by PetarMetodiev** 2020-05-20 07:09 UTC
Labels: Team2, pkg:editor

**Comment by tpalber** [comment] 2020-05-22 20:56
I am also seeing this same issue in Firefox. It only occurs when I have the `[iframe]` input is set to `false`, so there is either a bug in ProseMirror or a styling within my page that's setting the `white-space: pre-wrap` to something else. I will also try to replicate it.
I also noticed this warning in the console.
`ProseMirror expects the CSS white-space property to be set, preferably to 'pre-wrap'. It is recommended to load style/prosemirror.css from the prosemirror-view package.`

**Comment by Aayush9507** [comment] 2020-05-22 21:20
Good to know that somebody else is also on the same page, I thought I am doing something weird.
In my case, I don't have anything in the styling that would set the `white-space: pre-wrap` to something else.
I had to use `white-space: -moz-pre-space`, which fixed one of our editors but am still facing this issue in some other editor that we are using, and its implementation is exactly the same.
@tpalber If you fix it somehow, please let me know too.
