### ISSUE TITLE
ComboBox does not fire valueChange when the whole input text is deleted

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#860] opened 2017-08-29 15:20 UTC
## I'm submitting a...
* Bug report

## Current behavior

When text of the ComboBox' input is deleted and the component is blurred, the valueChange event does not fire (respectively the model binding is not updated).

## Expected behavior

When text of the ComboBox' input is deleted and the component is blurred, the valueChange event should fire and the model binding should be updated.

## Minimal reproduction of the problem with instructions

Example: http://plnkr.co/edit/6wzjEms1UkXfQT0fddt1?p=preview

Delete the input value and blur the component. Node that the model value is not updated.

**Comment by tapopov** [comment] 2017-09-01 08:31
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/824

**Closed by tapopov** 2017-09-01 08:31 UTC
Labels: Bug, pkg:dropdowns
