### ISSUE TITLE
Kendo angular 2 - grid with nested grid in detail interfere if navigable = true

### ISSUE THREAD

**Issue by DuncanMuirVerint** [telerik/kendo-angular#1919] opened 2018-11-15 13:05 UTC
## I'm submitting a...

* Bug report 

## Current behavior
If the main grid and the nested grid are both set to be navigable ([navigable]="true") navigation occurs in both grids in the corresponding grid rows and cells.

The StackBlitz https://angular-klehik.stackblitz.io is a copy of an existing example from Telerik, with the only change being the setting of navigable to true in the main grid and the nested grid (which in this case is in a separate component). If you open the nested grid and click on a cell or use the arrow keys or tab to navigate in th grid you can see the problem in action.

## Expected behavior
This should not happen - the grids should be separately navigable without interfering with each other.

## Minimal reproduction of the problem with instructions
https://angular-klehik.stackblitz.io

If you open the nested grid and click on a cell or use the arrow keys or tab to navigate in th grid you can see the problem in action.

## Environment

Browser:

- Chrome (desktop) version 70.0.3538.102 (Official Build) (64-bit)

System:
- Platform:  Windows

**Comment by DuncanMuirVerint** [comment] 2018-11-15 13:10
https://angular-klehik.stackblitz.io

If the main grid and the nested grid are both set to be navigable ([navigable]="true") navigation occurs in both grids in the corresponding grid rows and cells.

The StackBlitz above is a copy of an existing example from Telerik, with the only change being the setting of navigable to true in the main grid and the nested grid (which in this case is in a separate component). If you open the nested grid and click on a cell or use the arrow keys or tab to navigate in th grid you can see the problem in action.

**Comment by danielkaradachki** [comment] 2018-11-15 13:36
Seems like duplicate of https://github.com/telerik/kendo-angular/issues/1919

**Comment by DuncanMuirVerint** [comment] 2018-11-15 13:44
You're right. I should have seen this.

**Closed** 2018-11-15 14:18 UTC
Labels: Duplicate, pkg:grid
