### ISSUE TITLE
Popup scroll issue

### ISSUE THREAD

**Issue by rtaum** [telerik/kendo-angular#2934] opened 2020-06-03 07:05 UTC
**Describe the bug**

Kendo popup sticks to the original position even when the parent component is being scrolled up/down.
Also popup appears in a wrong location if the parent element was scrolled up/down.

This reportedly got fixed [here](https://github.com/telerik/kendo-angular/issues/900) but I still have the issue.

**Note: all issues appear in Edge browser. It works as expected in Chrome.**

**To Reproduce**

Open a window with a scrollable content in Edge. 
Open a popup for one of controls in the window then scroll the window up/down.
Or scroll it first then show the popup (it is the case on the screenshot).

**Expected behavior**

In Chrome it scrolls with the parent control and always looks attached to that control.
That seems to be a proper behavior to me.

**Screenshots**

![image](https://user-images.githubusercontent.com/13500710/83606009-2e9eb400-a579-11ea-9b27-b4c44dcab338.png)

**Browser**
 - OS: Windows 10
 - Browser Microsoft Edge 
 - Version 44.18362.449.0

**Additional context**
    "@progress/kendo-angular-buttons": "^5.1.1",
    "@progress/kendo-angular-common": "^1.2.1",
    "@progress/kendo-angular-dateinputs": "^4.2.2",
    "@progress/kendo-angular-dialog": "^4.1.1",
    "@progress/kendo-angular-dropdowns": "^4.2.4",
    "@progress/kendo-angular-editor": "^1.0.6",
    "@progress/kendo-angular-excel-export": "^3.1.3",
    "@progress/kendo-angular-grid": "4.6.4",
    "@progress/kendo-angular-inputs": "^6.4.0",
    "@progress/kendo-angular-intl": "^2.0.0",
    "@progress/kendo-angular-l10n": "^2.0.0",
    "@progress/kendo-angular-label": "^2.2.0",
    "@progress/kendo-angular-layout": "^4.1.5",
    "@progress/kendo-angular-pdf-export": "^2.0.3",
    "@progress/kendo-angular-popup": "^3.0.0",
    "@progress/kendo-angular-progressbar": "0.2.1",
    "@progress/kendo-angular-tooltip": "^2.1.2",
    "@progress/kendo-angular-treeview": "^4.1.0",
    "@progress/kendo-data-query": "^1.5.2",
    "@progress/kendo-drawing": "^1.5.12",
    "@progress/kendo-theme-bootstrap": "^4.11.0",
    "@progress/kendo-theme-default": "4.12.2",

**Comment by svetq** [comment] 2020-06-03 15:03
We tested the example demonstrated in the [referenced issue](https://github.com/telerik/kendo-angular/issues/900) in Edge version 44+, but couldn't reproduce the reported undesired behavior. Here is the example:
https://stackblitz.com/edit/angular-nnvhgz?file=app/app.component.ts

Please let us know in case we are missing something. Please provide a StackBlitz example demonstrating the undesired behavior in case the issue persists. You can also fork the provided StackBlitz and update it accordingly so that it reproduces the issue. Thank you.

**Comment by elena-gancheva** [comment] 2020-06-11 08:04
We are closing this issue, since we couldn't reproduce the problem described. If still present, please open a new issue or follow up this one, with a provided runnable StackBlitz example demonstrating the undesired behavior.

**Closed by elena-gancheva** 2020-06-11 08:04 UTC
Labels: pkg:popup
