### ISSUE TITLE
DropDownList: scroll top on filterpanel apper 

### ISSUE THREAD

**Issue by Attosius** [telerik/kendo-angular#1791] opened 2018-09-14 15:10 UTC
## I'm submitting a...

Bug report
## Pre condition
Create kendo-dropdownlist with [filterable]="true"

## Current behavior

When dropdownlist opened, parent container scroll top

## Expected behavior
When dropdownlist opened, no scrolling (as  [filterable]="false")

## Minimal reproduction of the problem with instructions

1. create kendo-dropdownlist with [filterable]="true"
2. click on the dropdownlist  list to open it

![filter-scroll](https://user-images.githubusercontent.com/21027214/45558446-9adb0080-b848-11e8-8a11-99322f30788e.gif)

https://stackblitz.com/edit/angular-scrollfilter?file=app%2Fapp.component.ts

## Environment

Package versions:
"@progress/kendo-angular-dropdowns": "3.0.3",

![image](https://user-images.githubusercontent.com/21027214/45558698-32405380-b849-11e8-9783-2cb373993cb2.png)

Browser:
- Chrome (desktop) version  66.0.3359.181

**Comment by tapopov** [comment] 2018-09-17 06:45
Duplicate of https://github.com/telerik/kendo-angular/issues/1784

**Closed** 2018-09-18 05:42 UTC
Labels: Bug, Duplicate, pkg:dropdowns
