### ISSUE TITLE
Row's height is not updated after exiting edit mode with locked columns

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-angular#902] opened 2017-09-13 06:36 UTC
* Bug report 

## Current behavior
When exiting edit mode, row's height is not re-calculated.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/dAerQoiWHLbKyiXvs5GB?p=preview

Package versions:
kendo-angular-grid: 1.4.1

**Comment by geokaps** [comment] 2017-09-20 15:26
Also seeing this behavior when toggling the locked state of a column (i.e., [locked]="true") dynamically. Row height for toggled locked column rows is not being calculated correctly in kendo-angular-grid 1.4.1, as it was working properly with kendo-angular-grid 1.3.2. This is especially apparent if you use <kendo-grid-column-group>'s to wrap <kendo-grid-column>'s. Please compare with how v1.3.2 worked.

**Comment by ipeshev** [comment] 2017-09-29 06:43
@geokaps we tried on our side with both version and it looks fine ( regarding your comment ) . Could you give us more specific scenario for this issue ? Maybe some code snippet ?

**Comment by tsvetomir** [comment] 2017-10-10 06:52
Closing due to inactivity. @geokaps feel free to reopen if you're still experiencing the problem wigh v1.5.0 of the Grid.

**Comment by tsvetomir** [comment] 2017-10-10 09:34
My bad, the original issue is still reproducible.

**Comment by ipeshev** [comment] 2017-12-08 13:18
Fixed in v1.6.3-dev.201712071310

**Comment by geokaps** [comment] 2017-12-11 20:08
I can verify that the issue with the row height getting out of sync between the locked columns and the unlocked columns is fixed in v1.6.3-dev.201712071310. Thank you very much!

My only issue is this: Let's say that I'm using a locked column (the left-most one displayed) containing the name of a country and also using a `kendoGridGroupHeaderTemplate` that represents a region of the world that appears as a grouping banner above the various countries. The output looks like this:

![image](https://user-images.githubusercontent.com/7048638/33850137-e3683d9c-de80-11e7-9a6f-7ef77178a175.png)


**When I lock the first column** the output changes, wrapping the text in the group header to this:
![image](https://user-images.githubusercontent.com/7048638/33851135-00c50cf0-de84-11e7-870b-0d225a4d15d6.png)


That's perfectly acceptable. **My only issue is that when you unlock the column, the wrapped text returns to it's unwrapped state, but the padding added to the group header remains (compare this to the first image, see the extra padding?):**

![image](https://user-images.githubusercontent.com/7048638/33851164-1eac5c14-de84-11e7-9f6a-176b88f0998d.png)

The problem I have with this is that when you do a PDF export, the group headers with the extra padding also export with the extra padding, creating printed copies with large group banners which don't look correct and waste a lot of vertical space, resulting in PDF documents that are longer than they need to be.

Can the height of the `kendoGridGroupHeaderTemplate` objects be recalculated when the columns are unlocked so that they match the **original** unlocked state?

**Comment by rkonstantinov** [comment] 2017-12-13 09:10
The behavior you have described is caused by the fact that the group rows will not be re-rendered when toggling the locked option, thus, not removing the previously set height. You could workaround this by re-binding the component when unlocking the columns. [Here](https://plnkr.co/edit/928DjY4cMyNsmZ8ORdkZ?p=preview) you can find a small plunker which demonstrates this in action.

**Closed** 2018-01-12 13:30 UTC
Labels: Bug, Passed-QA, pkg:grid
