### ISSUE TITLE
Popup jumps to initial position on scrolling top became negative value

### ISSUE THREAD

**Issue by AkunaMatata** [telerik/kendo-angular#237] opened 2017-01-27 08:53 UTC
example plunkr http://embed.plnkr.co/Xyi3swaL0528TuAx2Hpq/
On scrolling when popup reaches the top of window it jumps to center page(depends on the initial position).

**Comment by ggkrustev** [comment] 2017-01-30 12:07
Hi @AkunaMatata,
in general the Popup component is designed to close when its content if outside of the view port. That is why it exposes [`afterViewportLeave`](http://www.telerik.com/kendo-angular-ui/components/popup/api/PopupComponent/#toc-anchorviewportleave-eventemitter) event.

We will consider improving popup's behavior when it is outside the viewport. For now I would suggest you just hide the component when event is raised.

I will update the thread once we have more information on how we are planning to resolve the issue.

**Comment by ggkrustev** [comment] 2017-02-14 13:57
The enhancement is scheduled for the official (v1.0.0) release of Kendo Popup component for Angular. The issue is moved in the private Popup repo, hence I will close this thread for now.

**Closed by ggkrustev** 2017-02-14 13:57 UTC
Labels: Enhancement, pkg:popup

**Comment by AkunaMatata** [comment] 2017-02-14 14:02
Thanks
