### ISSUE TITLE
InsertLink Toolbar Tool bug

### ISSUE THREAD

**Issue by ngbao3105** [telerik/kendo-angular#2561] opened 2019-10-24 03:25 UTC
Idk is there anyone met my issue.
When inserting a link by the createLink tool on Kendo Toolbar It's works. But when left-clicking on the <a> inserted nothing is happened.

**Comment by danielkaradachki** [comment] 2019-10-24 06:02
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/2445

**Closed by danielkaradachki** 2019-10-24 06:02 UTC
Labels: Duplicate, pkg:editor
