### ISSUE TITLE
[Dialog] Error when dynamically creating dialog instance with a kendo-dialog-titlebar in template

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-angular#3121] opened 2020-11-17 14:38 UTC
**Describe the bug**
An error is thrown when a dialog is initialized via the DialogService and the custom content component contains a kendo-dialog-titlebar component in its template.

**To Reproduce**
Open [this demo](https://stackblitz.com/edit/dialog-missing-service?file=app/user-info.component.ts) and click the button to open the dialog.

**Expected behavior**
The dialog should appear without errors.

**Screenshots**
![null service](https://user-images.githubusercontent.com/45083324/99402651-3f0dd580-28f2-11eb-800e-f5284bdf66e3.png)

**Browser**
 - OS: any
 - Browser: any
 - Version: 4.2.3

**Comment by Nividica** [comment] 2020-11-18 22:18
Just ran into this one as well.
Using a custom component, and its template contains kendo-dialog-titlebar.

**Comment by PaluMacil** [comment] 2020-11-18 22:23
Confirmed, same issue and repro for my team's product. Breaks a lot of modals since the update to 2020 R3

**Comment by gkarapeev** [comment] 2020-11-19 07:34
For the time being, our suggested workaround would be go revert to the previous version - 4.2.2 - until we resolve the issue. Thank you for your understanding.

**Comment by Raisolution** [comment] 2020-12-15 11:39
Fix is available in the latest dev version of the `kendo-angular-dialog` package. An official version will be released tomorrow.

**Closed by Raisolution** 2020-12-15 11:39 UTC
Labels: Bug, Team2, pkg:dialog
