### ISSUE TITLE
Kendo Theme default 2.40 - Grid filter row

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#830] opened 2017-08-16 07:46 UTC
## I'm submitting a...
* Bug report

## Current behavior
Since kendo-theme-default 2.40 the grid filter row became even messier. The numeric and dropdown filters are much much wider than the column itself and the operator dropdown is not visible.

## Minimal reproduction of the problem with instructions
Filter demo from the Kendo docs:
http://plnkr.co/edit/cxXXJZ9K8jrZHwYWThTk?p=preview

![image](https://user-images.githubusercontent.com/323925/29352583-f3a3c310-826f-11e7-9cea-a6bc857b22cf.png)

## What is the motivation or use case for changing the behavior?
I expect the filters to stay within the bounds of the column and the operators dropdown to be visible

**Comment by gyoshev** [comment] 2017-08-16 08:54
Thank you for reporting this. This will be addressed in the next version of the theme, which we should release by the end of the day. Until then, use the following workaround:

    .k-filtercell-wrapper > .k-widget {
        width: 100%;
    }

**Comment by gyoshev** [comment] 2017-08-16 12:26
`@progress/kendo-theme-default@2.40.1` resolves the bug.

**Comment by moxival** [comment] 2017-08-17 11:58
For us the issue still stands:

![image](https://user-images.githubusercontent.com/323925/29411189-63c13ef6-835c-11e7-816e-1638608ef8ca.png)

The plunkr still shows the bug as well.

**Comment by gyoshev** [comment] 2017-08-17 13:18
The version on the site is 2.40.0 until our next site upload. After [updating the plunker with version 2.40.1 from unpkg](http://plnkr.co/edit/joudFHxj3voCoPz2FZT0?p=preview), the issue disappeared. If the plunker differs from the application use case, can you please update it so that it shows the issue?

**Comment by moxival** [comment] 2017-08-18 06:00
Hi @gyoshev yes you are correct the plunkr was with the old version but now it only works because the dropdown is not wide enough. Here is a plunkr that demonstrates the bug still appearing: http://plnkr.co/edit/WAZ83UiL8s3KSt9tIRfT?p=preview

**Comment by gyoshev** [comment] 2017-08-18 10:10
Indeed, thank you for the details. The issue is caused by the extra element rendered by the custom filter; the extra element does not match the selector `.k-filtercell-wrapper>.k-widget`. The issue can be fixed by setting `style="width: 100%;"` on the kendo-dropdownlist, as [seen in this plunker](http://plnkr.co/edit/pEPwcTO6Lgf911yss1EQ?p=preview). I feel that this behavior is managed better by the custom component; setting `width:100%` to all component through the theme may conflict with the author's intent (for example, when there are more elements in the custom filter). What are your thoughts on this?

**Comment by moxival** [comment] 2017-08-19 06:01
Well it is true that it might have some negative impact. At the moment I would expect every custom filter to use all the available space in the filter cell, we can achieve this easily with the custom.scss however this should be noted in the documentation for the custom grid.

**Comment by moxival** [comment] 2017-08-21 07:07
Hey @gyoshev discovered that the boolean filter is misbehaving as well: http://plnkr.co/edit/94kjT9eZALM5Nh4iX7mw?p=preview

The column is obviously very small but that is just to showcase the problem (select false)
![image](https://user-images.githubusercontent.com/323925/29506761-fdb8c7da-8655-11e7-8cfd-6db4b46b9753.png)

**Comment by inikolova** [comment] 2017-08-21 14:40
Hey @moxival, thank you for the details. I have just pushed a fix for the boolean filter appearance

**Comment by ipeshev** [comment] 2017-09-29 06:55
Fixed in v2.42.1

**Closed by ipeshev** 2017-09-29 06:55 UTC
Labels: Bug, Needs-QA, Styling
