### ISSUE TITLE
filterable kendo-dropdownlist closes immediately again when scrolled

### ISSUE THREAD

**Issue by dvdgutzmann** [telerik/kendo-angular#1857] opened 2018-10-17 14:38 UTC
## I'm submitting a...

* Bug report 

## Current behavior
A filterable kendo-dropdownlist closes immediately again when positioned towards the bottom of a page and therefore needs to be scrolled into view prior to clicking on the control.

## Expected behavior
The control should stay open.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/kendo-dropdownlist-filter-bug

**Comment by dvdgutzmann** [comment] 2018-10-17 14:49
This Issue seems to be a duplicate of #1851, however there is no mention of `[filterable]="true"` Without enabling filtering the control works as expected.

**Comment by dtopalov** [comment] 2018-10-17 14:58
Closing as a duplicate of [https://github.com/telerik/kendo-angular/issues/1784](https://github.com/telerik/kendo-angular/issues/1784)

**Closed by dtopalov** 2018-10-17 14:58 UTC
