### ISSUE TITLE
[MultiColumnComboBox] column border misaligned when list data is less than the listHeight

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3477] opened 2021-10-20 20:58 UTC
**Describe the bug**
When the data content is less than the listHeight, the column borders are not aligned with the header border.

**To Reproduce**

[StackBlitz example](https://stackblitz.com/edit/angular-hcwrw5?file=app/app.component.ts) replicating the issue.

**Expected behavior**
The column border should be aligned with the header border.

**Screenshots**
![image](https://user-images.githubusercontent.com/25337886/138170453-443e93d7-982d-4b1c-9e18-0102a0bfd22d.png)

**Comment by JoomFX** [comment] 2023-09-21 07:13
The issue is fixed in version 13.5.0

**Closed by JoomFX** 2023-09-21 07:13 UTC
Labels: Bug, pkg:dropdowns, Team1, sev1: low, freq2: possible
