### ISSUE TITLE
Panel Bar Title

### ISSUE THREAD

**Issue by PMoransais** [telerik/kendo-angular#450] opened 2017-04-04 19:19 UTC
When specifying an Icon, there is no spacing between icon and Title.

It would be great to allow template or HTML content for Title - we could use any icon in any color!

**Comment by Raisolution** [comment] 2017-04-04 19:49
Hi @PMoransais,

Have you tried the [PanelBarItemTitleDirective](http://www.telerik.com/kendo-angular-ui/components/layout/api/PanelBarItemTitleDirective/) to achieve the desired behavior?

**Comment by PMoransais** [comment] 2017-04-05 17:01
I missed that! Sorry. I will try.

**Comment by PMoransais** [comment] 2017-04-05 17:25
@Raisolution 

I use the panel bar as follows:
            <kendo-panelbar [items]="items" (stateChange)="onPanelChange($event)">
            </kendo-panelbar>

The items variable contains the hierarchy of items and I rely on it do display the panel items.
I do not know how to use the PanelBarItemTitleDirective in this case?
 Is it possible?

Thanks

**Comment by PMoransais** [comment] 2017-04-05 17:54
I am trying to change the display of the title with the PanelBarItemTitleDirective.

It works BUT it does not replace the display of the Title string! When set to space or empty string the title displays as Untitled and the content of the directive then follows.

![image](https://cloud.githubusercontent.com/assets/19433579/24719101/8144e4ce-1a06-11e7-9350-70a30823c5f3.png)

I need the icon (from Font-Awsome) to be displayed on the left!
This is amazingly complicated and badly though-out! Coupled with the way you report events where it is left to users to figure out if it is a click or a panel that expands for the first time (this needing lazy loading)

Please throw a click event and a loadChildrenEvent. For the Title, how about TitleAsHTML?

As of now, the directive is useless!

**Comment by Raisolution** [comment] 2017-04-06 07:56
@PMoransais,

Regarding the first question, currently setting the title template is not possible when the items are specified as a collection of items.

Regarding the second one, this is the correct way to specify it. The problem is that the default title at the moment is `Untitled`. You could manually set it to an empty string (which is a good idea for us to implement out of the box too). The idea of the directive is to serve as the mentioned `TitleAsHTML`.

Regarding the events, thank you for the idea. We will discuss it.

**Comment by Raisolution** [comment] 2017-04-06 08:19
I am closing this for now, as the initial issue is resolved.

**Closed by Raisolution** 2017-04-06 08:19 UTC
Labels: pkg:layout

**Comment by PMoransais** [comment] 2017-04-06 13:04
Ok Thanks for the help.

Also, providing a AddtoHTML property in the Item Model would allow to have a custom Title in all cases and in a much simpler way. I would open up use cases such as buttons etc. I hope you consider that.

In addition, when adding items to a panel it is impossible to select them? Why not.

**Comment by dimodi** [comment] 2017-04-06 13:56
Hello @PMoransais,

Thank you for your interest in Kendo UI for Angular.

Normally, this GitHub issues list is for bug reports only. If you wish to report one, please follow [these guidelines](https://github.com/telerik/kendo-angular#bug-reporting) and open a new issue. For technical how-to questions, please consider submitting a support request in our [ticketing system](https://www.telerik.com/account/support-tickets) at telerik.com. Thank you.
