### ISSUE TITLE
DropdownList shows invalid when we Apply Disabled to it

### ISSUE THREAD

**Issue by bhavinmatariya** [telerik/kendo-angular#2006] opened 2019-01-02 13:36 UTC
<img width="1439" alt="kendodropdownlist" src="https://user-images.githubusercontent.com/30688070/50594082-0f51b200-0ec1-11e9-9d81-99bd965f6f6e.png">

If i Apply Disabled state to a DropDownlist it shows invalid, but if i remove disabled it shows the dropdownlist is valid

Example:
https://stackblitz.com/edit/angular-vqoajw?file=app%2Fapp.component.ts

**Comment by ipeshev** [comment] 2019-01-02 14:59
Thank you for the bug report, can confirm that it is a problem at our side.

**Comment by dimitar-pechev** [comment] 2019-01-07 12:53
This is actually an issue (or a design choice, depending on how you look at it) of Angular's `FormControl`.   It seems that when a `FormControl` is disabled its `valid` property will always return `false` - even if you remove the `required` attribute from it. Refer to [this example](https://stackblitz.com/edit/angular-vqoajw-zqr5cf) that uses a simple `input` element. The reasoning behind this behavior is explained [here](https://github.com/angular/angular/issues/11432).

As a workaround, you could set the **DropDownList's** `readonly` prop to `true` - the validation is correct in that case. Furthermore, if you want the widget to have the disabled styles used by the Kendo Themes, you can apply the `k-state-disabled` class to the **DropDownList**. Refer to [this example](https://stackblitz.com/edit/angular-vqoajw-z58m4p).

Closing the issue, as the problem is related to Angular and not to the Kendo component.

**Closed by dimitar-pechev** 2019-01-07 12:53 UTC
Labels: Bug, pkg:dropdowns
