### ISSUE TITLE
Button text disappears when disabled in panel

### ISSUE THREAD

**Issue by mikef907** [telerik/kendo-angular#2220] opened 2019-04-19 18:45 UTC
## I'm submitting a...

* Bug report 

## Current behavior

Button text inconstantly showing up in panel bar when button is disabled using bootstrap theme

## Expected behavior

Button text should always remain visible when panel is expanded

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-nf3gjt

## Environment

Browser:

- Chrome (desktop) version Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by ipeshev** [comment] 2019-04-22 07:07
@mikef907 can't reproduce it on our side, are there some other conditions ? Please provide snapshot if possible.

**Comment by ipeshev** [comment] 2019-04-22 11:51
We managed to reproduce it , will look at it.

**Comment by tsvetomir** [comment] 2019-05-15 07:47
Fixed in v3.3.1

**Closed by tsvetomir** 2019-05-15 07:47 UTC
Labels: Bug, Needs-QA, pkg:layout
