### ISSUE TITLE
[TimePicker] Input value not handled properly

### ISSUE THREAD

**Issue by Aiiden98** [telerik/kendo-angular#4144] opened 2023-11-02 15:58 UTC
I noticed that when I input a time from the keyboard, the component as an hard time to show the correct value inside the input

You can reproduce it on the official website by typing for example "13:13" here https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/formats/

**Comment by yanmariomenev** [comment] 2023-11-08 16:08
Duplicate of - https://github.com/telerik/kendo-angular/issues/4131
Feel free to try out the fix in version [14.1.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v14.1.0).

**Closed by yanmariomenev** 2023-11-08 16:08 UTC
Labels: Duplicate
