### ISSUE TITLE
kendo-theme-default: 2.59.0 - $font-size rem unit

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1891] opened 2018-11-06 08:55 UTC
We have customised so many aspects on our kendo theme based on bootstrap. 
Actually we don't use kendo bootstrap theme but we will move on it when boss will find few days 😄 .

Right now we have:

```
$font-size-base:             1rem;
$font-size: $font-size-base;
```

With latest version of kendo-theme-default: 2.59.0 we have error:

```
Error: node_modules\@progress\kendo-theme-default\scss\mixins\core\_math.scss
Error: 272em*px/rem isn't a valid CSS value.
        on line 6 of node_modules/@progress/kendo-theme-default/scss/mixins/core/_math.scss, in function `add-two`
        from line 768 of node_modules/@progress/kendo-theme-default/scss/_variables.scss
        from line 1 of node_modules/@progress/kendo-theme-default/scss/popup.scss
        from line 7 of packages/@aulos/kendo-theme/css/all.scss
>>     $_one: $multiplier * $one;
```

For now we just revert on previous version.

**Comment by gyoshev** [comment] 2018-11-23 14:48
As a temporary workaround, you can set `$calendar-cell-size: 34px;`.

The issue is caused by a calculation of the calendar cell size, which uses the `$font-size` to convert pixels to `em` units.

I'm moving this issue to the [kendo-themes repo](https://github.com/telerik/kendo-themes/issues/463), as this is a theme issue.

**Closed by gyoshev** 2018-11-23 14:48 UTC
Labels: Styling
