### ISSUE TITLE
Autocomplete does not show PopUp 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1914] opened 2018-11-15 08:09 UTC
## I'm submitting a...

* Bug report 

## Current behavior
The AutoComplete does not show the Popup with options when using the default Google keyboard to type on Android devices. 

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-lqrkvr-woptyv?file=app/app.component.ts](https://stackblitz.com/edit/angular-lqrkvr-woptyv?file=app/app.component.ts)

## Environment
Android 6.0.1
Chrome 70

**Comment by dimitar-pechev** [comment] 2019-02-14 10:39
Caused by #1958.

**Comment by dimitar-pechev** [comment] 2019-03-14 17:47
Fixed in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.2-dev.201903141745**.

**Comment by tsvetomir** [comment] 2019-03-15 16:31
Shipped in v3.5.2

**Closed by tsvetomir** 2019-03-15 16:31 UTC
Labels: Bug, Needs-QA, pkg:dropdowns
