### ISSUE TITLE
Grid: Column Resizing Odd Behavior in Certain Layouts

### ISSUE THREAD

**Issue by ngiebel** [telerik/kendo-angular#1825] opened 2018-10-03 20:02 UTC
## I'm submitting a...

* Bug report 

## Current behavior

In certain layouts when resizing columns it seems that the table content becoming scrollable horizontally is using the viewport size in its calculations.

## Minimal reproduction of the problem with instructions

Broken behavior example: 
 https://stackblitz.com/edit/angular-lrhsld-uymk6g?file=app/app.component.html

Before resizing any column if the 'window' size is changed the table keeps the correct content width but once a column is resized, for example making it larger, the table will grow in the horizontal amount that appears to be equal to how far it is offset from the left of the viewport. If the table is wrapped in an absolutely positioned element with left and right as zero and inherited padding it will size correctly but is not an option as it takes it out of the document flow.

Accidentally found workaround:
https://stackblitz.com/edit/angular-lrhsld-6b2eaj?file=app/app.component.html

No idea why this causes it to start 'working'. Change is addition of `style="overflow: auto"` on line 7 of the template.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Safari (desktop) version XX

**Comment by gyoshev** [comment] 2018-10-04 12:14
This is not an issue in the Grid component, rather in the specific layout. Using `overflow` to resolve this is okay. An alternative way of resolving the problem is to set `min-width: 0` on the w-100 container -- here is an [article that explains this](https://moduscreate.com/blog/how-to-fix-overflow-issues-in-css-flex-layouts/) in more detail.

The behavior is observed after resizing because the grid columns get assigned a `width`, so that they are not auto-sized. The same problem can also be observed if the gird is replaced with an arbitrary scroll container with enough content to cause a scroll. See [this Stackblitz example](https://stackblitz.com/edit/angular-lrhsld-pbin6h?file=app%2Fapp.component.html).

**Closed by gyoshev** 2018-10-04 12:14 UTC
Labels: Question, Styling, pkg:grid
