### ISSUE TITLE
Kendo dialog is not placed center of the screen

### ISSUE THREAD

**Issue by pooya1361** [telerik/kendo-angular#1183] opened 2018-01-05 09:30 UTC
## I'm submitting an issue with Kendo dialog which is not placed in the middle of the screen 

* Suggestion for improvement / Issue

## Current behavior
I have a very wide grid (Master-detail). when I show the dialog, it appears in the center of the grid rather than the center of the screen.

## Expected behavior
The dialog locates itself in the middle of the screen regardless of the parent component

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/QjjHr7LihpJVtqgAONUi

## Environment

Package versions:
```
+-- @angular/animations@5.1.3
+-- @angular/cli@1.6.3
+-- @angular/common@5.1.3
+-- @angular/compiler@5.1.3
+-- @angular/compiler-cli@5.1.3
+-- @angular/core@5.1.3
+-- @angular/forms@5.1.3
+-- @angular/http@5.1.3
+-- @angular/language-service@5.1.3
+-- @angular/platform-browser@5.1.3
+-- @angular/platform-browser-dynamic@5.1.3
+-- @angular/platform-server@5.1.3
+-- @angular/router@5.1.3
+-- @ng-bootstrap/ng-bootstrap@1.0.0-beta.8
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-dateinputs@1.4.2
+-- @progress/kendo-angular-dialog@1.3.0
+-- @progress/kendo-angular-dropdowns@1.5.0
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.6.5
+-- @progress/kendo-angular-inputs@1.4.2
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.2.0
+-- @progress/kendo-angular-popup@1.3.1
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.0
+-- @progress/kendo-theme-default@2.46.0
+-- @types/jasmine@2.8.3
+-- @types/jasminewd2@2.0.3
+-- @types/node@8.0.58
+-- bootstrap@4.0.0-beta.3
+-- chalk@2.3.0
+-- codelyzer@4.0.2
+-- core-js@2.5.3
+-- css-loader@0.28.8
+-- font-awesome@4.7.0
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- UNMET PEER DEPENDENCY jquery@1.9.1 - 3
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.3
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- ng2-toastr@4.1.2
+-- UNMET PEER DEPENDENCY popper.js@^1.12.9
+-- protractor@5.2.2
+-- rxjs@5.5.6
+-- ts-node@4.1.0
+-- tslint@5.8.0
+-- typescript@2.5.3
`-- zone.js@0.8.19

npm ERR! peer dep missing: jquery@1.9.1 - 3, required by bootstrap@4.0.0-beta.3
npm ERR! peer dep missing: popper.js@^1.12.9, required by bootstrap@4.0.0-beta.3
npm ERR! missing: hawk@3.1.3, required by node-pre-gyp@0.6.39
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.39
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.39
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.39
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: cryptiles@2.0.5, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: sntp@1.0.9, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: hawk@3.1.3, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1
```

Browser:

- Chrome (desktop) version 63.0.3239.108 (Official Build) (64-bit)

**Comment by tsvetomir** [comment] 2018-01-08 14:40
The Dialog will be positioned relative to its parent container, in this case the detail row.

To get a proper modal dialog, we need to attach it to the document instead. This is only possible by using the [Dialog Service](https://www.telerik.com/kendo-angular-ui/components/dialog/service/). The syntax is slightly different, but you get full control on where the dialog is rendered.

**Comment by pooya1361** [comment] 2018-01-09 13:33
Thanks @tsvetomir but it didn't help
https://plnkr.co/edit/QjjHr7LihpJVtqgAONUi?p=preview

**Comment by tsvetomir** [comment] 2018-01-12 12:44
The kendoDialogContainer should be placed after to main grid or in the body, [see plunkr](https://plnkr.co/edit/TQPVjVxd39uscwstLs2m?p=preview).

Closing this issue, as this behavior is by design.

**Closed by tsvetomir** 2018-01-12 12:44 UTC
Labels: Question, pkg:dialog

**Comment by JBoothUA** [comment] 2024-02-16 19:35
there has to be a better way to center things in the viewport
