### ISSUE TITLE
Crazy dropdown (popup) behaviour within a modal dialog

### ISSUE THREAD

**Issue by jrdutton** [telerik/kendo-angular#3499] opened 2021-11-10 16:28 UTC
**Describe the bug**
When a drop-down list is included within a modal dialog over a page that scrolls, and the drop-down is opened, and the page is scrolled via the mouse wheel, then craziness occurs.

**To Reproduce**
https://stackblitz.com/edit/angular-stm6zy?file=app%2Fapp.component.ts
- Open the dialog.
- Open the drop-down.
- Scroll up and down with the mouse wheel.

**Expected behavior**
The drop-down should remain firmly in position, and not move up and down.

**Comment by ciiara** [comment] 2021-11-11 13:30
Thank you for the feedback.
The root cause of the observed problem is that the page is scrollable when the Dialog is opened. We are aware of this issue, I am closing this one in favour of [https://github.com/telerik/kendo-angular/issues/3157](https://github.com/telerik/kendo-angular/issues/3157)

**Closed by ciiara** 2021-11-11 13:30 UTC
