### ISSUE TITLE
[Combobox] Using async with kendoDropDownFilter parameter subscribes twice to the observable

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#2461] opened 2019-09-03 07:29 UTC
**Describe the bug**
Using the async pipe for the data field in conjunction with the kendoDropDownFilter parameter subscribe to the observable twice.

**To Reproduce**

https://stackblitz.com/edit/angular-njrpwg

        <kendo-combobox
            [data]="listItems | async"
            [kendoDropDownFilter]="{'caseSensitive' : false,'operator' : 'contains'}"
            >
          </kendo-combobox>

The alert will open twice, once for each subscribe. 
Remove the kendoDropDownFilter from the template and it will only open once.

**Expected behavior**
Should only subscribe once

**Browser**
Chrome 76.0
Windows 10

**Comment by dimitar-pechev** [comment] 2019-09-03 08:58
The double subscription occurs as both the **ComboBox** component and the filtering directive have a `data` input property. So the `async` pipe subscribes in both places. The simple workaround here would be to subscribe manually to the service and pass the fetched items in the template without the `async` pipe as demonstrated [here](https://stackblitz.com/edit/angular-njrpwg-x5defa).

The name overlapping was actually intentional to allow for simpler directive configuration. In general, the directive was intended to cover simple use cases where the data is preloaded. It doesn't cover scenarios such as server-side filtering, setting loading state, min filter length, changing the no-data-found label, etc. More complex use cases are meant to be implemented by the user of the code.

I must admit though that the `async` pipe scenario was obviously overlooked. However, amending the directive `data` input prop now would be a breaking change for a lot of users, so I honestly don't think it's something we'll go for now. Another option would be to add another property and read the data from it as well, however, such configuration would be confusing to some, so again I don't think it would be ideal.

When the directive was introduced, the main feature was actually updating the component state when the `data` is changed through the component API (`combobox.data = /** */`). That allows the user of the code to implement filtering directives that can cover a variety of use cases tailored to the specific scenario. The implementation of such a directive is rather simple. Refer to [this example](https://stackblitz.com/edit/angular-njrpwg-drjyyw).

@Neaco, thank you for bringing this to our attention, however, I'll label this as `Won't fix` as I don't think we'll change the current behavior. If you need help with implementing a more complex filtering directive, I'd encourage you to open a [support ticket](https://www.telerik.com/account/support-tickets). 

Also, if you have any remarks, please do share them here. We could reopen the thread if deemed necessary and take it from there.

**Closed by dimitar-pechev** 2019-09-03 08:58 UTC
