### ISSUE TITLE
[Textbox] Shows undefined variable as "undefined" instead of empty

### ISSUE THREAD

**Issue by ankerer** [telerik/kendo-angular#3638] opened 2022-04-01 14:05 UTC
I created a <kendo-textbox> which has a simple [(ngModel)] binding to a string property which is undefined at the beginning. Instead of an empty textbox, "undefined" is the value that is displayed in the box.

https://stackblitz.com/edit/angular-be9ev1?file=app/app.component.ts

I would expect the same behavior as the standard HTML input, that undefined is displayed as empty string.

It is a pretty obvious behavior and it could well be that it is intended, but I haven't found anything in the documentation that states that this is standard behavior.

**Comment by mbechev** [comment] 2022-04-04 08:35
Hi @ankerer,

Generally the TextBox component behaves as the standard HTML `<input />` element. 

Setting the `<input />` value to _undefined_ is also shown as a value in the component:

https://stackblitz.com/edit/angular-be9ev1-6y1bfe

Consider using _null_ or empty string ('') as value instead.

**Comment by dtopalov** [comment] 2022-04-04 08:53
@ankerer,

Indeed, there are discrepancies in the behavior when binding to `undefined` in some scenarios, caused by the Input element value binding described by @mbechev.

We are closing this thread as a duplicate of https://github.com/telerik/kendo-angular/issues/3615 - additional details are available in the discussion under the original issue, and all further updates will be shared there once available.

**Closed by dtopalov** 2022-04-04 08:53 UTC
Labels: Duplicate, Question, pkg:inputs, Team2
