### ISSUE TITLE
Memory leak when using kendoUploadDropZone or kendoFileSelectDropZone directives

### ISSUE THREAD

**Issue by RyanFM** [telerik/kendo-angular#4295] opened 2024-05-08 12:53 UTC
**Describe the bug**
Using the UploadDropZoneDirective in the Kendo FileSelect or Upload components causes a memory leak, as seen when repeatedly initializing and destroying the component such as in an ngIf.

### Example with the directive, after showing and hiding the component 10 times
<img width="550" alt="Screenshot 2024-05-08 134406" src="https://github.com/telerik/kendo-angular/assets/24604594/eabf798a-092d-4b21-803e-3748e6997666">
<img width="550" alt="Screenshot 2024-05-08 134335" src="https://github.com/telerik/kendo-angular/assets/24604594/2e2108f1-7147-4899-b682-66bb20274ddf">

### Example without the directive
<img width="550" alt="Screenshot 2024-05-08 141341" src="https://github.com/telerik/kendo-angular/assets/24604594/d3bec06c-3d14-4e78-be8a-4541a62e2ea8">
<img width="550" alt="Screenshot 2024-05-08 134142" src="https://github.com/telerik/kendo-angular/assets/24604594/0a7eb8b7-0719-47c2-962f-d099442e7398">

**To Reproduce**
Using this example:
https://stackblitz.com/edit/angular-kg16zc-5gczvx?file=src%2Fapp%2Fapp.component.ts

1. Click the "Click here" text repeatedly to show and hide the file select component.
2. Open DevTools (Chrome or Edge) and go to the memory tab.
3. Select the JavaScript VM instance that looks like the highlighted one here:

<img width="550" alt="Screenshot 2024-05-08 134036" src="https://github.com/telerik/kendo-angular/assets/24604594/c06c5eed-9464-4c0c-9335-d37f19311301">

4. Take a heap snapshot.
5. In summary view, filter for "dropzone" or "component"  to see that FileSelectComponents, UploadDropZoneDirectives and others are present multiple times, for each time you show and hide it.

**Comment by yanmariomenev** [comment] 2024-05-24 08:53
Duplicate of - https://github.com/telerik/kendo-angular/issues/4213

**Closed by yanmariomenev** 2024-05-24 08:53 UTC
Labels: Duplicate
