### ISSUE TITLE
Tooltip can't reposition when is right positioned

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3608] opened 2022-03-03 07:28 UTC
**Describe the bug**
By default when the Tooltip cannot fit on the specified side, the set **position** is ignored. The Tooltip position is automatically changed. Here is an example where the Tooltip should appear on the left, but because of the left space, it is right positioned:
https://stackblitz.com/edit/angular-phifgc-zxdtgc

But when the Tooltip should appear on the right side of its anchor and the space is not enough, it doesn't change its position automatically. Instead, the alignment is broken. Check the following screencast for more details:
https://screenrec.com/share/PAbWuHOc2U

**To Reproduce**
Drag the StackBlitz splitter to reduce the demo viewport width.
https://stackblitz.com/edit/angular-phifgc-wfdega

Might be related to https://github.com/telerik/kendo-angular/issues/3292 and https://github.com/telerik/kendo-angular/issues/2181

**Comment by Raisolution** [comment] 2022-03-10 15:16
Closing this as a duplicate of #3292 which could be used for tracking purposes.

**Closed by Raisolution** 2022-03-10 15:16 UTC
Labels: Bug, Duplicate, pkg:tooltip, Team2
