### ISSUE TITLE
Kendo- Drop down scoller reaches to last element jumping the focus from drop down list to page and page also scrolling

### ISSUE THREAD

**Issue by SailajaAlluri** [telerik/kendo-angular#930] opened 2017-09-21 12:53 UTC
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment] 2017-09-21 13:26
@SailajaAlluri, the described behavior is a native browser behavior. Once the end of the inner scrollable element is reached, the outer scrollable element will be scrolled. 

I am afraid that this behavior cannot be controlled easily. For instance, scroll event is not preventable and keeping scrollTop position of the outer element is not an option.

I will close this thread as it is not a bug in the Kendo UI DropDowns for Angular.

Please comment below if I am missing something in the reported case.

**Closed by ggkrustev** 2017-09-21 13:26 UTC
Labels: pkg:dropdowns, Question

**Comment by SailajaAlluri** [comment] 2017-09-25 06:47
That is not a native browser issue. I have verified with other controls like HTML. This scroll issue not happening with that controls.
