### ISSUE TITLE
MultiSelect always focuses the first item of the list when bound to a function

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1307] opened 2018-02-12 08:52 UTC
When the MultiSelect's value is bound to a function that always returns a new instance of an object, always the first value in the list is focused, regardless of what the user types in the INPUT. Observable in the Grid [MultiSelect filtering online demo](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/built-in-template/#toc-customizing-filter-menus):

[https://plnkr.co/edit/ntYwLeGTS1jxIO1B7cEG?p=preview](https://plnkr.co/edit/ntYwLeGTS1jxIO1B7cEG?p=preview)

Open the Category Filter menu

Type "se" - focus should go to "Seafood", but stays on "Beverages" (as it is the first item).

**Comment by tapopov** [comment] 2018-02-12 09:06
Seems like a duplicate of https://github.com/telerik/kendo-angular/issues/1068

**Comment by sboyd** [comment] 2018-02-12 14:48
Hi @tapopov this isn't quite a duplicate as my assumption from a code stanpoint is they will require different fixes.

**Comment by tapopov** [comment] 2018-02-12 14:52
@sboyd 
Out investigation suggests that the issues occur when the `value` input is bound to a function that returns a new array instance each time it is called. The scenarios in both issues will be thoroughly tested before we mark them as resolved.

**Comment by sboyd** [comment] 2018-02-12 14:59
@tapopov that's what it looked like to me as well :0)
Thanks!! As always greatly appreciated.
--Steve

**Comment by ipeshev** [comment] 2018-02-28 09:34
Fixed in v2.1.0-dev.201802271249

**Comment by tsvetomir** [comment] 2018-03-06 12:42
Released in v2.1.0

**Closed by tsvetomir** 2018-03-06 12:42 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
