### ISSUE TITLE
[Grid] (cellClick) event is fired after (dblclick)

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2466] opened 2019-09-04 11:06 UTC
**Describe the bug**
When modifying the [in-cell editing example](https://www.telerik.com/kendo-angular-ui/components/grid/editing/in-cell-editing/) to edit a cell on (dblclick) and the Grid has a large number of columns - 50, then the (cellClick) event is fired twice after the generic (dblclick) event. At the same time, the generic (click) event is fired twice before the (dblclick) event which is the proper behavior.

**To Reproduce**

Check the followiong example demonstrating this scenario:
https://stackblitz.com/edit/angular-dcgnhd-opbagf?file=app/app.component.ts

**Comment by PaskalevStoyan** [comment] 2021-12-07 13:37
We are closing this issue as the described behavior is caused by the internal handling of the DOM events necessary for their built-in functionality. There is no guaranteed sequence between custom Grid component events and the generic DOM ones (like dblclick).

**Closed by PaskalevStoyan** 2021-12-07 13:37 UTC
Labels: Bug, pkg:grid, Team2
