### ISSUE TITLE
ThemeBuilder throws a server error on theme download

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#3204] opened 2021-02-08 21:10 UTC
Logging this as a public item for `Kendo UI for Angular`.

The [Theme builder](https://themebuilder.telerik.com/kendo-angular-ui) occasionally throws a server error when downloading the custom theme. The issue is reproducible in multiple scenarios, listing some of them below:

### Scenario 1
- Click `Start Theming`
- Click `Create` with all components selected
- Update all five `Brand Colors` inputs with a custom color
- Wait for the preview to load and click `Download`
- Enter theme name and click OK

### Scenario 2
- Click `Start Theming`
- Click `Create` with all components selected
- Open the `Selected Components` dropdown and deselect any component(s)
- Wait for the preview to load and click `Download`
- Enter theme name and click OK

**Comment by joneff** [comment] 2021-03-02 15:16
The issue is fixed in themebuilder codebase. It will be made available with next deploy.

**Closed** 2021-03-19 08:35 UTC
Labels: Bug
