### ISSUE TITLE
Treelist expands when dropdown is expanded

### ISSUE THREAD

**Issue by abdulhamid-chanouha** [telerik/kendo-angular#4383] opened 2024-08-12 08:57 UTC
**Describe the bug**
I have a Treelist in my angular app, on each row i have the last column to include a button dropdown combo box, when i open the dropdown the rows of the treelist are expanded.
![image](https://github.com/user-attachments/assets/149be9d3-58c3-47a6-917d-d31c6ad517fc)

none of the treelist events or the dropdown events are used.

**Expected behavior**
The rows remain collapsed when the dropdown is opened

**Comment by yanmariomenev** [comment] 2024-08-12 12:02
Duplicate of https://github.com/telerik/kendo-angular/issues/3871

**Closed by yanmariomenev** 2024-08-12 12:02 UTC
Labels: Duplicate
