### ISSUE TITLE
[MultiSelect] when placed inside a kendoGridFilterMenuTemplate navigation is not functioning

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1792] opened 2018-09-17 07:50 UTC
## I'm submitting a...
* Bug report 

## Current behavior

Using version 3.0.3 of the DropDowns module, when we place a MultiSelect inside a template with kendoGridFilterMenuTemplate directive, the navigation is not functioning. Check the "Category" column in the following example:
[https://stackblitz.com/edit/angular-klu4s6?file=app/app.component.ts](https://stackblitz.com/edit/angular-klu4s6?file=app/app.component.ts)

## Workaround

Use version 3.0.0 of the DropDowns package.

**Comment by dtopalov** [comment] 2018-12-18 13:56
Duplicate of https://github.com/telerik/kendo-angular/issues/1068

**Closed by dtopalov** 2018-12-18 13:56 UTC
Labels: Bug, pkg:dropdowns
