### ISSUE TITLE
[ComboBox] selectionChange is not fired after call form.resetForm()

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2188] opened 2019-04-10 03:26 UTC
**Describe the bug**
`selectionChange` event is not fire when select the same item that before call `form.resetForm()` 

**To Reproduce**

1. Select `Albania`
2. Click `Reset` button to reset form
3. Select `Albania`

**Expected behavior**
Fire the `selectionChange` event

**Screenshots**
![a](https://user-images.githubusercontent.com/9428909/55849484-5071f600-5b83-11e9-9103-84440e0d2cbb.gif)

There is no selectionChange on second time

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 73.0.3683.75

**Comment by danielkaradachki** [comment] 2019-04-10 14:23
Seems the same as https://github.com/telerik/kendo-angular/issues/1733

**Comment by dimitar-pechev** [comment] 2019-06-11 07:58
The problem is indeed the same as in #1733 - restoring the previous value after programmatic value change does not trigger `selectionChange`. Closing this issue in favor of the other one to track its status in one place. We'll look to introduce a fix for this soon.

**Closed by dimitar-pechev** 2019-06-11 07:58 UTC
Labels: Bug, Team1, pkg:dropdowns
