### ISSUE TITLE
[Grid] .k-grid-column-resizing CSS class is not appended correctly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2543] opened 2019-10-18 09:36 UTC
**Describe the bug**
The _.k-grid-column-resizing_ CSS class is not removed when the [autoFitColumns](https://www.telerik.com/kendo-angular-ui/components/grid/columns/resizing/#toc-auto-fitting-the-content) method is used in **pageChange** event handler. 
When we double click between the columns in the header removes the class but does not add it back when we resize a column manually.

**To Reproduce**
https://stackblitz.com/edit/angular-enzyig?file=app/app.component.ts
Screencast: https://www.screencast.com/t/jyS9zPFZ

Reported in private support ticket- **1434915**

**Comment by siyka-marinova** [comment] 2019-12-03 09:59
The issue is fixed in `@progress/kendo-angular-grid v4.5.0`

**Comment by siyka-marinova** [comment] 2019-12-03 15:46
Fixed in `@progress/kendo-angular-grid v.4.5.0`

**Closed by siyka-marinova** 2019-12-03 15:46 UTC
Labels: Bug, pkg:grid
