### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by DBhail** [telerik/kendo-angular#2850] opened 2020-04-16 09:01 UTC
## I'm submitting a...
 Issues with   "@progress/kendo-angular-scheduler": "^1.1.4",
This doesnt work properly with overlap of all day events. 

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior
When there is an overlap of "all-day" events the scheduler display goes horribly wrong. It adds a scroll at bottom and gets all the days muddled.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by mbechev** [comment] 2020-04-24 14:56
Hi @DBhail,
Could you provide some more details about this issue, screenshots, or ideally a [StackBlitz example](https://stackblitz.com/edit/angular-xdm2u4?file=app/app.component.ts) that demonstrates the issue. Thank you in advance.

**Comment by mbechev** [comment] 2020-06-17 15:18
Hi @DBhail 

Having a minimal reproducible scenario allows us to quickly confirm a bug (or point out a coding problem) as well as confirm that we are fixing the right problem.

Now I will close this issue due to the lack of information.

Please open a new issue if you are still encountering a similar or related problem.

**Closed by mbechev** 2020-06-17 15:18 UTC
Labels: pkg:scheduler
