### ISSUE TITLE
Grid - Text filter not being removed even when it's empty

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#873] opened 2017-09-05 08:57 UTC
A text filter is not being removed when there are no characters in the textbox.

[http://plnkr.co/edit/enO1aUAAgxfJ9ysTy9ZI?p=preview](http://plnkr.co/edit/enO1aUAAgxfJ9ysTy9ZI?p=preview)

Enter any text in the filter for `Product Name`. And then delete the text from the text field. You can see that the filter is still there in the `state.filter` variable.

Do the same for other filters, and you'll find that the filters get removed from the `state.filter` variable.

**Comment by ggkrustev** [comment] 2017-09-05 09:06
Hi @vivek201, I tried to replicate the issue, but to no avail. It seems that the filter is correctly applied and removed when textbox is modified. Here is a screencast that demonstrates my tests:

https://screencast.com/t/ncS3YC4icd

Could you let me know what I am missing? Also it will be great if you can follow the ticket template structure as it provides more valuable information about the used Angular, browser, provides specific reproduction steps and etc. Thanks in advance.

**Comment by Xizario** [comment] 2017-09-05 12:12
It is visible in the video, the filter is not removed. But it looks to work only because the default filter is Contains.

To see the real problem:
1) Select `Is Equal To`
2) Type `Chai`
3) Delete the `Chai`

As result: The clear filter button is missing, but the filter is still applied and no records are visible.

**Comment by ggkrustev** [comment] 2017-09-05 12:31
Indeed, the filter descriptor is not removed. Thanks for the heads up.

**Comment by ipeshev** [comment] 2017-09-20 07:16
fixed in v1.4.2-dev.201709191052

**Closed by ipeshev** 2017-09-20 07:16 UTC
Labels: Bug, Passed-QA, pkg:grid
