### ISSUE TITLE
KeepItemContent of PanelBarCompoent does not work when add new panelbaritem dynamically

### ISSUE THREAD

**Issue by RonnyRen** [telerik/kendo-angular#1224] opened 2018-01-17 05:25 UTC
For my application, I used tabstrip compoent with two tabs and each tab use panelbar component. Tabstrip: KeepTabContent = true
PanelBar A (Tab A): KeepItemContent = false
PanelBar B (Tab B): KeepItemContent = true

Case A:  PanelBar A has 2 panelbar items, PanelBar B has 2 panelbar items.
1. When I navigate Tab A, and then navigate to Tab B and expand 2 items. 
2. Back to Tab A, and do some operations to add a new item for PanelBar A and PanelBar B.
3. Then navigate to PanelBar B,  the old items are expanded, the new item is collapsed.
4. Collapse and then expand the old two items, the content does not reload.
5. Collapse and expand the new item, the content always reload.
Expect Result: The new item just reload content once for first time expand.
Note: The content (DOM) disappear when collapse new items. Why KeepItemContent does not work for new items?

Case B:  PanelBar A has 2 panelbar items, PanelBar B has 2 panelbar items.
1. Navigate Tab A and do some operations to add a new item for PanelBar A and PanelBar B.
2. Then navigate to PanelBar B,  the old items and new item are collapsed.
3. Collapse and then expand the old two items, the content just reload once for first time expand.
4. Collapse and expand the new item, the content just reload once for first time expand.

Based on above two cases, KeepItemContent property just work for first access status of PanelBar. It means when we add new panelbar items and then navigate back, the content (DOM) for new items will always load when expand.

**Comment by ggkrustev** [comment] 2018-01-17 07:29
Hi @RonnyRen,

Thanks for the detailed reproduction steps. Could you also provide a runnable demo that replicates the case? You can use [our online demos](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/) as a base. Also it will be very helpful if you can provide more details about the versions of the angular packages. 

Please note that any of the required information in the *issue template* that we require to open a thread in our repo is important for the faster resolution of the case.

**Comment by RonnyRen** [comment] 2018-01-18 05:33
Thanks for your quick response.
I wrote an online demo (https://plnkr.co/edit/Um0rOauUUHRgDQK4tRDf?p=preview) as you suggestion. Please take a view and reproduce as following steps:
Steps:
1. By default, there is only one panelbar item ( item old) in expanded status.
2. Click 'Add New' button, the new panelbar item (item new) display.
3. Expand new panelbar item (item new), the content display as '**old content**'.
4. Click 'Change Content' button, the content update and display as '**new content**'.
5. Collapse new panelbar item (item new) and then expand it, the content still display '**old content**' instead of '**new content'** before collapse. Therefore, the keepItemContent feature does not work for new item.

**Comment by RonnyRen** [comment] 2018-01-19 01:40
@ggkrustev Is there any easy workaround?

**Comment by ggkrustev** [comment] 2018-01-19 14:58
@RonnyRen, thanks for the repro demo and for the detailed explanation.

I reviewed the test demo and I can confirm that the described behavior is actually expected. On PanelBarItem collapse the  **custom component is destroyed**. We can proof that using the Angular OnDestroy event hook:
- https://plnkr.co/edit/hbTIaoDbmkdj7mVdNWJ2?p=preview
When the `item new` is collapsed its internals will be destroyed by Angular. *This is the default behavior of the `*ngIf` structure directive that the PanelBar uses internally.*

I am afraid that there is no component configuration, which I can provide in order to overcome this default Angular behavior. When an element is removed with the `*ngIf` directive its internal components will be destroyed and we cannot stop that.

The workaround that I can think of is to persist the `my-comp1` state outside. Basically, you can provide events that will be triggered by the custom component, passing the changed state. It also will provide the required @Input properties to define the initial state. Thus the component will display the latest state when the PanelBarItem is expanded. Check the modified demo which depicts the suggested approach:

https://plnkr.co/edit/G428c6lKJDdVz1uITmL7?p=preview

Please note that the discussed issue is not related to PanelBar by any means, but rather it is a general Angular knowledge. I would suggest you examine the Angular documentation for better understanding on how *ngIf* works:

https://angular.io/guide/component-interaction
https://angular.io/guide/template-syntax
https://angular.io/guide/displaying-data#conditional-display-with-ngif

**Comment by RonnyRen** [comment] 2018-01-19 15:37
@ggkrustev 
Please view my new demo (https://plnkr.co/edit/G428c6lKJDdVz1uITmL7?p=preview)
NOTE:
The both of two panelbar items use *ngIf directive. The difference of them is old item display by default, the new item display when click 'Add New' button. The content in the old item does not reload when collapse and expand. Why the content in the new item always reload when collapse and expand it.
When collapse/expand panelbar item, *ngIf condition does not change and panelbar item does not destroy,  why the internal component was destroyed?

**Comment by ggkrustev** [comment] 2018-01-19 17:03
@RonnyRen,

Probably my explanation was a bit unclear. By '`*ngIf` destroys the content' I meant the *ngIf directive that PanelBarItem class uses internally to show/hide its content. When the item is collapsed, it sets `*ngIf="false"` to its content, which will to hide it. Angular will remove theitem content and will destroy its content. This is the default behavior of the built-in ngIf directive.

With that being said, we are left with the approach where the component receives its state from outside and emits any change in order to persist that state, again, outside the custom component. I am afraid that there is no other workaround in this, because of the default *ngIf behavior.

**Comment by RonnyRen** [comment] 2018-01-19 23:27
@ggkrustev 
Thanks for your explanation. I doubt why the content in the old item does not destroy when collapse, it also use *ngIf directive (see the new demo (https://plnkr.co/edit/G428c6lKJDdVz1uITmL7?p=preview). The difference is that the new item is added later, the old item display by default. Could you please help me explain why they have the different behavior?

**Comment by RonnyRen** [comment] 2018-01-22 01:52
@ggkrustev 
I saw you reopened this issue, and I am glad to write a correct demo to show my problem clearly. Thanks you for your time that view my demo and understand my problem. It seems as a bug, right? Is there any plan to fix it?

**Comment by ggkrustev** [comment] 2018-01-22 11:12
@RonnyRen 
Yep, I messed this one up. The repro demo you've shared shows the limitation clearly. The `keepItemContent` option is not reflected when PanelBarItem component is added dynamically using `*ngIf` structure directive.

We found the cause and will release a fix soon. I'll update the thread once the DEV release is out.

Thanks for the continuous involvement and persistence in this bug report.

**Comment by RonnyRen** [comment] 2018-02-09 02:37
@ggkrustev 
Is there any progress about this bug?

**Comment by tsvetomir** [comment] 2018-02-09 10:14
The fix is available in the latest [development build](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/), version v2.0.1-dev.201802090750

**Comment by tsvetomir** [comment] 2018-02-27 11:54
Version 2.0.1 has been released in the "latest" channel.

**Closed by tsvetomir** 2018-02-27 11:54 UTC
Labels: Bug, Passed-QA, pkg:layout
