### ISSUE TITLE
Issue with Navigation in angular kendo grid?

### ISSUE THREAD

**Issue by snspvd** [telerik/kendo-angular#1478] opened 2018-04-21 14:01 UTC
Tab/Shift+Tab navigation is not working in grid. please look into below plunker to get my issue.
https://plnkr.co/edit/4Bp5k9XPhDMqlpXD5yxI?p=preview

**Comment by tsvetomir** [comment] 2018-04-24 06:43
Looks like a duplicate of #1479

**Comment by Raisolution** [comment] 2018-05-01 08:14
Closing this as a duplicate of #1479.

**Closed by Raisolution** 2018-05-01 08:14 UTC
Labels: Duplicate, Question, pkg:grid
