### ISSUE TITLE
Horizontal scroll jump from left to right when click cell to edit mode

### ISSUE THREAD

**Issue by AdamTur** [telerik/kendo-angular#2447] opened 2019-08-27 08:16 UTC
### Describe the bug
Problem is with kendo-grid for angular when we have many columns (horizontal scroll  in grid is active).

Click on the last cell in row to enable edit mode (only part of cell is visible).

![image](https://user-images.githubusercontent.com/53558224/62278585-aa573e00-b448-11e9-9400-d80b8e52fb93.png)

After that scroll with whole grid quickly go to the left and after that return to good scroll position.
After that we can click on random cells to enable edit mode and we have the same problem.
 
### Enviroment
IE 11

### Expected behavior
After enable edit mode in cell, scroll cannot jump to the start position and return, but must have  the same behaviour like in other browsers. Also cell (only part of cell is visible) in edit mode have to be whole visible after click.

**Comment by AdamTur** [comment] 2019-08-27 08:31
This issue have high priority. My client wants to have resolved this problem as soon as it possible.

**Comment by danielkaradachki** [comment] 2019-08-27 10:37
Which version are you using? There was a similar [issue](https://github.com/telerik/kendo-angular/issues/2049) that should already fixed in the latest version. If you are using the latest version, then please provide a runnable sample that demonstrates the problem.

**Comment by AdamTur** [comment] 2019-08-29 06:27
I'm using version 3.13.1. The problem here is not moving the column to the right after entering the edit mode. The problem is the visible shift of the scroll first to the maximum to the left and then the shift to a correctly calculated position.

**Comment by danielkaradachki** [comment] 2019-10-11 07:22
Closing due to inactivity. Will reopen the issue once a runnable example that demonstrates it is available, assuming that the problem is different than the one described in the linked issue.

**Closed by danielkaradachki** 2019-10-11 07:22 UTC
Labels: pkg:grid
