### ISSUE TITLE
Numerictextbox crashes IE when default value is null and focus is lost quickly

### ISSUE THREAD

**Issue by ISSTJ** [telerik/kendo-angular#964] opened 2017-10-03 11:20 UTC
## I'm submitting a...
* Bug report

## Current behavior
If you tab through kendo-numerictextboxes in IE11, with a default valud of NULL, IE crashes.

## Expected behavior
Browser should not crash

## Minimal reproduction of the problem with instructions
1. Open http://plnkr.co/edit/6JOwV46Kjk1WrEPxtjgY?p=info in IE
2. Click Run
3. Click into the first numeric textbox
4. Tab quickly through the numeric boxes

--> Crash

## Environment
Latest version of Angular and Kendo UI

Browser:
- IE version 11

System:
- Platform:  Windows

**Comment by danielkaradachki** [comment] 2017-10-05 13:44
Seems to be fixed in the latest version. Could you check if the problem can still be reproduced in the provided plunker?

**Comment by SoulTransfer** [comment] 2017-10-07 16:15
Is fixed
Plunker no longer crashes in IE.

**Comment by ipeshev** [comment] 2017-10-09 11:18
Fixed in v1.3.1

**Closed by ipeshev** 2017-10-09 11:18 UTC
Labels: Bug, Passed-QA, pkg:inputs
