### ISSUE TITLE
Switch input handle not animating to the right when switched to true

### ISSUE THREAD

**Issue by grahamhency** [telerik/kendo-angular#1595] opened 2018-06-06 16:04 UTC
## I'm submitting a...
* Bug report

## Current behavior
  * The k-switch-handle does not animate from left to right when true, see plunk taken from docs and just updated the theme url to Material theme

## Expected behavior
When toggled 'on' the handle should slide to the right with appropriate animation.

## Reproduction of the problem
Plunker: https://plnkr.co/edit/7bsgNTU8f5x0sAvqrNLf?p=preview

**Comment by grahamhency** [comment] 2018-06-06 16:28
I actually wrote a quick fix for this.

In `kendo-theme-material/scss/switch/_layout.scss` I added the lines:

```
&.k-switch-on{
    .k-switch-handle{
        left: $switch-container-size;
    }
}
```

At the end, but within the .k-switch class. Full code for _layout.scss below:

```
$switch-size: 3em !default;
$switch-handle-size: (.4 * $switch-size * 2) !default;

@import "../../modules/@progress/kendo-theme-default/scss/switch/layout";

@include exports('switch/layout/material') {
    $switch-container-size: $switch-size / 2 !default;

    .k-switch {
        overflow: visible;

        .k-switch-container {
            height: $switch-container-size;
        }

        .k-switch-handle {
            background-clip: border-box;
            position: relative;
            top: -$switch-container-size / 2;
            left: -$switch-container-size;
        }

        .k-switch-label-on,
        .k-switch-label-off {
            display: none;
        }

        &.k-switch-on{
            .k-switch-handle{
                left: $switch-container-size;
            }
        }
    }
}
```

**Comment by danielkaradachki** [comment] 2018-06-07 05:39
Hi,

This is a known problem that we are currently working on. Will close this issue as duplicate of https://github.com/telerik/kendo-angular/issues/1577

**Closed by danielkaradachki** 2018-06-07 05:39 UTC
Labels: Duplicate, pkg:inputs
