### ISSUE TITLE
TreeView Click Handler Broken After Collapsing/Expanding Tree Node (2.3.1 doesn't work, works in 2.3.0)

### ISSUE THREAD

**Issue by johnhamm** [telerik/kendo-angular#1827] opened 2018-10-04 15:02 UTC
## I'm submitting a...
* Bug report

## Current behavior
Exception is thrown when selecting a node that has previously been collapsed.  The same code works in 2.3.0 but does not after upgrading to 2.3.1.

## Expected behavior
I expect a node to be able to be collapsed then expanded.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gpaaue-4qpmch

1. Click "Furniture" node (this will programatically expand the node)
2. Click "Furniture" node again (this will programatically collapse the node)
3. Click "Furniture" node again (this will throw an exception in the TreeView's mapChildren method)
4.  _(optional)_ Change "@progress/kendo-angular-treeview" to "2.3.0" in the package.json file
5. _(optional)_ Try steps 1-3 again.  No exception is thrown and the code works again.

## Environment

Package versions:
- Reproducible on TreeView demo

Browser:

- Chrome (desktop) version 68.0.3440.106 (Official Build) (64-bit)

System:
- Reproducible on Stackblitz

**Comment by danielkaradachki** [comment] 2018-10-05 04:53
The issue is the same one as the one described [here](https://github.com/telerik/kendo-angular/issues/1821). It is already fixed in version 2.3.2:
https://stackblitz.com/edit/angular-gpaaue-tv1wbn?file=app/app.component.ts

**Closed by danielkaradachki** 2018-10-05 04:53 UTC
Labels: Bug, Duplicate, pkg:treeview
