### ISSUE TITLE
 filter button is out of position in IE and Edge

### ISSUE THREAD

**Issue by nanana73** [telerik/kendo-angular#1222] opened 2018-01-16 10:01 UTC
Hi Team, I think I found a bug.
Filter button is out of position in IE and Edge.

[Basics - Grid Filtering - Kendo UI for Angular](https://telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/)
## Current behavior

(IE, Edge)
![current](https://user-images.githubusercontent.com/2003150/34982718-96bbec5c-faee-11e7-8ba4-fe76c893e4f0.png)

## Expected behavior

(latest chrome)
![expected](https://user-images.githubusercontent.com/2003150/34982741-a8b2cbec-faee-11e7-83b6-2eac9740c582.png)

## Environment
Browser:
- IE version 11
- Edge version 41.16299.15.0

System:
- TypeScript version: 2.4.2
- Node version: node 6.9.1, npm 3.9.0
- Platform:  Windows

**Comment by dtopalov** [comment] 2018-01-17 20:03
Duplicate of [https://github.com/telerik/kendo-theme-default/issues/834](https://github.com/telerik/kendo-theme-default/issues/834)

**Closed** 2018-01-22 15:26 UTC
Labels: Bug, Styling, pkg:grid
