### ISSUE TITLE
Bug: Dialog Service doesn't give keyboard focus to dialog on open.

### ISSUE THREAD

**Issue by talynone** [telerik/kendo-angular#800] opened 2017-08-05 12:51 UTC
## I'm submitting a...

* Bug report 

## Current behavior

When a dialog is opened by the dialog service the last focused element under the dialog retains focus.

## Expected behavior

The default button defined on the dialog opened by the dialog service should have focus when the dialog is opened.

## Minimal reproduction of the problem with instructions

1.) Go here: http://www.telerik.com/kendo-angular-ui/components/dialog/service/
2.) Press the "OPEN AS PLUNKER" button under the first usage example.
3.) In Plunker on the right-side output frame press the "Please confirm" button.
4.) Once the dialog is open, press enter on the keyboard repeatedly and you'll see the dialog open over and over again as the button under the dialog window has focus as pressing enter executes it. 
## What is the motivation or use case for changing the behavior?

Save developer from having to write fix it code to deal with duplicate open dialog calls. 

## Environment

Browser:

- Chrome (desktop) version 59.0.3071.115 (Official Build) (64-bit)

System:
- TypeScript version: 2.4.2 
- Node version: v6.11.0 
- NPM version: v5.2.0
- Platform:  Windows

**Comment by gyoshev** [comment] 2017-08-07 08:18
Thank you for the feedback. The issue is quite frustrating. This is likely to land along with the keyboard support feature from #530.

**Comment by gyoshev** [comment] 2017-11-09 09:55
A more elaborate workaround is to wrap the `DialogService` in a custom service that remembers the last focused element, and returns focus to it once the dialog closes. This can be seen in [this plunker snippet](http://plnkr.co/edit/pqiuqlgowIfaDWUnOYiK?p=preview).

This is likely to be the behavior provided by the component, once keyboard support has been implemented.

**Comment by Raisolution** [comment] 2018-03-09 14:59
This has been fixed with the introduction of Dialog keyboard support in v3.2.0

**Closed by Raisolution** 2018-03-09 14:59 UTC
Labels: Enhancement, pkg:dialog
