### ISSUE TITLE
[Menu] Clicking a menu item causes a selection of the whole page content

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2600] opened 2019-11-18 11:30 UTC
**Describe the bug**
Using the Menu component, when clicking a sub-menu item and then a top level menu item, the content on the page gets selected by moving the cursor (without dragging).

**To Reproduce**
Please check the following example using Edge version 44:
https://stackblitz.com/edit/angular-ktn4li-qdadd3?file=app/app.component.ts

1. Hover "Item2" and click on any of its children.
2. Click on any of the top level menu items.
3. Move the mouse over the Grid and see how the content on the page is selected.

**Browser**
 - Browser: Edge version 44 (the issue isn't reproduced in lower versions)

**Comment by elena-gancheva** [comment] 2020-06-16 11:48
The issue is caused by a bug in Edge v 44. It isn't present in the latest versions of Edge 82 or 83. We are closing this issue as the Angular framework supports the 2 most recent major Edge versions:
https://angular.io/guide/browser-support

**Closed by elena-gancheva** 2020-06-16 11:48 UTC
Labels: Bug, Team2, freq2: possible, pkg:menu, sev2: medium
