### ISSUE TITLE
Error in the selected slot in kendo scheduler in all scheduler version for the day of day light saving change 

### ISSUE THREAD

**Issue by notRohitT** [telerik/kendo-angular#4237] opened 2024-03-01 17:15 UTC
**Describe the bug**
Error in the selected slot in kendo scheduler in all scheduler version for the day of day light saving change 
**To Reproduce**
Select a US time zone( eastern, central or pacific) select either 10th march or 3rd November 2024 select 3am, 4am or 5am till 2+ offset of the time zone and observe the start and end of slot click event. 

**Expected behavior**
when i click 3am slot i wish the start time to reflect 3 am but it reflects 4 am on 10th march 2024

**Screenshots**
I clicked 3am slot.
![image](https://github.com/telerik/kendo-angular/assets/102506139/4a30bc82-53a0-45f7-97e2-1fd71bb94fdf)

**Browser**
 - OS: Windows
 - Browser chrome
 - Version Version 122.0.6261.95 (Official Build) (64-bit)

**Additional context**
Different for all time zones of US for 2+offest of the time zone. EX for central error observed from 2 am to 8am

**Comment by stnikolova** [comment] 2024-03-18 08:30
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/4242

**Closed by stnikolova** 2024-03-18 08:30 UTC
