### ISSUE TITLE
Combobox Inview Alignment

### ISSUE THREAD

**Issue by alpkarli** [telerik/kendo-angular#2110] opened 2019-03-05 14:05 UTC
### Bug report

Kendo Combobox is not showing correct item if I use service to get value. (Probably it is not related with only service) It acts inconsistent. It doesn't focus first search letter many times and also when I press backspace it doesn't focus correct one either. Align problem is not limited by text length.

### Reproduction of the problem

In example, write "v" in the combobox, then write "a" for reproduction.

https://stackblitz.com/edit/angular-yyafdd-vyvxnj

### Current behavior

Popup doesn't focus and align correct search.

![combo1](https://user-images.githubusercontent.com/28437603/53810729-a17d4180-3f68-11e9-972f-7a9d180cdc50.png)

### Expected/desired behavior

Popup auto scroll to focused item.

![combo2](https://user-images.githubusercontent.com/28437603/53810748-a7732280-3f68-11e9-858a-1ab61d5b7e4f.png)

### Environment

* **Browser:** [all] 

### Related Link

https://github.com/telerik/kendo-ui-core/issues/4603

**Comment by dimitar-pechev** [comment] 2019-03-05 18:05
@alpkarli, I cannot reproduce the described behavior with the provided stackblitz example. Below is a gif with the current behavior from the code snippet when I ran it. 

Perhaps I am missing something? Could you please elaborate?

![667162c7-288b-4a7f-b40d-8ed7a2aa7a33](https://user-images.githubusercontent.com/18740853/53826424-3c821580-3f81-11e9-88a0-c74d4dd6bcf8.GIF)

**Comment by alpkarli** [comment] 2019-03-06 01:19
@dimitar-pechev, If you noticed, I used directive in the stackblitz example. The delay amount is 200ms. Is it possible that the problem caused by the library takes search string before filter changed event? Could you please write fast as on the gif below? I tried it multiple browser and computers, I got same results as below.

![kendo](https://user-images.githubusercontent.com/28437603/53848021-e387a100-3fc3-11e9-811f-a41242fb7f51.gif)

**Comment by dimitar-pechev** [comment] 2019-03-06 18:23
@alpkarli, I see now. I managed to reproduce it and it seems like a nasty race between the internal notification that an item in the data list should be scrolled to and the actual rendering of the item. We'll look to provide a fix for this. Thanks for reporting it.

**Comment by dimitar-pechev** [comment] 2019-06-03 10:46
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (**v3.5.6-dev.201906031029**).

**Comment by dimitar-pechev** [comment] 2019-06-06 12:48
Shipped in **v3.5.6**.

**Closed by dimitar-pechev** 2019-06-06 12:48 UTC
Labels: Bug, Passed-QA, Team1, pkg:dropdowns
