### ISSUE TITLE
TextBox directive causes blur and focus events to fire twice

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1622] opened 2018-06-19 14:31 UTC
[https://plnkr.co/edit/0vAPa7eHFL6VsDJGAKra?p=preview](https://plnkr.co/edit/0vAPa7eHFL6VsDJGAKra?p=preview)

Suggested workaround - debounce the event:

[https://plnkr.co/edit/xMGUKNj2u6Akbn3FQ3IR?p=preview](https://plnkr.co/edit/xMGUKNj2u6Akbn3FQ3IR?p=preview)

**Comment by Jidehem** [comment] 2018-06-22 12:53
Duplicate of #1400

**Comment by Raisolution** [comment] 2018-06-25 07:50
Closing as a duplicate.

**Closed by Raisolution** 2018-06-25 07:50 UTC
Labels: Bug, pkg:inputs
