### ISSUE TITLE
DropdownList loses its value by submitting in reactive form after filtering.

### ISSUE THREAD

**Issue by eastjie** [telerik/kendo-angular#1908] opened 2018-11-12 11:09 UTC
## I'm submitting a...
* Bug report  

## Current behavior
We have used Dropdown List in reactive form with filtering but the value is not lost by submitting it.
The early bugs https://github.com/telerik/kendo-angular/issues/1629 and https://github.com/telerik/kendo-angular/issues/1377 seems to be fixed, but there seems to be still the problem for the value of Dropdown List.

## Expected behavior
The correct value should be correct in the FormControl by submitting.

## Minimal reproduction of the problem with instructions
The bug can be reproduced in the [example](https://stackblitz.com/edit/angular-rvbryb?file=app/app.component.ts). The console gives always default value, although the user has entered other value by filtering.
 
Thanks very much.

**Comment by dimitar-pechev** [comment] 2018-11-12 12:34
@eastjie Thanks for reporting this problem!

Looks similar to #1104. At first glance it looks like a problem when `filterable` is enabled and a `defaultItem` is set. Your example works as expected without a `defaultItem`. I'll investigate further if there is a separate problem when using reactive forms. 

I'll anyway look to provide a fix shortly for the issues reported in the two threads.

**Comment by eastjie** [comment] 2018-11-12 14:06
Thanks very much for your hint. I have just tried a workaround in the project.
1. delete "defauItem" in HTML;
2. just add the defauItem for "data" in intialization;
3. set it in FormControl by building FormGroup.

It could work first of all ([example](https://stackblitz.com/edit/angular-rvbryb-aalzw5?file=app/app.component.ts)) and seems right that "defaultItem" causes filtered value missing.

**Comment by dimitar-pechev** [comment] 2018-11-23 11:44
@eastjie I investigated your case and I couldn't find an issue related to the usage of reactive forms. The problem is the same as the one described in #1104. The bug caused by the `defaultItem` is resolved in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (**v3.4.1-dev.201811231129**). 

Closing this issue, as the reported bug is tracked in #1104.

**Closed by dimitar-pechev** 2018-11-23 11:44 UTC
Labels: Bug, pkg:dropdowns
