### ISSUE TITLE
Datepicker Alt + Up shortcut does not work

### ISSUE THREAD

**Issue by cphill88** [telerik/kendo-angular#766] opened 2017-07-24 15:31 UTC
The demo of the component says that Alt + Up will close the calendar pop up but it does not on the demo or in my environment when I use the component.

http://plnkr.co/edit/sTzgJFL7LnkdZdYXIP3J?p=preview

**Comment by ggkrustev** [comment] 2017-07-25 07:01
Indeed, the component won't close using 'Alt+UP' combination when the Calendar component is focused.

Once the issue is fixed, we will update the issue. Thanks for reporting the bug.

**Comment by ggkrustev** [comment] 2017-11-01 09:56
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment] 2017-11-13 14:54
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.

**Closed by ggkrustev** 2017-11-13 14:54 UTC
Labels: Bug, Passed-QA, pkg:date-inputs
