### ISSUE TITLE
[Ripple] Ripple effect not working/showing as expected in Checkboxes and Radio buttons

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3664] opened 2022-04-29 02:51 UTC
**Describe the bug**
1. Ripple doesn't appear at all for checkboxes with any theme
2. Ripple appears in wrong place for radio buttons with Default and Bootstrap themes
3. Ripple doesn't appear at all for radio buttons with Material theme

**To Reproduce**

Run the StackBlitz example in the [Kendo UI Ripple Overview page](https://www.telerik.com/kendo-angular-ui/components/ripple/).

Refer private support ticket: **1563033**

**Comment by svetq** [comment] 2022-04-29 07:18
This issue is caused by a bug in the Kendo themes. Thus I will proceed with closing it in favor of https://github.com/telerik/kendo-themes/issues/3568

**Closed by svetq** 2022-04-29 07:18 UTC
