### ISSUE TITLE
[DropDowns] don't open their popups when spacebar is pressed

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3191] opened 2021-01-28 09:26 UTC
**Describe the bug**
Currently the DropDown components don't open their popups if they are focused and the spacebar is pressed. The opening of the popup is achieved by pressing alt + arrowDown. As the HTML5 select element opens on spacebar, that would be expected to function for the Kendo DropDown components as well.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-bscjhu?file=app/app.component.ts

**Comment by dlwhiteman5** [comment] 2021-01-28 15:40
This should actually be marked as a bug, since it is a regression from Kendo for jQuery.  Go to the example here and you can see that the spacebar does cause the dropdown to open its popup: [https://demos.telerik.com/kendo-ui/dropdownlist/index]

**Comment by dlwhiteman5** [comment] 2022-10-13 18:39
Can we please get this implemented? This is an important accessibility feature.

**Comment by yanmariomenev** [comment] 2023-07-19 13:30
The issue is moved to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1616817-dropdowns-spacebar-press-should-open-the-popup-of-the-component

Feel free to cast your vote. Our team will create a knowledge base article on this matter until the feature request is approved.

**Closed by yanmariomenev** 2023-07-19 13:30 UTC
Labels: Enhancement, pkg:dropdowns, Team1
