### ISSUE TITLE
[TimePicker]: Does not switch to next segment when value with leading zero is typed. 

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#1108] opened 2017-11-24 10:52 UTC
## I'm submitting a...
* Bug report

## Current behavior
DateInput allows leading zeros input, but doesn't switch to the next segment when current section is fulfilled ('01' is typed).

## Expected behavior
Move to next segment when segment length is fulfilled. 

## Minimal reproduction of the problem with instructions
1. Run http://plnkr.co/edit/nCPHAnchot2fr4tYAPum?p=preview
2. Focus the TimePicker
3. Type '013'

The output should be '01:03', but the end value is '13:30'.

## What is the motivation or use case for changing the behavior?
Allow consistent value input while typing fast.

## Environment

Package versions:
```
├── @angular/animations@4.4.6
├── @angular/common@4.4.6
├── @angular/compiler@4.4.6
├── @angular/compiler-cli@4.4.6
├── @angular/core@4.4.6
├── @angular/forms@4.4.6
├── @angular/http@4.4.6
├── @angular/platform-browser@4.4.6
├── @angular/platform-browser-dynamic@4.4.6
├── @angular/platform-server@4.4.6
├── @krux/condition-jenkins@1.0.1
├── @progress/kendo-angular-intl@1.3.0
├── @progress/kendo-angular-l10n@1.0.5
├── @progress/kendo-angular-popup@1.3.0
├── @progress/kendo-angular-tasks@9.1.32
├── @progress/kendo-date-math@1.1.0
├── @progress/kendo-theme-default@2.45.0
├── @telerik/semantic-prerelease@1.2.1
├── @types/core-js@0.9.35
├── @types/jasmine@2.2.34
├── @types/selenium-webdriver@2.53.33
├── @types/zone.js@0.0.27
├── cldr-data@30.0.4
├── codelyzer@3.2.2
├── core-js@2.5.1
├── cz-conventional-changelog@1.2.0
├── ghooks@1.3.2
├── gulp@3.9.1
├── protractor@4.0.9
├── rxjs@5.5.2
├── semantic-release@6.3.6
├── tslib@1.8.0
├── tslint@5.8.0
├── typescript@2.3.4
├── validate-commit-msg@1.3.0
├── webdriver-manager@10.2.5
└── zone.js@0.8.12
```

Browser: All

System:
- TypeScript version: ^2.3
- Node version: ^6.x.x
- Platform:  All

Reported in TicketID: 1141859, Ticket ID: 1157010

**Comment by munnaonc** [comment] 2017-11-27 05:34
Hi Georgi Krustev,

There are some other scenarios that also I failed to mention in the original issue. For instance, if the user is trying to type "00:30" which is essentially half an hour, on in a date format half past midnight. 

When the user enters "00" the focus does not move to the minute portion. The user has to explicitly press a tab to move the focus to type the minute portion. 

In my opinion, this is not a show stopper. But for the power users who are keyboard ninja will start bragging about why it is not working.

Thanks,

**Comment by munnaonc** [comment] 2017-12-19 01:13
Hi,
I was just wondering any probable fix planned or not.
Thanks

**Comment by ggkrustev** [comment] 2017-12-19 08:13
Hi @munnaonc, we still don't have ETA for this issue. Nevertheless, it should be fixed with the next batch fixes for the DateInputs early next year.

**Comment by munnaonc** [comment] 2018-01-08 00:56
Correction on the steps.
> The output should be '01:03', but the end value is '13:30'.
The output should be "01:30", that is one hour 30 min.
Thanks.

**Comment by munnaonc** [comment] 2018-01-16 06:24
Hi,
Hope this finds everyone well. Any update on this issue? 
Thanks.

**Comment by ggkrustev** [comment] 2018-01-16 08:04
We haven't work on this yet. We will update the thread once there is a fix.

**Comment by munnaonc** [comment] 2018-03-04 22:39
Hi. 
I would appreciate if there is an update on this. The issue is reported almost 3 months ago, is there any milestone for this one?

**Comment by ggkrustev** [comment] 2018-03-05 08:33
@munnaonc, we haven't planned anything for now. We are working on tasks related to DateInputs with higher priorities right now. 

Please note that we addressed many of the bugs that had high priority in the last DEV release. This one will addressed with the next batch of fixes, which will be either at the end of this month of the beginning of the next.

**Comment by munnaonc** [comment] 2018-03-25 22:56
Any update?

**Comment by munnaonc** [comment] 2018-04-30 22:28
Any milestone or update on this issue, please!

**Comment by ggkrustev** [comment] 2018-05-07 12:08
Hi @munnaonc, I'd like to inform you that we were able to address the issue. The fix will be available in the DEV channel till the end of the week. I'll update the thread once it is available.

**Comment by munnaonc** [comment] 2018-05-08 02:54
Thanks for the update. 
Whan is the next scheduled production release?

**Comment by ggkrustev** [comment] 2018-05-14 10:45
@munnaonc, the latest DEV release includes includes the fixes. Check `v3.3.0-dev.201805141027` or just run `npm install @progress/kendo-angular-dateinputs@dev` command.

The dev branch should be pushed to production within few days. It will be great if you can check the DEV release before it is pushed to production.

**Comment by munnaonc** [comment] 2018-05-22 23:21
Installed the latest version. And the feature seems to be working.
Thanks.

**Comment by munnaonc** [comment] 2018-05-22 23:21
You can close this issue.
Thanks.

**Comment by JasonChenLogibec** [comment] 2018-08-17 12:30
This is still a problem when using the format "yy/MM/dd" (I'm guessing that it's a problem whenever the short-year format is used and the year segment is not at the end). Demo: https://angular-yjmtq3.stackblitz.io

**Comment by tsvetomir** [comment] 2018-08-21 07:57
Related issue #1203

**Comment by stnikolova** [comment] 2023-06-15 07:41
The TimePicker issue is no longer reproducible https://stackblitz.com/edit/angular-wmvsgq

**Closed by stnikolova** 2023-06-15 07:41 UTC
Labels: Bug, pkg:date-inputs, Team1, sev1: low, freq1: rare
