### ISSUE TITLE
[Editor] Underlying value does not change when used in a reactive form

### ISSUE THREAD

**Issue by aiscrim** [telerik/kendo-angular#2496] opened 2019-09-25 08:55 UTC
**Describe the bug**
Starting from version 0.8.0, if the editor is used in a reactive form, its value is null.
In version 0.7.0 the exact same form was working correctly.

**To Reproduce**

Initialize the editor with any value.
Change the content of the editor.
When you check the value, it's still the initial one.

[https://8t32hw.run.stackblitz.io/](https://8t32hw.run.stackblitz.io/)

**Expected behavior**
The value should change when the editor content changes.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.100

**Comment by valchev** [comment] 2019-09-27 16:39
Hi @aiscrim 

Thank you for bringing this to our attention, we'll do our best to provide a fix in a short period of time.

**Comment by valchev** [comment] 2019-10-02 09:26
The issue is fixed in v0.9.0. For more information please follow the discussion in telerik/kendo-angular#2346

**Closed** 2019-10-03 12:02 UTC
Labels: Bug, Team2, pkg:editor
