### ISSUE TITLE
[Grid] last visible row not selected when both keyboard navigation and virtualization are present

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1987] opened 2018-12-17 10:21 UTC
Clicking on the last visible row in a navigable Grid with virtual scrolling scrolls the Grid and does not select the clicked row:

[https://stackblitz.com/edit/gridselectionbug](https://stackblitz.com/edit/gridselectionbug) (click 11)

Selection is working as expected when **navigable** is not set:

[https://stackblitz.com/edit/gridselectionbug-jrshap?file=app%2Fapp.component.ts](https://stackblitz.com/edit/gridselectionbug-jrshap?file=app%2Fapp.component.ts)

**Comment by Raisolution** [comment] 2021-11-22 11:03
Closing this issue, as the problem is not reproducing in latest Grid version.

**Closed by Raisolution** 2021-11-22 11:03 UTC
Labels: Bug, pkg:grid, Team2, sev1: low, freq1: rare

**Comment by mbechev** [comment] 2023-01-30 14:13
I am reopening this issue, as it's still reproducable in the latest version of the Grid:
Grid -v11.0.0
Angular - v13

Try clicking 11 row. The Grid is scrolled instead selected:
https://stackblitz.com/edit/angular-ylhwaj

**Comment by zachary22321** [comment] 2023-02-06 20:04
[unwanted scrolling.zip](https://github.com/telerik/kendo-angular/files/10668720/unwanted.scrolling.zip)
I believe that I"m having the same problem. I click on a. row and it scrolls downward instead of firing the cell clicked event. I just wanted to add this video, in case it helps. Once it happens the scrolling is no longer correct. If you jump to the 40 second mark of the video i am trying to scroll up and you can see it continuously scrolling downward.  Would it be possible to install an early p review of the fix on my side to see if it works ahead of the general release? I had some trouble creating a sample project, but I could test it in the main project.
