### ISSUE TITLE
[Upload] Remove event not firing for non multiple uploads

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3576] opened 2022-02-04 10:23 UTC
**Describe the bug**
When the component has `multiple = false`. This means only one file is allowed.

Given one file is already selected, and then we replace that file - it should fire off the remove event (thus calling removeUrl) for the first file.

This happens when the user explicitly removes the files and then adds another one. I believe the same behaviour should be the same.

**To Reproduce**

https://stackblitz.com/edit/angular-ywawvf-4nqy1l?file=app/upload.component.ts

* Upload file
* Upload another file

**Expected behavior**
Remove event for the first file to trigger

**Screenshots**

First screenshot shows replacing
![image](https://user-images.githubusercontent.com/13205912/152512661-fee28ede-e143-4767-b294-ab017efaa4f6.png)

Second screenshot showing remove and add
![image](https://user-images.githubusercontent.com/13205912/152512788-c339d7e8-6343-4338-8b66-e127579e778a.png)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by Raisolution** [comment] 2022-02-14 13:11
Hi @cheng93 ,

The described behavior is by design - `remove` event will be emitted and a request to the `removeUrl` will be initiated only when the user explicitly clicks on the remove file button. This is not the case in the current scenario.

In the current setup, the developer is aware that the Upload component is configured as `multiple="false"`, thus if additional logic is needed on file select (e.g. removal of previously selected file), he could adjust the application code accordingly.

**Closed by Raisolution** 2022-02-14 13:11 UTC
Labels: Invalid, pkg:upload, Team2
