### ISSUE TITLE
[Grid] Virtual Scrolled Grid is unselectable inside kendo dialog

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#789] opened 2017-07-31 07:47 UTC
## I'm submitting an issue
I am using Kendo Grid inside a Kendo Dialog,
This Kendo Grid is using virtual scrolling, and pagesize is 10.

Steps to reproduce:

1. Open this kendo dialog
2. Select items in kendo grid, at the this time, items can be selected.
3. Then scroll down the items,  try to select an item, you will see nothing is selected.

## Current behavior
Grid is unselectable when you scroll down when using virtual scrolling,

## Expected behavior
Grid should always be able to select items if it has any.

After debugging several times, I figure out this maybe a bug related to z-index.
I try to change the styles like below:

    .k-grid-virtual .k-grid-content > .k-height-container {
        position: absolute;
        z-index: 10000;
    }

It works, but grid's layout is broken.  

BTW, I am using kendo-grid 1.2.3 and kendo-dialog 1.0.0.

Any ideas on this issue?

**Comment by zhao125787935** [comment] 2017-08-04 08:20
Hi kendo team,  any updates?

**Comment by zhao125787935** [comment] 2017-08-11 08:58
Any updates from you guys ?

**Comment by ggkrustev** [comment] 2017-08-11 10:55
Hi @zhao125787935, please excuse us for the delayed reply.

I reviewed the bug report and tried to replicate the issue locally, but to no avail. This demo works just fine, testing it in Chrome:

http://plnkr.co/edit/pPh6g3rWBC0ZhMYwFFQ5?p=preview
The selection + virtualization work as expected.

Could you modify the plunkr and demonstrate the erroneous behavior?

**Comment by Raisolution** [comment] 2017-09-06 13:58
I am closing this as we were unable to reproduce the problem with the new Grid selection.

**Closed by Raisolution** 2017-09-06 13:58 UTC
Labels: pkg:grid
