### ISSUE TITLE
Date picker. Impossible to enter from keyboard date or month with one digit

### ISSUE THREAD

**Issue by IAfanasov** [telerik/kendo-angular#1039] opened 2017-10-25 08:52 UTC
## I'm submitting a...

* Bug report 
could be related to  #1034 

## Current behavior
open dateinput sample https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/
focus on input
from keyboard type 01021234
result date is 10/21/234
![image](https://user-images.githubusercontent.com/10142653/31989199-ce57981c-b99b-11e7-9fb2-c0ba38fa58ea.png)

## Expected behavior
result date should be 01/02/1234

## Minimal reproduction of the problem with instructions
Reproducing steps above are enough

## What is the motivation or use case for changing the behavior?
Obvious bug

## Environment

Browser:

- Chrome (iOS) version 61.0.3163.100 (Official Build) (64-bit)

**Comment by ggkrustev** [comment] 2017-10-25 09:07
This is a known limitation, which was mentioned in this Github issue: https://github.com/telerik/kendo-angular/issues/910

We will update the other thread once the issue is resolved.

Will close this one as duplicate.

**Closed by ggkrustev** 2017-10-25 09:07 UTC
