### ISSUE TITLE
[Treelist] Wrong behavior of "select all" checkbox 

### ISSUE THREAD

**Issue by MoheshChandran** [telerik/kendo-angular#3423] opened 2021-09-01 08:33 UTC
Select all checkbox provided in tree list module is not working as expected. Below are the detailed step to reproduce

**To Reproduce**

**Scenario 1 :** 
1. Checked on select all checkbox
2. Unchecked any of the row, the select all checkbox still checked.

**Scenario 2 with pagination:**
1. Checked on select all checkbox
2. Move to next page
3.  Select all checkbox is checked, but the rows is not selected

**Scenario 3:**
1. Checked on select all checkbox
2. Expand the parent node, the child node is not checked

**Expected behavior**
**Scenario 1:**
The select all checkbox should be unchecked. Same as what provided in [Grid module](https://www.telerik.com/kendo-angular-ui/components/grid/selection/row-selection/#toc-select-all-checkbox)
**Scenario 2:**
The select all checkbox should be unchecked
**Scenario 3:** 
The child node need to be checked

**Comment by yanmariomenev** [comment] 2021-09-08 08:56
Closing this issue as a duplicate of #3080

**Closed by yanmariomenev** 2021-09-08 08:56 UTC
Labels: Team2, pkg:treelist
