### ISSUE TITLE
Space not preserved in currency/percentage pattern when loading CDLR data with Intl

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#1109] opened 2017-11-24 13:04 UTC
## I'm submitting a...
* Bug report 

## Current behavior
The kendo-angular-intl does not preserve space when calculating the pattern for currency and percentage when loading CDLR data with the load function. When my CDLR data contains: { numbers: { "currencyFormats-numberSystem-latn": { standard: "¤ #,##0.00" } }}, the currency pattern is set to ["$n"]

## Expected behavior
I expect the currency pattern to be set to ["$ n"] (so preserving the space).

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/oFFGEFPcmpMbXcERqAkk?p=preview

## What is the motivation or use case for changing the behavior?
Better output

**Comment by danielkaradachki** [comment] 2017-11-24 13:29
Indeed, seems that spaces are not interpreted correctly. The default locales use non-breaking space character so their pattern is correct. Until the issue is fixed I can suggest the same:
http://plnkr.co/edit/8ZE2li8M2CpitKHBeCqD?p=preview

**Comment by JaapMosselman** [comment] 2017-11-24 14:36
Thanks, that is a good workaround for the time being.

**Comment by ipeshev** [comment] 2017-12-18 15:01
Fixed in v1.3.1

**Closed by ipeshev** 2017-12-18 15:01 UTC
Labels: Bug, Passed-QA, pkg:intl
