### ISSUE TITLE
Kendo multiselect  dropdown list scrolls to top

### ISSUE THREAD

**Issue by daniloacim** [telerik/kendo-angular#1953] opened 2018-11-27 17:41 UTC
## I'm submitting a...

* Bug report about kendo multiselect dropdown list

## Current behavior
If have scroller then try to scroll down and select an item further down the list, it doesn't select and pops you back to the top of the list

## Expected behavior

It should select item not to scroll to the top
## Minimal reproduction of the problem with instructions

Similar to the case in the example:
https://plnkr.co/edit/dKHILUdPFB383jln5cYM?p=preview
## Environment

Package versions:

![problem](https://user-images.githubusercontent.com/24303759/49100173-91700a80-f273-11e8-97a5-78f45fe84cb5.PNG)

Browser:

- Chrome (desktop)
- Firefox
- IE

System:
- Node version: v8.9.4  
- Platform: Windows

**Comment by dimitar-pechev** [comment] 2018-11-28 08:33
@daniloacim Thanks for your input!

It seems, however, that this is not a bug but a problem with the configuration of the component.

```
<kendo-dropdownlist [data]="listItems()">

/* ... */

public listItems(): Array<number> { return  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]; }
```

As you are binding the component data to a function, the latter will produce a new array on every change detection cycle (even though the primitive data values are the same, the array reference is not), which results in constant recreation of the options dropdown. And that can cause all sorts of unpredictable behavior, not just problems with the selection - you can also notice the keyboard navigation is not working in your example.

However, as mentioned earlier, this is not considered a bug. The component is not designed to work in such a way, as constantly changing the data would result in bad and laggy performance especially in slower browsers or when the data list has a few hundered items or more. 

If you need to always show up-to-date data, you should change/fetch your data only on certain events and user interactions - e.g. when the list is getting opened. Refer to [this example](https://stackblitz.com/edit/angular-rp6aob). 

If you need further assistance with how to setup your component for a specific and unusual scenario, I'll encourage you to open a support ticket.

**Comment by daniloacim** [comment] 2018-11-28 08:59
Thanks for your response!

Maybe I should open support ticket, what's the process?

**Comment by daniloacim** [comment] 2018-11-28 09:11
@dimitar-pechev Thanks for your response!

I've changed from function to array but still getting the same issue.
When click on any item further down the list it scrolls to the top except already have anything selected then works correctly. But if there is no any item selected it won't work well.

![kendo](https://user-images.githubusercontent.com/24303759/49140888-abeac800-f2f5-11e8-9fdf-1650619f0554.PNG)

**Comment by dimitar-pechev** [comment] 2018-11-28 09:31
@daniloacim You can sibmit a support ticket from your [account page](https://www.telerik.com/account/support-tickets).

If you could share more code about the **MultiSelect**, I will investigate the case. A full runnable example, like the one you provided about the **DropDownList** would be best, as just the mark-up gives you only half the picture.

**Comment by daniloacim** [comment] 2018-11-29 11:14
Posting modified version from Kendo example so you can notice the same issue.
https://stackblitz.com/edit/angular-aufcdc?embed=1&file=src/index.html

**Comment by dimitar-pechev** [comment] 2018-11-30 13:54
@daniloacim The problem is similar to the one in your previous example: you are binding the **MultiSelect** component value to a function which produces a new array instance on every change detection cycle. Which triggers an internal state reset of the component.

I noticed, however, that this is a simplified version of an example in our docs about custom filters. Also, this behavior was supported in previous versions of the component (binding the value to a function that returns a new array). So, in the upcoming days we'll look either to include a fix to support this behavior, or we'll just change the demo with a correct approach for setting the value, as in principle it's not needed to reset the value every time change detection is run.

In the meantime you can refer to [this example](https://stackblitz.com/edit/angular-azgzmd) that supports the desired behavior. In it the **MultiSelect** initial value is assigned only once when the component is created via a custom directive. According to your needs, you could alternatively wrap the **MultiSelect** in a component instead of using a directive - it would work all the same.

**Comment by daniloacim** [comment] 2018-11-30 14:14
@dimitar-pechev Changed it to static list but still not working.
Please check it https://stackblitz.com/edit/angular-aufcdc.

**Comment by dimitar-pechev** [comment] 2018-12-03 11:01
@daniloacim As mentioned in my previous comment, the issue in your case is coming from binding the **value** to a function that returns a new array, not the **data**.

The provided [example](https://stackblitz.com/edit/angular-azgzmd) contains a possible solution to your issue. Please review it. If it doesn't solve your problem, I suggest you open a support ticket, where you could get help for your specific implementation.

**Comment by daniloacim** [comment] 2018-12-03 11:22
Yes, you are right. Thought to the data instead of value.
The example you've sent to me is working. 

Thank you very much!

**Comment by dimitar-pechev** [comment] 2018-12-03 11:44
Glad I could help!
Closing the issue now.

**Closed by dimitar-pechev** 2018-12-03 11:44 UTC
Labels: Question, pkg:dropdowns

**Comment by Dror-Bar** [comment] 2019-05-19 09:03
Thanks, this thread helped me solve my issue.
