### ISSUE TITLE
Grid: Cancel selection event approach

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#863] opened 2017-08-30 14:48 UTC
I'm testing new selection api of latest grid version (great work!!!!)

I have to find a way to cancel selection where row has special property for example:

http://plnkr.co/edit/mFTg08iJyxAbyMmOpHml?p=preview

I have implemented method:

```
 public gridSelectionChange(selectionEvent: SelectionEvent) {
        if (selectionEvent.selected) {
            let selectedResult = this.gridData[selectionEvent.index];
            if (selectedResult.UnitsInStock > 0) {
                // Ok selection permitted
            } else {
                selectionEvent.selectedRows = selectionEvent.deselectedRows;
                selectionEvent.deselectedRows = [];
            }
        }
    }
```

As you can see when `UnitsInStock ` is zero i just swap selection and deselection array.
Is it a correct approach? what do you think?

Thanks.

**Comment by meriturva** [comment] 2017-08-30 14:57
I found that if i assign with `rowClass ` callback class `k-state-disabled` to row selection is disabled. am i right?

**Comment by Raisolution** [comment] 2017-08-30 15:27
Hi @meriturva,

I would recommend another approach for scenarios like the current one. You could utilize the `rowSelected` property of the Grid and override the built in function that decides which row should be selected. Basically you could include the `UnitsInStock > 0` condition in this custom function. Here is an [example of this](http://plnkr.co/edit/oGfd61OKl1FfMmuVDgdN?p=preview).

**Comment by meriturva** [comment] 2017-08-31 06:58
@Raisolution actually i have also to show that row is disabled so class `k-state-disabled` and `rowClass` callback will be used for sure. Do you still think that i have to add your solution? so is it necessary that double check?

**Comment by Raisolution** [comment] 2017-09-01 07:01
@meriturva, it's not necessary to implement it as in the example. I just thought this is what you are looking to achieve, without the manual manipulations in the `selectionChange` event.

I will close this issue now, as it is not a bug. Feel free to open it, if you notice anything unexpected.

**Closed by Raisolution** 2017-09-01 07:01 UTC
Labels: pkg:grid, Question
