### ISSUE TITLE
Demo examples don't work on STACKBLITZ

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1813] opened 2018-09-26 11:27 UTC
When you click on the 'OPEN IN STACKBLITZ' link, you get an error on that service. See https://www.telerik.com/kendo-angular-ui/components/dropdowns/
```
Can't find modules:
rxjs/Subject (@6.3.3)
rxjs/operators/auditTime (@6.3.3)

Check your import statements & ensure you're importing the correct module names.
```
Chrome v. 69 was used

**Comment by tsvetomir** [comment] 2018-09-26 12:27
Thanks for reporting. The issue seems to be caused by a missing rxjs version on the unpkg CDN:
https://unpkg.com/rxjs@6.3.3/

The project doesn't reference this version, so there must be some problem with StackBlitz as well.
We're investigating the issue.

**Comment by tsvetomir** [comment] 2018-09-26 12:30
Logged https://github.com/unpkg/unpkg.com/issues/137 with the unpkg team.

**Comment by tsvetomir** [comment] 2018-09-27 07:03
Seems to be fixed with the latest StackBlitz update.

**Closed by tsvetomir** 2018-09-27 07:03 UTC
