### ISSUE TITLE
Shortcut disable bug of kendo

### ISSUE THREAD

**Issue by AmanGhatge** [telerik/kendo-angular#3413] opened 2021-08-20 12:14 UTC
Component
-------------
Kendo editor (https://www.telerik.com/kendo-angular-ui/components/editor/)
Kendo chat (https://www.telerik.com/kendo-angular-ui/components/conversational-ui/)

Functionality
--------------
Used chat module and for input editor module of kendo (links are above). On keydown a function is handled in kendo chat module which will prevent bold functionality of Editor.

Bug
----
On initial load Ctrl + B is working even if we have done e.preventDefault and error is also generated of mismatched transaction (Necessary attachments are below).

Screenshots
-------------
![chat](https://user-images.githubusercontent.com/83629796/130231223-9e04c0b9-830c-4981-8b40-e561e5c438bb.PNG)
![error](https://user-images.githubusercontent.com/83629796/130231229-cbcf27c1-e14f-4574-b747-a683082d7d3f.PNG)

**Comment by yanmariomenev** [comment] 2021-08-20 13:13
Closing this issue as a duplicate of https://github.com/telerik/kendo-angular/issues/3352

**Closed by yanmariomenev** 2021-08-20 13:13 UTC
Labels: Duplicate
