### ISSUE TITLE
dropdownlist will be overlaid within grid

### ISSUE THREAD

**Issue by wenminglee** [telerik/kendo-angular#589] opened 2017-05-26 00:54 UTC
if dropdownlist popup height exceed the grid height, it will be overlaid

![image](https://cloud.githubusercontent.com/assets/25415660/26476370/d0eccc64-41f0-11e7-9958-74032f06d2cc.png)

**Comment by wenminglee** [comment] 2017-05-26 01:04
plnkr:
http://plnkr.co/edit/DIp4cSPZE7BI9gYxf4Iz?p=preview

**Comment by ggkrustev** [comment] 2017-05-26 11:37
Duplicate of this issue - https://github.com/telerik/kendo-angular/issues/410

**Comment by ggkrustev** [comment] 2017-05-26 11:38
Please note that the fix is in the pipeline and after a few more tests will be published live. Probably it will become available next week.

**Closed** 2017-05-26 11:37 UTC
