### ISSUE TITLE
Demo of window dragging does not drag window in current web site demos

### ISSUE THREAD

**Issue by paulsperanza** [telerik/kendo-angular#1300] opened 2018-02-08 14:30 UTC
## I'm submitting a. bug

* Bug report Window demo https://www.telerik.com/kendo-angular-ui/components/dialogs/window/#toc-dragging does npt drag window

## Expected behavior
Window should be draggable

## Minimal reproduction of the problem with instructions
Go to https://www.telerik.com/kendo-angular-ui/components/dialogs/window/#toc-dragging

Try to drag window

## Environment
Windows 10

Browser:

- Chrome desktop Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Raisolution** [comment] 2018-02-08 14:41
Hi @paulsperanza,

thanks for submitting this. The issue has already been fixed and the fix is available in v3.0.1. Later today we will also push a new version of the site, in which the demos will work too.

**Comment by ipeshev** [comment] 2018-02-08 14:41
Duplicate of https://github.com/telerik/kendo-angular/issues/1278

**Closed by Raisolution** 2018-02-08 14:41 UTC
Labels: pkg:dialog
