### ISSUE TITLE
Provide better solution for graphs in hidden parent 

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#1528] opened 2018-05-11 08:40 UTC
## I'm submitting a...
* Bug report
* Suggestion for improvement

## Current behavior
If a graph is inside hidden parent element (for example a TAB), graph is not rendered correctly (for example it doesnt take entire width of parent element) until user clicks in component, or call resize() on graph manually.

(in SVG mode, width is not correct, in CANVAS mode, graph is invisible)

## Expected behavior
I think it may be possible to make graphs aware of visibility of parent element and call "redraw" itself when visibility of parent element (or tree) has changed.

Do we really need to chain events from "TABS" component component by component to call resize() on graph?

**Comment by montella1507** [comment] 2018-05-11 10:37
I have very similar problems like in several forum issues in JQUERY version of kendo charts.. for example:
https://www.telerik.com/forums/kendo-ui-chart-does-not-use-the-entire-width-of-the-div-when-the-div-containing-the-chart-is-hidden

Maybe it occurs only as a combination with @angular/material tabs.

**Comment by montella1507** [comment] 2018-05-11 11:31
I may be able to provide plunker, however here is the video with that strange behavior:
https://youtu.be/gINhiVh_p_I

**Comment by danielkaradachki** [comment] 2018-05-15 08:06
Indeed, from the video it seems that the chart is not properly sized, but I am unable to reproduce it. Could you clarify which tabs components are you using? A runnable sample demonstrating the problem will be welcomed.

**Comment by montella1507** [comment] 2018-05-15 19:57
Unfortunately i am not able to simulate it in minimal repro, however i would like to keep this issue open in case i got the problem solved to let you know.

**Comment by tsvetomir** [comment] 2018-06-01 08:52
Currently, we can fix this problem only with [ResizeObserver](https://caniuse.com/#feat=resizeobserver) in Chrome. For the rest of the browsers you'd have to call `resize()`. Such partial fix might be more confusing than no fix at all - do you agree?

**Comment by montella1507** [comment] 2018-06-06 11:06
i agree. thank you

**Comment by tsvetomir** [comment] 2018-06-07 06:42
Marking as `Won't fix` until ResizeObserver becomes available in major browsers.

**Closed by tsvetomir** 2018-06-07 06:42 UTC
Labels: Bug, Won't Fix, pkg:charts
