### ISSUE TITLE
Plnkrs not working on site

### ISSUE THREAD

**Issue by lslocum** [telerik/kendo-angular#1129] opened 2017-12-01 19:43 UTC
## I'm submitting a...Support Request

* Regression report 
* Documentation issue or request

## Current behavior
When opening a plnkr from your site the plnkr never loads and console errors are thrown.

## Expected behavior
The plnkr loads

## Minimal reproduction of the problem with instructions
1. Open a plnkr link from your documentation page.
2. Observe the endless spinner.
3. Open the console and see the following errors:

`xhr construction TypeError: window.XDomainRequest is not a constructor 
    at Object.t.ajax (jstag?nc=15184186-Freestar_RON:12) 
    at n.B.load (jstag?nc=15184186-Freestar_RON:12) 
    at Object.<anonymous> (jstag?nc=15184186-Freestar_RON:12) 
    at Object.n [as tryCatch] (jstag?nc=15184186-Freestar_RON:12) 
    at jstag?nc=15184186-Freestar_RON:12 
    at new Promise (<anonymous>) 
    at jstag?nc=15184186-Freestar_RON:12 
    at Array.map (<anonymous>) 
    at Object.t._map (jstag?nc=15184186-Freestar_RON:12) 
    at i (jstag?nc=15184186-Freestar_RON:12) `

`Failed to load https://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-grid/dist/cdn/js/kendo-angular-grid.js: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.`

`Error: Error: XHR error loading https://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-grid/dist/cdn/js/kendo-angular-grid.js 
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.12/dist/zone.js:424:31) 
	    at Zone.runTask (https://unpkg.com/zone.js@0.8.12/dist/zone.js:191:47) 
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.8.12/dist/zone.js:486:38) 
	Error loading https://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-grid/dist/cdn/js/kendo-angular-grid.js as "@progress/kendo-angular-grid" from http://run.plnkr.co/IBg0heqrlTPeDYzg/app/ng.module.ts`

## What is the motivation or use case for changing the behavior?
Trying to play with our examples before I implement them in my code.

## Environment

Package versions: n/a

```

```

Browser:

Only tested with
- Chrome (desktop) version XX
- Edge version XX

System: n/a
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dtopalov** [comment] 2017-12-01 19:55
Duplicate of https://github.com/telerik/kendo-angular/issues/1120

We are currently working on fixing this, but meanwhile clearing the cache is the way to go.

**Comment by tsvetomir** [comment] 2017-12-04 06:25
The problem should go away by itself as the browser cache expires. Let us know if this is not the case.

**Closed by tsvetomir** 2017-12-04 06:25 UTC

**Comment by lslocum** [comment] 2017-12-04 19:53
Clearing the cache is no longer working for me. It worked the first day, but I have tried several times today. I opened the site in incognito mode and with IE 11 (which should have nothing cached because I never use it) and still get the console errors and an endless spinner.

**Comment by tsvetomir** [comment] 2017-12-05 10:39
@lslocum thanks for getting back. I think we finally figured it out - we needed a "[Vary: Origin" header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) to make sure the browser caches the correct origin.

You might still need to clear the cache once more or wait for it to expire (4 hours). But after that, it should be fine.

**Comment by tsvetomir** [comment] 2017-12-05 10:49
Okay, that was a bit rushed - the issue is still reproducible in Chrome.

**Comment by tsvetomir** [comment] 2017-12-05 15:17
Fixed at last. Thank you for the patience.

**Comment by lslocum** [comment] 2017-12-05 15:18
It is working for me now. Thanks!

**Comment by aliawilkinson** [comment] 2018-02-21 21:25
I am experiencing this exact error now in Chrome.

**Comment by tsvetomir** [comment] 2018-02-27 09:54
@aliawilkinson can you share the plunkr URL?
