### ISSUE TITLE
Kendo scheduler events rounding to half hour

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-angular#2025] opened 2019-01-17 19:32 UTC
The appointments are every 45 mins yet they are displayed as a half hour slots. I would expect regardless of the side guides that the events would be displayed correctly. thanks

## Current behavior
Rounding events to the nearest half hour.

## Expected behavior
I would expect the events to be displayed in their correct size relative to the side measure.

## Environment

Package versions:
"@progress/kendo-angular-scheduler": "^0.5.0",

**Comment by tsvetomir** [comment] 2019-01-18 08:00
Similar to how `snap: false` works in KUI/jQuery, https://dojo.telerik.com/ihiZEgub

**Comment by enricobenedos** [comment] 2019-02-07 14:26
We are using "^0.8.0" and we had the same "issue".

**Comment by nicolaspierre1990** [comment] 2019-04-05 06:47
Using "^0.10.1" and having the same issue

**Comment by shaizel** [comment] 2019-07-24 09:34
This is a major issue for my project. Is there a plan to fix it in the near future?

I wouldn't call it an enhancement since the expected behavior for events is for them to appear with the position and the height that their start and end times dictate...
@tsvetomir

**Comment by shaizel** [comment] 2019-07-24 13:13
> Similar to how `snap: false` works in KUI/jQuery, https://dojo.telerik.com/ihiZEgub

Actually I've looked at your example here and the issue here isn't related to `snap: false`. True, this setting allows you to edit events without them snapping to the grid, but even with snap being true, events show with their correct height and top, which is the issue raised here.

You can see in the following demo how the event appears correctly in the scheduler when it loads and doesn't snap to the grid lines:
https://dojo.telerik.com/ihiZEgub/16

**Comment by sbenyo** [comment] 2019-07-31 10:28
It is also very important in our project. It's actually the main issue preventing us from using the new scheduler now. The whole project is Angular2 except for the schedule component which currently using the jquery. The performance of the jquery is not good and not usable for production. The need to move to the new schedule is becoming critical to the project.

Can you give esitmation to when this issue will be resolved?

**Comment by dtopalov** [comment] 2019-08-07 08:59
Also requested as an urgent priority in a private support thread - 1424358.

**Comment by ipeshev** [comment] 2019-08-28 12:11
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by shaizel** [comment] 2019-09-01 13:20
The dev version does seem to work correctly.
I've set up a demo in Stackblitz [here](https://stackblitz.com/edit/angular-moogea).
Kudos!

**Comment by tsvetomir** [comment] 2019-09-03 12:29
Released in v0.16

**Closed by tsvetomir** 2019-09-03 12:29 UTC
Labels: Enhancement, Passed-QA, pkg:scheduler
