### ISSUE TITLE
DataSourceRequest parsing date incorrectly when using Grid Date Filter with toDataSourceRequestString

### ISSUE THREAD

**Issue by kambbado** [telerik/kendo-angular#657] opened 2017-06-16 17:08 UTC
I have a grid where I use **toDataSourceRequestString** to convert the **State**  into  **DataSourceRequest** query string.  The field in the grid is of type "Date".  The filter value before the call to **toDataSourceRequestString** is _**Wed Jun 07 2017 00:00:00 GMT-0400 (Eastern Daylight Time**)_  but after the call the results are as such:

`filter=eta~gte~2017-06-07T00-00-00&page=1&sort=name-asc&pageSize=20"`

My grid row is as following:

` <kendo-grid-column field="eta" title="ETA" sortable="true" [width]="130"  format="{0:D}">
      <ng-template kendoGridFilterCellTemplate let-filter let-column="column">
        <kendo-grid-date-filter-cell
                                     [showOperators]="false"
                                     [column]="column"
                                     [filter]="filter">
        </kendo-grid-date-filter-cell>
      </ng-template>
    </kendo-grid-column>`
#
I hope I was able to explain the issue correctly.

Do you have a suggestion fix this?

Thank you

**Comment by rkonstantinov** [comment] 2017-06-19 10:29
Hey @kambbado thanks for the report. Indeed, there is an issue with the date serialization format and it should be fix with the next version of the kendo-data-query package.

**Comment by rkonstantinov** [comment] 2017-06-20 07:37
The v1.0.4 of `kendo-data-query` contains the fix for this issue. Please give it a try.

**Comment by kambbado** [comment] 2017-06-21 03:20
It works, thank you

**Closed** 2017-06-21 07:13 UTC
Labels: Bug, pkg:data-query

**Comment by nikhil-ds** [comment] 2018-09-24 04:50
Hi. I have v1.5.0 of data query running but the issue still pertains and the date is getting formatted incorrectly

The filter that is set is Wed Sep 19 2018 00:00:00 GMT+0530 (India Standard Time)
and after the call the filter is set as the following
filter=(Status~eq~'Open'~and~CreatedDate~gte~datetime'2018-09-19T00-00-00')&page=1&pageSize=20

**Comment by nikhil-ds** [comment] 2018-09-24 04:55
Hi. I have v1.5.0 of data query running but the issue still pertains and the date is getting formatted incorrectly. This is for Angular 2 version of data query.

The filter that is set is Wed Sep 19 2018 00:00:00 GMT+0530 (India Standard Time)
and after the call the filter is set as the following
filter=(Statuseq'Open'andCreatedDategtedatetime'2018-09-19T00-00-00')&page=1&pageSize=20

**Comment by tsvetomir** [comment] 2018-09-24 09:50
@nikhil-ds the fix seems to be in effect as the date is prefixed with `datetime` and quoted. Please, open a new issue with more details for the problem and the expected behavior.
