### ISSUE TITLE
[Tabstrip] Graphic bug with dialog.

### ISSUE THREAD

**Issue by CptGerV-stack** [telerik/kendo-angular#3528] opened 2021-12-13 14:41 UTC
**Describe the bug**
When a dialog with * ngIf is open in a tab, we can keep clicking and changing the tab.

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/angular-n4soxj?file=app%2Fapp.component.ts)

**Expected behavior**
Tabstrip must not be accessible when dialog is opened.

**Comment by Raisolution** [comment] 2021-12-14 06:43
Hi @CptGerV-stack 

Closing this as a duplicate of #3475

**Closed by Raisolution** 2021-12-14 06:43 UTC
Labels: pkg:layout, Styling, Team2
