### ISSUE TITLE
[Recurrence Editor] Repeat on and End rule radio buttons do not work with click handler in EditDialogTemplate

### ISSUE THREAD

**Issue by anton-marchenko** [telerik/kendo-angular#2883] opened 2020-05-08 12:38 UTC
**Describe the bug**
Cannot select any of the radio buttons for Repeat on and End edits when the recurrence editor is hosted in an component with HostListener.

**To Reproduce**

  1. Open it in [StackBlitz](https://stackblitz.com/edit/recurrence-editor-bug-7u5q7h?file=src%2Fapp%2Fapp.component.ts).
  2. Double click by calendar cell.
  4. Open "Repeat" -> "Daily".
  5. Change "End" to "After...".

**Expected behavior**
Should be able to change and configure the options.

**Browser**
 - Browser Chrome

**Additional context**
The reason of this behavior is HostListener (line 24 in app.component.ts).

Similar issue is https://github.com/telerik/kendo-angular/issues/2413

**Comment by dtopalov** [comment] 2020-08-25 08:08
Further investigation showed that the issue is observable if any additional click handler is attached on or above the recurrence-editor component in the DOM hierarchy:

https://stackblitz.com/edit/angular-gjcpat-hnaq88?file=app/app.component.ts

When there is no edit template, the radio buttons are working as expected:

https://stackblitz.com/edit/angular-gjcpat-vjarsr?file=app/app.component.ts

**Comment by BeniFreitag** [comment] 2020-09-07 09:30
I experienced that radio buttons sopped working in a Dialog having `<kendo-recurrence-editor>`. The exact same code worked with Angular 8 but stopped working with Angular 10, both having kendo-angular-scheduler 1.2.0.
* Angular 8: https://stackblitz.com/edit/kendo-recurrence-editor-in-dialog-ng8 --> Radio Buttons work correctly.
* Angular 10: https://stackblitz.com/edit/kendo-recurrence-editor-in-dialog-ng10 --> Radio Buttons are not selectable.

Is there any known workaround? There isn't any HostListener in my code...

**Comment by dtopalov** [comment] 2020-09-09 08:02
Hi @BeniFreitag,

The reason is the same as described above - the MatDialog overlay seems to add a click event listener directly to the document's body:

![image](https://user-images.githubusercontent.com/7533599/92568509-f26da480-f287-11ea-9f21-f7e77e7f0e2c.png)

After removing it, the radio-buttons are working as expected:

![image](https://user-images.githubusercontent.com/7533599/92568577-0addbf00-f288-11ea-9ac3-20bf36edb8ed.png)

We will do our best to address this issue as soon as possible, and this thread will be updated accordingly once the fix is available.

**Comment by BeniFreitag** [comment] 2020-09-10 09:13
Thanks. As a workaround I placed the `<kendo-recurrence-editor>` in a div which is conditionally shown and has the same styles/classes as the MatDialog.

**Comment by Jesse-imuzo** [comment] 2020-10-19 10:51
> Thanks. As a workaround I placed the `<kendo-recurrence-editor>` in a div which is conditionally shown and has the same styles/classes as the MatDialog.

Hi @BeniFreitag, could you show me how you achieved this?

**Comment by BeniFreitag** [comment] 2021-02-25 12:42
Here's the workaround I used: https://stackblitz.com/edit/kendo-recurrence-editor-in-dialog-ng10-workaround

**Comment by martagor11** [comment] 2021-11-24 09:29
One of possible workaround is to write code in pure javascript - usage of MutationObserver. MutationObserver is listening for changes on DOM elements, so we can detect change and react on it. In my case I'm using kendo-scheduler-edit-dialog with custom form template and I had the same issue. My solution was:

add field in component with scheduler:
private changes: MutationObserver;

`private initMutationObserver() {
    this.changes = new MutationObserver((mutations: MutationRecord[]) => {
    if (mutations[0].target.nodeName === 'KENDO-SCHEDULER-EDIT-DIALOG' ) {				
      (document as any).removeAllListeners('click');
    }

   const element = document.getElementsByTagName(	'kendo-scheduler-edit-dialog')[0];

   const config = {
	attributes: true,
	childList: true,
	characterData: true,
  };

  this.changes.observe(element, config);
}`

when using MutationObserver it needs to be disconnected in ngOnDestroy

`ngOnDestroy(): void {
  this.changes.disconnect();
}`

**Comment by EricSch** [comment] 2021-12-01 14:00
@martagor11 Thanks for the sample, I tried it, but didn't work for me. Still same effect.
And in your sample, I think there are some missing `)` and `}`

**Comment by martagor11** [comment] 2021-12-07 07:20
@EricSch, in my case it was Angular version 12.1. Which version are you using? I've updated comment for missing `)` and `}`

**Comment by EricSch** [comment] 2021-12-23 17:47
@martagor11 It was 10.1, now I upgraded to 13.1. But same issue.

**Comment by JanneHarju** [comment] 2024-01-26 10:44
Have you found any solution for this? I ahve this same issue with same scenario with @martagor11 so using kendo-scheduler-edit-dialog with custom form template has something to do with it. Tried that solution but didn't work.

**Comment by JanneHarju** [comment] 2024-01-29 07:19
Finally I got your suggestion to work. I just needed to change document to window. So I needed to remove click event handlers from window. Do you have any idea what those click handlers are and what might got broken when removing them?

**Comment by EricSch** [comment] 2024-01-29 09:37
In my case, it's working now. I think I redesigned my edit dialog, used everywhere the latest versions and the <kendo-formfield> form fields.

**Comment by svetq** [comment] 2024-02-20 09:59
A fix is available in `@progress/kendo-angular-scheduler` version 15.0.2-develop.12

**Comment by svetq** [comment] 2024-02-22 13:23
Fixed in @progress/kendo-angular-scheduler v 15.1.0

**Closed by svetq** 2024-02-22 13:23 UTC
Labels: Bug, pkg:scheduler, Team1, sev3: high, freq1: rare
