### ISSUE TITLE
DateInputs v0.3.2: Which is a working version for AoT?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#286] opened 2017-02-08 15:11 UTC
I'm using DateInputs v0.3.2 specially the calendar control with Angular 2.4.6.

Compiling it, some errors are thrown, like wrongly implemented Angular events
`    MonthComponent.prototype.ngOnChanges = function () {` -> parameter is mandatory

and others private defined properties like

> Property 'widgetClasses' is private and only accessible within class 'CalendarComponent'

Thanks

**Comment by ggkrustev** [comment] 2017-02-08 17:17
Strangely enough, the DateInputs works just fine in our Angular AOT project, which is used for testing. This is the versions of the more important dependencies:
- typescript@2.1.5
- @angular/*@2.4.6
- angular-cli@@1.0.0-beta.28.3
- @progress/kendo-angular-dateinputs@0.3.2

Would it be possible to provide more details? It will be great if you can share a runnable project that replicates the issue.

P.S.
The `MonthComponent.prototype.ngOnChanges` function indeed doesn't use any arguments in this case, but I don't see any restriction in such usage.

The second function is decorated with @HostBinding and I am not aware of any restriction of the access modifiers in this case (probably I'm wrong though).

**Comment by ggkrustev** [comment] 2017-02-09 08:01
Hi @EricSch,
we pushed a patch version that includes the required changes. Unfortunately, I am still not able to replicate the issue locally. Could you try the `@progress/kendo-angular-dateinputs@0.3.3` and let me know whether the problem is still present?

**Comment by EricSch** [comment] 2017-02-09 08:12
Strange, yes. 
In our experience, you have to define the parameter like the signature, even when he isn't used. If not, the compiler will throw an error like we have:

> month.component.ngfactory.ts:152:7: Supplied parameters do not match any signature of call target.

Version like are we the same (typescript@2.1.5, angular 2.4.6) For tree shaking we are using rollup rollup@0.41.4

I try to provide more details. Perhaps we could compare the generated ngFactories?

Here our tsconfig (part):

>   "compilerOptions": {
>     "noImplicitAny": false,
>     "removeComments": true,
>     "forceConsistentCasingInFileNames": true,
>     "allowSyntheticDefaultImports": true,
>     "experimentalDecorators": true,
>     "declaration": true,
>     "noEmitHelpers": true,
>     "target": "es5",
>     "module": "es2015",
>     "moduleResolution": "node",
>     "lib": [ "es5", "dom", "es2015.promise", "es2015.collection", "es2015.iterable" ],
>     "skipDefaultLibCheck": true,
>     "skipLibCheck": true,
>     "outDir": "./aot",
>     "typeRoots": [
>       "../node_modules/@types",
>       "../node_modules"
>     ]
>   },
>   "angularCompilerOptions": {
>     "genDir": "./aot",
>     "annotateForClosureCompiler": false,
>     "skipMetadataEmit": true
>   },

**Comment by EricSch** [comment] 2017-02-09 08:13
@ggkrustev thanks, will try 0.3.3

**Comment by EricSch** [comment] 2017-02-09 08:27
@ggkrustev  Before I had 10 errors, now one error is left with 0.3.3

`/aot/node_modules/@progress/kendo-angular-dateinputs/dist/es/calendar/month-view.component.ngfactory.ts:440:45: Property 'service' is protected and only accessible within class 'MonthViewComponent' and its subclasses.`

**Comment by ggkrustev** [comment] 2017-02-09 13:37
@EricSch, the additional information about the building infrastructure helped a lot to replicate the issue. I will post here once a fix is published.

**Comment by ggkrustev** [comment] 2017-02-09 14:49
`@progress/kendo-angular-dateinputs@0.3.4` is out. It should work, at least it works on our end :)

**Comment by EricSch** [comment] 2017-02-09 15:53
Yes, thank you. It is working now. 
May ask what the difference was?

**Comment by ggkrustev** [comment] 2017-02-09 16:57
Great! I will close the issue as resolved.

Mainly the AOT dont's :) - HostBindings should decorate only public functions. 
The MonthViewComponent was injecting a protected service, where an inner component was injecting a public instance from the same type and etc :) In short real 'chore'.

**Closed by ggkrustev** 2017-02-09 16:57 UTC
Labels: pkg:date-inputs
