### ISSUE TITLE
Panel bar - undesirable scrolling to top in IE

### ISSUE THREAD

**Issue by DaniilPalii** [telerik/kendo-angular#2173] opened 2019-04-01 10:21 UTC
**Describe the bug**
Kendo panel bar when used with scroll on selecting become scrolled to top (bug exists only in IE, in Chrome - all is OK). 

**To Reproduce**
- Use browser IE 11.
- Create kendo panel bar place with several panel bar items, place panel bar in div with fixed height and overflow-y: scroll.
(Runnable snippet on StackBlitz: https://stackblitz.com/edit/angular-tsgkbe)
- Scroll panel bar to down, select some item by clicking it with mouse button.

**Expected behavior**
In IE 11 kendo panel bar when used with scroll on selecting don't become scrolled to top as in Chrome. 

**Browser**
 - IE 11

**Comment by danielkaradachki** [comment] 2019-04-02 07:39
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/1775

**Closed by danielkaradachki** 2019-04-02 07:39 UTC
Labels: Bug, Duplicate, pkg:layout
