### ISSUE TITLE
[Scheduler] All-day recurrent event issue

### ISSUE THREAD

**Issue by bajzat** [telerik/kendo-angular#2463] opened 2019-09-03 10:02 UTC
Describe the bug
In case of all-day recurrent events the last event will be shown twice if the end of the recurrence set to the following day of the event. (e.g. event: Jan 01 end of recurrence: Jan 02)

To Reproduce

https://stackblitz.com/edit/kendo-schduler-recurrent-event-issue
Result: You can see the second event on Jan 02

Expected behavior
Event shouldn't be shown on Jan 02

Screenshots

![image](https://user-images.githubusercontent.com/1759750/64164042-abfa9400-ce42-11e9-9f56-624d4959a20e.png)

Browser

OS: Windows 10
Browser Chrome, EDGE
Version latest Kendo packages

**Comment by tsvetomir** [comment] 2020-09-29 06:59
The `UNTIL` condition of the recurrence rule is set to Jan 02, 00:00 in the selected time zone (`20210101T230000Z`). According to the [recurrence rule spec](https://tools.ietf.org/html/rfc5545#section-3.3.10), the second event is displayed correctly:

> The UNTIL rule part defines a DATE or DATE-TIME value that bounds the recurrence rule in an **inclusive** manner.

If we change the `UNTIL` value to the last hour of Jan 1 in the selected time zone (`20210101T225959Z`), the event does not appear, [see demo](https://stackblitz.com/edit/kendo-schduler-recurrent-event-issue-ns658v).

The problem is likely caused by how the recurrence editor sets the `UNTIL` date. Closing in favor of https://github.com/telerik/kendo-angular/issues/3063.

**Closed by tsvetomir** 2020-09-29 06:59 UTC
Labels: Bug, pkg:scheduler
