### ISSUE TITLE
kendo-angular-grid upgrading beyond 1.6.1 and targeting es2016 throws TypeError

### ISSUE THREAD

**Issue by mramirez-fdb** [telerik/kendo-angular#1288] opened 2018-02-02 14:34 UTC
## Current behavior
I upgraded kendo-angular-grid from version 1.6.1(running fine) to version 2.0.0.  After the upgrade any instances of the GridComponent throw exception "TypeError: Class constructor EventEmitter cannot be invoked without 'new'".  I am running my project with angular 5.1.0 and angular/cli v1.6.1 and targeting the typescript build for es2016.  When I change my target to es5 the problem goes away.  Problem persists when targeting es2015.  I have tracked the error to 
progress/kendo-angular-grid/dist/es/common/event-emitter.js, the constructor of ZoneAwareEventEmitter.  Basically it tries to instantiate an instance of the angular EventEmitter with .call() but that type of call is not allowed in es2016, nor es2015, from what I have read.
## Expected behavior
I expect the the GridComponent to output proper es2016 code if I target it.  I have not experienced similar issues in any other kendo angular component nor in previous versions of GridComponent.  Every release after v1.6.1, all the way to v2 has the issues.

## Minimal reproduction of the problem with instructions

1. `npm install @angular/cli@1.6.1 -g`
2. ng new kendo-app
3. in kendo-app add `@progress/kendo-angular-grid` and any dependencies.
4. add `import { GridModule } from "@progress/kendo-angular-grid";` to app.module.ts and import it into AppModule.
5. In app.component.html add `<kendo-grid></kendo-grid>`
6. In tsconfig.app.json make sure that your compilerOptions have "target": "es2016"
9. serve the app with ng serve
10. When app loads in browser you should see error in developer console: 
       ERROR TypeError: Class constructor EventEmitter cannot be invoked without 'new'
    at new ZoneAwareEventEmitter (event-emitter.js:10)
    at new GridComponent (grid.component.js:212)
    at createClass (core.js:10365)
    at createDirectiveInstance (core.js:10200)
    at createViewNodes (core.js:11657)
    at callViewAction (core.js:12091)
    at execComponentViewsAction (core.js:12000)
    at createViewNodes (core.js:11685)
    at createRootView (core.js:11546)
    at callWithDebugContext (core.js:12912)
11. I cannot produce an online runnable demo because plunker does not support angular cli projects and stackblitz does not allow changing the tsconfig so I cannot target es2016

## What is the motivation or use case for changing the behavior?
I wanted to upgrade to latest version of the kendo grid to stay up-to-date with latest features and bug fixes but I also want to keep targeting es2016 to take advantage of smaller package sizes and faster execution.

## Environment

Package versions:

```
+-- @angular-devkit/schematics@0.2.0
+-- @angular/animations@5.2.3
+-- @angular/cli@1.6.7
+-- @angular/common@5.2.3
+-- @angular/compiler@5.2.3
+-- @angular/compiler-cli@5.2.3
+-- @angular/core@5.2.3
+-- @angular/forms@5.2.3
+-- @angular/http@5.2.3
+-- @angular/language-service@5.2.3
+-- @angular/platform-browser@5.2.3
+-- @angular/platform-browser-dynamic@5.2.3
+-- @angular/router@5.2.3
+-- @progress/kendo-angular-buttons@3.0.1
+-- @progress/kendo-angular-dateinputs@2.0.0
+-- @progress/kendo-angular-dialog@3.0.0
+-- @progress/kendo-angular-dropdowns@2.0.0
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@2.0.1
+-- @progress/kendo-angular-inputs@2.0.0
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-popup@2.0.0
+-- @progress/kendo-angular-upload@3.0.0
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-default@2.47.2
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.96
+-- codelyzer@4.1.0
+-- core-js@2.5.3
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.1
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.6
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
`-- zone.js@0.8.20
```

Browser:
- Chrome (desktop) version 64

System:
- TypeScript version: 2.2.1
- Node version: 6.9.1
- Platform:  Windows 10

**Comment by tsvetomir** [comment] 2018-02-02 15:26
Pretty neat to see that you're using ES2016 code in the browser :)

The issue seems to be caused by the fact that we ship only es5 bundles. As a result the ZoneAwareEventEmitter function "extends" the EventEmitter class from the Angular [ES2015 bundle](https://unpkg.com/@angular/core@5.0.2/esm2015/core.js).

We should be able to fix this by shipping an ES2015 bundle in the packages.

Related to angular/angular-cli#8910 and Microsoft/TypeScript#15397

**Comment by mramirez-fdb** [comment] 2018-02-02 16:39
Will the es2015 bundle be included in the next version of the package?

**Comment by tsvetomir** [comment] 2018-02-05 20:26
The latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the Grid package adds an ES2015 bundle. This should resolve this issue and hopefully improve performance in modern browsers.

We'll continue with the rest of the packages over the next few days.

**Comment by tsvetomir** [comment] 2018-02-08 12:37
All packages now ship ES2015 bundles in their latest dev versions. Feel free to give them a spin.

**Comment by tsvetomir** [comment] 2018-02-08 12:37
Fixed in `@progress/kendo-angular-grid` v2.0.2

**Comment by tsvetomir** [comment] 2018-02-14 16:07
Fixed in all latest package versions.

**Closed** 2018-02-15 07:35 UTC
Labels: Enhancement, pkg:grid

**Comment by tsvetomir** [comment] 2018-05-10 05:06
Just noticed that this no longer works in Angular 6 production builds. Disabling the build optimizer seems to fix it, see angular/angular-cli#10658

**Comment by vishalmote** [comment] 2021-04-28 15:53
Facing same issue in latest version     "@progress/kendo-angular-grid": "^5.0.3", with angular 12.0.0-rc.0

**Comment by tsvetomir** [comment] 2021-04-29 08:11
@vishalmote can you please try upgrading to the [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)?

```
npm install --save @progress/kendo-angular-grid@dev
```
