### ISSUE TITLE
Dropdowns: Kendo-multiselect - values appear twice while filtering

### ISSUE THREAD

**Issue by patrykp57** [telerik/kendo-angular#1808] opened 2018-09-21 08:25 UTC
## I'm submitting a...
* Bug report 

## Current behavior
Problem only appears when filtering is turned to true. When I choose any value, and then I'm searching for another one, and delete back the letter, previous values are displaying twice. You can check this behaviour on gif which I've places below.  Problem also exist on official example from documentation which I've also linked below.
## Expected behavior
Already selected values, shouldn't appear twice while filtering. 

## Minimal reproduction of the problem with instructions
**Demo on your website**
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/open-state/

**Demo in my case:**
![Example](https://media.giphy.com/media/2ZYHXrAV0JfY5dFzb5/giphy.gif)

 

## Environment

Package versions:
```
+-- @progress/kendo-angular-buttons@4.1.3
+-- @progress/kendo-angular-charts@3.3.2
+-- @progress/kendo-angular-dateinputs@3.4.4
+-- @progress/kendo-angular-dialog@3.7.0
+-- @progress/kendo-angular-dropdowns@3.0.3
+-- @progress/kendo-angular-excel-export@2.1.2
+-- @progress/kendo-angular-grid@3.7.0
+-- @progress/kendo-angular-inputs@3.2.1
+-- @progress/kendo-angular-intl@1.5.0
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.2
+-- @progress/kendo-angular-menu@1.0.0
+-- @progress/kendo-angular-popup@2.4.1
+-- @progress/kendo-angular-resize-sensor@3.0.4
+-- @progress/kendo-angular-treeview@2.2.0
+-- @progress/kendo-angular-upload@4.1.4
+-- @progress/kendo-data-query@1.5.0
+-- @progress/kendo-date-math@1.2.0
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-popup-common@1.6.0
+-- @progress/kendo-theme-default@2.55.0
```

Browser:
- Chrome version: 69.0.3497.100

System:
- TypeScript version: 6.2.0
- Node version: Node 10.6.0, NPM 6.2.0

**Comment by danielkaradachki** [comment] 2018-09-21 08:51
Seems like duplicate of https://github.com/telerik/kendo-angular/issues/1767

**Closed** 2018-09-21 10:07 UTC
Labels: Bug, Duplicate, pkg:dropdowns

**Comment by zhaoyouliang** [comment] 2018-11-30 02:36
@patrykp57  That's great ! You solved the same problem for me. I have another question ,How to have a triangular button on the right side ？
![image](https://user-images.githubusercontent.com/8610227/49265077-bb9c1500-f48b-11e8-99a4-926017c5ad24.png)
Thanks
