### ISSUE TITLE
Keyboard and input on kendo-datepicker improvement

### ISSUE THREAD

**Issue by monkeecheetah** [telerik/kendo-angular#910] opened 2017-09-14 07:28 UTC
## I'm submitting a...
* Suggestion for improvement

## Current behavior

I'm not sure if this is just a localization thing. When you fill in date manually and start a number with '0' the character is not registered. So if you are going to input 01/01/2001 to kendo-datepicker it will only register the first '1', then it will register the '0' and the first field will be 10 and the pointer will continue to the next field. So it will be 10/12 and you realise the input you try to do is not what you intended

If you write '1', then you have to use the arrowkeys to change to the next inputfield,.

## Expected behavior

If I write '0101' it would be nice if it is registered as 01/01 alternatively 1/1 (and the '0' is removed) but the change of pointer happens as intended and not register as 10/1.

## Minimal reproduction of the problem with instructions

http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/ 
Try to write 01012001 to set the date without using other than numberinputs (no arrowkeys or mice)

## What is the motivation or use case for changing the behavior?

The change in behavior will make it more keyboardfriendly and fewer context switches and fewer typing errors (and annoyances)

**Comment by ggkrustev** [comment] 2017-09-14 07:35
Hi @monkeecheetah, thanks for the report. 

The described issue is a known limitation with the current implementation. The DateInput will clear the value once `0` is typed and then will accept `1` as valid number. The main reason is that `0` is not valid day/month as a single digit.

It is in our short-term plans to improve DateInput behavior, but I am afraid that I wouldn't be able to provide specific ETA. I will update the thread once the issue is fixed.

**Comment by ggkrustev** [comment] 2017-10-24 07:10
Related to https://github.com/telerik/kendo-angular/issues/686

**Comment by ggkrustev** [comment] 2017-11-01 08:39
The issues is fixed in the latest @dev version of `@progress/kendo-angular-dateinputs`. Just install the `@progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730` and give it a spin.

**Comment by surya-gadiraju** [comment] 2017-11-12 23:02
hello @ggkrustev the issue is not yet released in the main version. Do you have an estimated date when this will be available in the production version

**Comment by ggkrustev** [comment] 2017-11-13 07:58
Hello @surya-gadiraju, the fix will be available early this week. I will update the thread once the fix is out.

**Comment by ggkrustev** [comment] 2017-11-14 13:46
The `@progress/kendo-angular-dateinputs@v1.4.0` package is released. Will close this issue as resolved. Please feel free to comment if something come up.

**Closed by ggkrustev** 2017-11-14 13:46 UTC
Labels: Enhancement, Needs-QA, pkg:date-inputs
