### ISSUE TITLE
[DateInputs] Format does not change when dynamically changing locale

### ISSUE THREAD

**Issue by SimeonGeorgievPr** [telerik/kendo-angular#4146] opened 2023-11-03 08:48 UTC
**Describe the bug**
When dynamically changing the locale, the DateInputs reflects correctly only the first change.

**To Reproduce**

https://stackblitz.com/edit/angular-vsxueb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts

1. Select a different locale.
2. DateInputs correctly reflect the change.
3. Change the locale again.
4. DateInputs do not reflect the change.

**Expected behavior**
Change the DateInputs format every time the locale is changed.

**Additional context**
Seems to be working as expected in version 13.2.0:
https://stackblitz.com/edit/angular-ziusve-hr2gbu

May be related to https://github.com/telerik/kendo-angular/issues/4131

**Comment by stnikolova** [comment] 2023-11-14 14:13
Hi @MattiaMalandrone, the issue is part of our immediate bug-fixing effort and the team is already working to resolve it. When a fix is available, we'll update the issue accordingly.

**Comment by MattiaMalandrone** [comment] 2023-11-14 14:16
> Hi @MattiaMalandrone, the issue is part of our immediate bug-fixing effort and the team is already working to resolve it. When a fix is available, we'll update the issue accordingly.

Thanks!

**Comment by MattiaMalandrone** [comment] 2023-11-17 07:56
Hi @stnikolova ! any news about the fix?

**Comment by MattiaMalandrone** [comment] 2023-11-22 14:52
> Hi @stnikolova ! any news about the fix?

**Comment by stnikolova** [comment] 2023-11-22 15:22
Hi @MattiaMalandrone, the fix is now available in the dev version of `@progress/kendo-angular-dateinputs` package - **14.2.0-develop.1** and it will be included in the next official release.

**Comment by stnikolova** [comment] 2023-12-07 09:04
The fix is available in **v14.2.0** of `@progress/kendo-angular-dateinputs`

**Closed by stnikolova** 2023-12-07 09:04 UTC
Labels: Bug, pkg:date-inputs, Team1, Regression
