### ISSUE TITLE
Data binding not works correct for grouped grid

### ISSUE THREAD

**Issue by MichaelSemchenko** [telerik/kendo-angular#954] opened 2017-10-02 00:55 UTC
* Bug report

## Current behavior
* data binding not works correct for grouped Grid

## Minimal reproduction of the problem with instructions
1. Go to http://plnkr.co/edit/WdDiYpulHrWnrT5Ybwed
2. Group by firstName (drag header)
3. click 'test' button.
4. As you can see groups render not updates, before you close/open group.
5. Scroll position is wrong when all groups closed
6. Empty group headers doesn't removed
7. Btw if we have generated data in kendoGridGroupHeaderTemplate (for example count of grouped items), it not updates too)

**Comment by rkonstantinov** [comment] 2017-10-02 07:02
Hi @MichaelSemchenko and thanks for the report.

I have looked at the provided test page. It seems that you have missed setting the scrollable option to `virtual` as well as the `rowHeight` option's value is not correct for the sample. Setting those should address the scroll position issue. 

I'm not sure want you mean by "Empty group headers doesn't removed", could you please elaborate a bit more.

Regarding the behavior where Grid does not reflect changes of the data. This will be addressed in the next version of the grid package.

**Comment by MichaelSemchenko** [comment] 2017-10-02 10:01
Hello< @rkonstantinov, thank you for fast answer.

> It seems that you have missed setting the scrollable option to virtual as well as the rowHeight option's value is not correct for the sample

I suppose correct behavior means rowHeight property should be ignored case scroll mode is not switched to 'virtual'.

> I'm not sure want you mean by "Empty group headers doesn't removed", could you please elaborate a bit more.

Look at my testcase please after clicking 'test' button. We get several empty groups (only header visible, and no one item):

[screenshot](http://prntscr.com/gs8cb1)

I think correct behavior - empty group headers should be removed in this case..

**Comment by rkonstantinov** [comment] 2017-10-02 10:53
The `kendoGridGroupBinding` directive works only with virtual scrolling enabled. However, we could add a warning when in develop mode, about the incorrect configuration - having set a `rowHeight` without virtual scrolling enabled.

The empty groups are caused by changed data not picked-up by the directive.

**Comment by tsvetomir** [comment] 2017-10-10 06:52
Fix published in v1.5.0

**Closed by tsvetomir** 2017-10-10 06:52 UTC
Labels: Bug, Passed-QA, pkg:grid
