### ISSUE TITLE
Grid headers are not responding to width changes

### ISSUE THREAD

**Issue by kallenkortuem** [telerik/kendo-angular#709] opened 2017-06-30 18:47 UTC
Here is a plunker showing the issue. Click the 'X' on the side pop-over to allow the width of the grid change. Note the visibility of the non-locked column headers.

[http://plnkr.co/edit/LOR0tKKDnaclwwgio0dz?p=preview](http://plnkr.co/edit/LOR0tKKDnaclwwgio0dz?p=preview)

Would it be possible to add a public resize method to the grid component for issues like this? (If one already exists disregard)

**Comment by siyka-marinova** [comment] 2017-07-13 14:38
The issue is still reproducible with the given example and `kendo-angular-grid v.1.2.3`

**Comment by tsvetomir** [comment] 2017-07-25 14:55
Should be fixed in v1.2.4-dev.201707251109

**Comment by tsvetomir** [comment] 2017-07-25 15:30
As suggested by @gyoshev we might need to clip the header content with:

```css
.k-grid-header {
  flex: 1 0 auto;
  overflow-x: hidden;
}
```

@rkonstantinov @rusev do you think this can cause trouble with e.g. column menus?

**Comment by tsvetomir** [comment] 2017-07-26 07:02
To illustrate:
![resize](https://user-images.githubusercontent.com/247917/28608548-65a65f1e-71e9-11e7-94fe-fd526d329ab4.gif)

Observe the column headers during resize.

**Comment by gyoshev** [comment] 2017-07-26 09:08
After giving it some thought, we can skip the need for the `overflow-x: hidden` if we calculate the layout with flexbox. It will also remove then need to set the `width` through scripts, and yields better performance. Here is the [updated plunker](http://plnkr.co/edit/2wMPA6qkCLPdKz52Dgml?p=preview), requires a bit more testing.

**Comment by tsvetomir** [comment] 2017-08-11 06:29
Fix shipped in v1.3.1

**Closed by tsvetomir** 2017-08-11 06:29 UTC
Labels: Bug, Passed-QA, pkg:grid
