### ISSUE TITLE
kendo-combobox selectionChange $event ==> undefined in version 1.2.2

### ISSUE THREAD

**Issue by snowerdries** [telerik/kendo-angular#996] opened 2017-10-11 11:31 UTC
I updated my npm package to "@progress/kendo-angular-dropdowns": "^1.2.2"

Now the $event parameter is undefined in the new version. When I revert to 1.2.1 the behaviour is back as expected and I retrieve the selected object in the $event parameter.

**Comment by ipeshev** [comment] 2017-10-11 11:53
Hi @snowerdries could you share a bit more code, we couldn't reproduce it on our [official demos](http://plnkr.co/edit/FabG3IJtLPmOJ1EyJX63?p=preview) is it working for you here ( it is latest version 1.2.2)

**Comment by snowerdries** [comment] 2017-10-11 11:59
<ng-template kendoGridCellTemplate let-dataItem="dataItem">
            <kendo-combobox [allowCustom]="true" [valuePrimitive]="true" *ngIf='!isStartOrEnd(dataItem) && isOfferEditable()' [data]="addresses"
                [value]="dataItem.name" (selectionChange)="selectedDestinationChanged($event, dataItem)" textField="fullName"
                valueField="fullName"></kendo-combobox>
        </ng-template>

**Comment by ipeshev** [comment] 2017-10-11 12:44
@snowerdries we were able to observe this faulty behavior, thanks for the bug report !

**Comment by ipeshev** [comment] 2017-11-01 07:19
Fixed in v1.2.3-dev.201710301334

**Comment by ipeshev** [comment] 2018-02-05 10:46
Shipped with v1.2.4

**Closed by ipeshev** 2018-02-05 10:46 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
