### ISSUE TITLE
Upload reopens file browser if select event is prevented and autoUpload is false 

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-angular#2203] opened 2019-04-13 23:22 UTC
**Describe the bug**
Upload reopens file browser if the select event is prevented and autoUpload is false. When the upload button is pressed the file browser opens.

**Expected behaviour**
Not to reopen the file browser

**Screenshots**

**Browser**
 - OS: macOS
 - Browser Chrome
 - Version [73]

**Comment by Raisolution** [comment] 2019-04-15 07:39
Hi @pabloxn,

We were unable to reproduce this behaviour on our end. Please send us an example, that demonstrates this in action (for example in [stackblitz](https://stackblitz.com/edit/angular-d3ycgc?file=app/upload.component.ts)).

**Comment by pabloxn** [comment] 2019-04-15 09:29
Hi I have used your stackblitz example and it works fine though it was the upload event not select (my bad) however mine is in a dialog and even if i strip out the other code it is still doing it.

**Comment by Raisolution** [comment] 2019-04-15 10:22
Hi @pabloxn ,

I updated [the example](https://stackblitz.com/edit/angular-d3ycgc?file=app%2Fupload.component.ts). The problem is still not present, so I am closing this issue for now. Feel free to reopen it and send a runnable example. If specific help with the implementation is needed, please open a [support ticket](https://www.telerik.com/account/support-tickets) instead.

**Closed by Raisolution** 2019-04-15 10:22 UTC
Labels: pkg:upload

**Comment by pabloxn** [comment] 2019-04-24 17:52
Hi

I have created a stackblitz that now replicates the problem. It occurs when using the dialog as a service.

[my example](https://stackblitz.com/github/xorivqxo)

thanks

**Comment by Raisolution** [comment] 2019-04-25 06:27
Hi @pabloxn,

The link to the example is broken. Could you double check it?

**Comment by pabloxn** [comment] 2019-04-25 07:55
I have fixed the above link (I hope) [my example](https://stackblitz.com/edit/github-l3dlnr)

**Comment by Raisolution** [comment] 2019-04-25 10:19
The problem in the provided example is that the Upload component is wrapped in a <label> tag, so each click inside of the label is reopening the browsers file select dialog. As a solution place the Upload outside the label.

**Comment by pabloxn** [comment] 2019-04-25 12:53
ok, thanks - that solved it.
