### ISSUE TITLE
Grid no records text not shown

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#2362] opened 2019-07-01 14:08 UTC
**Describe the bug**

The no records text in the grid are not displayed correct, if the first column is small.

**To Reproduce**

Open a grid with no data, and a small first column.
Demo: https://stackblitz.com/edit/angular-grid-norecords

**Expected behavior**

Show the complete text, not only in the first column.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Additional context**

**Comment by danielkaradachki** [comment] 2019-07-01 14:30
Closing as duplicate of https://github.com/telerik/kendo-themes/issues/781

**Closed by danielkaradachki** 2019-07-01 14:30 UTC
Labels: Bug, Duplicate, Styling, pkg:grid
