### ISSUE TITLE
Set value on slider 6.4.2 -> no animation

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2729] opened 2020-02-06 11:33 UTC
Just see:

https://stackblitz.com/edit/angular-yv4hun

every time we set a new value slide is moved correctly but without animation. With version 6.4.1 animation was correctly triggered.

**Comment by Raisolution** [comment] 2020-02-06 11:52
Hi @meriturva,

Thank you for noticing this. The described behavior is intended and by design in the latest inputs release, so the handle does not feel sluggish while being dragged. Animation will be triggered however when the value is set by clicking on the arrows or by clicking on the ticks. We will update the release notes to explicitly state this change.

**Comment by meriturva** [comment] 2020-02-06 14:47
Mmmmmm, I think this is not fair!
We need to show animation also on the programmatic model change approach.
I guess the best way is to have an animation flag and decide independently from the interaction way.

**Comment by meriturva** [comment] 2020-02-12 19:58
Any news here? what your team @Raisolution thing about it?

**Comment by Raisolution** [comment] 2020-02-13 14:27
@meriturva we will expose an `animation` property to handle the case. When it is enabled, the animation will be played on both click and model change, otherwise it won't be played in neither of the cases.

**Comment by meriturva** [comment] 2020-02-13 14:39
Perfect...thanks!

**Comment by siyka-marinova** [comment] 2020-02-18 14:21
Fixed in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-inputs`

**Comment by siyka-marinova** [comment] 2020-02-18 15:29
Fix is now available in the latest `kendo-angular-inputs v6.5.0`

**Closed by siyka-marinova** 2020-02-18 15:29 UTC
Labels: Team2, pkg:inputs
