### ISSUE TITLE
Menu is not closed when blurred

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2261] opened 2019-05-15 09:11 UTC
**Describe the bug**
When using iOS and we open the Menu, then it is not closed if it is blurred.

**To Reproduce**
Use the basic usage example:
https://www.telerik.com/kendo-angular-ui/components/menus/menu/#toc-menu-overview

1. Open the Menu.
2. Try to blur the menu.

**Comment by ipeshev** [comment] 2021-03-01 13:33
Looks like working on both develop and master branches of documentation. Am I missing something, when I open a menu on iPhone and tap on body it closes the menu, is it correct ?

**Comment by stnikolova** [comment] 2021-03-02 11:33
The behavior can be a little inconsistent. Without the fix, the `closing` behavior is inconsistent - it can be observed in the master branch documentation (might need to tap twice to close or would not close at all), for example:
1. Open 'Item 2' 
2. Tap somewhere outside to close it
3. Open 'Item 2' again
4. Tap somewhere outside to close it - item would not close or would require multiple taps to close


https://user-images.githubusercontent.com/18744873/109642353-8ba4b600-7b5b-11eb-9b69-af98448fde88.mov


If you open the example in StackBlitz (again on iOS) the issue is even more obvious - https://stackblitz.com/edit/angular-1wv9qv - items won't close at all. 

The difference in the behavior comes from the HTML layouts in the two environments.

**Comment by ipeshev** [comment] 2021-03-02 12:25
Fix available in [latest dev version]([url](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds)).

**Comment by gkarapeev** [comment] 2021-03-30 10:24
Fix available with v3.0.1

**Closed by gkarapeev** 2021-03-30 10:24 UTC
Labels: Bug, Team1, freq2: possible, pkg:menu, sev3: high
