### ISSUE TITLE
Calendar layout is broken in IE10

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#665] opened 2017-06-20 13:19 UTC
The Calendar is not displayed as expected in IE10:
[http://run.plnkr.co/mHr5CfoKaupCIzHc/](http://run.plnkr.co/mHr5CfoKaupCIzHc/)

![screenshot_3](https://user-images.githubusercontent.com/7533599/27335118-263fbc52-55d4-11e7-8ac3-8f628b78a625.png)

**Comment by tsvetomir** [comment] 2017-06-20 13:35
Looks like a duplicate of #651

**Comment by gyoshev** [comment] 2017-06-21 07:28
Closing as duplicate, will follow up in the other thread.

**Closed by gyoshev** 2017-06-21 07:28 UTC
Labels: Bug, pkg:date-inputs
