### ISSUE TITLE
Splitter "hangs" after resizing with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#1422] opened 2018-03-28 22:41 UTC
## I'm submitting a...
* Bug report 

## Current behavior
Under ChangeDetectionStrategy.OnPush, when the user resizes a pane, the splitter "hangs" until the user double clicks the splitter bar. While hanging, controls within the splitter panes are not able to activate.

## Expected behavior
Resizing completes as the user ends the resize action.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/W17dAZidsqMaXDw9IWnD
1) Click button, observe entry in console log.
2) resize splitter
3) Click button, observe no action in console log
4) double click splitter bar
5) Click button, observe entry in console log

## What is the motivation or use case for changing the behavior?
Resize of splitter by user should end when the user stops resizing the splitter.

## Environment

Browser:

- Chrome (desktop) version 65.0.3325.181 (64-bit)
- Firefox version 59.0.2 (64-bit)
- Edge version 41.16299.248.0

System:
- TypeScript version: Version 1.0.3.0 (2.5.3)
- Node version: v6.10.3, NPM version: v.3.10.10
- Platform:  Windows

**Comment by gyoshev** [comment] 2018-03-29 05:46
Duplicate of https://github.com/telerik/kendo-angular/issues/1343

**Comment by zrsio4** [comment] 2018-05-03 19:09
Issue #1343 says closed with a fix in Layout 3.0.0.
This issue still persists and is not related to #1343

**Comment by gyoshev** [comment] 2018-05-04 05:51
@zrsio4 I tried to open the provided plunker snippet, however it seems that it was deleted. I tried to reproduce the issue again by setting `ChangeDetectionStrategy.OnPush` with the latest build in [this plunker](https://plnkr.co/edit/rNyj7hqPQ0uy0IlnSCLa?p=preview), however it appears to function well. Could you please provide the problematic scenario again, so that we can verify the issue?

**Comment by gyoshev** [comment] 2018-05-04 06:07
It seems that this was a temporary problem with plunker, we have reproduced the issue.

**Comment by gyoshev** [comment] 2018-06-04 07:49
The latest development build, `v3.1.1-dev.201806040748`, resolves the problem. The easiest way to install it is to use the `dev` channel on npm, `npm install @progress/kendo-angular-layout@dev`

**Comment by gyoshev** [comment] 2018-10-22 11:43
Fixed in `@progress/kendo-angular-layout@3.1.1`

**Closed by gyoshev** 2018-10-22 11:43 UTC
Labels: Duplicate
