### ISSUE TITLE
[Editor] breaks in IE 11

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2763] opened 2020-02-18 11:34 UTC
**Describe the bug**
Once the Editor Module is imported in the app.module of an Angular 9 application, then the application cannot be run using IE 11.

The issue seems to be caused due to a 3rd party package (related to Prosemirror) that the Editor Component uses. The following issue seems similar: [2603](https://github.com/telerik/kendo-angular/issues/2603).

**To Reproduce**

1. Create a new Angular 9 project using ng new.
2. Install the Editor package and add it to the app.module by running ng add @progress/kendo-angular-editor
3. Configure the project to be compatible with IE 11.
Run ng serve

Here is an example project:
[editor-test.zip](https://github.com/telerik/kendo-angular/files/4218930/editor-test.zip)

**Comment by andrpelz** [comment] 2020-02-20 07:52
Hello, we have the same problem in our application.

Is there a workaround for this?
Or can we downgrade to a specific editor version?

**Comment by PetarMetodiev** [comment] 2020-02-24 12:04
The issue seems to be caused by a specific version of `core-js` used as `angular/cli`'s dependency. [The Angular team is aware of the problem](https://github.com/angular/angular-cli/issues/16955) and [working on it](https://github.com/angular/angular-cli/pull/17059). 

In the meantime there are two possible workarounds:
1. Roll back to Angular 8

**OR**

2. Manually update `core-js`:
	* run `npm install core-js@latest` in the project folder.
	* delete `node_modules/@angular-devkit/build-angular/node_modules/core-js/`
> NOTE: Manual update for `core-js` should be performed after each `npm install` until the issue has been fixed by the Angular team.

**Comment by Samdabell** [comment] 2020-02-28 17:45
The angular team appear to have pushed a fix for this now, my application is working in IE again on Angular 9

**Closed** 2020-03-13 09:28 UTC
Labels: Bug, Team2, freq3: likely, pkg:editor, sev3: high
