### ISSUE TITLE
Chart and sparkline tooltips not moving with target

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#783] opened 2017-07-28 04:34 UTC
## I'm submitting a...

* Bug report 

## Current behavior
I'm using angular material.  There is a sidenav component with content that is comprised of rows of cards that each contain an chart and a sparkline.  When scrolling,  the tooltip for the sparkline stays where the element was originally rendered.  So as you scroll the content up to get to lower cards and their charts, and then mouse over a sparkline, the tooltip is way down on the page where the sparkline started.  The chart is not quite as bad, the tooltip appears in the wrong place but then it animates up to where the chart has been scrolled to.
## Expected behavior
tooltips would move with the chart / sparkline they are associated with.

## Minimal reproduction of the problem with instructions
Scroll up and down in this plunker and then mouse over charts and sparklines and see how the tooltips are not displaying properly.

## What is the motivation / use case for changing the behavior?
so chart tooltips will work on this page if you have to scroll at all.

## Environment
Package versions:

```
+-- @angular/animations@4.3.1
+-- @angular/cdk@2.0.0-beta.8
+-- @angular/cli@1.3.0-rc.2
+-- @angular/common@4.3.1
+-- @angular/compiler@4.3.1
+-- @angular/compiler-cli@4.3.1
+-- @angular/core@4.3.1
+-- @angular/flex-layout@2.0.0-beta.8
+-- @angular/forms@4.3.1
+-- @angular/http@4.3.1
+-- @angular/material@2.0.0-beta.8
+-- @angular/platform-browser@4.3.1
+-- @angular/platform-browser-dynamic@4.3.1
+-- @angular/router@4.3.1
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-charts@1.2.2
+-- @progress/kendo-angular-dateinputs@1.0.5
+-- @progress/kendo-angular-dialog@1.1.0
+-- @progress/kendo-angular-dropdowns@1.1.2
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.2.3
+-- @progress/kendo-angular-inputs@1.0.7
+-- @progress/kendo-angular-intl@1.2.2
+-- @progress/kendo-angular-l10n@1.0.2
+-- @progress/kendo-angular-label@1.0.3
+-- @progress/kendo-angular-layout@1.0.5
+-- @progress/kendo-data-query@1.0.6
+-- @progress/kendo-drawing@1.1.2
+-- @progress/kendo-theme-default@2.38.2
+-- codelyzer@3.1.2
+-- core-js@2.4.1
+-- hammerjs@2.0.8
+-- rxjs@5.4.2
+-- ts-node@3.3.0
+-- tslint@5.5.0
+-- typescript@2.4.2
+-- web-animations-js@2.3.1
`-- zone.js@0.8.14
```

Browser:

- Chrome (desktop) version 60
- IE version 11 - does **NOT** have issue
- Microsoft Edge 40.15063.0.0

System:
- TypeScript version: 2.4.2
- Node version: 8.2.1 (npm: 5.3)
- Platform:  Windows 10

**Comment by ncrawlins** [comment] 2017-07-30 17:00
I have updated the issue with a plunkr that shows the problem

[plunker problem repro](http://plnkr.co/edit/J9Whv6Me6txu4b2JP5B2?p=preview)

scroll up and down and mouse over the charts and sparklines

**Comment by danielkaradachki** [comment] 2017-07-31 08:40
Thanks for the example. We will look into it.

**Comment by ncrawlins** [comment] 2017-08-15 14:23
original plunkr doesn't load anymore (ecosystem changes fast).  Here is an updated plunkr

http://plnkr.co/edit/wLVqloYKziJM7FFPTDGq?p=preview

We are pretty committed to angular material at this point and to the kendo chart package.  Not being able to have tooltips on charts on any page that may end up scrolling is a big blocker right now.

**Comment by ncrawlins** [comment] 2017-08-18 12:53
It seems to be primarily related to the overflow settings of the parent container and also the 3d transforms that angular material applies to the main content in a sidenav container.  If I put the same code in a statically sized container and set overflow-y to scroll, then the tooltips function properly.

The problem with this though is that on IE-11, that setup causes an extremely annoying redraw flicker effect that affects the whole container. anytime you the mouse moves into the vicinity of a tooltip.

However, if I use CSS to disable the transform that the angular material library is applying to the content, everything works in all browsers regardless of the container layout and overflow settings.  And while I can't see any obvious loss of function or presentation when i disable that transform, I am worried that I'm breaking something else I just haven't noticed yet when I disable it.  I imagine the material people put it in there for a reason?

**Comment by ggkrustev** [comment] 2017-08-23 16:52
@ncrawlins, indeed the issue is observable only when parent is scrollable and transformed. The main cause is the `position: fixed` styling of the Popup.

The good news is that we made a progress on this issue and we've got a fix that is under QA review. It should be released under the @dev tag soon.  I'll update the thread once the fix is available.

**Comment by siyka-marinova** [comment] 2017-09-01 07:30
Fix for this issue is currently available in the following dev. version of the kendo-angular-popup package: `@progress/kendo-angular-popup@1.1.2-dev.201708241128`. The official package will be released shortly.

**Comment by siyka-marinova** [comment] 2017-09-12 15:13
Fix is now available in the latest official package: `@progress/kendo-angular-popup@1.2.1`

**Closed by siyka-marinova** 2017-09-12 15:13 UTC
Labels: Bug, Passed-QA, pkg:charts
