### ISSUE TITLE
KendoEditor -> new iframe mode -> value not update on ngModel

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2504] opened 2019-09-26 15:06 UTC
**Describe the bug**
New kendo editor enables new iframe mode (default enabled) but with ngModel there is no way to get back model value.

**To Reproduce**
Just see:
https://stackblitz.com/edit/angular-1nsqz1

content1 value is not update

**Expected behavior**
Just it works as content2 (iframe disabled)

**Comment by danielkaradachki** [comment] 2019-09-27 06:31
Related to: 
https://github.com/telerik/kendo-angular/issues/2500
https://github.com/telerik/kendo-angular/issues/2496

**Comment by valchev** [comment] 2019-09-27 16:40
Hi @meriturva 

Thank you for bringing this to our attention, we'll do our best to provide a fix in a short period of time.

**Comment by valchev** [comment] 2019-10-02 09:25
The issue is fixed in v0.9.0. For more information please follow the discussion in telerik/kendo-angular#2346

**Closed** 2019-10-03 12:00 UTC
Labels: Bug, Team2, pkg:editor
