### ISSUE TITLE
DropDownList used as grid filter not firing change event in some cases

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#552] opened 2017-05-11 17:44 UTC
I was following the reusable filter component guide here [reusable filter](http://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/)

in my usage, the filter dropdown ended up having enough choices that it generated a scroll.  However, if the current choice scrolls out of view, then the change event for selecting a new choice does not happen. in other words, only the choices that show up in the initial drawing of the dropdown popup work.  If you scroll to any choices that were hidden, choosing them causes the dropdown to close with no change.

this can be seen if you take the plunker from your example and change it to use the more extensive products instead of sampleproducts.  [plunker](http://plnkr.co/edit/IKOQxBRLsjy3nzpLEtWR?p=preview)

In that plunker choose the category of beverages for the filter.  Then try to choose the bottom category (grains and cereal) and nothing happens. If you choose a category about halfway down, it will work and then you can choose grains and cereals.

I haven't tested if this happens to dropdownlists in every context or just when embedded in a grid filter.

**Comment by rkonstantinov** [comment] 2017-05-12 07:51
@ncrawlins, thanks for the report.

It appears that the issue is related to how the DropDownList's defaultItem value is constructed in the sample. While we are researching the DropDownList behavior, you should modify the reusable filter component similar to the following:

```javascript
    private _defaultItem : any;
    
    public get defaultItem(): any {
        if (!this._defaultItem) {
          this._defaultItem = {
              [this.textField]: "Select item...",
              [this.valueField]: null
          }
        }
        return this._defaultItem;
    }
```

**Comment by valchev** [comment] 2017-05-18 13:26
The issue with the DropDownList is fixed in the latest version.

**Closed** 2017-05-18 14:33 UTC
Labels: Bug, Needs-QA, pkg:dropdowns
