### ISSUE TITLE
ComboBox value is persisted after receiving data after filtering

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#638] opened 2017-06-12 15:44 UTC
Reported in ticket 1113762
[Plunkr example](http://plnkr.co/edit/VhtTarNit3CWovzAKmQL?p=preview)

**Comment by lexon0011** [comment] 2017-06-20 08:48
Is already known when the bug will be fixed?

**Comment by tapopov** [comment] 2017-06-20 11:59
The issue is being worked on, however we do not have an ETA yet.

**Comment by martijnkamphuis** [comment] 2017-06-23 09:45
Can you explain in more detail what are the steps to reproduce and what the issue is? I want to report an issue, but my guess is this issue is what I want to report. Also, how can I get to the ticket you mentioned, or is that something internal?

**Comment by lexon0011** [comment] 2017-06-23 12:42
- Open the following sampel: [Plunker Sample](http://plnkr.co/edit/VhtTarNit3CWovzAKmQL?p=preview)
- Insert into the Combobox a "C" and wait unit the list load all items which contains a "C"
- Select the first item (Condiments) and press Enter
- Now try to change the filter by pressing the Backspace
- As you can see, the filter could not changed because always the first selected item will be set

**Comment by lexon0011** [comment] 2017-07-05 05:52
I tried the latest version and notice that the problem still exists?? I have many troubles, because I use the component in my production environment and there is since one month no solution or workaround!!??

**Comment by tapopov** [comment] 2017-07-05 07:22
@lexon0011 
The fix is not yet included in an official release, however you can try the `v1.1.2-dev.201707041510` version.
We will move this to production as soon as possible.

**Comment by lexon0011** [comment] 2017-07-05 10:30
If I change the version of "@progress/kendo-angular-dropdowns" to v1.1.2-dev.201707041510 I have many many other problems. I will wait to the next release.

**Comment by tsvetomir** [comment] 2017-07-10 19:47
Please try upgrading to the official 1.1.2 release. Are you still having issues?

**Comment by lexon0011** [comment] 2017-07-11 13:51
`npm outdated` show as latest Version 1.1.1 - also in the changelog is the version 1.1.1 the latest one. (http://www.telerik.com/kendo-angular-ui/components/dropdowns/changelog/)

**Comment by tsvetomir** [comment] 2017-07-11 15:04
The changelog will be updated with the next site upload. The latest version at the moment is 1.1.2

**Comment by lexon0011** [comment] 2017-07-12 06:52
I can not install 1.1.2 - If I execute the command `npm install @progress/kendo-angular-dropdowns@1.1.2 --save` I get the following error:

![2017-07-12 08_51_18-administrator_ __](https://user-images.githubusercontent.com/16290662/28105336-524ad3f6-66df-11e7-8c3d-5cdbcb2e1fec.png)

If I try the command with Version 1.1.1 - it works!

So in my option, there is no Version 1.1.2 online

**Comment by tapopov** [comment] 2017-07-12 08:19
Hi @lexon0011 
We recently switched from private hosted registry to npmjs, so make sure the [.npmrc file](https://docs.npmjs.com/files/npmrc) does not contain the following lines:
```
@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken={my token string}
```

**Comment by lexon0011** [comment] 2017-07-12 09:44
yes, that was the problem. Now everything works great! Thank you very much!

**Closed** 2017-07-12 10:25 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
