### ISSUE TITLE
DropDown reset form does not reset component

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#656] opened 2017-06-16 12:10 UTC
When calling` form.reset`, the component does not visualy reset selection if drop down list in displayed on kendo-popup.

[Plunkr](http://plnkr.co/edit/9iS2rlYdBS9FRk1RvUYg?p=preview). (Select value from DropDownList and click reset)

**Comment by valchev** [comment] 2017-06-20 15:57
Hi @MaklaCof,

Thank you for bringing this to our attention. I can confirm that this is a bug, but it is not related to the popup, the issue can be reproduced even if the component is not inside a popup container. I will edit the title of the issue.

We will provide a fix in a short period of time.

**Comment by rusev** [comment] 2017-06-21 06:35
One more example related to this issue - http://plnkr.co/edit/I5Fxgu80emIQXNTbuGNb?p=preview

The selected items is reset on change. There is another odd behavior in the example - initially the selected item seems to be cleared.

We need to verify these scenarios in order to consider this issue resolved.

**Comment by valchev** [comment] 2017-06-22 16:02
The second issue, described by @rusev, occurs because the change detection does not detect change in the value (the `value` always stays equal to `null`).

In order to support this scenario, we decided to introduce a `reset` method for each component that will be responsible for clearing the component's value.

> Additional: How should the component behave when we set its value to something that doesn't exists in the data collection? Should we reset the selected item?

If the `allowCustom` configuration property is set to `true` the ComboBox widget will display the value even if it does not exists in the data set.

**Comment by siyka-marinova** [comment] 2017-06-26 15:04
Fix for this issue should be released shortly (it is currently available in the latest dev version).

**Closed** 2017-06-30 10:58 UTC
Labels: Bug, Passed-QA, pkg:dropdowns
