### ISSUE TITLE
Scheduler month view renders the event outside the control

### ISSUE THREAD

**Issue by vijeyashokk** [telerik/kendo-angular#2788] opened 2020-03-05 04:41 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When rendering events that span across multiple days between two weeks, the event doesn't wrap to next week in month view. Instead there is a horizontal scroll that appears and the event goes out of the scheduler. This happens only in month view.

## Expected behavior
The event should wrap and render inside the scheduler.

## Minimal reproduction of the problem with instructions
1. Open https://stackblitz.com/edit/angular-wrgj45-nfdw8m?file=app/app.component.ts
2. Change the scheduler view to "Month" on top right
3. Click ">" near the month on left to move to next month
4. Look at the horizontal scroll bar once you get to the month "August" and after
5. Scroll the horizontal scroll bar to the right

## Environment

Browser:

- Chrome (desktop) version 80.0.3987.122
- IE version 11.657.18362.0
- Edge version 44.18362.449.0

**Comment by mbechev** [comment] 2020-06-17 15:25
The issue is fixed in [v1.1.5](https://www.telerik.com/kendo-angular-ui/components/scheduler/changelog/) of the Scheduler package.
https://stackblitz.com/edit/angular-wrgj45-3suz7a?file=package.json

**Closed by mbechev** 2020-06-17 15:25 UTC
Labels: pkg:scheduler
