### ISSUE TITLE
[Sortable] addDataItem at the fore-last index add the item last

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#3188] opened 2021-01-26 10:48 UTC
**Describe the bug**
When you use the `addDataItem` method to add an item at the fore-last index, it instead adds it to the last position. 

**To Reproduce**

https://stackblitz.com/edit/angular-jrgess?file=app/app.component.ts

Press the Add Data Item button. It should add an item at index 1, but instead it adds it at index 2. Basically there is no different between `addDataItem(item, 1)` and `addDataItem(item, 2)` it always adds the item last when the number of items are 2. 

**Expected behavior**
Adding at the fore-last index should add an item in the fore-last position and not in the last position. 

**Screenshots**

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87

**Additional context**

**Comment by dtopalov** [comment] 2021-01-26 11:02
Seems to be a duplicate of https://github.com/telerik/kendo-angular/issues/3075

**Comment by svetq** [comment] 2021-01-26 14:10
Closing this as duplicate of [#3075](https://github.com/telerik/kendo-angular/issues/3075)

**Closed by svetq** 2021-01-26 14:10 UTC
Labels: Duplicate, Team1
