### ISSUE TITLE
Provide a focusedDate by default when DatePicker range is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1256] opened 2018-01-25 10:08 UTC
Currently when the DatePicker's range is set such that the current date is not in it, when the component has no value set, and is initially opened, a blank month view is displayed.

Perhaps when min/max are used, we should set the focused date to the start (or end) of the provided interval by default.

Currently the suggested approach is to explicitly bind the **_focusedDate_** property to the desired date.

**Comment by ggkrustev** [comment] 2018-02-01 10:58
Seems to work fine - https://plnkr.co/edit/MnCCD5LY6KKbEbYtRJl9?p=preview

**Comment by ggkrustev** [comment] 2018-02-01 11:16
The issue is reproducible here:
1. Load plunker: https://plnkr.co/edit/1GIGCjbvYngbKJUfSJ4A?p=preview
2. Open picker
3. See that no days are available to select

Reported in TicketID: 1149872

**Comment by ggkrustev** [comment] 2018-05-16 15:05
Seems to be fixed in the latest package - @progress/kendo-angular-dateinputs@3.3.0

Closing the thread as resolved.

**Closed by ggkrustev** 2018-05-16 15:05 UTC
Labels: Enhancement, pkg:date-inputs
