### ISSUE TITLE
Interface for Scheduler Event does not include ownerId

### ISSUE THREAD

**Issue by paologrimaldi** [telerik/kendo-angular#1991] opened 2018-12-18 14:02 UTC
## I'm submitting a...
Missing property?

* Bug report 

## Expected behavior

It should have the ownerID 
export interface SchedulerEvent {
    /**
     * The unique identifier of the event.
     * Typically, the ID is a number.
     * Can also be a string or an object.
     */
    id?: any;
    /**
     * The start date of the event.
     */
    start: Date;
    /**
     * The timezone name for the start date.
     */
    startTimezone?: string;
    /**
     * The end date of the event.
     */
    end: Date;
    /**
     * The timezone name for the end date.
     */
    endTimezone?: string;
    /**
     * A Boolean flag which indicates that the event occurs throughout the day.
     */
    isAllDay: boolean;
    /**
     * The title of the event.
     */
    title: string;
    /**
     * The detailed description of the event.
     */
    description?: string;
    /**
     * The rule which describes the recurring pattern of the event.
     */
    recurrenceRule?: string;
    /**
     * The `id` of the parent recurring event.
     */
    recurrenceId?: any;
    /**
     * The recurrence exceptions, if any.
     */
    recurrenceExceptions?: Date[];

    /**Missing Definition */
    ownerId: any;
}

I am guessing that it should be an integer

if you check the sample data provided in the examples they all have ownerId
const baseData: any[] = [
    {
        "TaskID": 4,
        "OwnerID": 2,
        "Title": "Consulta con Juan Lopez",
        "Description": "",
        "StartTimezone": null,
        "Start": "2013-06-09T21:00:00.000Z",
        "End": "2013-06-10T00:00:00.000Z",
        "EndTimezone": null,
        "RecurrenceRule": null,
        "RecurrenceID": null,
        "RecurrenceException": null,
        "IsAllDay": false
    }

## Environment

   "@progress/kendo-angular-scheduler": "^0.3.0",
```

```

Browser:

Not a browser issue

System:
- TypeScript version:3.1.6

**Comment by tsvetomir** [comment] 2018-12-18 14:20
We're working on supporting custom models in the Scheduler. With that update, the `SchedulerEvent` class will include a reference to the original `dataItem`.

Closing as duplicate of #1907

**Closed by tsvetomir** 2018-12-18 14:20 UTC
Labels: pkg:scheduler
