### ISSUE TITLE
Abnormal display of DatePicker widget in the newest Edge browser

### ISSUE THREAD

**Issue by yangzuo0621** [telerik/kendo-angular#1840] opened 2018-10-11 07:03 UTC
## I'm submitting a...

* Suggestion for improvement  

## Current behavior
I recently upgraded the Edge browser to `Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763)`.
The previous version is Microsoft Edge 42.17134.1.0 (Microsoft EdgeHTML 17.17134).

After upgrade, the behavior of the DatePicker display abnormal shown as following.

![image](https://user-images.githubusercontent.com/6189002/46785567-b7455c80-cd64-11e8-886f-4b4abdf76963.png)

And I compare the behavior in this two versions, I'm rather sure it's the new version cause the issue.

## Expected behavior

As the upgrade is inevitable, so I hope this behavior will be the same as before, which shown as following.

![image](https://user-images.githubusercontent.com/6189002/46785588-c75d3c00-cd64-11e8-81c9-1f8821147f77.png)

## Environment

Package versions:

```
@progress/kendo-angular-dateinputs@2.2.0
```

Browser:

- Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763)

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tsvetomir** [comment] 2018-10-12 09:04
My attempts to update to Edge 44 at the moment failed. It seems like the Windows 10 October 2018 [has been pulled out](https://blogs.windows.com/windowsexperience/2018/10/09/updated-version-of-windows-10-october-2018-update-released-to-windows-insiders/) and a fixed version is currently in testing. We'll try again when it becomes available for installation.

**Comment by sgampe** [comment] 2018-11-26 11:54
Same here with Edge & Windows 10.0.17763.134 ...

**Comment by tsvetomir** [comment] 2018-11-27 08:03
@sgampe I still can't see this update. Are you using an insiders build?

**Comment by tsvetomir** [comment] 2018-12-11 13:02
Confirmed, thanks!

**Comment by tsvetomir** [comment] 2018-12-12 08:02
Looks like a layout glitch that we'll fix in the themes.
You can add this style to your application as a workaround:

```css
.k-calendar table.k-calendar-weekdays {
  table-layout: auto;
}
```

**Comment by tsvetomir** [comment] 2018-12-12 14:30
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), [see demo](https://www.telerik.com/kendo-angular-ui-develop/components/dateinputs/datepicker/).

**Comment by yangzuo0621** [comment] 2018-12-13 01:38
> Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), [see demo](https://www.telerik.com/kendo-angular-ui-develop/components/dateinputs/datepicker/).

It works correctly. Thanks a lot for fixing.

**Closed** 2018-12-13 01:38 UTC
Labels: Bug, Needs-QA, pkg:date-inputs
