### ISSUE TITLE
[FormField] ExpressionChangedAfterItHasBeenCheckedError when changing the disabled state of an input

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-angular#4388] opened 2024-08-23 09:32 UTC
**Describe the bug**
In a Reactive Form for example, where the user needs to change the disabled state, in order to achieve cascading DropDownLists, the ExpressionChangedAfterItHasBeenCheckedError  error is thrown in the console.
Ticket 1662104

**To Reproduce**

1. Open [this Stackblitz](https://stackblitz.com/edit/angular-nj6f7x?file=src%2Fapp%2Fapp.component.ts) example.
2. Select a product in the "Product" field in order to enable the "Size" field.
3. Check the browser console.

**Expected behavior**
There should be no errors in the console.

**Comment by slavenai** [comment] 2024-08-29 05:23
Closing as a duplicate of https://github.com/telerik/kendo-angular/issues/3783

**Closed by slavenai** 2024-08-29 05:23 UTC
Labels: Bug, Duplicate, pkg:inputs, Team2
