### ISSUE TITLE
[Splitter] uses role="splitter"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3270] opened 2021-04-09 07:25 UTC
**Describe the bug**
The Splitter component adds the role="splitter" attribute to \<kendo-splitter\>.

**To Reproduce**
Please see the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/layout/splitter/

**Expected behavior**
The role="splitter" shouldn't be added.

**Workaround**
Use a custom directive with selector kendo-splitter to remove the role attribute:
https://stackblitz.com/edit/angular-quvr5h?file=app%2Fcustom.directive.ts

**Comment by mbechev** [comment] 2021-04-09 14:39
Closing this as a duplicate of #3266

**Closed by mbechev** 2021-04-09 14:39 UTC
Labels: Bug, Duplicate, Team2, pkg:layout
