### ISSUE TITLE
Panelbar inside TabStrip does not show sub groups

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular#225] opened 2017-01-24 12:15 UTC
IN the plunker link, I quickly added a "Test Panel" to show that if you now try to expand the panelbar inside a tabstrip, nothing got expanded.

I used the same script in my codes using Kendo layout modules from mid Decemember branch and panelbar and tabstrip was working very well together. After updating the latest component on 24th Jan 17, all panelbar inside tabstrip cease to expand. Please help

http://plnkr.co/edit/7Y1J4KQCWahxTcLOvPLm?p=preview

**Comment by gyoshev** [comment] 2017-01-24 14:55
The problem is caused by styling (the TabStrip styles override the PanelBar styles). A workaround at the time being is to add the following styles ([see plunkr](http://plnkr.co/edit/DJXmuGbIOZTZpMxosMVp?p=preview)):

    .k-tabstrip .k-panelbar .k-content {
      display: block;
      border-style: none;
    }

This is a bug in the theme that will be addressed.

**Comment by AlfredMan** [comment] 2017-01-24 19:18
Thanks for addressing this bug. Yeah, I was using that CSS fix too after looking into the bug myself and it worked.

**Comment by gyoshev** [comment] 2017-02-15 09:41
Closed via https://github.com/telerik/kendo-theme-default/commit/9ffc0a8b4fc2bec7a5ff15be9e48f1053902e152

**Closed by gyoshev** 2017-02-15 09:41 UTC
Labels: Bug, pkg:layout, Styling
