### ISSUE TITLE
kendo-treeview control un check issue

### ISSUE THREAD

**Issue by paonekumar** [telerik/kendo-angular#1332] opened 2018-02-22 14:59 UTC
Bug report

When we check root node it is selecting all leaf nodes, but when we try to un check  1st index(2nd item)  it is getting selected in chrome, but in IE we able to un check after second click. 

Plunker Link 
https://plnkr.co/edit/Wz2rzYUo8fyLBc2DDJix?p=preview

Steps to Reproduce from above plunker example.
1. Select Building 
2. Un check Correctional 

![Uploading image.png…]()

**Comment by ggkrustev** [comment] 2018-02-23 07:49
Hi @paonekumar,
I tried to replicate the issue in IE, but to no avail. Here is a screencast of my testing:

- https://screencast.com/t/TIVFhacMpywQ
It seems to work just fine. Could you let me know if I am missing something?

As a side note, please feel in the whole ticket template as it includes important information that could help us to replicate the issue faster and reduce the roundtrips.

**Comment by paonekumar** [comment] 2018-02-23 14:40
@ggkrustev 
Please use below steps to replicate.
1. Expand Select all 
2. Expand "Building"
3. Select "Building"
4. Un check Correctional

![image](https://user-images.githubusercontent.com/24321604/36599468-15202b50-1875-11e8-9078-94ffe6d0fbe2.png)

Please test in chrome.

**Comment by ggkrustev** [comment] 2018-02-23 14:46
@paonekumar, I can confirm that I see the very same result depicted in the screenshot while testing in Chrome. After the last step, the TreeView will
- uncheck `Correctional`
- mark `Correctional` parents (Building, Select All) with 'indeterminate' state

The described result is actually **the expected one**. This is how the built-in CheckDirective is intended to work while a child node is unchecked. If you want different implementation, then you will need to introduce a custom CheckDirective, like it is shown in the documentation:
- https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/#toc-custom

Let me know if I am missing something.

**Comment by paonekumar** [comment] 2018-02-23 14:57
@ggkrustev  Thanks for the clarification, will use custom CheckDirective.

**Comment by ggkrustev** [comment] 2018-02-23 15:31
I am afraid that I don't fully understand the question. Could you provide a specific steps that I could replicate the behavior locally?

As a side note I will close the thread as it is just a discussion of a built-in functionality of the component.

**Comment by ggkrustev** [comment] 2018-02-26 08:29
@paonekumar, thanks for the clarification. Indeed, the described behavior is erroneous and unexpected. Sorry for missing the obvious before.

We will try to addresses the issue in some of our next releases. Stay tuned for more updates in this thread.

**Comment by rkonstantinov** [comment] 2018-08-07 13:19
Should be fixed with #1701

**Closed by rkonstantinov** 2018-08-07 13:19 UTC
Labels: Bug, pkg:treeview
