### ISSUE TITLE
[FloatingLabel]  ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#2989] opened 2020-07-08 12:06 UTC
Version:
    "@progress/kendo-angular-label": "^2.3.2",
Angular 10

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'k-state-focused': 'false'. Current value: 'true'.
    at throwErrorIfNoChangesMode (core.js:8045) [angular]
    at bindingUpdated (core.js:19671) [angular]
    at checkStylingProperty (core.js:23273) [angular]
    at ɵɵclassProp (core.js:23173) [angular]
    at FloatingLabelComponent_HostBindings (index.js:594) [angular]

It happens when Labels are changed by Browsers autocomplete (Login form). 

`  ɵngcc0.ɵɵclassProp("k-floating-label-container", ctx.hostClasses)("k-state-focused", ctx.focusedClass)("k-state-invalid", ctx.invalidClass);`

you propably trying to do something like hostBinding  classes. however it changes between 2 change detection runs because of browser autocomplete.

**Comment by montella1507** [comment] 2020-07-08 12:11
Temporary fix is little bit strange... if i put "hack" inputs:

<input type="text" style="display:none">
<input type="password" style="display:none">

autocompelte still works, however, error is gone.

**Comment by dtopalov** [comment] 2020-07-08 13:37
Hi @montella1507 

We used to have issues with browsers' autocomplete in the past, but they were fixed in previous versions of the Label package. I tried to reproduce the described error in both a Stackblitz demo, and a standalone Angular 10 project, but could not:

https://stackblitz.com/edit/angular-f5v4xp-oyrrbx?file=app%2Fapp.component.ts

[Archive.zip](https://github.com/telerik/kendo-angular/files/4890947/Archive.zip)

Can you please modify one of the sample apps above, or send us a similar one where the problem can be reproduced alongside the steps to trigger the error, so we can investigate this further? Thank you in advance.

**Comment by dtopalov** [comment] 2020-07-14 07:16
Hi @montella1507,

We are closing this due to inactivity, if you send us an isolated runnable project where the problem can be observed, we will inspect it further, and reopen the issue.

**Closed by dtopalov** 2020-07-14 07:16 UTC
Labels: Team2, pkg:label

**Comment by andsala** [comment] 2021-12-02 10:25
Hi, I'm facing the same issue as @montella1507 regarding class `k-state-focused` but reproducing it on StackBliz I can only get the error on the `ng-untouched` class.

https://stackblitz.com/edit/angular-e9b2ss?file=app/app.component.ts

To reproduce the error type something in the textbox and press enter.

**Comment by Raisolution** [comment] 2021-12-07 10:50
Hi @andsala 

Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with the current FloatingLabel configuration.
