### ISSUE TITLE
ComboBox - when dropdown list closed with button, keyboard selection does not trigger valueChanges

### ISSUE THREAD

**Issue by richardhoggart** [telerik/kendo-angular#955] opened 2017-10-02 07:45 UTC
## I'm submitting a...
* Bug report

## Current behavior
With the dropdown list open - selecting items with up/down keyboard does not trigger valueChange

## Expected behavior
Selecting items when the dropdown list is open should trigger a valueChange

## Minimal reproduction of the problem with instructions
[http://plnkr.co/edit/4vzaTPeJ8xe0kUey9RWm?p=preview](http://plnkr.co/edit/4vzaTPeJ8xe0kUey9RWm?p=preview)
- Open the dropdown with the button
- Press keyboard down/up to select items in the dropdown
- Close the dropdown with the button
- No value changes

Using keyboard down/up with the dropdown list closed generates valueChanges

Browser:
- Edge version 38.14393.1066.0

**Comment by ggkrustev** [comment] 2017-10-02 08:09
@richardhoggart, thanks for the posting your observation and for the repro demo.

*The described behavior is actually intended and by design*. Once the list is opened, the user can loop through items multiple times and raising the `valueChange` event will overload the related parts. The event is raised when the list is closed, because the user doesn't see the next available item and we should *accept* the selected value as final.

As a side note, this is how the change event of the native HTML Select control behaves:

http://plnkr.co/edit/4vzaTPeJ8xe0kUey9RWm?p=preview

Currently, we do not have any immediate plans to change this behavior as it will differ than the native one. If the desired behavior is a must, then I will suggest you wire the `selectionChange` event instead of `valueChange`:

http://plnkr.co/edit/1SdSfBmHT8fcYTE0LG2y?p=preview

**Comment by richardhoggart** [comment] 2017-10-02 08:25
OK - I can see that the value change should not trigger while the dropdown is open.

But if I:
open the dropdown with the button,
select an item using the up/down keyboard
close the dropdown with the button

I would then expect the valueChange to fire ("The event is raised when the list is closed") this does not appear to be the case with the combobox control

**Comment by ggkrustev** [comment] 2017-10-02 08:36
@richardhoggart, you are absolute right. I will reopen the issue for further investigation.

**Comment by tapopov** [comment] 2017-10-02 11:56
Hello @richardhoggart 

Indeed, emitting a `valueChange` on closing the popup after selecting an item with the keyboard seems like the correct behavior. We'll implement it in one of the upcoming releases. Stay tuned.

**Comment by ipeshev** [comment] 2017-10-23 07:08
Fixed in v1.2.3-dev.201710120510

**Comment by ipeshev** [comment] 2018-02-05 10:46
Shipped with v1.2.4

**Closed by ipeshev** 2018-02-05 10:46 UTC
Labels: Passed-QA, pkg:dropdowns
