### ISSUE TITLE
Dropdown value binding not working when value is null.

### ISSUE THREAD

**Issue by DieterDS1983** [telerik/kendo-angular#985] opened 2017-10-10 08:22 UTC
I'm submitting a Bug report.

## Current behavior
See plnkr: http://plnkr.co/edit/PUHyCsvg3qLU0U7pXnOf?p=preview
On initial load nothing is selected. 

## Expected behavior
Since the value is null, we would expect that the item with value null is selected.

## Minimal reproduction of the problem with instructions
See plnkr: http://plnkr.co/edit/PUHyCsvg3qLU0U7pXnOf?p=preview

**Comment by DieterDS1983** [comment] 2017-11-07 13:40
Hi,

Do you have any updates on this?

thanks.

**Comment by tapopov** [comment] 2017-11-07 14:08
Hi @DieterDS1983 
We've pushed a fix in the latest dev version (v1.2.3-dev.201711071404). Please, let us know if the issue persists after upgrading.

**Comment by tapopov** [comment] 2017-11-07 15:09
I apologize for misleading you @DieterDS1983 
The issue is still present, as the latest dev release does not contain a fix for it. It seems this issue was accidentally referenced in a recently merged pull request. We are however, looking into fixing it, so you can expect an update soon.

**Comment by valchev** [comment] 2017-11-20 12:25
Hi @DieterDS1983, you should define the item with null value as defaultItem.

Here is an [updated plunkr](http://plnkr.co/edit/4azmgGNMSCxCUKOtELUV?p=preview) which demonstrates the right configuration.

**Comment by DieterDS1983** [comment] 2017-12-04 10:59
Ok, thanks for the info @valchev .
We will try this.

**Comment by DGolverdingen** [comment] 2017-12-12 09:16
I have also a problem with null -> After selecting a value and setting the bound value to null again programmatically, the default value is not shown. (only if I use the reset method on the dropdownlist)

When I do a form clear/reset with a dropdown in it the value becomes null so I really want to show the default item again.

In following plunker, select value and hit the button:
http://plnkr.co/edit/SP2K7jdgchb6yWk2RtKH?p=preview

**Comment by zrsio4** [comment] 2018-05-21 18:37
I am also having this issue with the current release (dropdowns 3.0.0).
Cannot programmatically select default item with value null

**Comment by ipeshev** [comment] 2018-06-18 12:36
Shipped with v3.0.2

**Closed** 2018-08-22 06:59 UTC
Labels: Invalid, Passed-QA, pkg:dropdowns
