### ISSUE TITLE
Blur event for kendo-autocomplete

### ISSUE THREAD

**Issue by alexanderromanov** [telerik/kendo-angular#206] opened 2017-01-20 08:30 UTC
Are there any plans to add blur event for kendo-autocomplete?

**Comment by ggkrustev** [comment] 2017-01-20 11:27
@alexanderromanov we are planing to add focus/blur events for all focusable (mainly forms) components. There are several roadblocks that we need to overcome. 

Currently the required functionality is in `investigation` stage. Once we have a proper solution, we will implement it immediately.

**Comment by tsvetomir** [comment] 2017-02-10 12:20
Closing this as a duplicate of #155

**Closed by tsvetomir** 2017-02-10 12:20 UTC
Labels: pkg:dropdowns, Question
